(* generated by Ott 0.34 from: test10menhir_with_aux.ott *)

type var = string (* term variable *)

type l =
  | Unknown
  | Int of string * l option
  | Generated of l
  | Range of Lexing.position * Lexing.position

type 'a annot = l * 'a

exception Parse_error_locn of l * string

let pp_lexing_position p = 
  Printf.sprintf  "file \"%s\" line %d char %d"
    p.Lexing.pos_fname p.Lexing.pos_lnum (p.Lexing.pos_cnum - p.Lexing.pos_bol)

let rec pp_l l =  match l with
    | Unknown -> "no location information available"
    | Generated l -> Printf.sprintf "Generated: %s"  (pp_l l)
    | Range(p1,p2) -> Printf.sprintf "Range: %s to %s" (pp_lexing_position p1) (pp_lexing_position p2)
    | Int(s,lo) -> Printf.sprintf "Int: %s %s" s (match lo with Some l -> pp_l l | None -> "none")


type 
term = 
   T_app of term * term * l
 | T_foo of term * l
 | T_var of var * l
 | T_paren of term * l
 | T_lambda of var * term * l



