/- generated by Ott 0.34 from: l1.ott -/




set_option linter.unusedVariables false

open Option

def Location := String /- Store locations -/
deriving instance BEq for Location

inductive Operations where /- operations -/
    | op_plus : Operations
    | op_gteq : Operations


inductive Tloc where /- types of locations -/
    | TLoc_intref : Tloc


inductive Expr where /- expressions -/
    | e_num : Int -> Expr
    | e_bool : Bool -> Expr
    | e_op : Expr -> Operations -> Expr -> Expr
    | e_if : Expr -> Expr -> Expr -> Expr
    | e_assign : Location -> Expr -> Expr
    | e_ref : Location -> Expr
    | e_skip : Expr
    | e_sequence : Expr -> Expr -> Expr
    | e_while : Expr -> Expr -> Expr


def Type_assumption := (Location×Tloc)


inductive Typ where /- types -/
    | t_int : Typ
    | t_bool : Typ
    | t_unit : Typ

open Operations Expr Typ Tloc

/- - subrules - -/
def is_v_of_expr (e_5:Expr) : Bool :=
  match e_5 with
  | (e_num n) => (true)
  | (e_bool b) => (true)
  | (e_op e1 op e2) => false
  | (e_if e1 e2 e3) => false
  | (e_assign l e) => false
  | (e_ref l) => false
  | e_skip => (true)
  | (e_sequence e1 e2) => false
  | (e_while e1 e2) => false


/- definitions -/


/- defns Jop -/
inductive reduce : (Expr × Store) -> (Expr × Store) -> Prop where    /- defn reduce -/
| op_plus: forall (n1:Int) (n2:Int) (s:List (Location × Int)) (n:Int),
( ( n1 + n2 = n ) )
 -> 
reduce  ( (e_op (e_num n1) op_plus (e_num n2)) ,  s )   ( (e_num n) ,  s ) 

| op_gteq: forall (n1:Int) (n2:Int) (s:List (Location × Int)) (b:Bool),
( (( n1 >= n2 )= b ) )
 -> 
reduce  ( (e_op (e_num n1) op_gteq (e_num n2)) ,  s )   ( (e_bool b) ,  s ) 

| op1: forall (e1:Expr) (op:Operations) (e2:Expr) (s:List (Location × Int)) (e1':Expr) (s':List (Location × Int)),
(reduce  ( e1 ,  s )   ( e1' ,  s' ) )
 -> 
reduce  ( (e_op e1 op e2) ,  s )   ( (e_op e1' op e2) ,  s' ) 

| op2: forall (e1:Expr) (op:Operations) (e2:Expr) (s:List (Location × Int)) (e2':Expr) (s':List (Location × Int)),
(reduce  ( e2 ,  s )   ( e2' ,  s' ) )
 -> 
reduce  ( (e_op e1 op e2) ,  s )   ( (e_op e1 op e2') ,  s' ) 

| deref: forall (l:Location) (s:List (Location × Int)) (n:Int),
( (List.lookup  l   s  = some ( n )) )
 -> 
reduce  ( (e_ref l) ,  s )   ( (e_num n) ,  s ) 

| assign1: forall (l:Location) (n:Int) (s:List (Location × Int)),
true
 -> 
reduce  ( (e_assign l (e_num n)) ,  s )   ( e_skip ,   (( l , n ):: s )  ) 

| assign2: forall (l:Location) (e:Expr) (s:List (Location × Int)) (e':Expr) (s':List (Location × Int)),
(reduce  ( e ,  s )   ( e' ,  s' ) )
 -> 
reduce  ( (e_assign l e) ,  s )   ( (e_assign l e') ,  s' ) 

| seq1: forall (e:Expr) (s:List (Location × Int)),
true
 -> 
reduce  ( (e_sequence e_skip e) ,  s )   ( e ,  s ) 

| seq2: forall (e1:Expr) (e2:Expr) (s:List (Location × Int)) (e1':Expr) (s':List (Location × Int)),
(reduce  ( e1 ,  s )   ( e1' ,  s' ) )
 -> 
reduce  ( (e_sequence e1 e2) ,  s )   ( (e_sequence e1' e2) ,  s' ) 

| if1: forall (e1:Expr) (e2:Expr) (s:List (Location × Int)),
true
 -> 
reduce  ( (e_if (e_bool  true ) e1 e2) ,  s )   ( e1 ,  s ) 

| if2: forall (e1:Expr) (e2:Expr) (s:List (Location × Int)),
true
 -> 
reduce  ( (e_if (e_bool  false ) e1 e2) ,  s )   ( e2 ,  s ) 

| if3: forall (e:Expr) (e1:Expr) (e2:Expr) (s:List (Location × Int)) (e':Expr) (s':List (Location × Int)),
(reduce  ( e ,  s )   ( e' ,  s' ) )
 -> 
reduce  ( (e_if e e1 e2) ,  s )   ( (e_if e' e1 e2) ,  s' ) 

| while: forall (e1:Expr) (e2:Expr) (s:List (Location × Int)),
true
 -> 
reduce  ( (e_while e1 e2) ,  s )   ( (e_if e1  ( (e_sequence e2 (e_while e1 e2)) )  e_skip) ,  s ) 


inductive typing : (List Type_assumption) -> Expr -> Typ -> Prop where    /- defn typing -/
| Ty_int: forall (G:(List Type_assumption)) (n:Int),
true
 -> 
typing G (e_num n) t_int

| Ty_bool: forall (G:(List Type_assumption)) (b:Bool),
true
 -> 
typing G (e_bool b) t_bool

| Ty_op_plus: forall (G:(List Type_assumption)) (e1:Expr) (e2:Expr),
(typing G e1 t_int) ->
(typing G e2 t_int)
 -> 
typing G (e_op e1 op_plus e2) t_int

| Ty_op_gteq: forall (G:(List Type_assumption)) (e1:Expr) (e2:Expr),
(typing G e1 t_int) ->
(typing G e2 t_int)
 -> 
typing G (e_op e1 op_gteq e2) t_bool

| Ty_if: forall (G:(List Type_assumption)) (e1:Expr) (e3:Expr) (T:Typ) (e2:Expr),
(typing G e1 t_bool) ->
(typing G e2 T) ->
(typing G e3 T)
 -> 
typing G (e_if e1 e1 e3) T

| Ty_assign: forall (G:(List Type_assumption)) (l:Location) (e:Expr),
( (List.lookup  l   G  = some ( TLoc_intref )) ) ->
(typing G e t_int)
 -> 
typing G (e_assign l e) t_unit

| Ty_deref: forall (G:(List Type_assumption)) (l:Location),
( (List.lookup  l   G  = some ( TLoc_intref )) )
 -> 
typing G (e_ref l) t_int

| Ty_skip: forall (G:(List Type_assumption)),
true
 -> 
typing G e_skip t_unit

| Ty_seq: forall (G:(List Type_assumption)) (e1:Expr) (e2:Expr) (T:Typ),
(typing G e1 t_unit) ->
(typing G e2 T)
 -> 
typing G (e_sequence e1 e2) T

| Ty_while: forall (G:(List Type_assumption)) (e1:Expr) (e2:Expr),
(typing G e1 t_bool) ->
(typing G e2 t_unit)
 -> 
typing G (e_while e1 e2) t_unit



