(* generated by Ott 0.34 from: test10menhir_with_aux.ott *)
{
open Test10menhir_with_aux_parser
exception Error of string
}

rule token = parse
| [' ' '\t']
    { token lexbuf }
| '
'
   { Lexing.new_line lexbuf; token lexbuf }
| "//" [^'\n']* '\n'
    { Lexing.new_line lexbuf; token lexbuf }
| eof
    { EOF }
| "\\"
    { BACKSLASH }
| "("
    { LPAREN }
| ")"
    { RPAREN }
| "."
    { DOT }
| "Foo"
    { FOO }
| ['a'-'z''A'-'Z']+ as var
    { VAR ( var) }
| _
    { raise (Error (Printf.sprintf "At offset %d: unexpected character.\n" (Lexing.lexeme_start lexbuf))) }


{
}

