/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test4.ott -/




abbrev ident := Nat
abbrev index := Nat

mutual
inductive type : Type where
  | Typ_unit : type
  | Typ_tuple (_ : list_type) : type
  deriving Inhabited
inductive list_type : Type where
  | Nil_list_type : list_type
  | Cons_list_type (t : type) (_ : list_type) : list_type
  deriving Inhabited
end

mutual
inductive expr : Type where
  /-- ident -/
  | Expr_var (x : ident) : expr
  /-- unit -/
  | Expr_unit : expr
  | Expr_tuple (_ : list_expr_type) : expr
  | Expr_proj (e : expr) (j : index) : expr
  | Expr_foo (e1 : expr) (e2 : expr) : expr
  deriving Inhabited
inductive list_expr_type : Type where
  | Nil_list_expr_type : list_expr_type
  | Cons_list_expr_type (e : expr) (t : type) (_ : list_expr_type) : list_expr_type
  deriving Inhabited
end

inductive list_expr_expr_type : Type where
  | Nil_list_expr_expr_type : list_expr_expr_type
  | Cons_list_expr_expr_type (e : expr) (e : expr) (t : type) (_ : list_expr_expr_type) : list_expr_expr_type
  deriving Inhabited

inductive foo3expr : Type where
  | Foo3Expr_tuple (x : ident) (_ : list_expr_type) : foo3expr
  deriving Inhabited

inductive foo2expr : Type where
  | Foo2Expr_tuple (x : ident) (_ : list_expr_expr_type) : foo2expr
  deriving Inhabited

inductive foo1expr : Type where
  | Foo1Expr_tuple (x : ident) (_ : list_expr_type) : foo1expr
  deriving Inhabited
open list_expr_expr_type list_type list_expr_type expr type foo1expr foo2expr foo3expr
def map_list_expr_expr_type {A : Type} (f : expr -> expr -> type -> A) (l : list_expr_expr_type) : List A :=
  match l with
  | Nil_list_expr_expr_type => []
  | Cons_list_expr_expr_type h0 h1 h2 tl_ => (f h0 h1 h2) :: (map_list_expr_expr_type f tl_)

def make_list_expr_expr_type (l : List (expr × expr × type)) : list_expr_expr_type :=
  match l with
  | [] => Nil_list_expr_expr_type
  | (h0,h1,h2) :: tl_ => Cons_list_expr_expr_type h0 h1 h2 (make_list_expr_expr_type tl_)

def unmake_list_expr_expr_type (l : list_expr_expr_type) : List (expr × expr × type) :=
  match l with
  | Nil_list_expr_expr_type => []
  | Cons_list_expr_expr_type h0 h1 h2 tl_ => (h0,h1,h2) :: (unmake_list_expr_expr_type tl_)

def nth_list_expr_expr_type (n : Nat) (l : list_expr_expr_type) : Option (expr × expr × type) :=
  match n, l with
  | 0, Cons_list_expr_expr_type h0 h1 h2 tl_ => some (h0,h1,h2)
  | 0, _ => none
  | _+1, Nil_list_expr_expr_type => none
  | k+1, Cons_list_expr_expr_type _ _ _ tl_ => nth_list_expr_expr_type k tl_

def app_list_expr_expr_type (l m : list_expr_expr_type) : list_expr_expr_type :=
  match l with
  | Nil_list_expr_expr_type => m
  | Cons_list_expr_expr_type h0 h1 h2 tl_ => Cons_list_expr_expr_type h0 h1 h2 (app_list_expr_expr_type tl_ m)

def map_list_type {A : Type} (f : type -> A) (l : list_type) : List A :=
  match l with
  | Nil_list_type => []
  | Cons_list_type h tl_ => (f h) :: (map_list_type f tl_)

def make_list_type (l : List type) : list_type :=
  match l with
  | [] => Nil_list_type
  | h :: tl_ => Cons_list_type h (make_list_type tl_)

def unmake_list_type (l : list_type) : List type :=
  match l with
  | Nil_list_type => []
  | Cons_list_type h tl_ => h :: (unmake_list_type tl_)

def nth_list_type (n : Nat) (l : list_type) : Option type :=
  match n, l with
  | 0, Cons_list_type h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_type => none
  | k+1, Cons_list_type _ tl_ => nth_list_type k tl_

def app_list_type (l m : list_type) : list_type :=
  match l with
  | Nil_list_type => m
  | Cons_list_type h tl_ => Cons_list_type h (app_list_type tl_ m)

def map_list_expr_type {A : Type} (f : expr -> type -> A) (l : list_expr_type) : List A :=
  match l with
  | Nil_list_expr_type => []
  | Cons_list_expr_type h0 h1 tl_ => (f h0 h1) :: (map_list_expr_type f tl_)

def make_list_expr_type (l : List (expr × type)) : list_expr_type :=
  match l with
  | [] => Nil_list_expr_type
  | (h0,h1) :: tl_ => Cons_list_expr_type h0 h1 (make_list_expr_type tl_)

def unmake_list_expr_type (l : list_expr_type) : List (expr × type) :=
  match l with
  | Nil_list_expr_type => []
  | Cons_list_expr_type h0 h1 tl_ => (h0,h1) :: (unmake_list_expr_type tl_)

def nth_list_expr_type (n : Nat) (l : list_expr_type) : Option (expr × type) :=
  match n, l with
  | 0, Cons_list_expr_type h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_expr_type => none
  | k+1, Cons_list_expr_type _ _ tl_ => nth_list_expr_type k tl_

def app_list_expr_type (l m : list_expr_type) : list_expr_type :=
  match l with
  | Nil_list_expr_type => m
  | Cons_list_expr_type h0 h1 tl_ => Cons_list_expr_type h0 h1 (app_list_expr_type tl_ m)


def aux_b_foo1expr_of_foo1expr (foo1expr5:foo1expr) : List type :=
  match foo1expr5 with
  | (Foo1Expr_tuple x e_t_list) => (unmake_list_type (make_list_type (map_list_expr_type (fun e_ t_ => t_) e_t_list)))


/- - library functions - -/
def list_assoc {α β : Type} [DecidableEq α] (l:List (α × β)) (x:α) : Option β :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def m_subst_expr_type_list (sub:List (ident×expr)) (foo3expr5:list_expr_type) : list_expr_type :=
  match foo3expr5 with
  | Nil_list_expr_type => Nil_list_expr_type
  | Cons_list_expr_type expr1 type2 expr_type_tl => Cons_list_expr_type (m_subst_expr sub expr1) type2 (m_subst_expr_type_list sub expr_type_tl)
def m_subst_expr (sub:List (ident×expr)) (e__6:expr) : expr :=
  match e__6 with
  | (Expr_var x) => (match list_assoc sub x with | none => (Expr_var x)| some e_5 => e_5 )
  | Expr_unit => Expr_unit 
  | (Expr_tuple e_t_list) => Expr_tuple (m_subst_expr_type_list sub e_t_list)
  | (Expr_proj e j) => Expr_proj (m_subst_expr sub e) j
  | (Expr_foo e1 e2) => Expr_foo (m_subst_expr sub e1) (m_subst_expr sub e2)
end

mutual
def subst_expr_type_list (e__5:expr) (x5:ident) (foo3expr5:list_expr_type) : list_expr_type :=
  match foo3expr5 with
  | Nil_list_expr_type => Nil_list_expr_type
  | Cons_list_expr_type expr1 type2 expr_type_tl => Cons_list_expr_type (subst_expr e__5 x5 expr1) type2 (subst_expr_type_list e__5 x5 expr_type_tl)
def subst_expr (e_5:expr) (x5:ident) (e__6:expr) : expr :=
  match e__6 with
  | (Expr_var x) => (if x=x5 then e_5 else (Expr_var x))
  | Expr_unit => Expr_unit 
  | (Expr_tuple e_t_list) => Expr_tuple (subst_expr_type_list e_5 x5 e_t_list)
  | (Expr_proj e j) => Expr_proj (subst_expr e_5 x5 e) j
  | (Expr_foo e1 e2) => Expr_foo (subst_expr e_5 x5 e1) (subst_expr e_5 x5 e2)
end

def m_subst_expr_expr_type_list (sub:List (ident×expr)) (foo2expr5:list_expr_expr_type) : list_expr_expr_type :=
  match foo2expr5 with
  | Nil_list_expr_expr_type => Nil_list_expr_expr_type
  | Cons_list_expr_expr_type expr1 expr2 type3 expr_expr_type_tl => Cons_list_expr_expr_type (m_subst_expr sub expr1) (m_subst_expr sub expr2) type3 (m_subst_expr_expr_type_list sub expr_expr_type_tl)


def subst_expr_expr_type_list (e_5:expr) (x5:ident) (foo2expr5:list_expr_expr_type) : list_expr_expr_type :=
  match foo2expr5 with
  | Nil_list_expr_expr_type => Nil_list_expr_expr_type
  | Cons_list_expr_expr_type expr1 expr2 type3 expr_expr_type_tl => Cons_list_expr_expr_type (subst_expr e_5 x5 expr1) (subst_expr e_5 x5 expr2) type3 (subst_expr_expr_type_list e_5 x5 expr_expr_type_tl)


def m_subst_foo3expr (sub:List (ident×expr)) (foo3expr5:foo3expr) : foo3expr :=
  match foo3expr5 with
  | (Foo3Expr_tuple x e__t__list) => Foo3Expr_tuple x (m_subst_expr_type_list sub e__t__list)


def m_subst_foo2expr (sub:List (ident×expr)) (foo2expr5:foo2expr) : foo2expr :=
  match foo2expr5 with
  | (Foo2Expr_tuple x e_e'_t_list) => Foo2Expr_tuple x (m_subst_expr_expr_type_list sub e_e'_t_list)


def m_subst_foo1expr (sub:List (ident×expr)) (foo1expr5:foo1expr) : foo1expr :=
  match foo1expr5 with
  | (Foo1Expr_tuple x e_t_list) => Foo1Expr_tuple x (m_subst_expr_type_list sub e_t_list)


def subst_foo3expr (e__5:expr) (x5:ident) (foo3expr5:foo3expr) : foo3expr :=
  match foo3expr5 with
  | (Foo3Expr_tuple x e__t__list) => Foo3Expr_tuple x (subst_expr_type_list e__5 x5 e__t__list)


def subst_foo2expr (e_5:expr) (x5:ident) (foo2expr5:foo2expr) : foo2expr :=
  match foo2expr5 with
  | (Foo2Expr_tuple x e_e'_t_list) => Foo2Expr_tuple x (subst_expr_expr_type_list e_5 x5 e_e'_t_list)


def subst_foo1expr (e_5:expr) (x5:ident) (foo1expr5:foo1expr) : foo1expr :=
  match foo1expr5 with
  | (Foo1Expr_tuple x e_t_list) => Foo1Expr_tuple x (subst_expr_type_list e_5 x5 e_t_list)


/- definitions -/


/- defns Jin -/
mutual
/-- defn eok -/
inductive eok : expr → Prop where
  | eok_unit :       eok Expr_unit

  | eok_tuple : ∀ (e_t_list : list_expr_type),
      eok (Expr_tuple e_t_list)


/-- defn ered -/
inductive ered : expr → expr → Prop where
  | ered_proj : ∀ (e_t_list : list_expr_type) (j : index),
      ered (Expr_proj (Expr_tuple e_t_list) j) ((fun (e_,t_) => e_) ((unmake_list_expr_type e_t_list)[j - 1]!))


end


