/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_freevars_1.ott -/




abbrev i := Nat
abbrev x := Nat

inductive p : Type where
  | p_x (x5 : x) : p
  deriving Inhabited

mutual
inductive t : Type where
  | t_x (x5 : x) : t
  | t_tuple (_ : list_t) : t
  | t_cond (_ : list_p_t) : t
  deriving Inhabited
inductive list_t : Type where
  | Nil_list_t : list_t
  | Cons_list_t (_ : t) (_ : list_t) : list_t
  deriving Inhabited
inductive list_p_t : Type where
  | Nil_list_p_t : list_p_t
  | Cons_list_p_t (_ : p) (_ : t) (_ : list_p_t) : list_p_t
  deriving Inhabited
end
open list_t list_p_t t p
def map_list_t {A : Type} (f : t -> A) (l : list_t) : List A :=
  match l with
  | Nil_list_t => []
  | Cons_list_t h tl_ => (f h) :: (map_list_t f tl_)

def make_list_t (l : List t) : list_t :=
  match l with
  | [] => Nil_list_t
  | h :: tl_ => Cons_list_t h (make_list_t tl_)

def unmake_list_t (l : list_t) : List t :=
  match l with
  | Nil_list_t => []
  | Cons_list_t h tl_ => h :: (unmake_list_t tl_)

def nth_list_t (n : Nat) (l : list_t) : Option t :=
  match n, l with
  | 0, Cons_list_t h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_t => none
  | k+1, Cons_list_t _ tl_ => nth_list_t k tl_

def app_list_t (l m : list_t) : list_t :=
  match l with
  | Nil_list_t => m
  | Cons_list_t h tl_ => Cons_list_t h (app_list_t tl_ m)

def map_list_p_t {A : Type} (f : p -> t -> A) (l : list_p_t) : List A :=
  match l with
  | Nil_list_p_t => []
  | Cons_list_p_t h0 h1 tl_ => (f h0 h1) :: (map_list_p_t f tl_)

def make_list_p_t (l : List (p × t)) : list_p_t :=
  match l with
  | [] => Nil_list_p_t
  | (h0,h1) :: tl_ => Cons_list_p_t h0 h1 (make_list_p_t tl_)

def unmake_list_p_t (l : list_p_t) : List (p × t) :=
  match l with
  | Nil_list_p_t => []
  | Cons_list_p_t h0 h1 tl_ => (h0,h1) :: (unmake_list_p_t tl_)

def nth_list_p_t (n : Nat) (l : list_p_t) : Option (p × t) :=
  match n, l with
  | 0, Cons_list_p_t h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_p_t => none
  | k+1, Cons_list_p_t _ _ tl_ => nth_list_p_t k tl_

def app_list_p_t (l m : list_p_t) : list_p_t :=
  match l with
  | Nil_list_p_t => m
  | Cons_list_p_t h0 h1 tl_ => Cons_list_p_t h0 h1 (app_list_p_t tl_ m)



/- - free variables - -/
mutual
def fv_p_t_list (l:list_p_t) : List x :=
  match l with
  | Nil_list_p_t => []
  | Cons_list_p_t p_ t_ p_t_list_ => (fv_t t_) ++ (fv_p_t_list p_t_list_)
def fv_t_list (l:list_t) : List x :=
  match l with
  | Nil_list_t => []
  | Cons_list_t t_ t_list_ => (fv_t t_) ++ (fv_t_list t_list_)
def fv_t (t_5:t) :  List x :=
  match t_5 with
  | (t_x x5) => [x5]
  | (t_tuple t_list) => (fv_t_list t_list)
  | (t_cond p_t_list) => (fv_p_t_list p_t_list)
end



