(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_4.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
Require Import Ott.ott_list_core.


Definition i : Set := nat.
Lemma eq_i: forall (x y : i), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_i : ott_coq_equality.

Inductive foo : Set := 
 | foo_tuple (_:list foo).

Inductive bar : Set := 
 | bar_tuple (_:list bar).
(** induction principles *)
Section foo_rect.

Variables
  (P_foo : foo -> Prop)
  (P_list_foo : list foo -> Prop).

Hypothesis
  (H_foo_tuple : forall (foo_list:list foo), P_list_foo foo_list -> P_foo (foo_tuple foo_list))
  (H_list_foo_nil : P_list_foo nil)
  (H_list_foo_cons : forall (foo0:foo), P_foo foo0 -> forall (foo_l:list foo), P_list_foo foo_l -> P_list_foo (cons foo0 foo_l)).

Fixpoint foo_ott_ind (n:foo) : P_foo n :=
  match n as x return P_foo x with
  | (foo_tuple foo_list) => H_foo_tuple foo_list (((fix foo_list_ott_ind (foo_l:list foo) : P_list_foo foo_l := match foo_l as x return P_list_foo x with nil => H_list_foo_nil | cons foo1 xl => H_list_foo_cons foo1(foo_ott_ind foo1)xl (foo_list_ott_ind xl) end)) foo_list)
end.

End foo_rect.


Section bar_rect.

Variables
  (P_bar : bar -> Prop)
  (P_list_bar : list bar -> Prop).

Hypothesis
  (H_bar_tuple : forall (bar_list:list bar), P_list_bar bar_list -> P_bar (bar_tuple bar_list))
  (H_list_bar_nil : P_list_bar nil)
  (H_list_bar_cons : forall (bar0:bar), P_bar bar0 -> forall (bar_l:list bar), P_list_bar bar_l -> P_list_bar (cons bar0 bar_l)).

Fixpoint bar_ott_ind (n:bar) : P_bar n :=
  match n as x return P_bar x with
  | (bar_tuple bar_list) => H_bar_tuple bar_list (((fix bar_list_ott_ind (bar_l:list bar) : P_list_bar bar_l := match bar_l as x return P_list_bar x with nil => H_list_bar_nil | cons bar1 xl => H_list_bar_cons bar1(bar_ott_ind bar1)xl (bar_list_ott_ind xl) end)) bar_list)
end.

End bar_rect.
(* definitions *)

(* defns J *)
Inductive J_D : foo -> Prop :=    (* defn D *)
 | J_D_tuple : forall (foo_list:list foo),
     (forall foo_, In foo_ (map (fun (foo_ : foo) => foo_) foo_list) -> (J_D foo_)) ->
     J_D (foo_tuple foo_list).
Check list_bar.
Check J_D_list.
Check make_list_bar.
Check make_J_D_list.



