/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.10.ott -/




/-- type variable -/
abbrev typevar := Nat
/-- term variable -/
abbrev termvar := Nat
/-- field label -/
abbrev label := Nat
/-- indices -/
abbrev index := Nat

mutual
/-- type -/
inductive T : Type where
  /-- type variable -/
  | T_Var (X : typevar) : T
  /-- record -/
  | T_Rec (_ : list_label_T) : T
  deriving Inhabited
inductive list_label_T : Type where
  | Nil_list_label_T : list_label_T
  | Cons_list_label_T (l : label) (_ : T) (_ : list_label_T) : list_label_T
  deriving Inhabited
end

/-- type environment -/
inductive G : Type where
  | G_empty : G
  | G_type (G5 : G) (X : typevar) (T5 : T) : G
  | G_term (G5 : G) (x : termvar) (T5 : T) : G
  deriving Inhabited

inductive list_G : Type where
  | Nil_list_G : list_G
  | Cons_list_G (_ : G) (_ : list_G) : list_G
  deriving Inhabited

mutual
/-- term -/
inductive t : Type where
  /-- variable -/
  | t_Var (x : termvar) : t
  /-- record --- complu with terminal -/
  | t_Rec_comp_lu_some (_ : list_label_t) : t
  /-- projection -/
  | t_Proj (t5 : t) (l : label) : t
  deriving Inhabited
inductive list_label_t : Type where
  | Nil_list_label_t : list_label_t
  | Cons_list_label_t (l : label) (_ : t) (_ : list_label_t) : list_label_t
  deriving Inhabited
end
open list_G list_label_t list_label_T T t G
def map_list_G {A : Type} (f : G -> A) (l : list_G) : List A :=
  match l with
  | Nil_list_G => []
  | Cons_list_G h tl_ => (f h) :: (map_list_G f tl_)

def make_list_G (l : List G) : list_G :=
  match l with
  | [] => Nil_list_G
  | h :: tl_ => Cons_list_G h (make_list_G tl_)

def unmake_list_G (l : list_G) : List G :=
  match l with
  | Nil_list_G => []
  | Cons_list_G h tl_ => h :: (unmake_list_G tl_)

def nth_list_G (n : Nat) (l : list_G) : Option G :=
  match n, l with
  | 0, Cons_list_G h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_G => none
  | k+1, Cons_list_G _ tl_ => nth_list_G k tl_

def app_list_G (l m : list_G) : list_G :=
  match l with
  | Nil_list_G => m
  | Cons_list_G h tl_ => Cons_list_G h (app_list_G tl_ m)

def map_list_label_t {A : Type} (f : label -> t -> A) (l : list_label_t) : List A :=
  match l with
  | Nil_list_label_t => []
  | Cons_list_label_t h0 h1 tl_ => (f h0 h1) :: (map_list_label_t f tl_)

def make_list_label_t (l : List (label × t)) : list_label_t :=
  match l with
  | [] => Nil_list_label_t
  | (h0,h1) :: tl_ => Cons_list_label_t h0 h1 (make_list_label_t tl_)

def unmake_list_label_t (l : list_label_t) : List (label × t) :=
  match l with
  | Nil_list_label_t => []
  | Cons_list_label_t h0 h1 tl_ => (h0,h1) :: (unmake_list_label_t tl_)

def nth_list_label_t (n : Nat) (l : list_label_t) : Option (label × t) :=
  match n, l with
  | 0, Cons_list_label_t h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_label_t => none
  | k+1, Cons_list_label_t _ _ tl_ => nth_list_label_t k tl_

def app_list_label_t (l m : list_label_t) : list_label_t :=
  match l with
  | Nil_list_label_t => m
  | Cons_list_label_t h0 h1 tl_ => Cons_list_label_t h0 h1 (app_list_label_t tl_ m)

def map_list_label_T {A : Type} (f : label -> T -> A) (l : list_label_T) : List A :=
  match l with
  | Nil_list_label_T => []
  | Cons_list_label_T h0 h1 tl_ => (f h0 h1) :: (map_list_label_T f tl_)

def make_list_label_T (l : List (label × T)) : list_label_T :=
  match l with
  | [] => Nil_list_label_T
  | (h0,h1) :: tl_ => Cons_list_label_T h0 h1 (make_list_label_T tl_)

def unmake_list_label_T (l : list_label_T) : List (label × T) :=
  match l with
  | Nil_list_label_T => []
  | Cons_list_label_T h0 h1 tl_ => (h0,h1) :: (unmake_list_label_T tl_)

def nth_list_label_T (n : Nat) (l : list_label_T) : Option (label × T) :=
  match n, l with
  | 0, Cons_list_label_T h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_label_T => none
  | k+1, Cons_list_label_T _ _ tl_ => nth_list_label_T k tl_

def app_list_label_T (l m : list_label_T) : list_label_T :=
  match l with
  | Nil_list_label_T => m
  | Cons_list_label_T h0 h1 tl_ => Cons_list_label_T h0 h1 (app_list_label_T tl_ m)


inductive list_label_t_T : Type where
    | Nil_list_label_t_T : list_label_t_T
    | Cons_list_label_t_T : label -> t -> T -> list_label_t_T -> list_label_t_T
  deriving Inhabited
open list_label_t_T

def map_list_label_t_T {A : Type} (f : label -> t -> T -> A) (l : list_label_t_T) : List A :=
  match l with
  | Nil_list_label_t_T => []
  | Cons_list_label_t_T h0 h1 h2 tl_ => (f h0 h1 h2) :: (map_list_label_t_T f tl_)

def make_list_label_t_T (l : List (label × t × T)) : list_label_t_T :=
  match l with
  | [] => Nil_list_label_t_T
  | (h0,h1,h2) :: tl_ => Cons_list_label_t_T h0 h1 h2 (make_list_label_t_T tl_)

def unmake_list_label_t_T (l : list_label_t_T) : List (label × t × T) :=
  match l with
  | Nil_list_label_t_T => []
  | Cons_list_label_t_T h0 h1 h2 tl_ => (h0,h1,h2) :: (unmake_list_label_t_T tl_)

def nth_list_label_t_T (n : Nat) (l : list_label_t_T) : Option (label × t × T) :=
  match n, l with
  | 0, Cons_list_label_t_T h0 h1 h2 tl_ => some (h0,h1,h2)
  | 0, _ => none
  | _+1, Nil_list_label_t_T => none
  | k+1, Cons_list_label_t_T _ _ _ tl_ => nth_list_label_t_T k tl_

def app_list_label_t_T (l m : list_label_t_T) : list_label_t_T :=
  match l with
  | Nil_list_label_t_T => m
  | Cons_list_label_t_T h0 h1 h2 tl_ => Cons_list_label_t_T h0 h1 h2 (app_list_label_t_T tl_ m)

/- definitions -/


/- defns Jtype -/
/-- defn Ty -/
inductive Ty : G → t → T → Prop where
  | Ty_Rcd_dotform : ∀ (l_t_T_list : list_label_t_T) (G5 : G),
      (∀ l_t_T_list_ ∈ (unmake_list_label_t_T l_t_T_list), (fun (l_,t_,T_) => (Ty G5 t_ T_)) l_t_T_list_) →
      Ty G5 (t_Rec_comp_lu_some (make_list_label_t (map_list_label_t_T (fun l_ t_ T_ => (l_,t_)) l_t_T_list))) (T_Rec (make_list_label_T (map_list_label_t_T (fun l_ t_ T_ => (l_,T_)) l_t_T_list)))

  | Ty_Proj_dotform : ∀ (l_T_list : list_label_T) (j : index) (G5 : G) (t5 : t),
      (Ty G5 t5 (T_Rec l_T_list)) →
      Ty G5 (t_Proj t5 ((fun (l_,T_) => l_) ((unmake_list_label_T l_T_list)[j - 1]!))) ((fun (l_,T_) => T_) ((unmake_list_label_T l_T_list)[j - 1]!))

  | Ty_Rcd_comp : ∀ (l_t_T_list : list_label_t_T) (G5 : G),
      (∀ l_t_T_list_ ∈ (unmake_list_label_t_T l_t_T_list), (fun (l_,t_,T_) => (Ty G5 t_ T_)) l_t_T_list_) →
      Ty G5 (t_Rec_comp_lu_some (make_list_label_t (map_list_label_t_T (fun l_ t_ T_ => (l_,t_)) l_t_T_list))) (T_Rec (make_list_label_T (map_list_label_t_T (fun l_ t_ T_ => (l_,T_)) l_t_T_list)))

  | Ty_Proj_comp : ∀ (l_T_list : list_label_T) (j : index) (G5 : G) (t5 : t),
      (Ty G5 t5 (T_Rec l_T_list)) →
      Ty G5 (t_Proj t5 ((fun (l_,T_) => l_) ((unmake_list_label_T l_T_list)[j]!))) ((fun (l_,T_) => T_) ((unmake_list_label_T l_T_list)[j]!))

  | Ty_Rcd_comp_u : ∀ (l_t_T_list : list_label_t_T) (G5 : G),
      (∀ l_t_T_list_ ∈ (unmake_list_label_t_T l_t_T_list), (fun (l_,t_,T_) => (Ty G5 t_ T_)) l_t_T_list_) →
      Ty G5 (t_Rec_comp_lu_some (make_list_label_t (map_list_label_t_T (fun l_ t_ T_ => (l_,t_)) l_t_T_list))) (T_Rec (make_list_label_T (map_list_label_t_T (fun l_ t_ T_ => (l_,T_)) l_t_T_list)))

  | Ty_Proj_comp_u : ∀ (l_T_list : list_label_T) (j : index) (G5 : G) (t5 : t),
      (Ty G5 t5 (T_Rec l_T_list)) →
      Ty G5 (t_Proj t5 ((fun (l_,T_) => l_) ((unmake_list_label_T l_T_list)[j]!))) ((fun (l_,T_) => T_) ((unmake_list_label_T l_T_list)[j]!))

  | Ty_Rcd_comp_lu : ∀ (l_t_T_list : list_label_t_T) (G5 : G),
      (∀ l_t_T_list_ ∈ (unmake_list_label_t_T l_t_T_list), (fun (l_,t_,T_) => (Ty G5 t_ T_)) l_t_T_list_) →
      Ty G5 (t_Rec_comp_lu_some (make_list_label_t (map_list_label_t_T (fun l_ t_ T_ => (l_,t_)) l_t_T_list))) (T_Rec (make_list_label_T (map_list_label_t_T (fun l_ t_ T_ => (l_,T_)) l_t_T_list)))

  | Ty_Proj_comp_lu : ∀ (l_T_list : list_label_T) (j : index) (G5 : G) (t5 : t),
      (Ty G5 t5 (T_Rec l_T_list)) →
      Ty G5 (t_Proj t5 ((fun (l_,T_) => l_) ((unmake_list_label_T l_T_list)[j - 1]!))) ((fun (l_,T_) => T_) ((unmake_list_label_T l_T_list)[j - 1]!))

  | Ty_Proj_dotform_minus : ∀ (l_T_list : list_label_T) (j : index) (G5 : G) (t5 : t),
      (Ty G5 t5 (T_Rec l_T_list)) →
      Ty G5 (t_Proj t5 ((fun (l_,T_) => l_) ((unmake_list_label_T l_T_list)[j]!))) ((fun (l_,T_) => T_) ((unmake_list_label_T l_T_list)[j]!))

  | Ty_Proj_comp_lu_minus : ∀ (l_T_list : list_label_T) (j : index) (G5 : G) (t5 : t),
      (Ty G5 t5 (T_Rec l_T_list)) →
      Ty G5 (t_Proj t5 ((fun (l_,T_) => l_) ((unmake_list_label_T l_T_list)[j]!))) ((fun (l_,T_) => T_) ((unmake_list_label_T l_T_list)[j]!))



