/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test11.ott -/




abbrev termvar := Nat

inductive t : Type where
  | t_Var (x : termvar) : t
  | t_Lam (x : termvar) (t5 : t) : t
  | t_App (t5 : t) (t' : t) : t
  | t_Foo (v5 : t) : t
  deriving Inhabited
open t

/- - subrules - -/
mutual
def is_t_of_t (t_6:t) : Bool :=
  match t_6 with
  | (t_Var x) => (true)
  | (t_Lam x t5) => ((is_t_of_t t5))
  | (t_App t5 t') => ((is_t_of_t t5) /\ (is_t_of_t t'))
  | (t_Foo v5) => ((is_v_of_t v5))
def is_v_of_t (t_6:t) : Bool :=
  match t_6 with
  | (t_Var x) => false
  | (t_Lam x t5) => ((is_t_of_t t5))
  | (t_App t5 t') => false
  | (t_Foo v5) => false
end

/- definitions -/


/- defns Jb -/
/-- defn Baz -/
inductive Baz : t → t → Prop where
  | ax : ∀ (t5 : t) (v5 : t),
      (is_t_of_t t5) →
      (is_v_of_t v5) →
      Baz t5 v5



