/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_4.ott -/




abbrev i := Nat

mutual
inductive bar : Type where
  | bar_tuple (_ : list_bar) : bar

inductive list_bar : Type where
  | Nil_list_bar : list_bar
  | Cons_list_bar (_ : bar) (_ : list_bar) : list_bar

end

mutual
inductive foo : Type where
  | foo_tuple (_ : list_foo) : foo

inductive list_foo : Type where
  | Nil_list_foo : list_foo
  | Cons_list_foo (_ : foo) (_ : list_foo) : list_foo

end
open list_bar list_foo foo bar
def map_list_bar {A : Type} (f : bar -> A) (l : list_bar) : List A :=
  match l with
  | Nil_list_bar => []
  | Cons_list_bar h tl_ => (f h) :: (map_list_bar f tl_)

def make_list_bar (l : List bar) : list_bar :=
  match l with
  | [] => Nil_list_bar
  | h :: tl_ => Cons_list_bar h (make_list_bar tl_)

def unmake_list_bar (l : list_bar) : List bar :=
  match l with
  | Nil_list_bar => []
  | Cons_list_bar h tl_ => h :: (unmake_list_bar tl_)

def nth_list_bar (n : Nat) (l : list_bar) : Option bar :=
  match n, l with
  | 0, Cons_list_bar h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_bar => none
  | k+1, Cons_list_bar _ tl_ => nth_list_bar k tl_

def app_list_bar (l m : list_bar) : list_bar :=
  match l with
  | Nil_list_bar => m
  | Cons_list_bar h tl_ => Cons_list_bar h (app_list_bar tl_ m)

def map_list_foo {A : Type} (f : foo -> A) (l : list_foo) : List A :=
  match l with
  | Nil_list_foo => []
  | Cons_list_foo h tl_ => (f h) :: (map_list_foo f tl_)

def make_list_foo (l : List foo) : list_foo :=
  match l with
  | [] => Nil_list_foo
  | h :: tl_ => Cons_list_foo h (make_list_foo tl_)

def unmake_list_foo (l : list_foo) : List foo :=
  match l with
  | Nil_list_foo => []
  | Cons_list_foo h tl_ => h :: (unmake_list_foo tl_)

def nth_list_foo (n : Nat) (l : list_foo) : Option foo :=
  match n, l with
  | 0, Cons_list_foo h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_foo => none
  | k+1, Cons_list_foo _ tl_ => nth_list_foo k tl_

def app_list_foo (l m : list_foo) : list_foo :=
  match l with
  | Nil_list_foo => m
  | Cons_list_foo h tl_ => Cons_list_foo h (app_list_foo tl_ m)


/- definitions -/


/- defns J -/
/-- defn D -/
inductive J_D : foo → Prop where
  | J_D_tuple : ∀ (foo_list : list_foo),
      (∀ foo_list_ ∈ (unmake_list_foo foo_list), (fun foo_ => (J_D foo_)) foo_list_) →
      J_D (foo_tuple foo_list)



