/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test18.0.ott -/





inductive c : Type where
  | c_bar : c
  deriving Inhabited

inductive a : Type where
  | a_c (c5 : c) : a
  deriving Inhabited

inductive b : Type where
  | b_foo : b
  deriving Inhabited
open a b c


