(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/nat.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/bool.ott *)
theory testRegr_sys_arith
imports Main
begin

(** warning: the backend selected ignores the file structure informations *)
(** syntax *)
datatype "t" =  \<comment> \<open>terms:\<close>
   TmZero   \<comment> \<open>constant zero\<close>
 | TmSucc "t"   \<comment> \<open>successor\<close>
 | TmPred "t"   \<comment> \<open>predecessor\<close>
 | TmIszero "t"   \<comment> \<open>zero test\<close>
 | TmTrue   \<comment> \<open>constant true\<close>
 | TmFalse   \<comment> \<open>constant false\<close>
 | TmIf "t" "t" "t"   \<comment> \<open>conditional\<close>


(** auxiliary functions on the new list types *)
(** library functions *)
(** subrules *)
primrec
is_v_of_t :: "t => bool"
where
"is_v_of_t TmZero = ((True))"
| "is_v_of_t (TmSucc t) = (((is_v_of_t t)))"
| "is_v_of_t (TmPred t) = (False)"
| "is_v_of_t (TmIszero t) = (False)"
| "is_v_of_t TmTrue = ((True))"
| "is_v_of_t TmFalse = ((True))"
| "is_v_of_t (TmIf t1 t2 t3) = (False)"

(** auxiliary functions *)
(** free variables *)
(** substitutions *)
(** context application *)

(** definitions *)
(* defns Jop *)
inductive red :: "t \<Rightarrow> t \<Rightarrow> bool"
where
(* defn red *)

E_SuccI: "\<lbrakk>red (t1) (t1')\<rbrakk> \<Longrightarrow>
red ((TmSucc t1)) ((TmSucc t1'))"

| E_PredZeroI: "red ((TmPred TmZero)) (TmZero)"

| E_PredSuccI: "\<lbrakk>is_v_of_t v1\<rbrakk> \<Longrightarrow>
red ((TmPred  (TmSucc v1) )) (v1)"

| E_PredI: "\<lbrakk>red (t1) (t1')\<rbrakk> \<Longrightarrow>
red ((TmPred t1)) ((TmPred t1'))"

| E_IsZeroZeroI: "red ((TmIszero TmZero)) (TmTrue)"

| E_IsZeroSuccI: "\<lbrakk>is_v_of_t v1\<rbrakk> \<Longrightarrow>
red ((TmIszero  (TmSucc v1) )) (TmFalse)"

| E_IsZeroI: "\<lbrakk>red (t1) (t1')\<rbrakk> \<Longrightarrow>
red ((TmIszero t1)) ((TmIszero t1'))"

| E_IfTrueI: "red ((TmIf TmTrue t2 t3)) (t2)"

| E_IfFalseI: "red ((TmIf TmFalse t2 t3)) (t3)"

| E_IfI: "\<lbrakk>red (t1) (t1')\<rbrakk> \<Longrightarrow>
red ((TmIf t1 t2 t3)) ((TmIf t1' t2 t3))"



end
