(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_1.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
Require Import Ott.ott_list_core.


Definition i : Set := UNDEFINED.
Definition x : Set := UNDEFINED.

Inductive b : Set := 
 | b_x (x5:x).

Inductive t : Set := 
 | t_x (x5:x)
 | t_letrec (_:list lb) (t5:t)
with lb : Set := 
 | lb_simple (x5:x) (t5:t).

Inductive E : Set := 
 | E_concrete (_:list b).
(** induction principles *)
Section lb_t_rect.

Variables
  (P_lb : lb -> Prop)
  (P_list_lb : list lb -> Prop)
  (P_t : t -> Prop).

Hypothesis
  (H_lb_simple : forall (x5:x), forall (t5:t), P_t t5 -> P_lb (lb_simple x5 t5))
  (H_t_x : forall (x5:x), P_t (t_x x5))
  (H_t_letrec : forall (lb_list:list lb), P_list_lb lb_list -> forall (t5:t), P_t t5 -> P_t (t_letrec lb_list t5))
  (H_list_lb_nil : P_list_lb nil)
  (H_list_lb_cons : forall (lb0:lb), P_lb lb0 -> forall (lb_l:list lb), P_list_lb lb_l -> P_list_lb (cons lb0 lb_l)).

Fixpoint t_ott_ind (n:t) : P_t n :=
  match n as x return P_t x with
  | (t_x x5) => H_t_x x5
  | (t_letrec lb_list t5) => H_t_letrec lb_list (((fix lb_list_ott_ind (lb_l:list lb) : P_list_lb lb_l := match lb_l as x return P_list_lb x with nil => H_list_lb_nil | cons lb1 xl => H_list_lb_cons lb1(lb_ott_ind lb1)xl (lb_list_ott_ind xl) end)) lb_list) t5 (t_ott_ind t5)
end
with lb_ott_ind (n:lb) : P_lb n :=
  match n as x return P_lb x with
  | (lb_simple x5 t5) => H_lb_simple x5 t5 (t_ott_ind t5)
end.

End lb_t_rect.


Section E_rect.

Variables
  (P_E : E -> Prop).

Hypothesis
  (H_E_concrete : forall (b_list:list b), P_E (E_concrete b_list))
.

Fixpoint E_ott_ind (n:E) : P_E n :=
  match n as x return P_E x with
  | (E_concrete b_list) => H_E_concrete b_list
end.

End E_rect.
(* definitions *)

(* defns Typing *)
Inductive Typing_ok : E -> Prop :=    (* defn ok *)
 | Typing_ok_nil : 
     Typing_ok  wibble 
 | Typing_ok_x : forall (E5:E) (x5:x),
     Typing_ok E5 ->
     Typing_ok  wibble 
with Typing_term : E -> t -> Prop :=    (* defn term *)
 | Typing_term_x : forall (E1:E) (x5:x) (E2:E),
     Typing_ok  wibble  ->
     Typing_term  wibble  (t_x x5)
 | Typing_term_letrec : forall (lb_E_list:list (lb*E)) (E_5:E) (t5:t),
     (PARSE_ERROR "File /home/pes20/claude-home/ott/regression/../tests/test_lists_1.ott on line 45 - 46" "no parses (char 35): E, E1, ... , En |- lb1 gives E1   .***..   E, E1, ... , En |- lbn ") ->
     Typing_term  wibble  t5 ->
     Typing_term E_5 (t_letrec (map (fun (pat_:(lb*E)) => match pat_ with (lb_,E_) => lb_ end ) lb_E_list) t5)
with Typing_lb : E -> lb -> E -> Prop :=    (* defn lb *)
 | Typing_lb_simple : forall (E5:E) (x5:x) (t5:t),
     Typing_term E5 t5 ->
     Typing_lb E5 (lb_simple x5 t5) (E_concrete (cons (b_x x5) nil)).


