(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test8.ott *)
theory testRegr_test8
imports Main
begin

type_synonym "value_name" = "string"
type_synonym "ident" = "string"
type_synonym "integer_literal" = "int"
type_synonym "index" = "nat"
datatype "typeconstr" = 
   TC_unit  
 | TC_bool  
 | TC_int  

datatype "typvar" = 
   TV_ident "ident"  

datatype "typexpr" = 
   TE_var "typvar"  
 | TE_arrow "typexpr" "typexpr"  
 | TE_constr0 "typeconstr"  

datatype "constant" = 
   CONST_int "integer_literal"  
 | CONST_false  
 | CONST_true  
 | CONST_unit  
 | CONST_and  
 | CONST_not  

datatype "typscheme" = 
   TS_ts "typvar list" "typexpr"  

datatype "expr" = 
   E_ident "value_name"  
 | E_constant "constant"  
 | E_apply "expr" "expr"  
 | E_function "value_name" "expr"  
 | E_let "value_name" "expr" "expr"  

datatype "G" = 
   G_em  
 | G_vn "G" "value_name" "typscheme"  


(** subrules *)
primrec
is_value_of_expr :: "expr => bool"
where
"is_value_of_expr (E_ident value_name) = (False)"
| "is_value_of_expr (E_constant constant) = ((True))"
| "is_value_of_expr (E_apply expr expr') = (False)"
| "is_value_of_expr (E_function value_name expr) = ((True))"
| "is_value_of_expr (E_let value_name expr expr') = (False)"

(** library functions *)
primrec
list_assoc :: "'a => ('a*'b) list => 'b option"
where
  "list_assoc x0 Nil = None"
| "list_assoc x0 (Cons xy  xys) = (if x0=fst xy then Some (snd xy) else list_assoc x0 xys)"


(** substitutions *)
primrec
tsubst_typexpr :: "(typvar*typexpr) list => typexpr => typexpr"
where
"tsubst_typexpr sub (TE_var typvar) = ((case list_assoc typvar sub of None => (TE_var typvar) | Some t5 => t5))"
| "tsubst_typexpr sub (TE_arrow typexpr typexpr') = (TE_arrow (tsubst_typexpr sub typexpr) (tsubst_typexpr sub typexpr'))"
| "tsubst_typexpr sub (TE_constr0 typeconstr) = (TE_constr0 typeconstr)"

primrec
tsubst_typscheme :: "(typvar*typexpr) list => typscheme => typscheme"
where
"tsubst_typscheme sub (TS_ts (typvar_list) typexpr) = (TS_ts typvar_list (tsubst_typexpr (List.filter (%(tv5,t5).Not(tv5 : set typvar_list)) sub) typexpr))"

primrec
tsubst_G :: "(typvar*typexpr) list => G => G"
where
"tsubst_G sub G_em = (G_em )"
| "tsubst_G sub (G_vn G value_name typscheme) = (G_vn (tsubst_G sub G) value_name (tsubst_typscheme sub typscheme))"

primrec
subst_expr :: "expr => value_name => expr => expr"
where
"subst_expr e5 x5 (E_ident value_name) = ((if value_name=x5 then e5 else (E_ident value_name)))"
| "subst_expr e5 x5 (E_constant constant) = (E_constant constant)"
| "subst_expr e5 x5 (E_apply expr expr') = (E_apply (subst_expr e5 x5 expr) (subst_expr e5 x5 expr'))"
| "subst_expr e5 x5 (E_function value_name expr) = (E_function value_name (if x5 : set [value_name] then expr else (subst_expr e5 x5 expr)))"
| "subst_expr e5 x5 (E_let value_name expr expr') = (E_let value_name (subst_expr e5 x5 expr) (if x5 : set [value_name] then expr' else (subst_expr e5 x5 expr')))"

(** library functions *)
primrec
list_minus :: "'a list => 'a list => 'a list"
where
  "list_minus Nil ys = Nil"
| "list_minus (Cons x xs) ys = (if Not(x : set ys) then Cons x (list_minus xs ys) else list_minus xs ys)"


(** free variables *)
primrec
ftv_typexpr :: "typexpr => typvar list"
where
"ftv_typexpr (TE_var typvar) = ([typvar])"
| "ftv_typexpr (TE_arrow typexpr typexpr') = ((ftv_typexpr typexpr) @ (ftv_typexpr typexpr'))"
| "ftv_typexpr (TE_constr0 typeconstr) = ([])"

primrec
ftv_typscheme :: "typscheme => typvar list"
where
"ftv_typscheme (TS_ts (typvar_list) typexpr) = ([] @ (list_minus (ftv_typexpr typexpr) typvar_list))"

primrec
ftv_G :: "G => typvar list"
where
"ftv_G G_em = ([])"
| "ftv_G (G_vn G value_name typscheme) = ((ftv_G G) @ (ftv_typscheme typscheme))"

(** definitions *)
(* defns Jtype *)
inductive VTSin :: "value_name \<Rightarrow> typscheme \<Rightarrow> G \<Rightarrow> bool"
 and G_constant :: "G \<Rightarrow> constant \<Rightarrow> typexpr \<Rightarrow> bool"
 and Get :: "G \<Rightarrow> expr \<Rightarrow> typexpr \<Rightarrow> bool"
where
(* defn VTSin *)

VTSin_vn1I: "VTSin (value_name) (typscheme) ((G_vn G value_name typscheme))"

| VTSin_vn2I: "\<lbrakk>VTSin (value_name) (typscheme) (G) ;
 Not(  value_name = value_name'  ) \<rbrakk> \<Longrightarrow>
VTSin (value_name) (typscheme) ((G_vn G value_name' typscheme'))"

| (* defn G_constant *)

constant_intI: "G_constant (G) ((CONST_int integer_literal)) ((TE_constr0 TC_int))"

| constant_falseI: "G_constant (G) (CONST_false) ((TE_constr0 TC_bool))"

| constant_trueI: "G_constant (G) (CONST_true) ((TE_constr0 TC_bool))"

| constant_unitI: "G_constant (G) (CONST_unit) ((TE_constr0 TC_unit))"

| constant_andI: "G_constant (G) (CONST_and) ((TE_arrow (TE_constr0 TC_bool)  (TE_arrow (TE_constr0 TC_bool) (TE_constr0 TC_bool)) ))"

| constant_notI: "G_constant (G) (CONST_not) ((TE_arrow (TE_constr0 TC_bool) (TE_constr0 TC_bool)))"

| (* defn Get *)

Get_value_nameI: "\<lbrakk>VTSin (x) (typscheme) (G) ;
 ? typvars . ? typexpr . ? s . 
              typscheme  = TS_ts typvars typexpr 
             & typvars=List.map fst s 
             & tsubst_typexpr s typexpr =  t \<rbrakk> \<Longrightarrow>
Get (G) ((E_ident x)) (t)"

| Get_constantI: "\<lbrakk>G_constant (G) (constant) (t)\<rbrakk> \<Longrightarrow>
Get (G) ((E_constant constant)) (t)"

| Get_applyI: "\<lbrakk>Get (G) (e) ((TE_arrow t1 t2)) ;
Get (G) (e') (t1)\<rbrakk> \<Longrightarrow>
Get (G) ((E_apply e e')) (t2)"

| Get_lambdaI: "\<lbrakk>Get ((G_vn G x1 (TS_ts [] t1))) (e) (t)\<rbrakk> \<Longrightarrow>
Get (G) ((E_function x1 e)) ((TE_arrow t1 t))"

| Get_letI: "\<lbrakk>Get (G) (e) (t) ;
Get ((G_vn G x typscheme)) (e') (t') ;
 typscheme =  (TS_ts (List.remdups (list_minus (ftv_typexpr  t ) (ftv_G  G )))  t )  \<rbrakk> \<Longrightarrow>
Get (G) ((E_let x e e')) (t')"
(** definitions *)
(* defns Jop *)
inductive JO_red :: "expr \<Rightarrow> expr \<Rightarrow> bool"
where
(* defn red *)

JO_red_appI: "\<lbrakk>is_value_of_expr v\<rbrakk> \<Longrightarrow>
JO_red ((E_apply  (E_function x e)  v)) ( subst_expr  v   x   e )"

| JO_red_letI: "\<lbrakk>is_value_of_expr v\<rbrakk> \<Longrightarrow>
JO_red ((E_let x v e)) ( subst_expr  v   x   e )"

| JO_red_context_app1I: "\<lbrakk>JO_red (e) (e')\<rbrakk> \<Longrightarrow>
JO_red ((E_apply e e1)) ((E_apply e' e1))"

| JO_red_context_app2I: "\<lbrakk>is_value_of_expr v ;
JO_red (e) (e')\<rbrakk> \<Longrightarrow>
JO_red ((E_apply v e)) ((E_apply v e'))"

| JO_red_context_letI: "\<lbrakk>JO_red (e) (e')\<rbrakk> \<Longrightarrow>
JO_red ((E_let x e e1)) ((E_let x e' e1))"

| JO_red_not_1I: "JO_red ((E_apply (E_constant CONST_not) (E_constant CONST_true))) ((E_constant CONST_false))"

| JO_red_not_2I: "JO_red ((E_apply (E_constant CONST_not) (E_constant CONST_false))) ((E_constant CONST_true))"

| JO_red_and_1I: "JO_red ((E_apply  (E_apply (E_constant CONST_and) (E_constant CONST_true))  e)) (e)"

| JO_red_and_2I: "JO_red ((E_apply  (E_apply (E_constant CONST_and) (E_constant CONST_false))  e)) ((E_constant CONST_false))"

end



