(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/1Bsemantics/l1.ott *)

type location = UNDEFINED (* Store locations *)

type 
operations =  (* operations *)
   Op_plus
 | Op_gteq


type 
tloc =  (* types of locations *)
   TLoc_intref


type 
expr =  (* expressions *)
   E_num of n
 | E_bool of b
 | E_op of expr * operations * expr
 | E_if of expr * expr * expr
 | E_assign of location * expr
 | E_ref of location
 | E_skip
 | E_sequence of expr * expr
 | E_while of expr * expr


type 
store =  (* stores *)
   Store_empty
 | Store_extend of store * location * n


type 
type_assumption =  (* type assumption *)
   TA_loc of location * tloc


type 
config =  (* configurations *)
   Config_config of expr * store


type 
typ =  (* types *)
   T_int
 | T_bool
 | T_unit


(** subrules *)
let is_v_of_expr (e_5:expr) : bool =
  match e_5 with
  | (E_num n) -> (true)
  | (E_bool b) -> (true)
  | (E_op (e1,op,e2)) -> false
  | (E_if (e1,e2,e3)) -> false
  | (E_assign (l,e1)) -> false
  | (E_ref l) -> false
  | E_skip -> (true)
  | (E_sequence (e1,e2)) -> false
  | (E_while (e1,e2)) -> false


(** definitions *)


