(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.5.ott *)

type value_name = UNDEFINED
type index = UNDEFINED

type 
a = 
   A_x of value_name
 | A_X of (value_name) list
 | A_F of c
 | A_E of ((c * c)) list

and c = 
   C_C of (a) list


(** substitutions *)
let rec subst_c (a_5:a) (x5:value_name) (c5:c) : c =
  match c5 with
  | (C_C (a_list)) -> C_C (List.map (fun a_ -> (subst_a a_5 x5 a_)) a_list)
and
subst_a (a5:a) (x_5:value_name) (a_6:a) : a =
  match a_6 with
  | (A_x x) -> (if x=x_5 then a5 else (A_x x))
  | (A_X (x_list)) -> A_X x_list
  | (A_F c) -> A_F (subst_c a5 x_5 c)
  | (A_E (c_c'_list)) -> A_E (List.map (fun (c_,c'_) -> ((subst_c a5 x_5 c_),(subst_c a5 x_5 c'_))) c_c'_list)




