/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test1.ott -/




abbrev ident := Nat

inductive type : Type where
  | Typ_unit : type
  | Typ_pair (type5 : type) (type' : type) : type
  | Typ_fun (type5 : type) (type' : type) : type
  deriving Inhabited

abbrev E := List (ident × type)


inductive exp : Type where
  | Exp_ident (x : ident) : exp
  | Exp_unit : exp
  | Exp_pair (exp5 : exp) (exp' : exp) : exp
  | Exp_fun (x : ident) (type5 : type) (exp5 : exp) : exp
  | Exp_app (exp5 : exp) (exp' : exp) : exp
  deriving Inhabited
open exp type
def indom (x : ident) (e : E) : Prop :=
  match e with
  | [] => False
  | (x',_) :: tl => if x = x' then True else indom x tl
 
/- definitions -/


/- defns Jtype -/
mutual
/-- defn Eok -/
inductive Eok : E → Prop where
  | Eok_empty :       Eok []

  | Eok_ident : ∀ (E5 : E) (x : ident) (t : type),
      (Eok E5) →
      (¬ ((indom x E5))) →
      Eok ((x, t) :: E5)


/-- defn Eet -/
inductive Eet : E → exp → type → Prop where
  | Eet_ident : ∀ (E5 : E) (x : ident) (t : type) (E' : E),
      (Eok (E' ++ (x, t) :: E5)) →
      Eet (E' ++ (x, t) :: E5) (Exp_ident x) t

  | Eet_unit : ∀ (E5 : E),
      (Eok E5) →
      Eet E5 Exp_unit Typ_unit

  | Eet_pair : ∀ (E5 : E) (e1 : exp) (e2 : exp) (t1 : type) (t2 : type),
      (Eet E5 e1 t1) →
      (Eet E5 e2 t2) →
      Eet E5 (Exp_pair e1 e2) (Typ_pair t1 t2)

  | Eet_fun : ∀ (E5 : E) (x : ident) (t1 : type) (e : exp) (t2 : type),
      (Eet ((x, t1) :: E5) e t2) →
      Eet E5 (Exp_fun x t1 e) (Typ_fun t1 t2)

  | Eet_app : ∀ (E5 : E) (e : exp) (e' : exp) (t2 : type) (t1 : type),
      (Eet E5 e (Typ_fun t1 t2)) →
      (Eet E5 e' t1) →
      Eet E5 (Exp_app e e') t2


end


