/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_2.ott -/




abbrev i := Nat

inductive constant : Type where
  | CONST_unit : constant
  deriving Inhabited

inductive e : Type where
  | E_constant (constant5 : constant) : e
  deriving Inhabited

inductive p : Type where
  | P_constant (constant5 : constant) : p
  deriving Inhabited
open constant p e

/- - subrules - -/
def is_v_of_e (e5:e) : Bool :=
  match e5 with
  | (E_constant constant5) => (true)


inductive list_e : Type where
    | Nil_list_e : list_e
    | Cons_list_e : e -> list_e -> list_e
  deriving Inhabited
open list_e

def map_list_e {A : Type} (f : e -> A) (l : list_e) : List A :=
  match l with
  | Nil_list_e => []
  | Cons_list_e h tl_ => (f h) :: (map_list_e f tl_)

def make_list_e (l : List e) : list_e :=
  match l with
  | [] => Nil_list_e
  | h :: tl_ => Cons_list_e h (make_list_e tl_)

def unmake_list_e (l : list_e) : List e :=
  match l with
  | Nil_list_e => []
  | Cons_list_e h tl_ => h :: (unmake_list_e tl_)

def nth_list_e (n : Nat) (l : list_e) : Option e :=
  match n, l with
  | 0, Cons_list_e h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_e => none
  | k+1, Cons_list_e _ tl_ => nth_list_e k tl_

def app_list_e (l m : list_e) : list_e :=
  match l with
  | Nil_list_e => m
  | Cons_list_e h tl_ => Cons_list_e h (app_list_e tl_ m)

/- definitions -/


/- defns Jred -/
/-- defn match -/
inductive JR_match : e → p → Prop where
  | JR_match_constant : ∀ (v_list : list_e) (v_5 : e) (constant5 : constant),
      (is_v_of_e v_5) →
      (List.all (unmake_list_e v_list) (fun v_ => is_v_of_e v_)) →
      (∀ v_list_ ∈ (unmake_list_e v_list), (fun v_ => (JR_match v_ (P_constant constant5))) v_list_) →
      JR_match v_5 (P_constant constant5)



