(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_subrules_1.ott *)
theory testRegr_test_subrules_1
imports Main
begin

datatype "big" = 
   big_foo "big"  
 | big_bar "big"  
 | big_qux "big"  


(** subrules *)
primrec
is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big :: "big => (bool) * (bool) * (bool)"
where
"is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big (big_foo big) = ((((%(is_tweedledum_of_big,is_tweedledee_of_big,is_big_of_big).is_tweedledum_of_big) (is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big big))) , (((%(is_tweedledum_of_big,is_tweedledee_of_big,is_big_of_big).is_tweedledee_of_big) (is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big big))) , (((%(is_tweedledum_of_big,is_tweedledee_of_big,is_big_of_big).is_big_of_big) (is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big big))))"
| "is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big (big_bar big) = (False , False , (((%(is_tweedledum_of_big,is_tweedledee_of_big,is_big_of_big).is_big_of_big) (is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big big))))"
| "is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big (big_qux tweedledum) = (False , False , (((%(is_tweedledum_of_big,is_tweedledee_of_big,is_big_of_big).is_tweedledum_of_big) (is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big tweedledum))))"

definition is_tweedledum_of_big :: "big => bool" where
"is_tweedledum_of_big == (%(is_tweedledum_of_big,is_tweedledee_of_big,is_big_of_big).is_tweedledum_of_big) o is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big"

definition is_tweedledee_of_big :: "big => bool" where
"is_tweedledee_of_big == (%(is_tweedledum_of_big,is_tweedledee_of_big,is_big_of_big).is_tweedledee_of_big) o is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big"

definition is_big_of_big :: "big => bool" where
"is_big_of_big == (%(is_tweedledum_of_big,is_tweedledee_of_big,is_big_of_big).is_big_of_big) o is_tweedledum_of_big_is_tweedledee_of_big_is_big_of_big"

lemma
"is_tweedledum_of_big (big_foo big) = ((is_tweedledum_of_big big))"
"is_tweedledum_of_big (big_bar big) = False"
"is_tweedledum_of_big (big_qux tweedledum) = False"
"is_tweedledee_of_big (big_foo big) = ((is_tweedledee_of_big big))"
"is_tweedledee_of_big (big_bar big) = False"
"is_tweedledee_of_big (big_qux tweedledum) = False"
"is_big_of_big (big_foo big) = ((is_big_of_big big))"
"is_big_of_big (big_bar big) = ((is_big_of_big big))"
"is_big_of_big (big_qux tweedledum) = ((is_tweedledum_of_big tweedledum))"
  by(simp_all add: is_tweedledum_of_big_def is_tweedledee_of_big_def is_big_of_big_def)


end



