(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test13.ott *)
theory testRegr_test13
imports Main
begin

type_synonym "terminal" = "string"
type_synonym "metavarroot" = "string"
type_synonym "nontermroot" = "string"
type_synonym "suffix" = "string"
type_synonym "auxfn" = "string"
type_synonym "prodname" = "string"
type_synonym "index" = "string"
datatype "metavar" = 
   mv_1 "metavarroot" "suffix"  

datatype "nonterm" = 
   nt_1 "nontermroot" "suffix"  

datatype "mse" = 
   mse_mv "metavar"  
 | mse_nt "nonterm"  
 | mse_f "auxfn" "nonterm"  
 | mse_union "mse" "mse"  
 | mse_empty  

datatype "element" = 
   e_tm "terminal"  
 | e_mv "metavar"  
 | e_nt "nonterm"  

datatype "bindspec" = 
   bs_bind "mse" "nonterm"  
 | bs_auxfn "auxfn" "mse"  

datatype "prod" = 
   p_1 "element list" "prodname" "bindspec list"  

datatype "rule" = 
   r_1 "nontermroot" "prod list"  

datatype "grammar_rules" = 
   g_1 "rule list"  


end



