(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test2.ott *)

type ident = UNDEFINED

type 
t = 
   T_integer
 | T_float


type 
e = 
   E_empty
 | E_ident of e * ident * t


type 
f = 
   F_empty
 | F_ident of e * ident * ident



