/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.6.ott -/





inductive a : Type where
  | a_AAA : a
  | a_BBB : a
  | a_CC : a
  | a_a (a5 : a) : a
  deriving Inhabited
open a

/- - subrules - -/
def is_avv_of_a (a_6:a) : Bool :=
  match a_6 with
  | a_AAA => false
  | a_BBB => false
  | a_CC => false
  | (a_a a5) => (true)


def is_avB_of_a (a_6:a) : Bool :=
  match a_6 with
  | a_AAA => false
  | a_BBB => (true)
  | a_CC => (true)
  | (a_a a5) => (true)


def is_avA_of_a (a_6:a) : Bool :=
  match a_6 with
  | a_AAA => (true)
  | a_BBB => false
  | a_CC => (true)
  | (a_a a5) => (true)


/- definitions -/


/- defns Jtype -/
/-- defn T -/
inductive T : a → a → Prop where
  | T_1 : ∀ (avv5 : a),
      (is_avv_of_a avv5) →
      T avv5 avv5



