/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test10.ott -/




set_option linter.unusedVariables false

/-- term variable -/
abbrev var := String

/-- term -/
inductive term : Type where
  /-- variable -/
  | t_var (x : var) : term
  /-- lambda -/
  | t_lam (x : var) (t : term) : term
  /-- app -/
  | t_app (t : term) (t' : term) : term
  deriving Inhabited
open term

/- - subrules - -/
def is_val_of_term (t5:term) : Bool :=
  match t5 with
  | (t_var x) => false
  | (t_lam x t) => (true)
  | (t_app t t') => false



/- - substitutions - -/
def tsubst_term (t5:term) (x5:var) (t_6:term) : term :=
  match t_6 with
  | (t_var x) => (if x=x5 then t5 else (t_var x))
  | (t_lam x t) => t_lam x (if  List.elem x5 ([x]) then t else (tsubst_term t5 x5 t))
  | (t_app t t') => t_app (tsubst_term t5 x5 t) (tsubst_term t5 x5 t')


/- definitions -/


/- defns Jop -/
/-- defn reduce -/
inductive reduce : term → term → Prop where
  | ax_app : ∀ (x : var) (t1 : term) (v2 : term),
      (is_val_of_term v2) →
      reduce (t_app (t_lam x t1) v2) (tsubst_term v2 x t1)

  | ctx_app_fun : ∀ (t1 : term) (t : term) (t1' : term),
      (reduce t1 t1') →
      reduce (t_app t1 t) (t_app t1' t)

  | ctx_app_arg : ∀ (v : term) (t1 : term) (t1' : term),
      (is_val_of_term v) →
      (reduce t1 t1') →
      reduce (t_app v t1) (t_app v t1')



