/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/bool.ott -/
/- - warning: the backend selected ignores the file structure informations - -/
/- - syntax - -/

/-- terms: -/
inductive t : Type where
  /-- constant true -/
  | TmTrue : t
  /-- constant false -/
  | TmFalse : t
  /-- conditional -/
  | TmIf (t1 : t) (t2 : t) (t3 : t) : t
  deriving Inhabited
open t

/- - auxiliary functions on the new list types - -/
/- - library functions - -/
/- - subrules - -/
def is_v_of_t (t_6:t) : Bool :=
  match t_6 with
  | TmTrue => (true)
  | TmFalse => (true)
  | (TmIf t1 t2 t3) => false


/- - auxiliary functions - -/
/- - free variables - -/
/- - substitutions - -/
/- - context application - -/

/- definitions -/


/- defns Jop -/
/-- defn red -/
inductive red : t → t → Prop where
  | E_IfTrue : ∀ (t2 : t) (t3 : t),
      red (TmIf TmTrue t2 t3) t2

  | E_IfFalse : ∀ (t2 : t) (t3 : t),
      red (TmIf TmFalse t2 t3) t3

  | E_If : ∀ (t1 : t) (t2 : t) (t3 : t) (t1' : t),
      (red t1 t1') →
      red (TmIf t1 t2 t3) (TmIf t1' t2 t3)



