/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test-lj-list_ambiguity.ott -/




abbrev t := String
abbrev i := Nat

mutual
inductive T : Type where
  | T_one (t5 : t) : T
  | T_many (_ : list_T) : T
  deriving Inhabited
inductive list_T : Type where
  | Nil_list_T : list_T
  | Cons_list_T (_ : T) (_ : list_T) : list_T
  deriving Inhabited
end
open list_T T
def map_list_T {A : Type} (f : T -> A) (l : list_T) : List A :=
  match l with
  | Nil_list_T => []
  | Cons_list_T h tl_ => (f h) :: (map_list_T f tl_)

def make_list_T (l : List T) : list_T :=
  match l with
  | [] => Nil_list_T
  | h :: tl_ => Cons_list_T h (make_list_T tl_)

def unmake_list_T (l : list_T) : List T :=
  match l with
  | Nil_list_T => []
  | Cons_list_T h tl_ => h :: (unmake_list_T tl_)

def nth_list_T (n : Nat) (l : list_T) : Option T :=
  match n, l with
  | 0, Cons_list_T h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_T => none
  | k+1, Cons_list_T _ tl_ => nth_list_T k tl_

def app_list_T (l m : list_T) : list_T :=
  match l with
  | Nil_list_T => m
  | Cons_list_T h tl_ => Cons_list_T h (app_list_T tl_ m)


inductive list_t : Type where
    | Nil_list_t : list_t
    | Cons_list_t : t -> list_t -> list_t
  deriving Inhabited
open list_t

def map_list_t {A : Type} (f : t -> A) (l : list_t) : List A :=
  match l with
  | Nil_list_t => []
  | Cons_list_t h tl_ => (f h) :: (map_list_t f tl_)

def make_list_t (l : List t) : list_t :=
  match l with
  | [] => Nil_list_t
  | h :: tl_ => Cons_list_t h (make_list_t tl_)

def unmake_list_t (l : list_t) : List t :=
  match l with
  | Nil_list_t => []
  | Cons_list_t h tl_ => h :: (unmake_list_t tl_)

def nth_list_t (n : Nat) (l : list_t) : Option t :=
  match n, l with
  | 0, Cons_list_t h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_t => none
  | k+1, Cons_list_t _ tl_ => nth_list_t k tl_

def app_list_t (l m : list_t) : list_t :=
  match l with
  | Nil_list_t => m
  | Cons_list_t h tl_ => Cons_list_t h (app_list_t tl_ m)

/- definitions -/


/- defns foo -/
/-- defn bar -/
inductive foo_bar : T → Prop where
  | foo_t_ti :       (PARSE_ERROR "File /home/pes20/claude-home/ott/regression/../tests/test-lj-list_ambiguity.ott on line 18 - 19" "multiple parses")

  | foo_T_t_T' :       (PARSE_ERROR "File /home/pes20/claude-home/ott/regression/../tests/test-lj-list_ambiguity.ott on line 21 - 22" "multiple parses")

  | foo_T_t_ti :       (PARSE_ERROR "File /home/pes20/claude-home/ott/regression/../tests/test-lj-list_ambiguity.ott on line 24 - 25" "multiple parses")

  | foo_T_ti_tj :       (PARSE_ERROR "File /home/pes20/claude-home/ott/regression/../tests/test-lj-list_ambiguity.ott on line 27 - 28" "multiple parses")

  | foo_t_ti2 : ∀ (t_list : list_t) (t_5 : t),
      foo_bar (T_many ((app_list_T (Cons_list_T (T_one t_5) Nil_list_T) (app_list_T (make_list_T (map_list_t (fun t_ => (T_one t_)) t_list)) Nil_list_T))))

  | foo_T_t_T'2 : ∀ (T5 : T) (t5 : t) (T' : T),
      foo_bar (T_many ((app_list_T (Cons_list_T T5 Nil_list_T) (app_list_T (Cons_list_T (T_one t5) Nil_list_T) (app_list_T (Cons_list_T T' Nil_list_T) Nil_list_T)))))

  | foo_T_t_ti2 : ∀ (t_list : list_t) (T5 : T) (t_5 : t),
      foo_bar (T_many ((app_list_T (Cons_list_T T5 Nil_list_T) (app_list_T (Cons_list_T (T_one t_5) Nil_list_T) (app_list_T (make_list_T (map_list_t (fun t_ => (T_one t_)) t_list)) Nil_list_T)))))

  | foo_T_ti_tj2 :       (PARSE_ERROR "File /home/pes20/claude-home/ott/regression/../tests/test-lj-list_ambiguity.ott on line 40 - 41" "multiple parses")



