/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.7.ott -/




abbrev value_name := Nat
abbrev index := Nat

mutual
inductive a : Type where
  | a_var (x : value_name) : a
  | a_let (_ : list_value_name_a) (a_5 : a) : a
  deriving Inhabited
inductive list_value_name_a : Type where
  | Nil_list_value_name_a : list_value_name_a
  | Cons_list_value_name_a (x : value_name) (_ : a) (_ : list_value_name_a) : list_value_name_a
  deriving Inhabited
end

inductive list_value_name : Type where
  | Nil_list_value_name : list_value_name
  | Cons_list_value_name (x : value_name) (_ : list_value_name) : list_value_name
  deriving Inhabited

inductive b : Type where
  | b_var (x : value_name) : b
  | b_let (_ : list_value_name) (a5 : a) : b
  deriving Inhabited
open list_value_name list_value_name_a a b
def map_list_value_name {A : Type} (f : value_name -> A) (l : list_value_name) : List A :=
  match l with
  | Nil_list_value_name => []
  | Cons_list_value_name h tl_ => (f h) :: (map_list_value_name f tl_)

def make_list_value_name (l : List value_name) : list_value_name :=
  match l with
  | [] => Nil_list_value_name
  | h :: tl_ => Cons_list_value_name h (make_list_value_name tl_)

def unmake_list_value_name (l : list_value_name) : List value_name :=
  match l with
  | Nil_list_value_name => []
  | Cons_list_value_name h tl_ => h :: (unmake_list_value_name tl_)

def nth_list_value_name (n : Nat) (l : list_value_name) : Option value_name :=
  match n, l with
  | 0, Cons_list_value_name h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_value_name => none
  | k+1, Cons_list_value_name _ tl_ => nth_list_value_name k tl_

def app_list_value_name (l m : list_value_name) : list_value_name :=
  match l with
  | Nil_list_value_name => m
  | Cons_list_value_name h tl_ => Cons_list_value_name h (app_list_value_name tl_ m)

def map_list_value_name_a {A : Type} (f : value_name -> a -> A) (l : list_value_name_a) : List A :=
  match l with
  | Nil_list_value_name_a => []
  | Cons_list_value_name_a h0 h1 tl_ => (f h0 h1) :: (map_list_value_name_a f tl_)

def make_list_value_name_a (l : List (value_name × a)) : list_value_name_a :=
  match l with
  | [] => Nil_list_value_name_a
  | (h0,h1) :: tl_ => Cons_list_value_name_a h0 h1 (make_list_value_name_a tl_)

def unmake_list_value_name_a (l : list_value_name_a) : List (value_name × a) :=
  match l with
  | Nil_list_value_name_a => []
  | Cons_list_value_name_a h0 h1 tl_ => (h0,h1) :: (unmake_list_value_name_a tl_)

def nth_list_value_name_a (n : Nat) (l : list_value_name_a) : Option (value_name × a) :=
  match n, l with
  | 0, Cons_list_value_name_a h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_value_name_a => none
  | k+1, Cons_list_value_name_a _ _ tl_ => nth_list_value_name_a k tl_

def app_list_value_name_a (l m : list_value_name_a) : list_value_name_a :=
  match l with
  | Nil_list_value_name_a => m
  | Cons_list_value_name_a h0 h1 tl_ => Cons_list_value_name_a h0 h1 (app_list_value_name_a tl_ m)


/- - library functions - -/
def list_assoc {α β : Type} [DecidableEq α] (l:List (α × β)) (x:α) : Option β :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def msubst_value_name_a_list (sub:List (value_name×a)) (a___7:list_value_name_a) : list_value_name_a :=
  match a___7 with
  | Nil_list_value_name_a => Nil_list_value_name_a
  | Cons_list_value_name_a value_name1 a2 value_name_a_tl => Cons_list_value_name_a value_name1 (msubst_a sub a2) (msubst_value_name_a_list sub value_name_a_tl)
def msubst_a (sub:List (value_name×a)) (a___7:a) : a :=
  match a___7 with
  | (a_var x) => (match list_assoc sub x with | none => (a_var x)| some a__6 => a__6 )
  | (a_let x_a_list a_5) => a_let (msubst_value_name_a_list sub x_a_list) (msubst_a (List.filter (fun (x_5,a__6) => not ( List.elem x_5 ((unmake_list_value_name (make_list_value_name (map_list_value_name_a (fun x_ a_ => x_) x_a_list)))))) sub) a_5)
end

mutual
def subst_value_name_a_list (a__6:a) (x_5:value_name) (a___7:list_value_name_a) : list_value_name_a :=
  match a___7 with
  | Nil_list_value_name_a => Nil_list_value_name_a
  | Cons_list_value_name_a value_name1 a2 value_name_a_tl => Cons_list_value_name_a value_name1 (subst_a a__6 x_5 a2) (subst_value_name_a_list a__6 x_5 value_name_a_tl)
def subst_a (a__6:a) (x_5:value_name) (a___7:a) : a :=
  match a___7 with
  | (a_var x) => (if x=x_5 then a__6 else (a_var x))
  | (a_let x_a_list a_5) => a_let (subst_value_name_a_list a__6 x_5 x_a_list) (if  List.elem x_5 ((unmake_list_value_name (make_list_value_name (map_list_value_name_a (fun x_ a_ => x_) x_a_list)))) then a_5 else (subst_a a__6 x_5 a_5))
end

def bmsubst_b (sub:List (value_name×b)) (b_6:b) : b :=
  match b_6 with
  | (b_var x) => (match list_assoc sub x with | none => (b_var x)| some b5 => b5 )
  | (b_let x_list a5) => b_let x_list a5


def bsubst_b (b5:b) (x_5:value_name) (b_6:b) : b :=
  match b_6 with
  | (b_var x) => (if x=x_5 then b5 else (b_var x))
  | (b_let x_list a5) => b_let x_list a5


def msubst_b (sub:List (value_name×a)) (b5:b) : b :=
  match b5 with
  | (b_var x) => b_var x
  | (b_let x_list a5) => b_let x_list (msubst_a (List.filter (fun (x_5,a_6) => not ( List.elem x_5 ((unmake_list_value_name x_list)))) sub) a5)


def subst_b (a_6:a) (x_5:value_name) (b5:b) : b :=
  match b5 with
  | (b_var x) => b_var x
  | (b_let x_list a5) => b_let x_list (if  List.elem x_5 ((unmake_list_value_name x_list)) then a5 else (subst_a a_6 x_5 a5))




