/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.11.ott -/




/-- type variable -/
abbrev typevar := Nat
/-- term variable -/
abbrev termvar := Nat
/-- field label -/
abbrev label := Nat
/-- indices -/
abbrev index := Nat

/-- type -/
inductive T : Type where
  /-- type variable -/
  | T_Var (X : typevar) : T
  /-- maximum type -/
  | T_Top : T
  /-- type of functions -/
  | T_Fun (T5 : T) (T' : T) : T
  /-- universal type -/
  | T_Forall (X : typevar) (T5 : T) (T' : T) : T
  /-- record -/
  | T_Rec (_ : List (label × T)) : T
  deriving Inhabited

/-- pattern -/
inductive p : Type where
  /-- variable pattern -/
  | P_Var (x : termvar) (T5 : T) : p
  /-- record pattern -/
  | P_Rec (_ : List (label × p)) : p
  deriving Inhabited

/-- term -/
inductive t : Type where
  /-- variable -/
  | t_Var (x : termvar) : t
  /-- abstraction -/
  | t_Lam (x : termvar) (T5 : T) (t5 : t) : t
  /-- application -/
  | t_App (t5 : t) (t' : t) : t
  /-- type abstraction -/
  | t_TLam (X : typevar) (T5 : T) (t5 : t) : t
  /-- type application -/
  | t_TApp (t5 : t) (T5 : T) : t
  /-- record -/
  | t_Rec (_ : List (label × t)) : t
  /-- projection -/
  | t_Proj (t5 : t) (l : label) : t
  /-- pattern binding -/
  | t_Let (p5 : p) (t5 : t) (t' : t) : t
  deriving Inhabited

/-- multiple term substitution -/
inductive s : Type where
  | S_singleton (x : termvar) (t5 : t) : s
  | S_list (_ : List s) : s
  deriving Inhabited

/-- type environment -/
inductive G : Type where
  | G_empty : G
  | G_type (G5 : G) (X : typevar) (T5 : T) : G
  | G_term (G5 : G) (x : termvar) (T5 : T) : G
  deriving Inhabited
open T t p G s
mutual
def aux_b_p_of_p_list (l_p_list:List (label × p)) : List termvar :=
  match l_p_list with
  | [] => []
  | (l_,p_) :: l_p_list_ => (aux_b_p_of_p p_) ++ (aux_b_p_of_p_list l_p_list_)
def aux_b_p_of_p (p_5:p) : List termvar :=
  match p_5 with
  | (P_Var x T5) => [x]
  | (P_Rec (l_p_list)) => (aux_b_p_of_p_list l_p_list)
end


/- - subrules - -/
mutual
def is_v_of_l_t_list (l_t_list:List (label × t)) : Bool :=
  match l_t_list with
  | [] => true
  | (l_,t_) :: l_t_list_ => ((is_v_of_t t_)) && (is_v_of_l_t_list l_t_list_)
def is_v_of_t (t_6:t) : Bool :=
  match t_6 with
  | (t_Var x) => false
  | (t_Lam x T5 t5) => (true)
  | (t_App t5 t') => false
  | (t_TLam X T5 t5) => (true)
  | (t_TApp t5 T5) => false
  | (t_Rec (l_t_list)) => (is_v_of_l_t_list l_t_list)
  | (t_Proj t5 l) => false
  | (t_Let p5 t5 t') => false
end

/- - library functions - -/
def list_assoc {α β : Type} [DecidableEq α] (l:List (α × β)) (x:α) : Option β :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def m_T_subst_label_T_list (sub:List (typevar×T)) (l_T_list:List (label × T)) : List (label × T) :=
  match l_T_list with
  | [] => []
  | (l_,T_) :: l_T_list_ => (l_,(m_T_subst_T sub T_)) :: (m_T_subst_label_T_list sub l_T_list_)
def m_T_subst_T (sub:List (typevar×T)) (S_6:T) : T :=
  match S_6 with
  | (T_Var X) => (match list_assoc sub X with | none => (T_Var X)| some S5 => S5 )
  | T_Top => T_Top 
  | (T_Fun T5 T') => T_Fun (m_T_subst_T sub T5) (m_T_subst_T sub T')
  | (T_Forall X T5 T') => T_Forall X (m_T_subst_T sub T5) (m_T_subst_T (List.filter (fun (X5,S5) => not ( List.elem X5 ([X]))) sub) T')
  | (T_Rec (l_T_list)) => T_Rec (m_T_subst_label_T_list sub l_T_list)
end

mutual
def Tsubst_label_T_list (S5:T) (X5:typevar) (l_T_list:List (label × T)) : List (label × T) :=
  match l_T_list with
  | [] => []
  | (l_,T_) :: l_T_list_ => (l_,(Tsubst_T S5 X5 T_)) :: (Tsubst_label_T_list S5 X5 l_T_list_)
def Tsubst_T (S5:T) (X5:typevar) (S_6:T) : T :=
  match S_6 with
  | (T_Var X) => (if X=X5 then S5 else (T_Var X))
  | T_Top => T_Top 
  | (T_Fun T5 T') => T_Fun (Tsubst_T S5 X5 T5) (Tsubst_T S5 X5 T')
  | (T_Forall X T5 T') => T_Forall X (Tsubst_T S5 X5 T5) (if  List.elem X5 ([X]) then T' else (Tsubst_T S5 X5 T'))
  | (T_Rec (l_T_list)) => T_Rec (Tsubst_label_T_list S5 X5 l_T_list)
end

mutual
def m_T_subst_label_p_list (sub:List (typevar×T)) (l_p_list:List (label × p)) : List (label × p) :=
  match l_p_list with
  | [] => []
  | (l_,p_) :: l_p_list_ => (l_,(m_T_subst_p sub p_)) :: (m_T_subst_label_p_list sub l_p_list_)
def m_T_subst_p (sub:List (typevar×T)) (p_5:p) : p :=
  match p_5 with
  | (P_Var x T5) => P_Var x (m_T_subst_T sub T5)
  | (P_Rec (l_p_list)) => P_Rec (m_T_subst_label_p_list sub l_p_list)
end

mutual
def Tsubst_label_p_list (S5:T) (X5:typevar) (l_p_list:List (label × p)) : List (label × p) :=
  match l_p_list with
  | [] => []
  | (l_,p_) :: l_p_list_ => (l_,(Tsubst_p S5 X5 p_)) :: (Tsubst_label_p_list S5 X5 l_p_list_)
def Tsubst_p (S5:T) (X5:typevar) (p_5:p) : p :=
  match p_5 with
  | (P_Var x T5) => P_Var x (Tsubst_T S5 X5 T5)
  | (P_Rec (l_p_list)) => P_Rec (Tsubst_label_p_list S5 X5 l_p_list)
end

mutual
def tsubst_label_t_list (t_6:t) (x5:termvar) (l_t_list:List (label × t)) : List (label × t) :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (l_,(tsubst_t t_6 x5 t_)) :: (tsubst_label_t_list t_6 x5 l_t_list_)
def tsubst_t (t_6:t) (x5:termvar) (t__7:t) : t :=
  match t__7 with
  | (t_Var x) => (if x=x5 then t_6 else (t_Var x))
  | (t_Lam x T5 t5) => t_Lam x T5 (if  List.elem x5 ([x]) then t5 else (tsubst_t t_6 x5 t5))
  | (t_App t5 t') => t_App (tsubst_t t_6 x5 t5) (tsubst_t t_6 x5 t')
  | (t_TLam X T5 t5) => t_TLam X T5 (tsubst_t t_6 x5 t5)
  | (t_TApp t5 T5) => t_TApp (tsubst_t t_6 x5 t5) T5
  | (t_Rec (l_t_list)) => t_Rec (tsubst_label_t_list t_6 x5 l_t_list)
  | (t_Proj t5 l) => t_Proj (tsubst_t t_6 x5 t5) l
  | (t_Let p5 t5 t') => t_Let p5 (tsubst_t t_6 x5 t5) (if  List.elem x5 ((aux_b_p_of_p p5)) then t' else (tsubst_t t_6 x5 t'))
end

mutual
def m_T_subst_label_t_list (sub:List (typevar×T)) (l_t_list:List (label × t)) : List (label × t) :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (l_,(m_T_subst_t sub t_)) :: (m_T_subst_label_t_list sub l_t_list_)
def m_T_subst_t (sub:List (typevar×T)) (t_6:t) : t :=
  match t_6 with
  | (t_Var x) => t_Var x
  | (t_Lam x T5 t5) => t_Lam x (m_T_subst_T sub T5) (m_T_subst_t sub t5)
  | (t_App t5 t') => t_App (m_T_subst_t sub t5) (m_T_subst_t sub t')
  | (t_TLam X T5 t5) => t_TLam X (m_T_subst_T sub T5) (m_T_subst_t (List.filter (fun (X5,S5) => not ( List.elem X5 ([X]))) sub) t5)
  | (t_TApp t5 T5) => t_TApp (m_T_subst_t sub t5) (m_T_subst_T sub T5)
  | (t_Rec (l_t_list)) => t_Rec (m_T_subst_label_t_list sub l_t_list)
  | (t_Proj t5 l) => t_Proj (m_T_subst_t sub t5) l
  | (t_Let p5 t5 t') => t_Let (m_T_subst_p sub p5) (m_T_subst_t sub t5) (m_T_subst_t sub t')
end

mutual
def m_t_subst_label_t_list (sub:List (termvar×t)) (l_t_list:List (label × t)) : List (label × t) :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (l_,(m_t_subst_t sub t_)) :: (m_t_subst_label_t_list sub l_t_list_)
def m_t_subst_t (sub:List (termvar×t)) (t__7:t) : t :=
  match t__7 with
  | (t_Var x) => (match list_assoc sub x with | none => (t_Var x)| some t_6 => t_6 )
  | (t_Lam x T5 t5) => t_Lam x T5 (m_t_subst_t (List.filter (fun (x5,t_6) => not ( List.elem x5 ([x]))) sub) t5)
  | (t_App t5 t') => t_App (m_t_subst_t sub t5) (m_t_subst_t sub t')
  | (t_TLam X T5 t5) => t_TLam X T5 (m_t_subst_t sub t5)
  | (t_TApp t5 T5) => t_TApp (m_t_subst_t sub t5) T5
  | (t_Rec (l_t_list)) => t_Rec (m_t_subst_label_t_list sub l_t_list)
  | (t_Proj t5 l) => t_Proj (m_t_subst_t sub t5) l
  | (t_Let p5 t5 t') => t_Let p5 (m_t_subst_t sub t5) (m_t_subst_t (List.filter (fun (x5,t_6) => not ( List.elem x5 ((aux_b_p_of_p p5)))) sub) t')
end

mutual
def Tsubst_label_t_list (S5:T) (X5:typevar) (l_t_list:List (label × t)) : List (label × t) :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (l_,(Tsubst_t S5 X5 t_)) :: (Tsubst_label_t_list S5 X5 l_t_list_)
def Tsubst_t (S5:T) (X5:typevar) (t_6:t) : t :=
  match t_6 with
  | (t_Var x) => t_Var x
  | (t_Lam x T5 t5) => t_Lam x (Tsubst_T S5 X5 T5) (Tsubst_t S5 X5 t5)
  | (t_App t5 t') => t_App (Tsubst_t S5 X5 t5) (Tsubst_t S5 X5 t')
  | (t_TLam X T5 t5) => t_TLam X (Tsubst_T S5 X5 T5) (if  List.elem X5 ([X]) then t5 else (Tsubst_t S5 X5 t5))
  | (t_TApp t5 T5) => t_TApp (Tsubst_t S5 X5 t5) (Tsubst_T S5 X5 T5)
  | (t_Rec (l_t_list)) => t_Rec (Tsubst_label_t_list S5 X5 l_t_list)
  | (t_Proj t5 l) => t_Proj (Tsubst_t S5 X5 t5) l
  | (t_Let p5 t5 t') => t_Let (Tsubst_p S5 X5 p5) (Tsubst_t S5 X5 t5) (Tsubst_t S5 X5 t')
end

mutual
def tsubst_s_list (t_6:t) (x5:termvar) (s_list:List s) : List s :=
  match s_list with
  | [] => []
  | s_ :: s_list_ => (tsubst_s t_6 x5 s_) :: (tsubst_s_list t_6 x5 s_list_)
def tsubst_s (t_6:t) (x5:termvar) (s_5:s) : s :=
  match s_5 with
  | (S_singleton x t5) => S_singleton x (tsubst_t t_6 x5 t5)
  | (S_list (s_list)) => S_list (tsubst_s_list t_6 x5 s_list)
end

mutual
def m_T_subst_s_list (sub:List (typevar×T)) (s_list:List s) : List s :=
  match s_list with
  | [] => []
  | s_ :: s_list_ => (m_T_subst_s sub s_) :: (m_T_subst_s_list sub s_list_)
def m_T_subst_s (sub:List (typevar×T)) (s_5:s) : s :=
  match s_5 with
  | (S_singleton x t5) => S_singleton x (m_T_subst_t sub t5)
  | (S_list (s_list)) => S_list (m_T_subst_s_list sub s_list)
end

def m_T_subst_G (sub:List (typevar×T)) (D5:G) : G :=
  match D5 with
  | G_empty => G_empty 
  | (G_type G5 X T5) => G_type (m_T_subst_G sub G5) X (m_T_subst_T sub T5)
  | (G_term G5 x T5) => G_term (m_T_subst_G sub G5) x (m_T_subst_T sub T5)


mutual
def m_t_subst_s_list (sub:List (termvar×t)) (s_list:List s) : List s :=
  match s_list with
  | [] => []
  | s_ :: s_list_ => (m_t_subst_s sub s_) :: (m_t_subst_s_list sub s_list_)
def m_t_subst_s (sub:List (termvar×t)) (s_5:s) : s :=
  match s_5 with
  | (S_singleton x t5) => S_singleton x (m_t_subst_t sub t5)
  | (S_list (s_list)) => S_list (m_t_subst_s_list sub s_list)
end

mutual
def Tsubst_s_list (S5:T) (X5:typevar) (s_list:List s) : List s :=
  match s_list with
  | [] => []
  | s_ :: s_list_ => (Tsubst_s S5 X5 s_) :: (Tsubst_s_list S5 X5 s_list_)
def Tsubst_s (S5:T) (X5:typevar) (s_5:s) : s :=
  match s_5 with
  | (S_singleton x t5) => S_singleton x (Tsubst_t S5 X5 t5)
  | (S_list (s_list)) => S_list (Tsubst_s_list S5 X5 s_list)
end

def Tsubst_G (S5:T) (X5:typevar) (D5:G) : G :=
  match D5 with
  | G_empty => G_empty 
  | (G_type G5 X T5) => G_type (Tsubst_G S5 X5 G5) X (Tsubst_T S5 X5 T5)
  | (G_term G5 x T5) => G_term (Tsubst_G S5 X5 G5) x (Tsubst_T S5 X5 T5)


/- - library functions - -/
def list_minus {α : Type} [BEq α] (l1:List α) (l2:List α) : (List α) :=
  match l1 with
  | [] => []
  | h::t => if List.elem h l2 then list_minus t l2 else h::(list_minus t l2)


/- - free variables - -/
mutual
def ftv_label_T_list (l_T_list:List (label × T)) : List typevar :=
  match l_T_list with
  | [] => []
  | (l_,T_) :: l_T_list_ => (ftv_T T_) ++ (ftv_label_T_list l_T_list_)
def ftv_T (S5:T) :  List typevar :=
  match S5 with
  | (T_Var X) => [X]
  | T_Top => []
  | (T_Fun T5 T') => (ftv_T T5) ++ (ftv_T T')
  | (T_Forall X T5 T') => (ftv_T T5) ++ (list_minus (ftv_T T') [X])
  | (T_Rec (l_T_list)) => (ftv_label_T_list l_T_list)
end

mutual
def ftv_label_p_list (l_p_list:List (label × p)) : List typevar :=
  match l_p_list with
  | [] => []
  | (l_,p_) :: l_p_list_ => (ftv_p p_) ++ (ftv_label_p_list l_p_list_)
def ftv_p (p_5:p) :  List typevar :=
  match p_5 with
  | (P_Var x T5) => (ftv_T T5)
  | (P_Rec (l_p_list)) => (ftv_label_p_list l_p_list)
end

mutual
def fv_label_t_list (l_t_list:List (label × t)) : List termvar :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (fv_t t_) ++ (fv_label_t_list l_t_list_)
def fv_t (t_6:t) :  List termvar :=
  match t_6 with
  | (t_Var x) => [x]
  | (t_Lam x T5 t5) => (list_minus (fv_t t5) [x])
  | (t_App t5 t') => (fv_t t5) ++ (fv_t t')
  | (t_TLam X T5 t5) => (fv_t t5)
  | (t_TApp t5 T5) => (fv_t t5)
  | (t_Rec (l_t_list)) => (fv_label_t_list l_t_list)
  | (t_Proj t5 l) => (fv_t t5)
  | (t_Let p5 t5 t') => (fv_t t5) ++ (list_minus (fv_t t') (aux_b_p_of_p p5))
end

mutual
def ftv_label_t_list (l_t_list:List (label × t)) : List typevar :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (ftv_t t_) ++ (ftv_label_t_list l_t_list_)
def ftv_t (t_6:t) :  List typevar :=
  match t_6 with
  | (t_Var x) => []
  | (t_Lam x T5 t5) => (ftv_T T5) ++ (ftv_t t5)
  | (t_App t5 t') => (ftv_t t5) ++ (ftv_t t')
  | (t_TLam X T5 t5) => (ftv_T T5) ++ (list_minus (ftv_t t5) [X])
  | (t_TApp t5 T5) => (ftv_t t5) ++ (ftv_T T5)
  | (t_Rec (l_t_list)) => (ftv_label_t_list l_t_list)
  | (t_Proj t5 l) => (ftv_t t5)
  | (t_Let p5 t5 t') => (ftv_p p5) ++ (ftv_t t5) ++ (ftv_t t')
end

mutual
def fv_s_list (s_list:List s) : List termvar :=
  match s_list with
  | [] => []
  | s_ :: s_list_ => (fv_s s_) ++ (fv_s_list s_list_)
def fv_s (s_5:s) :  List termvar :=
  match s_5 with
  | (S_singleton x t5) => (fv_t t5)
  | (S_list (s_list)) => (fv_s_list s_list)
end

mutual
def ftv_s_list (s_list:List s) : List typevar :=
  match s_list with
  | [] => []
  | s_ :: s_list_ => (ftv_s s_) ++ (ftv_s_list s_list_)
def ftv_s (s_5:s) :  List typevar :=
  match s_5 with
  | (S_singleton x t5) => (ftv_t t5)
  | (S_list (s_list)) => (ftv_s_list s_list)
end

def ftv_G (D5:G) :  List typevar :=
  match D5 with
  | G_empty => []
  | (G_type G5 X T5) => (ftv_G G5) ++ (ftv_T T5)
  | (G_term G5 x T5) => (ftv_G G5) ++ (ftv_T T5)


/- definitions -/


/- defns Judgement_in -/
mutual
/-- defn xinG -/
inductive xinG : termvar → G → Prop where
  | xinG_1 : ∀ (x : termvar) (G5 : G) (T5 : T),
      xinG x (G_term G5 x T5)

  | xinG_2 : ∀ (x : termvar) (G5 : G) (X' : typevar) (U' : T),
      (xinG x G5) →
      xinG x (G_type G5 X' U')

  | xinG_3 : ∀ (x : termvar) (G5 : G) (x' : termvar) (T' : T),
      (xinG x G5) →
      xinG x (G_term G5 x' T')


/-- defn XinG -/
inductive XinG : typevar → G → Prop where
  | XinG_1 : ∀ (X : typevar) (G5 : G) (U : T),
      XinG X (G_type G5 X U)

  | XinG_2 : ∀ (X : typevar) (G5 : G) (X' : typevar) (U' : T),
      (XinG X G5) →
      XinG X (G_type G5 X' U')

  | XinG_3 : ∀ (X : typevar) (G5 : G) (x' : termvar) (T' : T),
      (XinG X G5) →
      XinG X (G_term G5 x' T')


/-- defn tin -/
inductive tin : termvar → T → G → Prop where
  | tin_1 : ∀ (x : termvar) (T5 : T) (G5 : G),
      tin x T5 (G_term G5 x T5)

  | tin_2 : ∀ (x : termvar) (T5 : T) (G5 : G) (X' : typevar) (U' : T),
      (tin x T5 G5) →
      tin x T5 (G_type G5 X' U')

  | tin_3 : ∀ (x : termvar) (T5 : T) (G5 : G) (x' : termvar) (T' : T),
      (tin x T5 G5) →
      tin x T5 (G_term G5 x' T')


/-- defn Tin -/
inductive Tin : typevar → T → G → Prop where
  | Tin_1 : ∀ (X : typevar) (U : T) (G5 : G),
      Tin X U (G_type G5 X U)

  | Tin_2 : ∀ (X : typevar) (U : T) (G5 : G) (X' : typevar) (U' : T),
      (Tin X U G5) →
      Tin X U (G_type G5 X' U')

  | Tin_3 : ∀ (X : typevar) (U : T) (G5 : G) (x' : termvar) (T' : T),
      (Tin X U G5) →
      Tin X U (G_term G5 x' T')


end
/- definitions -/


/- defns Jtype -/
mutual
/-- defn Gok -/
inductive Gok : G → Prop where
  | Gok_1 :       Gok G_empty

  | Gok_2 : ∀ (G5 : G) (x : termvar) (T5 : T),
      (GT G5 T5) →
      (¬ ((xinG x G5))) →
      Gok (G_term G5 x T5)

  | Gok_3 : ∀ (G5 : G) (X : typevar) (T5 : T),
      (GT G5 T5) →
      (¬ ((XinG X G5))) →
      Gok (G_type G5 X T5)


/-- defn GT -/
inductive GT : G → T → Prop where
  | GT_Var : ∀ (G5 : G) (X : typevar) (U : T),
      (Gok G5) →
      (Tin X U G5) →
      GT G5 (T_Var X)

  | GT_Top : ∀ (G5 : G),
      (Gok G5) →
      GT G5 T_Top

  | GT_Fun : ∀ (G5 : G) (T5 : T) (T' : T),
      (GT G5 T5) →
      (GT G5 T') →
      GT G5 (T_Fun T5 T')

  | GT_Forall : ∀ (G5 : G) (X : typevar) (T5 : T) (T' : T),
      (GT (G_type G5 X T5) T') →
      GT G5 (T_Forall X T5 T')

  | GT_Rcd : ∀ (l_T_list : List (label × T)) (G5 : G),
      (∀ l_T_list_ ∈ l_T_list, (fun (l_,T_) => (GT G5 T_)) l_T_list_) →
      GT G5 (T_Rec (l_T_list))


/-- defn SA -/
inductive SA : G → T → T → Prop where
  | SA_Top : ∀ (G5 : G) (S : T),
      (Gok G5) →
      SA G5 S T_Top

  | SA_Refl_TVar : ∀ (G5 : G) (X : typevar),
      (Gok G5) →
      SA G5 (T_Var X) (T_Var X)

  | SA_Trans_TVar : ∀ (G5 : G) (X : typevar) (T5 : T) (U : T),
      (Tin X U G5) →
      (SA G5 U T5) →
      SA G5 (T_Var X) T5

  | SA_Arrow : ∀ (G5 : G) (S1 : T) (S2 : T) (T1 : T) (T2 : T),
      (SA G5 T1 S1) →
      (SA G5 S2 T2) →
      SA G5 (T_Fun S1 S2) (T_Fun T1 T2)

  | SA_All : ∀ (G5 : G) (X : typevar) (S1 : T) (S2 : T) (T1 : T) (T2 : T),
      (SA G5 T1 S1) →
      (SA (G_type G5 X T1) S2 T2) →
      SA G5 (T_Forall X S1 S2) (T_Forall X T1 T2)

  | SA_Rcd : ∀ (l_T_list : List (label × T)) (k_S_list : List (label × T)) (G5 : G) (i : index) (m : index) (j : index) (n : index),
      (forall i, (1<= i /\ i <= m) -> exists j, (1<= j /\ j <= n) -> (((((fun (k_,S_) => k_) (k_S_list[i]!)) = ((fun (l_,T_) => l_) (l_T_list[j]!))) /\ SA G5 ((fun (k_,S_) => S_) (k_S_list[i]!)) ((fun (l_,T_) => T_) (l_T_list[j]!))))) →
      SA G5 (T_Rec (k_S_list)) (T_Rec (l_T_list))


/-- defn Ty -/
inductive Ty : G → t → T → Prop where
  | Ty_Var : ∀ (G5 : G) (x : termvar) (T5 : T),
      (Gok G5) →
      (tin x T5 G5) →
      Ty G5 (t_Var x) T5

  | Ty_Abs : ∀ (G5 : G) (x : termvar) (T1 : T) (t2 : t) (T2 : T),
      (Ty (G_term G5 x T1) t2 T2) →
      Ty G5 (t_Lam x T1 t2) (T_Fun T1 T2)

  | Ty_App : ∀ (G5 : G) (t1 : t) (t2 : t) (T12 : T) (T11 : T),
      (Ty G5 t1 (T_Fun T11 T12)) →
      (Ty G5 t2 T11) →
      Ty G5 (t_App t1 t2) T12

  | Ty_TAbs : ∀ (G5 : G) (X : typevar) (T1 : T) (t2 : t) (T2 : T),
      (Ty (G_type G5 X T1) t2 T2) →
      Ty G5 (t_TLam X T1 t2) (T_Forall X T1 T2)

  | Ty_TApp : ∀ (G5 : G) (t1 : t) (T2 : T) (X : typevar) (T12 : T) (T11 : T),
      (Ty G5 t1 (T_Forall X T11 T12)) →
      (SA G5 T2 T11) →
      Ty G5 (t_TApp t1 T2) (Tsubst_T T2 X T12)

  | Ty_Let : ∀ (G5 : G) (p5 : p) (t1 : t) (t2 : t) (T2 : T) (T1 : T) (D : G),
      (Ty G5 t1 T1) →
      (Pat p5 T1 D) →
      (Ty (flatten_G ([(G5)] ++ [(D)])) t2 T2) →
      Ty G5 (t_Let p5 t1 t2) T2

  | Ty_Rcd : ∀ (l_t_T_list : List (label × t × T)) (G5 : G),
      (∀ l_t_T_list_ ∈ l_t_T_list, (fun (l_,t_,T_) => (Ty G5 t_ T_)) l_t_T_list_) →
      Ty G5 (t_Rec ((List.map (fun (l_,t_,T_) => (l_,t_)) l_t_T_list))) (T_Rec ((List.map (fun (l_,t_,T_) => (l_,T_)) l_t_T_list)))

  | Ty_Proj : ∀ (l_T_list : List (label × T)) (j : index) (G5 : G) (t5 : t),
      (Ty G5 t5 (T_Rec (l_T_list))) →
      Ty G5 (t_Proj t5 ((fun (l_,T_) => l_) (l_T_list[j]!))) ((fun (l_,T_) => T_) (l_T_list[j]!))

  | Ty_Sub : ∀ (G5 : G) (t5 : t) (T5 : T) (S : T),
      (Ty G5 t5 S) →
      (SA G5 S T5) →
      Ty G5 t5 T5


/-- defn Pat -/
inductive Pat : p → T → G → Prop where
  | Pat_Var : ∀ (x : termvar) (T5 : T),
      Pat (P_Var x T5) T5 (G_term G_empty x T5)

  | Pat_Rcd : ∀ (l_p_T_D_list : List (label × p × T × G)),
      (∀ l_p_T_D_list_ ∈ l_p_T_D_list, (fun (l_,p_,T_,D_) => (Pat p_ T_ D_)) l_p_T_D_list_) →
      Pat (P_Rec ((List.map (fun (l_,p_,T_,D_) => (l_,p_)) l_p_T_D_list))) (T_Rec ((List.map (fun (l_,p_,T_,D_) => (l_,T_)) l_p_T_D_list))) (flatten_G ((List.map (fun (l_,p_,T_,D_) => D_) l_p_T_D_list)))


end
/- definitions -/


/- defns Jop -/
mutual
/-- defn reduce -/
inductive reduce : t → t → Prop where
  | reduce_AppAbs : ∀ (x : termvar) (T11 : T) (t12 : t) (v2 : t),
      (is_v_of_t v2) →
      reduce (t_App (t_Lam x T11 t12) v2) (tsubst_t v2 x t12)

  | reduce_TappTabs : ∀ (X : typevar) (T11 : T) (t12 : t) (T2 : T),
      reduce (t_TApp (t_TLam X T11 t12) T2) (Tsubst_t T2 X t12)

  | reduce_LetV : ∀ (p5 : p) (t2 : t) (s5 : s) (v1 : t),
      (is_v_of_t v1) →
      (is_v_of_t v1) →
      (M p5 v1 s5) →
      reduce (t_Let p5 v1 t2) (m_t_subst_t s5 t2)

  | reduce_ProjRcd : ∀ (l'_v_list : List (label × t)) (j : index),
      (List.all l'_v_list (fun (l'_,v_) => is_v_of_t v_)) →
      reduce (t_Proj (t_Rec (l'_v_list)) ((fun (l'_,v_) => l'_) (l'_v_list[j]!))) ((fun (l'_,v_) => v_) (l'_v_list[j]!))

  | reduce_Ctx_app_fun : ∀ (t1 : t) (t_5 : t) (t1' : t),
      (reduce t1 t1') →
      reduce (t_App t1 t_5) (t_App t1' t_5)

  | reduce_Ctx_app_arg : ∀ (v5 : t) (t1 : t) (t1' : t),
      (is_v_of_t v5) →
      (reduce t1 t1') →
      reduce (t_App v5 t1) (t_App v5 t1')

  | reduce_Ctx_type_fun : ∀ (t1 : t) (T5 : T) (t1' : t),
      (reduce t1 t1') →
      reduce (t_TApp t1 T5) (t_TApp t1' T5)

  | reduce_Ctx_record : ∀ (l'_t_list : List (label × t)) (l_v_list : List (label × t)) (l : label) (t_5 : t) (t' : t),
      (List.all l_v_list (fun (l_,v_) => is_v_of_t v_)) →
      (reduce t_5 t') →
      reduce (t_Rec (l_v_list ++ [(l,t_5)] ++ l'_t_list)) (t_Rec (l_v_list ++ [(l,t')] ++ l'_t_list))

  | reduce_Ctx_let_binding : ∀ (p5 : p) (t1 : t) (t2 : t) (t1' : t),
      (reduce t1 t1') →
      reduce (t_Let p5 t1 t2) (t_Let p5 t1' t2)


/-- defn M -/
inductive M : p → t → s → Prop where
  | M_Var : ∀ (x : termvar) (T5 : T) (v5 : t),
      (is_v_of_t v5) →
      (is_v_of_t v5) →
      M (P_Var x T5) v5 (S_singleton x v5)

  | M_Rcd : ∀ (l_p_s_list : List (label × p × s)) (k_v_list : List (label × t)) (i : index) (m : index) (j : index) (n : index),
      (List.all k_v_list (fun (k_,v_) => is_v_of_t v_)) →
      (forall i, (1<= i /\ i <= m) -> exists j, (1<= j /\ j <= n) -> (((((fun (l_,p_,s_) => l_) (l_p_s_list[i]!)) = ((fun (k_,v_) => k_) (k_v_list[j]!))) /\ M ((fun (l_,p_,s_) => p_) (l_p_s_list[i]!)) ((fun (k_,v_) => v_) (k_v_list[j]!)) ((fun (l_,p_,s_) => s_) (l_p_s_list[i]!))))) →
      M (P_Rec ((List.map (fun (l_,p_,s_) => (l_,p_)) l_p_s_list))) (t_Rec (k_v_list)) (S_list ((List.map (fun (l_,p_,s_) => s_) l_p_s_list)))


end


