/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_subrule_1.ott -/




abbrev i := Nat
abbrev x := Nat

inductive foobar : Type where
  | foobar_foo : foobar
  | foobar_bar : foobar
  deriving Inhabited

inductive list_foobar_foobar : Type where
  | Nil_list_foobar_foobar : list_foobar_foobar
  | Cons_list_foobar_foobar (foo : foobar) (_ : foobar) (_ : list_foobar_foobar) : list_foobar_foobar
  deriving Inhabited

inductive seq : Type where
  | seq_foofoobar (_ : list_foobar_foobar) : seq
  deriving Inhabited
open list_foobar_foobar foobar seq
def map_list_foobar_foobar {A : Type} (f : foobar -> foobar -> A) (l : list_foobar_foobar) : List A :=
  match l with
  | Nil_list_foobar_foobar => []
  | Cons_list_foobar_foobar h0 h1 tl_ => (f h0 h1) :: (map_list_foobar_foobar f tl_)

def make_list_foobar_foobar (l : List (foobar × foobar)) : list_foobar_foobar :=
  match l with
  | [] => Nil_list_foobar_foobar
  | (h0,h1) :: tl_ => Cons_list_foobar_foobar h0 h1 (make_list_foobar_foobar tl_)

def unmake_list_foobar_foobar (l : list_foobar_foobar) : List (foobar × foobar) :=
  match l with
  | Nil_list_foobar_foobar => []
  | Cons_list_foobar_foobar h0 h1 tl_ => (h0,h1) :: (unmake_list_foobar_foobar tl_)

def nth_list_foobar_foobar (n : Nat) (l : list_foobar_foobar) : Option (foobar × foobar) :=
  match n, l with
  | 0, Cons_list_foobar_foobar h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_foobar_foobar => none
  | k+1, Cons_list_foobar_foobar _ _ tl_ => nth_list_foobar_foobar k tl_

def app_list_foobar_foobar (l m : list_foobar_foobar) : list_foobar_foobar :=
  match l with
  | Nil_list_foobar_foobar => m
  | Cons_list_foobar_foobar h0 h1 tl_ => Cons_list_foobar_foobar h0 h1 (app_list_foobar_foobar tl_ m)



/- - subrules - -/
def is_foo_of_foobar (foobar5:foobar) : Bool :=
  match foobar5 with
  | foobar_foo => (true)
  | foobar_bar => false


def is_seq_of_foobar_foobar_list (l:list_foobar_foobar) : Bool :=
  match l with
  | Nil_list_foobar_foobar => true
  | Cons_list_foobar_foobar foo_ foobar_ foo_foobar_list_ => ((is_foo_of_foobar foo_)) && (is_seq_of_foobar_foobar_list foo_foobar_list_)


def is_seq_of_seq (seq5:seq) : Bool :=
  match seq5 with
  | (seq_foofoobar foo_foobar_list) => (is_seq_of_foobar_foobar_list foo_foobar_list)


/- definitions -/


/- defns J -/
/-- defn zip -/
inductive J_zip : (list_foobar) → (list_foobar) → seq → Prop where
  | J_zip_zap : ∀ (foo_foobar_list : list_foobar_foobar),
      (List.all (unmake_list_foobar_foobar foo_foobar_list) (fun (foo_,foobar_) => is_foo_of_foobar foo_)) →
      J_zip (make_list_foobar (map_list_foobar_foobar (fun foo_ foobar_ => foo_) foo_foobar_list)) (make_list_foobar (map_list_foobar_foobar (fun foo_ foobar_ => foobar_) foo_foobar_list)) (seq_foofoobar foo_foobar_list)



