(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.2.ott *)

type value_name = UNDEFINED
type index = UNDEFINED

type 
a = 
   A_x of value_name
 | A_A of (a) list
 | A_X of (value_name) list

let rec aux_b_a_of_a (a_5:a) : value_name list =
  match a_5 with
  | (A_x x) -> [x]
  | (A_A (a_list)) -> (List.flatten (List.map aux_b_a_of_a (a_list)))
  | (A_X (x_list)) -> x_list



(** free variables *)
let rec fv_a (a_5:a) : value_name list =
  match a_5 with
  | (A_x x) -> [x]
  | (A_A (a_list)) -> (List.flatten (List.map (fun a_ -> (fv_a a_)) a_list))
  | (A_X (x_list)) -> []



(** substitutions *)
let rec msubst_a (sub: (value_name*a) list) (a__6:a) : a =
  match a__6 with
  | (A_x x) -> (try List.assoc x sub with Not_found -> (A_x x))
  | (A_A (a_list)) -> A_A (List.map (fun a_ -> (msubst_a sub a_)) a_list)
  | (A_X (x_list)) -> A_X x_list


let rec subst_a (a_5:a) (x_5:value_name) (a__6:a) : a =
  match a__6 with
  | (A_x x) -> (if x=x_5 then a_5 else (A_x x))
  | (A_A (a_list)) -> A_A (List.map (fun a_ -> (subst_a a_5 x_5 a_)) a_list)
  | (A_X (x_list)) -> A_X x_list




