(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4d.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.


Definition index : Set := nat.
Lemma eq_index: forall (x y : index), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_index : ott_coq_equality.
Definition x : Set := nat.
Lemma eq_x: forall (x' y : x), {x' = y} + {x' <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_x : ott_coq_equality.

Inductive a : Set := 
 | a_Ax (x5:x)
 | a_AA : a
 | a_a (a5:a)
 | a_C (_:list_a) (_:list_a)
 | a_CC (_:list_a) (_:list_a)
with list_a : Set := 
 | Nil_list_a : list_a
 | Cons_list_a (av:a) (_:list_a).
Fixpoint map_list_a (A:Type) (f:a->A) (l:list_a) : list A :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a h tl_ => cons (f h) (map_list_a A f tl_)
  end.
Arguments map_list_a [A] _ _.

Fixpoint make_list_a (l: list a): list_a :=
  match l with
  | nil  => Nil_list_a
  | cons h tl_ => Cons_list_a h (make_list_a tl_)
  end.

Fixpoint unmake_list_a (l: list_a): list a :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a h tl_ => cons h (unmake_list_a tl_)
  end.

Fixpoint nth_list_a (n:nat) (l: list_a) {struct n} : option a :=
  match n,l with
  | O, Cons_list_a h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_a => None
  | S m, Cons_list_a h tl_ => nth_list_a m tl_
  end.

Fixpoint app_list_a (l m: list_a): list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)
  end.


Fixpoint aux_b_a_of_a_list (l:list_a): list x :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a a'_ a_list_ => app (((aux_b_a_of_a a'_))) (aux_b_a_of_a_list a_list_)
end
with aux_b_a_of_a (a_6:a) : list x :=
  match a_6 with
  | (a_Ax x5) => (cons x5 nil)
  | a_AA => nil
  | (a_a a5) => (aux_b_a_of_a a5)
  | (a_C a_list a'_list) => (app (aux_b_a_of_a_list a_list) (aux_b_a_of_a_list a'_list))
  | (a_CC a_list a'_list) => (app (aux_b_a_of_a_list a_list) (aux_b_a_of_a_list a'_list))
end.


(** subrules *)
Fixpoint is_av_of_a'_list (l:list_a) : Prop :=
  match l with
  | Nil_list_a => True
  | Cons_list_a a'_ a'_list_ => (is_av_of_a a'_) /\ (is_av_of_a'_list a'_list_)
end
with is_av_of_a_list (l:list_a) : Prop :=
  match l with
  | Nil_list_a => True
  | Cons_list_a a_ a_list_ => (is_av_of_a a_) /\ (is_av_of_a_list a_list_)
end
with is_av_of_a (a_6:a) : Prop :=
  match a_6 with
  | (a_Ax x5) => False
  | a_AA => False
  | (a_a a5) => (True)
  | (a_C a_list a'_list) => (is_av_of_a_list a_list /\ is_av_of_a'_list a'_list)
  | (a_CC a_list a'_list) => (is_av_of_a_list a_list /\ is_av_of_a'_list a'_list)
end.


(** free variables *)
Fixpoint fv_a_list (l:list_a) : list x :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a a'_ a'_list_ => app ((fv_a a'_)) (fv_a_list a'_list_)
end
with fv_a (a_6:a) : list x :=
  match a_6 with
  | (a_Ax x5) => (cons x5 nil)
  | a_AA => nil
  | (a_a a5) => ((fv_a a5))
  | (a_C a_list a'_list) => (app (fv_a_list a_list) (fv_a_list a'_list))
  | (a_CC a_list a'_list) => (app (fv_a_list a_list) (fv_a_list a'_list))
end.

(** library functions *)
Fixpoint list_assoc A B (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list (A*B)) {struct l} : option B :=
  match l with
  | nil => None
  | cons (a,b) t => if (eq a x) then Some b else list_assoc A B eq x t
end.
Arguments list_assoc [A B] _ _ _.


(** substitutions *)
Fixpoint sum_a_list (sub:list (x*a)) (a__7:list_a) {struct a__7} : list_a :=
  match a__7 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (sum_a sub a) (sum_a_list sub a_tl)
end
with sum_a (sub:list (x*a)) (a__7:a) {struct a__7} : a :=
  match a__7 with
  | (a_Ax x5) => (match list_assoc eq_x x5 sub with None => (a_Ax x5) | Some a_6 => a_6 end)
  | a_AA => a_AA 
  | (a_a a5) => a_a (sum_a sub a5)
  | (a_C a_list a'_list) => a_C (sum_a_list sub a_list) (sum_a_list sub a'_list)
  | (a_CC a_list a'_list) => a_CC (sum_a_list sub a_list) (sum_a_list sub a'_list)
end.

Fixpoint su_a_list (a_6:a) (x_6:x) (a__7:list_a) {struct a__7} : list_a :=
  match a__7 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (su_a a_6 x_6 a) (su_a_list a_6 x_6 a_tl)
end
with su_a (a_6:a) (x_6:x) (a__7:a) {struct a__7} : a :=
  match a__7 with
  | (a_Ax x5) => (if eq_x x5 x_6 then a_6 else (a_Ax x5))
  | a_AA => a_AA 
  | (a_a a5) => a_a (su_a a_6 x_6 a5)
  | (a_C a_list a'_list) => a_C (su_a_list a_6 x_6 a_list) (su_a_list a_6 x_6 a'_list)
  | (a_CC a_list a'_list) => a_CC (su_a_list a_6 x_6 a_list) (su_a_list a_6 x_6 a'_list)
end.



