(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test16.2.ott *)
theory testRegr_test16_2
imports Main
begin

type_synonym "value_name" = "string"
datatype "a" = 
   a_x "value_name"  
 | a_A "a" "a"  
 | a_C  

primrec
aux_g_a_of_a_aux_f_a_of_a :: "a => (value_name list) * (value_name list)"
where
"aux_g_a_of_a_aux_f_a_of_a (a_x x) = ([x] , [x])"
| "aux_g_a_of_a_aux_f_a_of_a (a_A a1 a2) = (((%(aux_g_a_of_a,aux_f_a_of_a).aux_g_a_of_a) (aux_g_a_of_a_aux_f_a_of_a a1)) , ((%(aux_g_a_of_a,aux_f_a_of_a).aux_f_a_of_a) (aux_g_a_of_a_aux_f_a_of_a a1)) @ ((%(aux_g_a_of_a,aux_f_a_of_a).aux_f_a_of_a) (aux_g_a_of_a_aux_f_a_of_a a2)))"
| "aux_g_a_of_a_aux_f_a_of_a a_C = ([] , [])"

definition aux_g_a_of_a :: "a => value_name list" where
"aux_g_a_of_a == (%(aux_g_a_of_a,aux_f_a_of_a).aux_g_a_of_a) o aux_g_a_of_a_aux_f_a_of_a"

definition aux_f_a_of_a :: "a => value_name list" where
"aux_f_a_of_a == (%(aux_g_a_of_a,aux_f_a_of_a).aux_f_a_of_a) o aux_g_a_of_a_aux_f_a_of_a"

lemma
"aux_g_a_of_a (a_x x) = [x]"
"aux_g_a_of_a (a_A a1 a2) = (aux_g_a_of_a a1)"
"aux_g_a_of_a a_C = []"
"aux_f_a_of_a (a_x x) = [x]"
"aux_f_a_of_a (a_A a1 a2) = (aux_f_a_of_a a1) @ (aux_f_a_of_a a2)"
"aux_f_a_of_a a_C = []"
  by(simp_all add: aux_g_a_of_a_def aux_f_a_of_a_def)

(** library functions *)
primrec
list_assoc :: "'a => ('a*'b) list => 'b option"
where
  "list_assoc x0 Nil = None"
| "list_assoc x0 (Cons xy  xys) = (if x0=fst xy then Some (snd xy) else list_assoc x0 xys)"


(** substitutions *)
primrec
msubst_a :: "(value_name*a) list => a => a"
where
"msubst_a sub (a_x x) = ((case list_assoc x sub of None => (a_x x) | Some a_5 => a_5))"
| "msubst_a sub (a_A a1 a2) = (a_A (msubst_a sub a1) (msubst_a sub a2))"
| "msubst_a sub a_C = (a_C )"

primrec
subst_a :: "a => value_name => a => a"
where
"subst_a a_5 x5 (a_x x) = ((if x=x5 then a_5 else (a_x x)))"
| "subst_a a_5 x5 (a_A a1 a2) = (a_A (subst_a a_5 x5 a1) (subst_a a_5 x5 a2))"
| "subst_a a_5 x5 a_C = (a_C )"


end



