(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.3.ott *)
theory testRegr_test15_3
imports Main
begin

datatype "a" = 
   a_AA  
 | a_a "a"  
 | a_b "b"  
 | a_C "a" "b"  
 | a_D "a" "b"  
and "b" = 
   b_BB  
 | b_a "a"  
 | b_b "b"  


(** subrules *)
primrec
is_bv_of_b_is_b_of_b :: "b => (bool) * (bool)"
and is_av_of_a_is_a_of_a :: "a => (bool) * (bool)"
where
"is_bv_of_b_is_b_of_b b_BB = (False , (True))"
| "is_bv_of_b_is_b_of_b (b_a a) = ((((%(is_av_of_a,is_a_of_a).is_a_of_a) (is_av_of_a_is_a_of_a a))) , (((%(is_av_of_a,is_a_of_a).is_a_of_a) (is_av_of_a_is_a_of_a a))))"
| "is_bv_of_b_is_b_of_b (b_b b) = ((((%(is_bv_of_b,is_b_of_b).is_b_of_b) (is_bv_of_b_is_b_of_b b))) , (((%(is_bv_of_b,is_b_of_b).is_b_of_b) (is_bv_of_b_is_b_of_b b))))"
| "is_av_of_a_is_a_of_a a_AA = (False , (True))"
| "is_av_of_a_is_a_of_a (a_a a) = ((((%(is_av_of_a,is_a_of_a).is_a_of_a) (is_av_of_a_is_a_of_a a))) , (((%(is_av_of_a,is_a_of_a).is_a_of_a) (is_av_of_a_is_a_of_a a))))"
| "is_av_of_a_is_a_of_a (a_b b) = ((((%(is_bv_of_b,is_b_of_b).is_b_of_b) (is_bv_of_b_is_b_of_b b))) , (((%(is_bv_of_b,is_b_of_b).is_b_of_b) (is_bv_of_b_is_b_of_b b))))"
| "is_av_of_a_is_a_of_a (a_C av bv) = ((((%(is_av_of_a,is_a_of_a).is_av_of_a) (is_av_of_a_is_a_of_a av)) & ((%(is_bv_of_b,is_b_of_b).is_bv_of_b) (is_bv_of_b_is_b_of_b bv))) , (((%(is_av_of_a,is_a_of_a).is_av_of_a) (is_av_of_a_is_a_of_a av)) & ((%(is_bv_of_b,is_b_of_b).is_bv_of_b) (is_bv_of_b_is_b_of_b bv))))"
| "is_av_of_a_is_a_of_a (a_D av bv) = (False , (((%(is_av_of_a,is_a_of_a).is_av_of_a) (is_av_of_a_is_a_of_a av)) & ((%(is_bv_of_b,is_b_of_b).is_bv_of_b) (is_bv_of_b_is_b_of_b bv))))"

definition is_bv_of_b :: "b => bool" where
"is_bv_of_b == (%(is_bv_of_b,is_b_of_b).is_bv_of_b) o is_bv_of_b_is_b_of_b"

definition is_b_of_b :: "b => bool" where
"is_b_of_b == (%(is_bv_of_b,is_b_of_b).is_b_of_b) o is_bv_of_b_is_b_of_b"

definition is_av_of_a :: "a => bool" where
"is_av_of_a == (%(is_av_of_a,is_a_of_a).is_av_of_a) o is_av_of_a_is_a_of_a"

definition is_a_of_a :: "a => bool" where
"is_a_of_a == (%(is_av_of_a,is_a_of_a).is_a_of_a) o is_av_of_a_is_a_of_a"

lemma
"is_bv_of_b b_BB = False"
"is_bv_of_b (b_a a) = ((is_a_of_a a))"
"is_bv_of_b (b_b b) = ((is_b_of_b b))"
"is_b_of_b b_BB = (True)"
"is_b_of_b (b_a a) = ((is_a_of_a a))"
"is_b_of_b (b_b b) = ((is_b_of_b b))"
"is_av_of_a a_AA = False"
"is_av_of_a (a_a a) = ((is_a_of_a a))"
"is_av_of_a (a_b b) = ((is_b_of_b b))"
"is_av_of_a (a_C av bv) = ((is_av_of_a av) & (is_bv_of_b bv))"
"is_av_of_a (a_D av bv) = False"
"is_a_of_a a_AA = (True)"
"is_a_of_a (a_a a) = ((is_a_of_a a))"
"is_a_of_a (a_b b) = ((is_b_of_b b))"
"is_a_of_a (a_C av bv) = ((is_av_of_a av) & (is_bv_of_b bv))"
"is_a_of_a (a_D av bv) = ((is_av_of_a av) & (is_bv_of_b bv))"
  by(simp_all add: is_bv_of_b_def is_b_of_b_def is_av_of_a_def is_a_of_a_def)


end



