(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.0.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
Require Import Ott.ott_list_core.


Definition index : Set := nat.
Lemma eq_index: forall (x y : index), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_index : ott_coq_equality.

Inductive a : Set := 
 | a_AA : a
 | a_A (a5:a)
 | a_C (_:list a).
(** induction principles *)
Section a_rect.

Variables
  (P_a : a -> Prop)
  (P_list_a : list a -> Prop).

Hypothesis
  (H_a_AA : P_a a_AA)
  (H_a_A : forall (a5:a), P_a a5 -> P_a (a_A a5))
  (H_a_C : forall (a_list:list a), P_list_a a_list -> P_a (a_C a_list))
  (H_list_a_nil : P_list_a nil)
  (H_list_a_cons : forall (a0:a), P_a a0 -> forall (a_l:list a), P_list_a a_l -> P_list_a (cons a0 a_l)).

Fixpoint a_ott_ind (n:a) : P_a n :=
  match n as x return P_a x with
  | a_AA => H_a_AA 
  | (a_A a5) => H_a_A a5 (a_ott_ind a5)
  | (a_C a_list) => H_a_C a_list (((fix a_list_ott_ind (a_l:list a) : P_list_a a_l := match a_l as x return P_list_a x with nil => H_list_a_nil | cons a1 xl => H_list_a_cons a1(a_ott_ind a1)xl (a_list_ott_ind xl) end)) a_list)
end.

End a_rect.

(** subrules *)
Fixpoint is_av_of_a (a_6:a) : bool :=
  match a_6 with
  | a_AA => false
  | (a_A a5) => (true)
  | (a_C a_list) => ((forall_list (fun (a_:a) => (is_av_of_a a_)) a_list))
end.



