/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_tuple_2.ott -/




abbrev i := Nat

inductive barbar : Type where
  | barbar_Bar : barbar
  | barbar_Qux : barbar
  deriving Inhabited

inductive foo : Type where
  | foo_Foo : foo
  deriving Inhabited
open foo barbar

/- - subrules - -/
def is_bar_of_barbar (barbar5:barbar) : Bool :=
  match barbar5 with
  | barbar_Bar => (true)
  | barbar_Qux => false


inductive list_foo_barbar : Type where
    | Nil_list_foo_barbar : list_foo_barbar
    | Cons_list_foo_barbar : foo -> barbar -> list_foo_barbar -> list_foo_barbar
  deriving Inhabited
open list_foo_barbar

def map_list_foo_barbar {A : Type} (f : foo -> barbar -> A) (l : list_foo_barbar) : List A :=
  match l with
  | Nil_list_foo_barbar => []
  | Cons_list_foo_barbar h0 h1 tl_ => (f h0 h1) :: (map_list_foo_barbar f tl_)

def make_list_foo_barbar (l : List (foo × barbar)) : list_foo_barbar :=
  match l with
  | [] => Nil_list_foo_barbar
  | (h0,h1) :: tl_ => Cons_list_foo_barbar h0 h1 (make_list_foo_barbar tl_)

def unmake_list_foo_barbar (l : list_foo_barbar) : List (foo × barbar) :=
  match l with
  | Nil_list_foo_barbar => []
  | Cons_list_foo_barbar h0 h1 tl_ => (h0,h1) :: (unmake_list_foo_barbar tl_)

def nth_list_foo_barbar (n : Nat) (l : list_foo_barbar) : Option (foo × barbar) :=
  match n, l with
  | 0, Cons_list_foo_barbar h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_foo_barbar => none
  | k+1, Cons_list_foo_barbar _ _ tl_ => nth_list_foo_barbar k tl_

def app_list_foo_barbar (l m : list_foo_barbar) : list_foo_barbar :=
  match l with
  | Nil_list_foo_barbar => m
  | Cons_list_foo_barbar h0 h1 tl_ => Cons_list_foo_barbar h0 h1 (app_list_foo_barbar tl_ m)

/- definitions -/


/- defns J -/
mutual
/-- defn one -/
inductive J_one : foo → barbar → Prop where

/-- defn hello -/
inductive J_hello : Prop where
  | J_hello_world : ∀ (foo_bar_list : list_foo_barbar),
      (List.all (unmake_list_foo_barbar foo_bar_list) (fun (foo_,bar_) => is_bar_of_barbar bar_)) →
      (∀ foo_bar_list_ ∈ (unmake_list_foo_barbar foo_bar_list), (fun (foo_,bar_) => (J_one foo_ bar_)) foo_bar_list_) →
      J_hello


end


