/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_subrule_3.ott -/




abbrev i := Nat
abbrev ident := Nat

inductive constant : Type where
  | CONST_unit : constant
  deriving Inhabited

inductive expr : Type where
  | Expr_constant (constant5 : constant) : expr
  deriving Inhabited

inductive substs_x : Type where
  | substs_x_xs (_ : List (ident × expr)) : substs_x
  deriving Inhabited
open constant expr substs_x

/- - subrules - -/
def is_valu_of_expr (e5:expr) : Bool :=
  match e5 with
  | (Expr_constant constant5) => (true)


/- definitions -/


/- defns Jred -/
mutual
/-- defn match -/
inductive JR_match : expr → substs_x → Prop where
  | JR_match_alias : ∀ (x_v_list : List (ident × expr)) (x : ident) (v : expr),
      (is_valu_of_expr v) →
      (List.all x_v_list (fun (x_,v_) => is_valu_of_expr v_)) →
      (JR_match v (substs_x_xs (x_v_list))) →
      JR_match v (substs_x_xs (x_v_list ++ [(x,v)]))


/-- defn matches -/
inductive JR_matches : List expr → substs_x → Prop where
  | JR_matches_and : ∀ (v_list : List expr) (substs_x5 : substs_x),
      (∀ v_list_ ∈ v_list, (fun v_ => (JR_match v_ substs_x5)) v_list_) →
      JR_matches (v_list) substs_x5


end


