(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_4.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.


Definition i : Set := nat.
Lemma eq_i: forall (x y : i), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_i : ott_coq_equality.

Inductive bar : Set := 
 | bar_tuple (_:list_bar)
with list_bar : Set := 
 | Nil_list_bar : list_bar
 | Cons_list_bar (_:bar) (_:list_bar).

Inductive foo : Set := 
 | foo_tuple (_:list_foo)
with list_foo : Set := 
 | Nil_list_foo : list_foo
 | Cons_list_foo (_:foo) (_:list_foo).
Fixpoint map_list_bar (A:Type) (f:bar->A) (l:list_bar) : list A :=
  match l with
  | Nil_list_bar => nil
  | Cons_list_bar h tl_ => cons (f h) (map_list_bar A f tl_)
  end.
Arguments map_list_bar [A] _ _.

Fixpoint make_list_bar (l: list bar): list_bar :=
  match l with
  | nil  => Nil_list_bar
  | cons h tl_ => Cons_list_bar h (make_list_bar tl_)
  end.

Fixpoint unmake_list_bar (l: list_bar): list bar :=
  match l with
  | Nil_list_bar => nil
  | Cons_list_bar h tl_ => cons h (unmake_list_bar tl_)
  end.

Fixpoint nth_list_bar (n:nat) (l: list_bar) {struct n} : option bar :=
  match n,l with
  | O, Cons_list_bar h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_bar => None
  | S m, Cons_list_bar h tl_ => nth_list_bar m tl_
  end.

Fixpoint app_list_bar (l m: list_bar): list_bar :=
  match l with
  | Nil_list_bar => m
  | Cons_list_bar h tl_ => Cons_list_bar h (app_list_bar tl_ m)
  end.

Fixpoint map_list_foo (A:Type) (f:foo->A) (l:list_foo) : list A :=
  match l with
  | Nil_list_foo => nil
  | Cons_list_foo h tl_ => cons (f h) (map_list_foo A f tl_)
  end.
Arguments map_list_foo [A] _ _.

Fixpoint make_list_foo (l: list foo): list_foo :=
  match l with
  | nil  => Nil_list_foo
  | cons h tl_ => Cons_list_foo h (make_list_foo tl_)
  end.

Fixpoint unmake_list_foo (l: list_foo): list foo :=
  match l with
  | Nil_list_foo => nil
  | Cons_list_foo h tl_ => cons h (unmake_list_foo tl_)
  end.

Fixpoint nth_list_foo (n:nat) (l: list_foo) {struct n} : option foo :=
  match n,l with
  | O, Cons_list_foo h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_foo => None
  | S m, Cons_list_foo h tl_ => nth_list_foo m tl_
  end.

Fixpoint app_list_foo (l m: list_foo): list_foo :=
  match l with
  | Nil_list_foo => m
  | Cons_list_foo h tl_ => Cons_list_foo h (app_list_foo tl_ m)
  end.


(* definitions *)

(* defns J *)
Inductive J_D : foo -> Prop :=    (* defn D *)
 | J_D_tuple : forall (foo_list:list_foo),
     (forall foo_, In foo_ (map (fun (foo_ : foo) => foo_) (unmake_list_foo foo_list)) -> (J_D foo_)) ->
     J_D (foo_tuple foo_list).
Check list_bar.
Check J_D_list.
Check make_list_bar.
Check make_J_D_list.



