/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/bool.ott /home/pes20/claude-home/ott/regression/../examples/tapl/bool_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/arrow_typing.ott -/
/- - warning: the backend selected ignores the file structure informations - -/
/- - syntax - -/
abbrev termvar := Nat

/-- types: -/
inductive T : Type where
  /-- type of booleans -/
  | TyBool : T
  /-- type of functions -/
  | TyArr (T5 : T) (T' : T) : T
  deriving Inhabited

/-- contexts: -/
inductive G : Type where
  /-- empty context -/
  | G_empty : G
  /-- term variable binding -/
  | G_vn (G5 : G) (x : termvar) (T5 : T) : G
  deriving Inhabited

/-- terms: -/
inductive t : Type where
  /-- constant true -/
  | TmTrue : t
  /-- constant false -/
  | TmFalse : t
  /-- conditional -/
  | TmIf (t1 : t) (t2 : t) (t3 : t) : t
  /-- variable -/
  | TmVar (x : termvar) : t
  /-- abstraction -/
  | TmAbs (x : termvar) (T5 : T) (t5 : t) : t
  /-- application -/
  | TmApp (t1 : t) (t2 : t) : t
  deriving Inhabited
open G t T

/- - auxiliary functions on the new list types - -/
/- - library functions - -/
def list_minus {α : Type} [BEq α] (l1:List α) (l2:List α) : (List α) :=
  match l1 with
  | [] => []
  | h::t => if List.elem h l2 then list_minus t l2 else h::(list_minus t l2)

/- - subrules - -/
def is_v_of_t (t_6:t) : Bool :=
  match t_6 with
  | TmTrue => (true)
  | TmFalse => (true)
  | (TmIf t1 t2 t3) => false
  | (TmVar x) => false
  | (TmAbs x T5 t5) => (true)
  | (TmApp t1 t2) => false


/- - auxiliary functions - -/
/- - free variables - -/
def fv_t (t_6:t) :  List termvar :=
  match t_6 with
  | TmTrue => []
  | TmFalse => []
  | (TmIf t1 t2 t3) => (fv_t t1) ++ (fv_t t2) ++ (fv_t t3)
  | (TmVar x) => [x]
  | (TmAbs x T5 t5) => (list_minus (fv_t t5) [x])
  | (TmApp t1 t2) => (fv_t t1) ++ (fv_t t2)


/- - substitutions - -/
def subst_t (t_6:t) (x5:termvar) (t__7:t) : t :=
  match t__7 with
  | TmTrue => TmTrue 
  | TmFalse => TmFalse 
  | (TmIf t1 t2 t3) => TmIf (subst_t t_6 x5 t1) (subst_t t_6 x5 t2) (subst_t t_6 x5 t3)
  | (TmVar x) => (if x=x5 then t_6 else (TmVar x))
  | (TmAbs x T5 t5) => TmAbs x T5 (if  List.elem x5 ([x]) then t5 else (subst_t t_6 x5 t5))
  | (TmApp t1 t2) => TmApp (subst_t t_6 x5 t1) (subst_t t_6 x5 t2)


/- - context application - -/
def bound (x:termvar) (t0:T) (g:G) : Prop :=
  match g with
  | G_empty => False
  | G_vn g' x' t' => if x = x' then t0 = t' else bound x t0 g'


/- definitions -/


/- defns Jop -/
/-- defn red -/
inductive red : t → t → Prop where
  | E_IfTrue : ∀ (t2 : t) (t3 : t),
      red (TmIf TmTrue t2 t3) t2

  | E_IfFalse : ∀ (t2 : t) (t3 : t),
      red (TmIf TmFalse t2 t3) t3

  | E_If : ∀ (t1 : t) (t2 : t) (t3 : t) (t1' : t),
      (red t1 t1') →
      red (TmIf t1 t2 t3) (TmIf t1' t2 t3)

  | E_App1 : ∀ (t1 : t) (t2 : t) (t1' : t),
      (red t1 t1') →
      red (TmApp t1 t2) (TmApp t1' t2)

  | E_App2 : ∀ (v1 : t) (t2 : t) (t2' : t),
      (is_v_of_t v1) →
      (red t2 t2') →
      red (TmApp v1 t2) (TmApp v1 t2')

  | E_AppAbs : ∀ (x : termvar) (T5 : T) (t12 : t) (v2 : t),
      (is_v_of_t v2) →
      red (TmApp (TmAbs x T5 t12) v2) (subst_t v2 x t12)


/- defns Jtype -/
/-- defn typing -/
inductive typing : G → t → T → Prop where
  | T_True : ∀ (G5 : G),
      typing G5 TmTrue TyBool

  | T_False : ∀ (G5 : G),
      typing G5 TmFalse TyBool

  | T_If : ∀ (G5 : G) (t1 : t) (t2 : t) (t3 : t) (T5 : T),
      (typing G5 t1 TyBool) →
      (typing G5 t2 T5) →
      (typing G5 t3 T5) →
      typing G5 (TmIf t1 t2 t3) T5

  | T_Var : ∀ (G5 : G) (x : termvar) (T5 : T),
      (bound x T5 G5) →
      typing G5 (TmVar x) T5

  | T_Abs : ∀ (G5 : G) (x : termvar) (T1 : T) (t2 : t) (T2 : T),
      (typing (G_vn G5 x T1) t2 T2) →
      typing G5 (TmAbs x T1 t2) (TyArr T1 T2)

  | T_App : ∀ (G5 : G) (t1 : t) (t2 : t) (T12 : T) (T11 : T),
      (typing G5 t1 (TyArr T11 T12)) →
      (typing G5 t2 T11) →
      typing G5 (TmApp t1 t2) T12



