(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/arrow_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/sub_arrow.ott /home/pes20/claude-home/ott/regression/../examples/tapl/top.ott *)
From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
Require Import Ott.ott_list_core.
(** warning: the backend selected ignores the file structure informations *)
(** syntax *)
Definition termvar : Set := nat.
Lemma eq_termvar: forall (x y : termvar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_termvar : ott_coq_equality.

Inductive T : Set :=  (* types: *)
 | TyArr (T5:T) (T':T) (* type of functions *)
 | TyTop : T (* maximum type *).

Definition G : Set := list (termvar*T).

Inductive t : Set :=  (* terms: *)
 | TmVar (x:termvar) (* variable *)
 | TmAbs (x:termvar) (T5:T) (t5:t) (* abstraction *)
 | TmApp (t1:t) (t2:t) (* application *).

(** auxiliary functions on the new list types *)
(** library functions *)
Fixpoint list_mem A (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list A) {struct l} : bool :=
  match l with
  | nil => false
  | cons h t => if eq h x then true else list_mem A eq x t
end.
Arguments list_mem [A] _ _ _.

Fixpoint list_minus A (eq:forall a b:A,{a=b}+{a<>b}) (l1:list A) (l2:list A) {struct l1} : list A :=
  match l1 with
  | nil => nil
  | cons h t => if (list_mem (A:=A) eq h l2) then list_minus A eq t l2 else cons h (list_minus A eq t l2)
end.
Arguments list_minus [A] _ _ _.

(** subrules *)
Definition is_v_of_t (t_6:t) : bool :=
  match t_6 with
  | (TmVar x) => false
  | (TmAbs x T5 t5) => (true)
  | (TmApp t1 t2) => false
end.

(** auxiliary functions *)
(** free variables *)
Fixpoint fv_t (t_6:t) : list termvar :=
  match t_6 with
  | (TmVar x) => (cons x nil)
  | (TmAbs x T5 t5) => ((list_minus eq_termvar (fv_t t5) (cons x nil)))
  | (TmApp t1 t2) => (app (fv_t t1) (fv_t t2))
end.

(** substitutions *)
Fixpoint subst_t (t_6:t) (x5:termvar) (t__7:t) {struct t__7} : t :=
  match t__7 with
  | (TmVar x) => (if eq_termvar x x5 then t_6 else (TmVar x))
  | (TmAbs x T5 t5) => TmAbs x T5 (if list_mem eq_termvar x5 (cons x nil) then t5 else (subst_t t_6 x5 t5))
  | (TmApp t1 t2) => TmApp (subst_t t_6 x5 t1) (subst_t t_6 x5 t2)
end.

(** context application *)
Require Import Ott.ott_list. (* for [all_distinct] *)

Definition bound x T0 G :=
  exists G1, exists G2,
    (G = G1 ++ (x,T0)::G2)%list /\
    ~In x (List.map (@fst termvar T) G1).


(* definitions *)

(* defns Jop *)
Inductive red : t -> t -> Prop :=    (* defn red *)
 | E_App1 : forall (t1 t2 t1':t),
     red t1 t1' ->
     red (TmApp t1 t2) (TmApp t1' t2)
 | E_App2 : forall (v1 t2 t2':t),
     Is_true (is_v_of_t v1) ->
     red t2 t2' ->
     red (TmApp v1 t2) (TmApp v1 t2')
 | E_AppAbs : forall (x:termvar) (T5:T) (t12 v2:t),
     Is_true (is_v_of_t v2) ->
     red (TmApp  (TmAbs x T5 t12)  v2)  (subst_t  v2   x   t12 ) .

(* defns Jtype *)
Inductive typing : G -> t -> T -> Prop :=    (* defn typing *)
 | T_Var : forall (G5:G) (x:termvar) (T5:T),
      (bound  x   T5   G5 )  ->
     typing G5 (TmVar x) T5
 | T_Abs : forall (G5:G) (x:termvar) (T1:T) (t2:t) (T2:T),
     typing  (cons ( x , T1 )  G5 )  t2 T2 ->
     typing G5 (TmAbs x T1 t2) (TyArr T1 T2)
 | T_App : forall (G5:G) (t1 t2:t) (T12 T11:T),
     typing G5 t1 (TyArr T11 T12) ->
     typing G5 t2 T11 ->
     typing G5 (TmApp t1 t2) T12
 | T_Sub : forall (G5:G) (t5:t) (T5 S:T),
     typing G5 t5 S ->
     subtyping S T5 ->
     typing G5 t5 T5
with subtyping : T -> T -> Prop :=    (* defn subtyping *)
 | S_Refl : forall (S:T),
     subtyping S S
 | S_Trans : forall (S T5 U:T),
     subtyping S U ->
     subtyping U T5 ->
     subtyping S T5
 | S_Arrow : forall (S1 S2 T1 T2:T),
     subtyping T1 S1 ->
     subtyping S2 T2 ->
     subtyping (TyArr S1 S2) (TyArr T1 T2)
 | S_Top : forall (S:T),
     subtyping S TyTop.


