(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_subrule_1.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
Require Import Ott.ott_list_core.


Definition i : Set := nat.
Definition x : Set := nat.

Inductive foobar : Set := 
 | foobar_foo : foobar
 | foobar_bar : foobar.

Inductive seq : Set := 
 | seq_foofoobar (_:list (foobar*foobar)).

(** subrules *)
Definition is_foo_of_foobar (foobar5:foobar) : bool :=
  match foobar5 with
  | foobar_foo => (true)
  | foobar_bar => false
end.

Definition is_seq_of_seq (seq5:seq) : bool :=
  match seq5 with
  | (seq_foofoobar foo_foobar_list) => ((forall_list (fun (pat_:(foobar*foobar)) => match pat_ with (foo_,foobar_) => (is_foo_of_foobar foo_) end) foo_foobar_list))
end.

(* definitions *)

(* defns J *)
Inductive J_zip : list foobar -> list foobar -> seq -> Prop :=    (* defn zip *)
 | J_zip_zap : forall (foo_foobar_list:list (foobar*foobar)),
     (Forall (fun (tmp_:(foobar*foobar)) => match tmp_ with (foo_,foobar_) => Is_true (is_foo_of_foobar foo_) end) foo_foobar_list) ->
     J_zip (map (fun (pat_:(foobar*foobar)) => match pat_ with (foo_,foobar_) => foo_ end ) foo_foobar_list) (map (fun (pat_:(foobar*foobar)) => match pat_ with (foo_,foobar_) => foobar_ end ) foo_foobar_list) (seq_foofoobar foo_foobar_list).


