/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.2.ott -/




abbrev value_name := Nat
abbrev index := Nat

inductive list_value_name : Type where
  | Nil_list_value_name : list_value_name
  | Cons_list_value_name (x : value_name) (_ : list_value_name) : list_value_name
  deriving Inhabited

mutual
inductive a : Type where
  | a_x (x : value_name) : a
  | a_A (_ : list_a) : a
  | a_X (_ : list_value_name) : a
  deriving Inhabited
inductive list_a : Type where
  | Nil_list_a : list_a
  | Cons_list_a (_ : a) (_ : list_a) : list_a
  deriving Inhabited
end
open list_a list_value_name a
def map_list_a {A : Type} (f : a -> A) (l : list_a) : List A :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => (f h) :: (map_list_a f tl_)

def make_list_a (l : List a) : list_a :=
  match l with
  | [] => Nil_list_a
  | h :: tl_ => Cons_list_a h (make_list_a tl_)

def unmake_list_a (l : list_a) : List a :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => h :: (unmake_list_a tl_)

def nth_list_a (n : Nat) (l : list_a) : Option a :=
  match n, l with
  | 0, Cons_list_a h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_a => none
  | k+1, Cons_list_a _ tl_ => nth_list_a k tl_

def app_list_a (l m : list_a) : list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)

def map_list_value_name {A : Type} (f : value_name -> A) (l : list_value_name) : List A :=
  match l with
  | Nil_list_value_name => []
  | Cons_list_value_name h tl_ => (f h) :: (map_list_value_name f tl_)

def make_list_value_name (l : List value_name) : list_value_name :=
  match l with
  | [] => Nil_list_value_name
  | h :: tl_ => Cons_list_value_name h (make_list_value_name tl_)

def unmake_list_value_name (l : list_value_name) : List value_name :=
  match l with
  | Nil_list_value_name => []
  | Cons_list_value_name h tl_ => h :: (unmake_list_value_name tl_)

def nth_list_value_name (n : Nat) (l : list_value_name) : Option value_name :=
  match n, l with
  | 0, Cons_list_value_name h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_value_name => none
  | k+1, Cons_list_value_name _ tl_ => nth_list_value_name k tl_

def app_list_value_name (l m : list_value_name) : list_value_name :=
  match l with
  | Nil_list_value_name => m
  | Cons_list_value_name h tl_ => Cons_list_value_name h (app_list_value_name tl_ m)


mutual
def aux_b_a_of_a_list (l:list_a) : List value_name :=
  match l with
  | Nil_list_a => []
  | Cons_list_a a_ a_list_ => ((aux_b_a_of_a a_)) ++ (aux_b_a_of_a_list a_list_)
def aux_b_a_of_a (a_5:a) : List value_name :=
  match a_5 with
  | (a_x x) => [x]
  | (a_A a_list) => (aux_b_a_of_a_list a_list)
  | (a_X x_list) => (unmake_list_value_name x_list)
end


/- - free variables - -/
mutual
def fv_a_list (l:list_a) : List value_name :=
  match l with
  | Nil_list_a => []
  | Cons_list_a a_ a_list_ => (fv_a a_) ++ (fv_a_list a_list_)
def fv_a (a_5:a) :  List value_name :=
  match a_5 with
  | (a_x x) => [x]
  | (a_A a_list) => (fv_a_list a_list)
  | (a_X x_list) => []
end

/- - library functions - -/
def list_assoc {α β : Type} [DecidableEq α] (l:List (α × β)) (x:α) : Option β :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def msubst_a_list (sub:List (value_name×a)) (a__6:list_a) : list_a :=
  match a__6 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (msubst_a sub a) (msubst_a_list sub a_tl)
def msubst_a (sub:List (value_name×a)) (a__6:a) : a :=
  match a__6 with
  | (a_x x) => (match list_assoc sub x with | none => (a_x x)| some a_5 => a_5 )
  | (a_A a_list) => a_A (msubst_a_list sub a_list)
  | (a_X x_list) => a_X x_list
end

mutual
def subst_a_list (a_5:a) (x_5:value_name) (a__6:list_a) : list_a :=
  match a__6 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (subst_a a_5 x_5 a) (subst_a_list a_5 x_5 a_tl)
def subst_a (a_5:a) (x_5:value_name) (a__6:a) : a :=
  match a__6 with
  | (a_x x) => (if x=x_5 then a_5 else (a_x x))
  | (a_A a_list) => a_A (subst_a_list a_5 x_5 a_list)
  | (a_X x_list) => a_X x_list
end



