(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_4.ott *)
theory testRegr_test_lists_coq_list_functions_4
imports Main
begin

type_synonym "i" = "nat"
datatype "foo" = 
   foo_tuple "foo list"  

datatype "bar" = 
   bar_tuple "bar list"  

(** definitions *)
(* defns J *)
inductive J_D :: "foo \<Rightarrow> bool"
where
(* defn D *)

J_D_tupleI: "\<lbrakk>(List.list_all (% b . b) ((List.map (%(foo_XXX::foo).J_D (foo_XXX)) foo_list)))\<rbrakk> \<Longrightarrow>
J_D ((foo_tuple (foo_list)))"

end



