(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.14.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.


Definition value_name : Set := nat.
Lemma eq_value_name: forall (x y : value_name), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_value_name : ott_coq_equality.
Definition index : Set := nat.
Lemma eq_index: forall (x y : index), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_index : ott_coq_equality.

Inductive a : Set := 
 | a_x (x:value_name)
 | a_E (_:list_c_c_c)
with list_c_c_c : Set := 
 | Nil_list_c_c_c : list_c_c_c
 | Cons_list_c_c_c (_:c) (_:c) (_:c) (_:list_c_c_c)
with c : Set := 
 | c_C (_:list_a)
with list_a : Set := 
 | Nil_list_a : list_a
 | Cons_list_a (_:a) (_:list_a).
Fixpoint map_list_a (A:Type) (f:a->A) (l:list_a) : list A :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a h tl_ => cons (f h) (map_list_a A f tl_)
  end.
Arguments map_list_a [A] _ _.

Fixpoint make_list_a (l: list a): list_a :=
  match l with
  | nil  => Nil_list_a
  | cons h tl_ => Cons_list_a h (make_list_a tl_)
  end.

Fixpoint unmake_list_a (l: list_a): list a :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a h tl_ => cons h (unmake_list_a tl_)
  end.

Fixpoint nth_list_a (n:nat) (l: list_a) {struct n} : option a :=
  match n,l with
  | O, Cons_list_a h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_a => None
  | S m, Cons_list_a h tl_ => nth_list_a m tl_
  end.

Fixpoint app_list_a (l m: list_a): list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)
  end.

Fixpoint map_list_c_c_c (A:Type) (f:c->c->c->A) (l:list_c_c_c) : list A :=
  match l with
  | Nil_list_c_c_c => nil
  | Cons_list_c_c_c h0 h1 h2 tl_ => cons (f h0 h1 h2) (map_list_c_c_c A f tl_)
  end.
Arguments map_list_c_c_c [A] _ _.

Fixpoint make_list_c_c_c (l: list (c * c * c)): list_c_c_c :=
  match l with
  | nil  => Nil_list_c_c_c
  | cons (h0,h1,h2) tl_ => Cons_list_c_c_c h0 h1 h2 (make_list_c_c_c tl_)
  end.

Fixpoint unmake_list_c_c_c (l: list_c_c_c): list (c * c * c) :=
  match l with
  | Nil_list_c_c_c => nil
  | Cons_list_c_c_c h0 h1 h2 tl_ => cons (h0,h1,h2) (unmake_list_c_c_c tl_)
  end.

Fixpoint nth_list_c_c_c (n:nat) (l: list_c_c_c) {struct n} : option (c * c * c) :=
  match n,l with
  | O, Cons_list_c_c_c h0 h1 h2 tl_ => Some (h0,h1,h2)
  | O, _ => None
  | S m, Nil_list_c_c_c => None
  | S m, Cons_list_c_c_c h0 h1 h2 tl_ => nth_list_c_c_c m tl_
  end.

Fixpoint app_list_c_c_c (l m: list_c_c_c): list_c_c_c :=
  match l with
  | Nil_list_c_c_c => m
  | Cons_list_c_c_c h0 h1 h2 tl_ => Cons_list_c_c_c h0 h1 h2 (app_list_c_c_c tl_ m)
  end.



(** subrules *)
Fixpoint is_av_of_c_c'_c''_list (l:list_c_c_c) : Prop :=
  match l with
  | Nil_list_c_c_c => True
  | Cons_list_c_c_c c_ c'_ c''_ c_c'_c''_list_ => True /\ (is_av_of_c_c'_c''_list c_c'_c''_list_)
end.

Definition is_av_of_a (a5:a) : Prop :=
  match a5 with
  | (a_x x) => False
  | (a_E c_c'_c''_list) => (is_av_of_c_c'_c''_list c_c'_c''_list)
end.


(** substitutions *)
Fixpoint subst_c_c_c_list (a5:a) (x5:value_name) (a_6:list_c_c_c) {struct a_6} : list_c_c_c :=
  match a_6 with
  | Nil_list_c_c_c => Nil_list_c_c_c
  | Cons_list_c_c_c c1 c2 c3 c_c_c_tl => Cons_list_c_c_c (subst_c a5 x5 c1) (subst_c a5 x5 c2) (subst_c a5 x5 c3) (subst_c_c_c_list a5 x5 c_c_c_tl)
end
with subst_a (a5:a) (x5:value_name) (a_6:a) {struct a_6} : a :=
  match a_6 with
  | (a_x x) => (if eq_value_name x x5 then a5 else (a_x x))
  | (a_E c_c'_c''_list) => a_E (subst_c_c_c_list a5 x5 c_c'_c''_list)
end
with subst_a_list (a_5:a) (x5:value_name) (c5:list_a) {struct c5} : list_a :=
  match c5 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (subst_a a_5 x5 a) (subst_a_list a_5 x5 a_tl)
end
with subst_c (a_5:a) (x5:value_name) (c5:c) {struct c5} : c :=
  match c5 with
  | (c_C a_list) => c_C (subst_a_list a_5 x5 a_list)
end.


(** free variables *)
Fixpoint fv_a_list (l:list_a) : list value_name :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a a_ a_list_ => app ((fv_a a_)) (fv_a_list a_list_)
end
with fv_c (c5:c) : list value_name :=
  match c5 with
  | (c_C a_list) => ((fv_a_list a_list))
end
with fv_c_c_c_list (l:list_c_c_c) : list value_name :=
  match l with
  | Nil_list_c_c_c => nil
  | Cons_list_c_c_c c_ c'_ c''_ c_c'_c''_list_ => app ((app (fv_c c_) (app (fv_c c'_) (fv_c c''_)))) (fv_c_c_c_list c_c'_c''_list_)
end
with fv_a (a5:a) : list value_name :=
  match a5 with
  | (a_x x) => (cons x nil)
  | (a_E c_c'_c''_list) => ((fv_c_c_c_list c_c'_c''_list))
end.



