/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.3.ott -/





mutual
inductive a : Type where
  | a_AA : a
  | a_a (a5 : a) : a
  | a_b (b5 : b) : a
  | a_C (av5 : a) (bv5 : b) : a
  | a_D (av5 : a) (bv5 : b) : a
  deriving Inhabited
inductive b : Type where
  | b_BB : b
  | b_a (a5 : a) : b
  | b_b (b5 : b) : b
  deriving Inhabited
end
open a b

/- - subrules - -/
mutual
def is_b_of_b (b_6:b) : Bool :=
  match b_6 with
  | b_BB => (true)
  | (b_a a5) => ((is_a_of_a a5))
  | (b_b b5) => ((is_b_of_b b5))
def is_a_of_a (a_6:a) : Bool :=
  match a_6 with
  | a_AA => (true)
  | (a_a a5) => ((is_a_of_a a5))
  | (a_b b5) => ((is_b_of_b b5))
  | (a_C av5 bv5) => ((is_av_of_a av5) /\ (is_bv_of_b bv5))
  | (a_D av5 bv5) => ((is_av_of_a av5) /\ (is_bv_of_b bv5))
def is_bv_of_b (b_6:b) : Bool :=
  match b_6 with
  | b_BB => false
  | (b_a a5) => ((is_a_of_a a5))
  | (b_b b5) => ((is_b_of_b b5))
def is_av_of_a (a_6:a) : Bool :=
  match a_6 with
  | a_AA => false
  | (a_a a5) => ((is_a_of_a a5))
  | (a_b b5) => ((is_b_of_b b5))
  | (a_C av5 bv5) => ((is_av_of_a av5) /\ (is_bv_of_b bv5))
  | (a_D av5 bv5) => false
end



