/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.0.ott -/




abbrev index := Nat

mutual
inductive a : Type where
  | a_AA : a
  | a_A (a5 : a) : a
  | a_C (_ : list_a) : a
  deriving Inhabited
inductive list_a : Type where
  | Nil_list_a : list_a
  | Cons_list_a (av : a) (_ : list_a) : list_a
  deriving Inhabited
end
open list_a a
def map_list_a {A : Type} (f : a -> A) (l : list_a) : List A :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => (f h) :: (map_list_a f tl_)

def make_list_a (l : List a) : list_a :=
  match l with
  | [] => Nil_list_a
  | h :: tl_ => Cons_list_a h (make_list_a tl_)

def unmake_list_a (l : list_a) : List a :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => h :: (unmake_list_a tl_)

def nth_list_a (n : Nat) (l : list_a) : Option a :=
  match n, l with
  | 0, Cons_list_a h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_a => none
  | k+1, Cons_list_a _ tl_ => nth_list_a k tl_

def app_list_a (l m : list_a) : list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)



/- - subrules - -/
mutual
def is_av_of_a_list (l:list_a) : Bool :=
  match l with
  | Nil_list_a => true
  | Cons_list_a a_ a_list_ => ((is_av_of_a a_)) && (is_av_of_a_list a_list_)
def is_av_of_a (a_6:a) : Bool :=
  match a_6 with
  | a_AA => false
  | (a_A a5) => (true)
  | (a_C a_list) => (is_av_of_a_list a_list)
end



