(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.10.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.


Definition typevar : Set := nat. (* type variable *)
Lemma eq_typevar: forall (x y : typevar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_typevar : ott_coq_equality.
Definition termvar : Set := nat. (* term variable *)
Lemma eq_termvar: forall (x y : termvar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_termvar : ott_coq_equality.
Definition label : Set := nat. (* field label *)
Definition index : Set := nat. (* indices *)

Inductive T : Set :=  (* type *)
 | T_Var (X:typevar) (* type variable *)
 | T_Rec (_:list_label_T) (* record *)
with list_label_T : Set := 
 | Nil_list_label_T : list_label_T
 | Cons_list_label_T (l:label) (_:T) (_:list_label_T).

Inductive G : Set :=  (* type environment *)
 | G_empty : G
 | G_type (G5:G) (X:typevar) (T5:T)
 | G_term (G5:G) (x:termvar) (T5:T).

Inductive list_G : Set := 
 | Nil_list_G : list_G
 | Cons_list_G (_:G) (_:list_G).

Inductive t : Set :=  (* term *)
 | t_Var (x:termvar) (* variable *)
 | t_Rec_comp_lu_some (_:list_label_t) (* record --- complu with terminal *)
 | t_Proj (t5:t) (l:label) (* projection *)
with list_label_t : Set := 
 | Nil_list_label_t : list_label_t
 | Cons_list_label_t (l:label) (_:t) (_:list_label_t).
Fixpoint map_list_G (A:Type) (f:G->A) (l:list_G) : list A :=
  match l with
  | Nil_list_G => nil
  | Cons_list_G h tl_ => cons (f h) (map_list_G A f tl_)
  end.
Arguments map_list_G [A] _ _.

Fixpoint make_list_G (l: list G): list_G :=
  match l with
  | nil  => Nil_list_G
  | cons h tl_ => Cons_list_G h (make_list_G tl_)
  end.

Fixpoint unmake_list_G (l: list_G): list G :=
  match l with
  | Nil_list_G => nil
  | Cons_list_G h tl_ => cons h (unmake_list_G tl_)
  end.

Fixpoint nth_list_G (n:nat) (l: list_G) {struct n} : option G :=
  match n,l with
  | O, Cons_list_G h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_G => None
  | S m, Cons_list_G h tl_ => nth_list_G m tl_
  end.

Fixpoint app_list_G (l m: list_G): list_G :=
  match l with
  | Nil_list_G => m
  | Cons_list_G h tl_ => Cons_list_G h (app_list_G tl_ m)
  end.

Fixpoint map_list_label_t (A:Type) (f:label->t->A) (l:list_label_t) : list A :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t h0 h1 tl_ => cons (f h0 h1) (map_list_label_t A f tl_)
  end.
Arguments map_list_label_t [A] _ _.

Fixpoint make_list_label_t (l: list (label * t)): list_label_t :=
  match l with
  | nil  => Nil_list_label_t
  | cons (h0,h1) tl_ => Cons_list_label_t h0 h1 (make_list_label_t tl_)
  end.

Fixpoint unmake_list_label_t (l: list_label_t): list (label * t) :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t h0 h1 tl_ => cons (h0,h1) (unmake_list_label_t tl_)
  end.

Fixpoint nth_list_label_t (n:nat) (l: list_label_t) {struct n} : option (label * t) :=
  match n,l with
  | O, Cons_list_label_t h0 h1 tl_ => Some (h0,h1)
  | O, _ => None
  | S m, Nil_list_label_t => None
  | S m, Cons_list_label_t h0 h1 tl_ => nth_list_label_t m tl_
  end.

Fixpoint app_list_label_t (l m: list_label_t): list_label_t :=
  match l with
  | Nil_list_label_t => m
  | Cons_list_label_t h0 h1 tl_ => Cons_list_label_t h0 h1 (app_list_label_t tl_ m)
  end.

Fixpoint map_list_label_T (A:Type) (f:label->T->A) (l:list_label_T) : list A :=
  match l with
  | Nil_list_label_T => nil
  | Cons_list_label_T h0 h1 tl_ => cons (f h0 h1) (map_list_label_T A f tl_)
  end.
Arguments map_list_label_T [A] _ _.

Fixpoint make_list_label_T (l: list (label * T)): list_label_T :=
  match l with
  | nil  => Nil_list_label_T
  | cons (h0,h1) tl_ => Cons_list_label_T h0 h1 (make_list_label_T tl_)
  end.

Fixpoint unmake_list_label_T (l: list_label_T): list (label * T) :=
  match l with
  | Nil_list_label_T => nil
  | Cons_list_label_T h0 h1 tl_ => cons (h0,h1) (unmake_list_label_T tl_)
  end.

Fixpoint nth_list_label_T (n:nat) (l: list_label_T) {struct n} : option (label * T) :=
  match n,l with
  | O, Cons_list_label_T h0 h1 tl_ => Some (h0,h1)
  | O, _ => None
  | S m, Nil_list_label_T => None
  | S m, Cons_list_label_T h0 h1 tl_ => nth_list_label_T m tl_
  end.

Fixpoint app_list_label_T (l m: list_label_T): list_label_T :=
  match l with
  | Nil_list_label_T => m
  | Cons_list_label_T h0 h1 tl_ => Cons_list_label_T h0 h1 (app_list_label_T tl_ m)
  end.


Inductive list_label_t_T : Set := Nil_list_label_t_T | Cons_list_label_t_T (_:label) (_:t) (_:T) (tl_ : list_label_t_T).

Fixpoint map_list_label_t_T (A:Type) (f:label->t->T->A) (l:list_label_t_T) : list A :=
  match l with
  | Nil_list_label_t_T => nil
  | Cons_list_label_t_T h0 h1 h2 tl_ => cons (f h0 h1 h2) (map_list_label_t_T A f tl_)
  end.
Arguments map_list_label_t_T [A] _ _.

Fixpoint make_list_label_t_T (l: list (label * t * T)): list_label_t_T :=
  match l with
  | nil  => Nil_list_label_t_T
  | cons (h0,h1,h2) tl_ => Cons_list_label_t_T h0 h1 h2 (make_list_label_t_T tl_)
  end.

Fixpoint unmake_list_label_t_T (l: list_label_t_T): list (label * t * T) :=
  match l with
  | Nil_list_label_t_T => nil
  | Cons_list_label_t_T h0 h1 h2 tl_ => cons (h0,h1,h2) (unmake_list_label_t_T tl_)
  end.

Fixpoint nth_list_label_t_T (n:nat) (l: list_label_t_T) {struct n} : option (label * t * T) :=
  match n,l with
  | O, Cons_list_label_t_T h0 h1 h2 tl_ => Some (h0,h1,h2)
  | O, _ => None
  | S m, Nil_list_label_t_T => None
  | S m, Cons_list_label_t_T h0 h1 h2 tl_ => nth_list_label_t_T m tl_
  end.

Fixpoint app_list_label_t_T (l m: list_label_t_T): list_label_t_T :=
  match l with
  | Nil_list_label_t_T => m
  | Cons_list_label_t_T h0 h1 h2 tl_ => Cons_list_label_t_T h0 h1 h2 (app_list_label_t_T tl_ m)
  end.

(* definitions *)

(* defns Jtype *)
Inductive Ty : G -> t -> T -> Prop :=    (* defn Ty *)
 | Ty_Rcd_dotform : forall (l_t_T_list:list_label_t_T) (G5:G),
     (forall G5 t_ T_, In (G5,t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (G5,t_,T_) end) (unmake_list_label_t_T l_t_T_list)) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec_comp_lu_some (make_list_label_t (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,t_)) l_t_T_list))) (T_Rec (make_list_label_T (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,T_)) l_t_T_list)))
 | Ty_Proj_dotform : forall (l_T_list:list_label_T) (j:index) (G5:G) (t5:t) (t101 t102:(label*T)),
          nth_list_label_T (j - 1) l_T_list = Some t101 ->
     nth_list_label_T (j - 1) l_T_list = Some t102 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t102 with (l_,T_) => l_ end)) (match t101 with (l_,T_) => T_ end)
 | Ty_Rcd_comp : forall (l_t_T_list:list_label_t_T) (G5:G),
     (forall G5 t_ T_, In (G5,t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (G5,t_,T_) end) (unmake_list_label_t_T l_t_T_list)) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec_comp_lu_some (make_list_label_t (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,t_)) l_t_T_list))) (T_Rec (make_list_label_T (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,T_)) l_t_T_list)))
 | Ty_Proj_comp : forall (l_T_list:list_label_T) (j:index) (G5:G) (t5:t) (t103 t104:(label*T)),
          nth_list_label_T j l_T_list = Some t103 ->
     nth_list_label_T j l_T_list = Some t104 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t104 with (l_,T_) => l_ end)) (match t103 with (l_,T_) => T_ end)
 | Ty_Rcd_comp_u : forall (l_t_T_list:list_label_t_T) (G5:G),
     (forall G5 t_ T_, In (G5,t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (G5,t_,T_) end) (unmake_list_label_t_T l_t_T_list)) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec_comp_lu_some (make_list_label_t (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,t_)) l_t_T_list))) (T_Rec (make_list_label_T (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,T_)) l_t_T_list)))
 | Ty_Proj_comp_u : forall (l_T_list:list_label_T) (j:index) (G5:G) (t5:t) (t105 t106:(label*T)),
          nth_list_label_T j l_T_list = Some t105 ->
     nth_list_label_T j l_T_list = Some t106 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t106 with (l_,T_) => l_ end)) (match t105 with (l_,T_) => T_ end)
 | Ty_Rcd_comp_lu : forall (l_t_T_list:list_label_t_T) (G5:G),
     (forall G5 t_ T_, In (G5,t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (G5,t_,T_) end) (unmake_list_label_t_T l_t_T_list)) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec_comp_lu_some (make_list_label_t (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,t_)) l_t_T_list))) (T_Rec (make_list_label_T (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,T_)) l_t_T_list)))
 | Ty_Proj_comp_lu : forall (l_T_list:list_label_T) (j:index) (G5:G) (t5:t) (t107 t108:(label*T)),
          nth_list_label_T (j - 1) l_T_list = Some t107 ->
     nth_list_label_T (j - 1) l_T_list = Some t108 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t108 with (l_,T_) => l_ end)) (match t107 with (l_,T_) => T_ end)
 | Ty_Proj_dotform_minus : forall (l_T_list:list_label_T) (j:index) (G5:G) (t5:t) (t109 t110:(label*T)),
          nth_list_label_T j l_T_list = Some t109 ->
     nth_list_label_T j l_T_list = Some t110 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t110 with (l_,T_) => l_ end)) (match t109 with (l_,T_) => T_ end)
 | Ty_Proj_comp_lu_minus : forall (l_T_list:list_label_T) (j:index) (G5:G) (t5:t) (t111 t112:(label*T)),
          nth_list_label_T j l_T_list = Some t111 ->
     nth_list_label_T j l_T_list = Some t112 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t112 with (l_,T_) => l_ end)) (match t111 with (l_,T_) => T_ end).


