/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.13.ott -/




abbrev value_name := Nat
abbrev index := Nat

inductive list_value_name : Type where
  | Nil_list_value_name : list_value_name
  | Cons_list_value_name (x : value_name) (_ : list_value_name) : list_value_name
  deriving Inhabited

mutual
inductive a : Type where
  | a_x (x : value_name) : a
  | a_A (_ : list_a) : a
  | a_X (_ : list_value_name) : a
  | a_V (_ : list_a) : a
  | a_C (_ : list_c) : a

inductive list_c : Type where
  | Nil_list_c : list_c
  | Cons_list_c (_ : c) (_ : list_c) : list_c

inductive c : Type where
  | c_C (a5 : a) (a' : a) : c
  | c_VC (_ : list_a) : c

inductive list_a : Type where
  | Nil_list_a : list_a
  | Cons_list_a (av : a) (_ : list_a) : list_a

end
open list_value_name list_a list_c a c
def map_list_value_name {A : Type} (f : value_name -> A) (l : list_value_name) : List A :=
  match l with
  | Nil_list_value_name => []
  | Cons_list_value_name h tl_ => (f h) :: (map_list_value_name f tl_)

def make_list_value_name (l : List value_name) : list_value_name :=
  match l with
  | [] => Nil_list_value_name
  | h :: tl_ => Cons_list_value_name h (make_list_value_name tl_)

def unmake_list_value_name (l : list_value_name) : List value_name :=
  match l with
  | Nil_list_value_name => []
  | Cons_list_value_name h tl_ => h :: (unmake_list_value_name tl_)

def nth_list_value_name (n : Nat) (l : list_value_name) : Option value_name :=
  match n, l with
  | 0, Cons_list_value_name h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_value_name => none
  | k+1, Cons_list_value_name _ tl_ => nth_list_value_name k tl_

def app_list_value_name (l m : list_value_name) : list_value_name :=
  match l with
  | Nil_list_value_name => m
  | Cons_list_value_name h tl_ => Cons_list_value_name h (app_list_value_name tl_ m)

def map_list_a {A : Type} (f : a -> A) (l : list_a) : List A :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => (f h) :: (map_list_a f tl_)

def make_list_a (l : List a) : list_a :=
  match l with
  | [] => Nil_list_a
  | h :: tl_ => Cons_list_a h (make_list_a tl_)

def unmake_list_a (l : list_a) : List a :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => h :: (unmake_list_a tl_)

def nth_list_a (n : Nat) (l : list_a) : Option a :=
  match n, l with
  | 0, Cons_list_a h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_a => none
  | k+1, Cons_list_a _ tl_ => nth_list_a k tl_

def app_list_a (l m : list_a) : list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)

def map_list_c {A : Type} (f : c -> A) (l : list_c) : List A :=
  match l with
  | Nil_list_c => []
  | Cons_list_c h tl_ => (f h) :: (map_list_c f tl_)

def make_list_c (l : List c) : list_c :=
  match l with
  | [] => Nil_list_c
  | h :: tl_ => Cons_list_c h (make_list_c tl_)

def unmake_list_c (l : list_c) : List c :=
  match l with
  | Nil_list_c => []
  | Cons_list_c h tl_ => h :: (unmake_list_c tl_)

def nth_list_c (n : Nat) (l : list_c) : Option c :=
  match n, l with
  | 0, Cons_list_c h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_c => none
  | k+1, Cons_list_c _ tl_ => nth_list_c k tl_

def app_list_c (l m : list_c) : list_c :=
  match l with
  | Nil_list_c => m
  | Cons_list_c h tl_ => Cons_list_c h (app_list_c tl_ m)


def aux_b_a_of_a_list (l:list_a) : List value_name :=
  match l with
  | Nil_list_a => []
  | Cons_list_a av_ a_list_ => ([]) ++ (aux_b_a_of_a_list a_list_)


mutual
def aux_b_c_of_c (c5:c) : List value_name :=
  match c5 with
  | (c_C a5 a') => (aux_b_a_of_a a5)
  | (c_VC av_list) => (aux_b_a_of_a_list av_list)
def aux_b_c_of_c_list (l:list_c) : List value_name :=
  match l with
  | Nil_list_c => []
  | Cons_list_c c_ c_list_ => ((aux_b_c_of_c c_)) ++ (aux_b_c_of_c_list c_list_)
def aux_b_a_of_a (a_5:a) : List value_name :=
  match a_5 with
  | (a_x x) => [x]
  | (a_A a_list) => (aux_b_a_of_a_list a_list)
  | (a_X x_list) => (unmake_list_value_name x_list)
  | (a_V av_list) => (aux_b_a_of_a_list av_list)
  | (a_C c_list) => (aux_b_c_of_c_list c_list)
end


/- - subrules - -/
def is_a_of_x_list (l:list_value_name) : Bool :=
  match l with
  | Nil_list_value_name => true
  | Cons_list_value_name x_ x_list_ => (true) && (is_a_of_x_list x_list_)


mutual
def is_c_of_a_list (l:list_a) : Bool :=
  match l with
  | Nil_list_a => true
  | Cons_list_a av_ av_list_ => ((is_av_of_a av_)) && (is_c_of_a_list av_list_)
def is_c_of_c (c5:c) : Bool :=
  match c5 with
  | (c_C a5 a') => ((is_a_of_a a5) /\ (is_a_of_a a'))
  | (c_VC av_list) => (is_c_of_a_list av_list)
def is_a_of_c_list (l:list_c) : Bool :=
  match l with
  | Nil_list_c => true
  | Cons_list_c c_ c_list_ => ((is_c_of_c c_)) && (is_a_of_c_list c_list_)
def is_a_of_a_list (l:list_a) : Bool :=
  match l with
  | Nil_list_a => true
  | Cons_list_a av_ av_list_ => ((is_av_of_a av_)) && (is_a_of_a_list av_list_)
def is_a_of_a (a_5:a) : Bool :=
  match a_5 with
  | (a_x x) => (true)
  | (a_A a_list) => (is_a_of_a_list a_list)
  | (a_X x_list) => (is_a_of_x_list x_list)
  | (a_V av_list) => (is_a_of_a_list av_list)
  | (a_C c_list) => (is_a_of_c_list c_list)
def is_av_of_a_list (l:list_a) : Bool :=
  match l with
  | Nil_list_a => true
  | Cons_list_a av_ av_list_ => ((is_av_of_a av_)) && (is_av_of_a_list av_list_)
def is_av_of_a (a_5:a) : Bool :=
  match a_5 with
  | (a_x x) => false
  | (a_A a_list) => (is_av_of_a_list a_list)
  | (a_X x_list) => false
  | (a_V av_list) => (is_av_of_a_list av_list)
  | (a_C c_list) => false
end

/- - library functions - -/
def list_minus {α : Type} [BEq α] (l1:List α) (l2:List α) : (List α) :=
  match l1 with
  | [] => []
  | h::t => if List.elem h l2 then list_minus t l2 else h::(list_minus t l2)


/- - free variables - -/
mutual
def fv_c (c5:c) :  List value_name :=
  match c5 with
  | (c_C a5 a') => (fv_a a5) ++ (list_minus (fv_a a') (aux_b_a_of_a a5))
  | (c_VC av_list) => []
def fv_c_list (l:list_c) : List value_name :=
  match l with
  | Nil_list_c => []
  | Cons_list_c c_ c_list_ => (fv_c c_) ++ (fv_c_list c_list_)
def fv_a_list (l:list_a) : List value_name :=
  match l with
  | Nil_list_a => []
  | Cons_list_a a_ a_list_ => (fv_a a_) ++ (fv_a_list a_list_)
def fv_a (a_5:a) :  List value_name :=
  match a_5 with
  | (a_x x) => [x]
  | (a_A a_list) => (fv_a_list a_list)
  | (a_X x_list) => []
  | (a_V av_list) => []
  | (a_C c_list) => (fv_c_list c_list)
end

/- - library functions - -/
def list_assoc {α β : Type} [DecidableEq α] (l:List (α × β)) (x:α) : Option β :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def msubst_c (sub:List (value_name×a)) (c5:c) : c :=
  match c5 with
  | (c_C a5 a') => c_C (msubst_a sub a5) (msubst_a (List.filter (fun (x5,a_6) => not ( List.elem x5 ((aux_b_a_of_a a5)))) sub) a')
  | (c_VC av_list) => c_VC av_list
def msubst_c_list (sub:List (value_name×a)) (a__6:list_c) : list_c :=
  match a__6 with
  | Nil_list_c => Nil_list_c
  | Cons_list_c c c_tl => Cons_list_c (msubst_c sub c) (msubst_c_list sub c_tl)
def msubst_a_list (sub:List (value_name×a)) (a__6:list_a) : list_a :=
  match a__6 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (msubst_a sub a) (msubst_a_list sub a_tl)
def msubst_a (sub:List (value_name×a)) (a__6:a) : a :=
  match a__6 with
  | (a_x x) => (match list_assoc sub x with | none => (a_x x)| some a_5 => a_5 )
  | (a_A a_list) => a_A (msubst_a_list sub a_list)
  | (a_X x_list) => a_X x_list
  | (a_V av_list) => a_V av_list
  | (a_C c_list) => a_C (msubst_c_list sub c_list)
end

mutual
def subst_c (a_6:a) (x5:value_name) (c5:c) : c :=
  match c5 with
  | (c_C a5 a') => c_C (subst_a a_6 x5 a5) (if  List.elem x5 ((aux_b_a_of_a a5)) then a' else (subst_a a_6 x5 a'))
  | (c_VC av_list) => c_VC av_list
def subst_c_list (a_5:a) (x_5:value_name) (a__6:list_c) : list_c :=
  match a__6 with
  | Nil_list_c => Nil_list_c
  | Cons_list_c c c_tl => Cons_list_c (subst_c a_5 x_5 c) (subst_c_list a_5 x_5 c_tl)
def subst_a_list (a_5:a) (x_5:value_name) (a__6:list_a) : list_a :=
  match a__6 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (subst_a a_5 x_5 a) (subst_a_list a_5 x_5 a_tl)
def subst_a (a_5:a) (x_5:value_name) (a__6:a) : a :=
  match a__6 with
  | (a_x x) => (if x=x_5 then a_5 else (a_x x))
  | (a_A a_list) => a_A (subst_a_list a_5 x_5 a_list)
  | (a_X x_list) => a_X x_list
  | (a_V av_list) => a_V av_list
  | (a_C c_list) => a_C (subst_c_list a_5 x_5 c_list)
end



