(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/tmp_test7.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.


Definition typevar : Set := nat. (* type variable *)
Lemma eq_typevar: forall (x y : typevar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_typevar : ott_coq_equality.
Definition termvar : Set := nat. (* term variable *)
Lemma eq_termvar: forall (x y : termvar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_termvar : ott_coq_equality.
Definition label : Set := nat. (* field label *)
Definition index : Set := nat. (* indices *)

Inductive T : Set :=  (* type *)
 | Ty_Var (X:typevar) (* type variable *)
 | Ty_Top : T (* maximum type *)
 | Ty_Fun (T5:T) (T':T) (* type of functions *)
 | Ty_Forall (X:typevar) (T5:T) (T':T) (* universal type *)
 | Ty_Rec (_:list_label_T) (* record *)
with list_label_T : Set := 
 | Nil_list_label_T : list_label_T
 | Cons_list_label_T (l:label) (_:T) (_:list_label_T).

Inductive list_label_p : Set := 
 | Nil_list_label_p : list_label_p
 | Cons_list_label_p (l:label) (_:p) (_:list_label_p)
with p : Set :=  (* pattern *)
 | P_Var (x:termvar) (T5:T) (* variable pattern *)
 | P_Rec (_:list_label_p) (* record pattern *).

Inductive list_label_t : Set := 
 | Nil_list_label_t : list_label_t
 | Cons_list_label_t (l:label) (v:t) (_:list_label_t)
with t : Set :=  (* term *)
 | t_Var (x:termvar) (* variable *)
 | t_Lam (x:termvar) (T5:T) (t5:t) (* abstraction *)
 | t_App (t5:t) (t':t) (* application *)
 | t_TLam (X:typevar) (T5:T) (t5:t) (* type abstraction *)
 | t_TApp (t5:t) (T5:T) (* type application *)
 | t_Rec (_:list_label_t) (* record *)
 | t_Proj (t5:t) (l:label) (* projection *)
 | t_Let (p5:p) (t5:t) (t':t) (* pattern binding *).

Inductive G : Set :=  (* type environment *)
 | G_empty : G
 | G_type (G5:G) (X:typevar) (T5:T)
 | G_term (G5:G) (x:termvar) (T5:T).

Definition s : Set := list (termvar*t).

Inductive list_G : Set := 
 | Nil_list_G : list_G
 | Cons_list_G (_:G) (_:list_G).
Fixpoint map_list_G (A:Type) (f:G->A) (l:list_G) : list A :=
  match l with
  | Nil_list_G => nil
  | Cons_list_G h tl_ => cons (f h) (map_list_G A f tl_)
  end.
Arguments map_list_G [A] _ _.

Fixpoint make_list_G (l: list G): list_G :=
  match l with
  | nil  => Nil_list_G
  | cons h tl_ => Cons_list_G h (make_list_G tl_)
  end.

Fixpoint unmake_list_G (l: list_G): list G :=
  match l with
  | Nil_list_G => nil
  | Cons_list_G h tl_ => cons h (unmake_list_G tl_)
  end.

Fixpoint nth_list_G (n:nat) (l: list_G) {struct n} : option G :=
  match n,l with
  | O, Cons_list_G h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_G => None
  | S m, Cons_list_G h tl_ => nth_list_G m tl_
  end.

Fixpoint app_list_G (l m: list_G): list_G :=
  match l with
  | Nil_list_G => m
  | Cons_list_G h tl_ => Cons_list_G h (app_list_G tl_ m)
  end.

Fixpoint map_list_label_p (A:Type) (f:label->p->A) (l:list_label_p) : list A :=
  match l with
  | Nil_list_label_p => nil
  | Cons_list_label_p h0 h1 tl_ => cons (f h0 h1) (map_list_label_p A f tl_)
  end.
Arguments map_list_label_p [A] _ _.

Fixpoint make_list_label_p (l: list (label * p)): list_label_p :=
  match l with
  | nil  => Nil_list_label_p
  | cons (h0,h1) tl_ => Cons_list_label_p h0 h1 (make_list_label_p tl_)
  end.

Fixpoint unmake_list_label_p (l: list_label_p): list (label * p) :=
  match l with
  | Nil_list_label_p => nil
  | Cons_list_label_p h0 h1 tl_ => cons (h0,h1) (unmake_list_label_p tl_)
  end.

Fixpoint nth_list_label_p (n:nat) (l: list_label_p) {struct n} : option (label * p) :=
  match n,l with
  | O, Cons_list_label_p h0 h1 tl_ => Some (h0,h1)
  | O, _ => None
  | S m, Nil_list_label_p => None
  | S m, Cons_list_label_p h0 h1 tl_ => nth_list_label_p m tl_
  end.

Fixpoint app_list_label_p (l m: list_label_p): list_label_p :=
  match l with
  | Nil_list_label_p => m
  | Cons_list_label_p h0 h1 tl_ => Cons_list_label_p h0 h1 (app_list_label_p tl_ m)
  end.

Fixpoint map_list_label_t (A:Type) (f:label->t->A) (l:list_label_t) : list A :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t h0 h1 tl_ => cons (f h0 h1) (map_list_label_t A f tl_)
  end.
Arguments map_list_label_t [A] _ _.

Fixpoint make_list_label_t (l: list (label * t)): list_label_t :=
  match l with
  | nil  => Nil_list_label_t
  | cons (h0,h1) tl_ => Cons_list_label_t h0 h1 (make_list_label_t tl_)
  end.

Fixpoint unmake_list_label_t (l: list_label_t): list (label * t) :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t h0 h1 tl_ => cons (h0,h1) (unmake_list_label_t tl_)
  end.

Fixpoint nth_list_label_t (n:nat) (l: list_label_t) {struct n} : option (label * t) :=
  match n,l with
  | O, Cons_list_label_t h0 h1 tl_ => Some (h0,h1)
  | O, _ => None
  | S m, Nil_list_label_t => None
  | S m, Cons_list_label_t h0 h1 tl_ => nth_list_label_t m tl_
  end.

Fixpoint app_list_label_t (l m: list_label_t): list_label_t :=
  match l with
  | Nil_list_label_t => m
  | Cons_list_label_t h0 h1 tl_ => Cons_list_label_t h0 h1 (app_list_label_t tl_ m)
  end.

Fixpoint map_list_label_T (A:Type) (f:label->T->A) (l:list_label_T) : list A :=
  match l with
  | Nil_list_label_T => nil
  | Cons_list_label_T h0 h1 tl_ => cons (f h0 h1) (map_list_label_T A f tl_)
  end.
Arguments map_list_label_T [A] _ _.

Fixpoint make_list_label_T (l: list (label * T)): list_label_T :=
  match l with
  | nil  => Nil_list_label_T
  | cons (h0,h1) tl_ => Cons_list_label_T h0 h1 (make_list_label_T tl_)
  end.

Fixpoint unmake_list_label_T (l: list_label_T): list (label * T) :=
  match l with
  | Nil_list_label_T => nil
  | Cons_list_label_T h0 h1 tl_ => cons (h0,h1) (unmake_list_label_T tl_)
  end.

Fixpoint nth_list_label_T (n:nat) (l: list_label_T) {struct n} : option (label * T) :=
  match n,l with
  | O, Cons_list_label_T h0 h1 tl_ => Some (h0,h1)
  | O, _ => None
  | S m, Nil_list_label_T => None
  | S m, Cons_list_label_T h0 h1 tl_ => nth_list_label_T m tl_
  end.

Fixpoint app_list_label_T (l m: list_label_T): list_label_T :=
  match l with
  | Nil_list_label_T => m
  | Cons_list_label_T h0 h1 tl_ => Cons_list_label_T h0 h1 (app_list_label_T tl_ m)
  end.


Fixpoint aux_b_p_of_label_p_list (l:list_label_p): list termvar :=
  match l with
  | Nil_list_label_p => nil
  | Cons_list_label_p l_ p_ label_p_list_ => app (((aux_b_p_of_p p_))) (aux_b_p_of_label_p_list label_p_list_)
end
with aux_b_p_of_p (p_5:p) : list termvar :=
  match p_5 with
  | (P_Var x T5) => (cons x nil)
  | (P_Rec l_p_list) => (aux_b_p_of_label_p_list l_p_list)
end.


(** subrules *)
Fixpoint is_v_of_l_t_list (l:list_label_t) : Prop :=
  match l with
  | Nil_list_label_t => True
  | Cons_list_label_t l_ t_ l_t_list_ => (is_v_of_t t_) /\ (is_v_of_l_t_list l_t_list_)
end
with is_v_of_t (t_6:t) : Prop :=
  match t_6 with
  | (t_Var x) => False
  | (t_Lam x T5 t5) => (True)
  | (t_App t5 t') => False
  | (t_TLam X T5 t5) => (True)
  | (t_TApp t5 T5) => False
  | (t_Rec l_t_list) => (is_v_of_l_t_list l_t_list)
  | (t_Proj t5 l) => False
  | (t_Let p5 t5 t') => False
end.

(** library functions *)
Fixpoint list_mem A (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list A) {struct l} : bool :=
  match l with
  | nil => false
  | cons h t => if eq h x then true else list_mem A eq x t
end.
Arguments list_mem [A] _ _ _.

Fixpoint list_assoc A B (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list (A*B)) {struct l} : option B :=
  match l with
  | nil => None
  | cons (a,b) t => if (eq a x) then Some b else list_assoc A B eq x t
end.
Arguments list_assoc [A B] _ _ _.

Fixpoint list_minus2 A B (eq:forall a b:A,{a=b}+{a<>b}) (l1:list (A*B)) (l2:list A) {struct l1} : list (A*B) :=
  match l1 with
  | nil => nil
  | cons a t => if (list_mem (A:=A) eq (@fst A B a) l2) then list_minus2 A B eq t l2 else cons a (list_minus2 A B eq t l2)
end.
Arguments list_minus2 [A B] _ _ _.


(** substitutions *)
Fixpoint m_T_subst_label_T_list (sub:list (typevar*T)) (S_6:list_label_T) {struct S_6} : list_label_T :=
  match S_6 with
  | Nil_list_label_T => Nil_list_label_T
  | Cons_list_label_T label1 T2 label_T_tl => Cons_list_label_T label1 (m_T_subst_T sub T2) (m_T_subst_label_T_list sub label_T_tl)
end
with m_T_subst_T (sub:list (typevar*T)) (S_6:T) {struct S_6} : T :=
  match S_6 with
  | (Ty_Var X) => (match list_assoc eq_typevar X sub with None => (Ty_Var X) | Some S5 => S5 end)
  | Ty_Top => Ty_Top 
  | (Ty_Fun T5 T') => Ty_Fun (m_T_subst_T sub T5) (m_T_subst_T sub T')
  | (Ty_Forall X T5 T') => Ty_Forall X (m_T_subst_T sub T5) (m_T_subst_T (list_minus2 eq_typevar sub (cons X nil)) T')
  | (Ty_Rec l_T_list) => Ty_Rec (m_T_subst_label_T_list sub l_T_list)
end.

Fixpoint Tsubst_label_T_list (S5:T) (X5:typevar) (S_6:list_label_T) {struct S_6} : list_label_T :=
  match S_6 with
  | Nil_list_label_T => Nil_list_label_T
  | Cons_list_label_T label1 T2 label_T_tl => Cons_list_label_T label1 (Tsubst_T S5 X5 T2) (Tsubst_label_T_list S5 X5 label_T_tl)
end
with Tsubst_T (S5:T) (X5:typevar) (S_6:T) {struct S_6} : T :=
  match S_6 with
  | (Ty_Var X) => (if eq_typevar X X5 then S5 else (Ty_Var X))
  | Ty_Top => Ty_Top 
  | (Ty_Fun T5 T') => Ty_Fun (Tsubst_T S5 X5 T5) (Tsubst_T S5 X5 T')
  | (Ty_Forall X T5 T') => Ty_Forall X (Tsubst_T S5 X5 T5) (if list_mem eq_typevar X5 (cons X nil) then T' else (Tsubst_T S5 X5 T'))
  | (Ty_Rec l_T_list) => Ty_Rec (Tsubst_label_T_list S5 X5 l_T_list)
end.

Fixpoint m_T_subst_label_p_list (sub:list (typevar*T)) (p_5:list_label_p) {struct p_5} : list_label_p :=
  match p_5 with
  | Nil_list_label_p => Nil_list_label_p
  | Cons_list_label_p label1 p2 label_p_tl => Cons_list_label_p label1 (m_T_subst_p sub p2) (m_T_subst_label_p_list sub label_p_tl)
end
with m_T_subst_p (sub:list (typevar*T)) (p_5:p) {struct p_5} : p :=
  match p_5 with
  | (P_Var x T5) => P_Var x (m_T_subst_T sub T5)
  | (P_Rec l_p_list) => P_Rec (m_T_subst_label_p_list sub l_p_list)
end.

Fixpoint Tsubst_label_p_list (S5:T) (X5:typevar) (p_5:list_label_p) {struct p_5} : list_label_p :=
  match p_5 with
  | Nil_list_label_p => Nil_list_label_p
  | Cons_list_label_p label1 p2 label_p_tl => Cons_list_label_p label1 (Tsubst_p S5 X5 p2) (Tsubst_label_p_list S5 X5 label_p_tl)
end
with Tsubst_p (S5:T) (X5:typevar) (p_5:p) {struct p_5} : p :=
  match p_5 with
  | (P_Var x T5) => P_Var x (Tsubst_T S5 X5 T5)
  | (P_Rec l_p_list) => P_Rec (Tsubst_label_p_list S5 X5 l_p_list)
end.

Fixpoint m_T_subst_G (sub:list (typevar*T)) (D5:G) {struct D5} : G :=
  match D5 with
  | G_empty => G_empty 
  | (G_type G5 X T5) => G_type (m_T_subst_G sub G5) X (m_T_subst_T sub T5)
  | (G_term G5 x T5) => G_term (m_T_subst_G sub G5) x (m_T_subst_T sub T5)
end.

Fixpoint m_T_subst_label_t_list (sub:list (typevar*T)) (t_6:list_label_t) {struct t_6} : list_label_t :=
  match t_6 with
  | Nil_list_label_t => Nil_list_label_t
  | Cons_list_label_t label1 t2 label_t_tl => Cons_list_label_t label1 (m_T_subst_t sub t2) (m_T_subst_label_t_list sub label_t_tl)
end
with m_T_subst_t (sub:list (typevar*T)) (t_6:t) {struct t_6} : t :=
  match t_6 with
  | (t_Var x) => t_Var x
  | (t_Lam x T5 t5) => t_Lam x (m_T_subst_T sub T5) (m_T_subst_t sub t5)
  | (t_App t5 t') => t_App (m_T_subst_t sub t5) (m_T_subst_t sub t')
  | (t_TLam X T5 t5) => t_TLam X (m_T_subst_T sub T5) (m_T_subst_t (list_minus2 eq_typevar sub (cons X nil)) t5)
  | (t_TApp t5 T5) => t_TApp (m_T_subst_t sub t5) (m_T_subst_T sub T5)
  | (t_Rec l_t_list) => t_Rec (m_T_subst_label_t_list sub l_t_list)
  | (t_Proj t5 l) => t_Proj (m_T_subst_t sub t5) l
  | (t_Let p5 t5 t') => t_Let (m_T_subst_p sub p5) (m_T_subst_t sub t5) (m_T_subst_t sub t')
end.

Fixpoint m_t_subst_label_t_list (sub:list (termvar*t)) (t__7:list_label_t) {struct t__7} : list_label_t :=
  match t__7 with
  | Nil_list_label_t => Nil_list_label_t
  | Cons_list_label_t label1 t2 label_t_tl => Cons_list_label_t label1 (m_t_subst_t sub t2) (m_t_subst_label_t_list sub label_t_tl)
end
with m_t_subst_t (sub:list (termvar*t)) (t__7:t) {struct t__7} : t :=
  match t__7 with
  | (t_Var x) => (match list_assoc eq_termvar x sub with None => (t_Var x) | Some t_6 => t_6 end)
  | (t_Lam x T5 t5) => t_Lam x T5 (m_t_subst_t (list_minus2 eq_termvar sub (cons x nil)) t5)
  | (t_App t5 t') => t_App (m_t_subst_t sub t5) (m_t_subst_t sub t')
  | (t_TLam X T5 t5) => t_TLam X T5 (m_t_subst_t sub t5)
  | (t_TApp t5 T5) => t_TApp (m_t_subst_t sub t5) T5
  | (t_Rec l_t_list) => t_Rec (m_t_subst_label_t_list sub l_t_list)
  | (t_Proj t5 l) => t_Proj (m_t_subst_t sub t5) l
  | (t_Let p5 t5 t') => t_Let p5 (m_t_subst_t sub t5) (m_t_subst_t (list_minus2 eq_termvar sub (aux_b_p_of_p p5)) t')
end.

Fixpoint Tsubst_G (S5:T) (X5:typevar) (D5:G) {struct D5} : G :=
  match D5 with
  | G_empty => G_empty 
  | (G_type G5 X T5) => G_type (Tsubst_G S5 X5 G5) X (Tsubst_T S5 X5 T5)
  | (G_term G5 x T5) => G_term (Tsubst_G S5 X5 G5) x (Tsubst_T S5 X5 T5)
end.

Fixpoint Tsubst_label_t_list (S5:T) (X5:typevar) (t_6:list_label_t) {struct t_6} : list_label_t :=
  match t_6 with
  | Nil_list_label_t => Nil_list_label_t
  | Cons_list_label_t label1 t2 label_t_tl => Cons_list_label_t label1 (Tsubst_t S5 X5 t2) (Tsubst_label_t_list S5 X5 label_t_tl)
end
with Tsubst_t (S5:T) (X5:typevar) (t_6:t) {struct t_6} : t :=
  match t_6 with
  | (t_Var x) => t_Var x
  | (t_Lam x T5 t5) => t_Lam x (Tsubst_T S5 X5 T5) (Tsubst_t S5 X5 t5)
  | (t_App t5 t') => t_App (Tsubst_t S5 X5 t5) (Tsubst_t S5 X5 t')
  | (t_TLam X T5 t5) => t_TLam X (Tsubst_T S5 X5 T5) (if list_mem eq_typevar X5 (cons X nil) then t5 else (Tsubst_t S5 X5 t5))
  | (t_TApp t5 T5) => t_TApp (Tsubst_t S5 X5 t5) (Tsubst_T S5 X5 T5)
  | (t_Rec l_t_list) => t_Rec (Tsubst_label_t_list S5 X5 l_t_list)
  | (t_Proj t5 l) => t_Proj (Tsubst_t S5 X5 t5) l
  | (t_Let p5 t5 t') => t_Let (Tsubst_p S5 X5 p5) (Tsubst_t S5 X5 t5) (Tsubst_t S5 X5 t')
end.

Fixpoint tsubst_label_t_list (t_6:t) (x5:termvar) (t__7:list_label_t) {struct t__7} : list_label_t :=
  match t__7 with
  | Nil_list_label_t => Nil_list_label_t
  | Cons_list_label_t label1 t2 label_t_tl => Cons_list_label_t label1 (tsubst_t t_6 x5 t2) (tsubst_label_t_list t_6 x5 label_t_tl)
end
with tsubst_t (t_6:t) (x5:termvar) (t__7:t) {struct t__7} : t :=
  match t__7 with
  | (t_Var x) => (if eq_termvar x x5 then t_6 else (t_Var x))
  | (t_Lam x T5 t5) => t_Lam x T5 (if list_mem eq_termvar x5 (cons x nil) then t5 else (tsubst_t t_6 x5 t5))
  | (t_App t5 t') => t_App (tsubst_t t_6 x5 t5) (tsubst_t t_6 x5 t')
  | (t_TLam X T5 t5) => t_TLam X T5 (tsubst_t t_6 x5 t5)
  | (t_TApp t5 T5) => t_TApp (tsubst_t t_6 x5 t5) T5
  | (t_Rec l_t_list) => t_Rec (tsubst_label_t_list t_6 x5 l_t_list)
  | (t_Proj t5 l) => t_Proj (tsubst_t t_6 x5 t5) l
  | (t_Let p5 t5 t') => t_Let p5 (tsubst_t t_6 x5 t5) (if list_mem eq_termvar x5 (aux_b_p_of_p p5) then t' else (tsubst_t t_6 x5 t'))
end.

(** library functions *)
Fixpoint list_minus A (eq:forall a b:A,{a=b}+{a<>b}) (l1:list A) (l2:list A) {struct l1} : list A :=
  match l1 with
  | nil => nil
  | cons h t => if (list_mem (A:=A) eq h l2) then list_minus A eq t l2 else cons h (list_minus A eq t l2)
end.
Arguments list_minus [A] _ _ _.


(** free variables *)
Fixpoint ftv_label_T_list (l:list_label_T) : list typevar :=
  match l with
  | Nil_list_label_T => nil
  | Cons_list_label_T l_ T_ l_T_list_ => app ((ftv_T T_)) (ftv_label_T_list l_T_list_)
end
with ftv_T (S5:T) : list typevar :=
  match S5 with
  | (Ty_Var X) => (cons X nil)
  | Ty_Top => nil
  | (Ty_Fun T5 T') => (app (ftv_T T5) (ftv_T T'))
  | (Ty_Forall X T5 T') => (app (ftv_T T5) (list_minus eq_typevar (ftv_T T') (cons X nil)))
  | (Ty_Rec l_T_list) => ((ftv_label_T_list l_T_list))
end.

Fixpoint ftv_label_p_list (l:list_label_p) : list typevar :=
  match l with
  | Nil_list_label_p => nil
  | Cons_list_label_p l_ p_ l_p_list_ => app ((ftv_p p_)) (ftv_label_p_list l_p_list_)
end
with ftv_p (p_5:p) : list typevar :=
  match p_5 with
  | (P_Var x T5) => ((ftv_T T5))
  | (P_Rec l_p_list) => ((ftv_label_p_list l_p_list))
end.

Fixpoint fv_label_t_list (l:list_label_t) : list termvar :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t l_ t_ l_t_list_ => app ((fv_t t_)) (fv_label_t_list l_t_list_)
end
with fv_t (t_6:t) : list termvar :=
  match t_6 with
  | (t_Var x) => (cons x nil)
  | (t_Lam x T5 t5) => ((list_minus eq_termvar (fv_t t5) (cons x nil)))
  | (t_App t5 t') => (app (fv_t t5) (fv_t t'))
  | (t_TLam X T5 t5) => ((fv_t t5))
  | (t_TApp t5 T5) => ((fv_t t5))
  | (t_Rec l_t_list) => ((fv_label_t_list l_t_list))
  | (t_Proj t5 l) => ((fv_t t5))
  | (t_Let p5 t5 t') => (app (fv_t t5) (list_minus eq_termvar (fv_t t') (aux_b_p_of_p p5)))
end.

Fixpoint ftv_G (D5:G) : list typevar :=
  match D5 with
  | G_empty => nil
  | (G_type G5 X T5) => (app (ftv_G G5) (ftv_T T5))
  | (G_term G5 x T5) => (app (ftv_G G5) (ftv_T T5))
end.

Fixpoint ftv_label_t_list (l:list_label_t) : list typevar :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t l_ t_ l_t_list_ => app ((ftv_t t_)) (ftv_label_t_list l_t_list_)
end
with ftv_t (t_6:t) : list typevar :=
  match t_6 with
  | (t_Var x) => nil
  | (t_Lam x T5 t5) => (app (ftv_T T5) (ftv_t t5))
  | (t_App t5 t') => (app (ftv_t t5) (ftv_t t'))
  | (t_TLam X T5 t5) => (app (ftv_T T5) (list_minus eq_typevar (ftv_t t5) (cons X nil)))
  | (t_TApp t5 T5) => (app (ftv_t t5) (ftv_T T5))
  | (t_Rec l_t_list) => ((ftv_label_t_list l_t_list))
  | (t_Proj t5 l) => ((ftv_t t5))
  | (t_Let p5 t5 t') => (app (ftv_p p5) (app (ftv_t t5) (ftv_t t')))
end.


 Fixpoint append_G (g1 g2 : G) {struct g2} : G :=
   match g2 with
   | G_empty => g1
   | G_type gh tv t => G_type (append_G g1 gh) tv t
   | G_term gh v t => G_term (append_G g1 gh) v t
 end.  
 Fixpoint flatten_G (gl:list_G) : G :=
   match gl with 
   | Nil_list_G => G_empty
   | Cons_list_G g gs => append_G g (flatten_G gs)
 end.  
(* definitions *)

(* defns Judgement_in *)
Inductive xinG : termvar -> G -> Prop :=    (* defn xinG *)
 | xinG_1 : forall (x:termvar) (G5:G) (T5:T),
     xinG x (G_term G5 x T5)
 | xinG_2 : forall (x:termvar) (G5:G) (X':typevar) (U':T),
     xinG x G5 ->
     xinG x (G_type G5 X' U')
 | xinG_3 : forall (x:termvar) (G5:G) (x':termvar) (T':T),
     xinG x G5 ->
     xinG x (G_term G5 x' T')
with XinG : typevar -> G -> Prop :=    (* defn XinG *)
 | XinG_1 : forall (X:typevar) (G5:G) (U:T),
     XinG X (G_type G5 X U)
 | XinG_2 : forall (X:typevar) (G5:G) (X':typevar) (U':T),
     XinG X G5 ->
     XinG X (G_type G5 X' U')
 | XinG_3 : forall (X:typevar) (G5:G) (x':termvar) (T':T),
     XinG X G5 ->
     XinG X (G_term G5 x' T')
with tin : termvar -> T -> G -> Prop :=    (* defn tin *)
 | tin_1 : forall (x:termvar) (T5:T) (G5:G),
     tin x T5 (G_term G5 x T5)
 | tin_2 : forall (x:termvar) (T5:T) (G5:G) (X':typevar) (U':T),
     tin x T5 G5 ->
     tin x T5 (G_type G5 X' U')
 | tin_3 : forall (x:termvar) (T5:T) (G5:G) (x':termvar) (T':T),
     tin x T5 G5 ->
     tin x T5 (G_term G5 x' T')
with Tin : typevar -> T -> G -> Prop :=    (* defn Tin *)
 | Tin_1 : forall (X:typevar) (U:T) (G5:G),
     Tin X U (G_type G5 X U)
 | Tin_2 : forall (X:typevar) (U:T) (G5:G) (X':typevar) (U':T),
     Tin X U G5 ->
     Tin X U (G_type G5 X' U')
 | Tin_3 : forall (X:typevar) (U:T) (G5:G) (x':termvar) (T':T),
     Tin X U G5 ->
     Tin X U (G_term G5 x' T').
Inductive list_label_t_T : Set := Nil_list_label_t_T | Cons_list_label_t_T (_:label) (_:t) (_:T) (tl_ : list_label_t_T).

Fixpoint map_list_label_t_T (A:Type) (f:label->t->T->A) (l:list_label_t_T) : list A :=
  match l with
  | Nil_list_label_t_T => nil
  | Cons_list_label_t_T h0 h1 h2 tl_ => cons (f h0 h1 h2) (map_list_label_t_T A f tl_)
  end.
Arguments map_list_label_t_T [A] _ _.

Fixpoint make_list_label_t_T (l: list (label * t * T)): list_label_t_T :=
  match l with
  | nil  => Nil_list_label_t_T
  | cons (h0,h1,h2) tl_ => Cons_list_label_t_T h0 h1 h2 (make_list_label_t_T tl_)
  end.

Fixpoint unmake_list_label_t_T (l: list_label_t_T): list (label * t * T) :=
  match l with
  | Nil_list_label_t_T => nil
  | Cons_list_label_t_T h0 h1 h2 tl_ => cons (h0,h1,h2) (unmake_list_label_t_T tl_)
  end.

Fixpoint nth_list_label_t_T (n:nat) (l: list_label_t_T) {struct n} : option (label * t * T) :=
  match n,l with
  | O, Cons_list_label_t_T h0 h1 h2 tl_ => Some (h0,h1,h2)
  | O, _ => None
  | S m, Nil_list_label_t_T => None
  | S m, Cons_list_label_t_T h0 h1 h2 tl_ => nth_list_label_t_T m tl_
  end.

Fixpoint app_list_label_t_T (l m: list_label_t_T): list_label_t_T :=
  match l with
  | Nil_list_label_t_T => m
  | Cons_list_label_t_T h0 h1 h2 tl_ => Cons_list_label_t_T h0 h1 h2 (app_list_label_t_T tl_ m)
  end.

Inductive list_label_p_T_G : Set := Nil_list_label_p_T_G | Cons_list_label_p_T_G (_:label) (_:p) (_:T) (_:G) (tl_ : list_label_p_T_G).

Fixpoint map_list_label_p_T_G (A:Type) (f:label->p->T->G->A) (l:list_label_p_T_G) : list A :=
  match l with
  | Nil_list_label_p_T_G => nil
  | Cons_list_label_p_T_G h0 h1 h2 h3 tl_ => cons (f h0 h1 h2 h3) (map_list_label_p_T_G A f tl_)
  end.
Arguments map_list_label_p_T_G [A] _ _.

Fixpoint make_list_label_p_T_G (l: list (label * p * T * G)): list_label_p_T_G :=
  match l with
  | nil  => Nil_list_label_p_T_G
  | cons (h0,h1,h2,h3) tl_ => Cons_list_label_p_T_G h0 h1 h2 h3 (make_list_label_p_T_G tl_)
  end.

Fixpoint unmake_list_label_p_T_G (l: list_label_p_T_G): list (label * p * T * G) :=
  match l with
  | Nil_list_label_p_T_G => nil
  | Cons_list_label_p_T_G h0 h1 h2 h3 tl_ => cons (h0,h1,h2,h3) (unmake_list_label_p_T_G tl_)
  end.

Fixpoint nth_list_label_p_T_G (n:nat) (l: list_label_p_T_G) {struct n} : option (label * p * T * G) :=
  match n,l with
  | O, Cons_list_label_p_T_G h0 h1 h2 h3 tl_ => Some (h0,h1,h2,h3)
  | O, _ => None
  | S m, Nil_list_label_p_T_G => None
  | S m, Cons_list_label_p_T_G h0 h1 h2 h3 tl_ => nth_list_label_p_T_G m tl_
  end.

Fixpoint app_list_label_p_T_G (l m: list_label_p_T_G): list_label_p_T_G :=
  match l with
  | Nil_list_label_p_T_G => m
  | Cons_list_label_p_T_G h0 h1 h2 h3 tl_ => Cons_list_label_p_T_G h0 h1 h2 h3 (app_list_label_p_T_G tl_ m)
  end.

(* definitions *)

(* defns Jtype *)
Inductive Gok : G -> Prop :=    (* defn Gok *)
 | Gok_1 : 
     Gok G_empty
 | Gok_2 : forall (G5:G) (x:termvar) (T5:T),
     GT G5 T5 ->
      not(   (  xinG x G5  )   )  ->
     Gok (G_term G5 x T5)
 | Gok_3 : forall (G5:G) (X:typevar) (T5:T),
     GT G5 T5 ->
      not(   (  XinG X G5  )   )  ->
     Gok (G_type G5 X T5)
with GT : G -> T -> Prop :=    (* defn GT *)
 | GT_Var : forall (G5:G) (X:typevar) (U:T),
     Gok G5 ->
     Tin X U G5 ->
     GT G5 (Ty_Var X)
 | GT_Top : forall (G5:G),
     Gok G5 ->
     GT G5 Ty_Top
 | GT_Fun : forall (G5:G) (T5 T':T),
     GT G5 T5 ->
     GT G5 T' ->
     GT G5 (Ty_Fun T5 T')
 | GT_Forall : forall (G5:G) (X:typevar) (T5 T':T),
     GT (G_type G5 X T5) T' ->
     GT G5 (Ty_Forall X T5 T')
 | GT_Rcd : forall (l_T_list:list_label_T) (G5:G),
     (forall G5 T_, In (G5,T_) (map (fun (pat_: (label*T)) => match pat_ with (l_,T_) => (G5,T_) end) (unmake_list_label_T l_T_list)) -> (GT G5 T_)) ->
     GT G5 (Ty_Rec l_T_list)
with SA : G -> T -> T -> Prop :=    (* defn SA *)
 | SA_Top : forall (G5:G) (S:T),
     Gok G5 ->
     SA G5 S Ty_Top
 | SA_Refl_TVar : forall (G5:G) (X:typevar),
     Gok G5 ->
     SA G5 (Ty_Var X) (Ty_Var X)
 | SA_Trans_TVar : forall (G5:G) (X:typevar) (T5 U:T),
     Tin X U G5 ->
     SA G5 U T5 ->
     SA G5 (Ty_Var X) T5
 | SA_Arrow : forall (G5:G) (S1 S2 T1 T2:T),
     SA G5 T1 S1 ->
     SA G5 S2 T2 ->
     SA G5 (Ty_Fun S1 S2) (Ty_Fun T1 T2)
 | SA_All : forall (G5:G) (X:typevar) (S1 S2 T1 T2:T),
     SA G5 T1 S1 ->
     SA (G_type G5 X T1) S2 T2 ->
     SA G5 (Ty_Forall X S1 S2) (Ty_Forall X T1 T2)
 | SA_Rcd : forall (l_T_list k_S_list:list_label_T) (G5:G) (i m:index) (t101 t102:(label*T)),
          nth_list_label_T (i - 1) k_S_list = Some t101 ->
     nth_list_label_T (i - 1) k_S_list = Some t102 ->
 (forall  i , (1<= i  /\  i  <= m) ->  SAf G5 (match t102 with (k_,S_) => k_ end) (match t101 with (k_,S_) => S_ end) l_T_list )  ->
     SA G5 (Ty_Rec k_S_list) (Ty_Rec l_T_list)
with SAf : G -> label -> T -> (list_label_T) -> Prop :=    (* defn SAf *)
 | SAf_found : forall (l_T_list:list_label_T) (G5:G) (k:label) (S T_5:T),
     SA G5 S T_5 ->
     SAf G5 k S ((app_list_label_T (Cons_list_label_T k T_5 Nil_list_label_T) (app_list_label_T l_T_list Nil_list_label_T)))
 | SAf_skip : forall (l_T_list:list_label_T) (G5:G) (k:label) (S:T) (l:label) (T_5:T),
     SAf G5 k S l_T_list ->
     SAf G5 k S ((app_list_label_T (Cons_list_label_T l T_5 Nil_list_label_T) (app_list_label_T l_T_list Nil_list_label_T)))
with Ty : G -> t -> T -> Prop :=    (* defn Ty *)
 | TyCh_Var : forall (G5:G) (x:termvar) (T5:T),
     Gok G5 ->
     tin x T5 G5 ->
     Ty G5 (t_Var x) T5
 | TyCh_Abs : forall (G5:G) (x:termvar) (T1:T) (t2:t) (T2:T),
     Ty (G_term G5 x T1) t2 T2 ->
     Ty G5 (t_Lam x T1 t2) (Ty_Fun T1 T2)
 | TyCh_App : forall (G5:G) (t1 t2:t) (T12 T11:T),
     Ty G5 t1 (Ty_Fun T11 T12) ->
     Ty G5 t2 T11 ->
     Ty G5 (t_App t1 t2) T12
 | TyCh_TAbs : forall (G5:G) (X:typevar) (T1:T) (t2:t) (T2:T),
     Ty (G_type G5 X T1) t2 T2 ->
     Ty G5 (t_TLam X T1 t2) (Ty_Forall X T1 T2)
 | TyCh_TApp : forall (G5:G) (t1:t) (T2:T) (X:typevar) (T12 T11:T),
     Ty G5 t1 (Ty_Forall X T11 T12) ->
     SA G5 T2 T11 ->
     Ty G5 (t_TApp t1 T2)  (Tsubst_T  T2   X   T12 ) 
 | TyCh_Let : forall (G5:G) (p5:p) (t1 t2:t) (T2 T1:T) (D:G),
     Ty G5 t1 T1 ->
     Pat p5 T1 D ->
     Ty  (flatten_G  ((app_list_G (Cons_list_G G5 Nil_list_G) (app_list_G (Cons_list_G D Nil_list_G) Nil_list_G))) )  t2 T2 ->
     Ty G5 (t_Let p5 t1 t2) T2
 | TyCh_Rcd : forall (l_t_T_list:list_label_t_T) (G5:G),
     (forall G5 t_ T_, In (G5,t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (G5,t_,T_) end) (unmake_list_label_t_T l_t_T_list)) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec (make_list_label_t (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,t_)) l_t_T_list))) (Ty_Rec (make_list_label_T (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,T_)) l_t_T_list)))
 | TyCh_Proj : forall (l_T_list:list_label_T) (j:index) (G5:G) (t5:t) (t103 t104:(label*T)),
          nth_list_label_T (j - 1) l_T_list = Some t103 ->
     nth_list_label_T (j - 1) l_T_list = Some t104 ->
Ty G5 t5 (Ty_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t104 with (l_,T_) => l_ end)) (match t103 with (l_,T_) => T_ end)
 | TyCh_Sub : forall (G5:G) (t5:t) (T5 S:T),
     Ty G5 t5 S ->
     SA G5 S T5 ->
     Ty G5 t5 T5
with Pat : p -> T -> G -> Prop :=    (* defn Pat *)
 | Pat_Var : forall (x:termvar) (T5:T),
     Pat (P_Var x T5) T5 (G_term G_empty x T5)
 | Pat_Rcd : forall (l_p_T_D_list:list_label_p_T_G),
     (forall p_ T_ D_, In (p_,T_,D_) (map (fun (pat_: (label*p*T*G)) => match pat_ with (l_,p_,T_,D_) => (p_,T_,D_) end) (unmake_list_label_p_T_G l_p_T_D_list)) -> (Pat p_ T_ D_)) ->
     Pat (P_Rec (make_list_label_p (map_list_label_p_T_G (fun (l_:label) (p_:p) (T_:T) (D_:G) => (l_,p_)) l_p_T_D_list))) (Ty_Rec (make_list_label_T (map_list_label_p_T_G (fun (l_:label) (p_:p) (T_:T) (D_:G) => (l_,T_)) l_p_T_D_list)))  (flatten_G  (make_list_G (map_list_label_p_T_G (fun (l_:label) (p_:p) (T_:T) (D_:G) => D_) l_p_T_D_list)) ) .
Inductive list_label_p_s : Set := Nil_list_label_p_s | Cons_list_label_p_s (_:label) (_:p) (_:s) (tl_ : list_label_p_s).

Fixpoint map_list_label_p_s (A:Type) (f:label->p->s->A) (l:list_label_p_s) : list A :=
  match l with
  | Nil_list_label_p_s => nil
  | Cons_list_label_p_s h0 h1 h2 tl_ => cons (f h0 h1 h2) (map_list_label_p_s A f tl_)
  end.
Arguments map_list_label_p_s [A] _ _.

Fixpoint make_list_label_p_s (l: list (label * p * s)): list_label_p_s :=
  match l with
  | nil  => Nil_list_label_p_s
  | cons (h0,h1,h2) tl_ => Cons_list_label_p_s h0 h1 h2 (make_list_label_p_s tl_)
  end.

Fixpoint unmake_list_label_p_s (l: list_label_p_s): list (label * p * s) :=
  match l with
  | Nil_list_label_p_s => nil
  | Cons_list_label_p_s h0 h1 h2 tl_ => cons (h0,h1,h2) (unmake_list_label_p_s tl_)
  end.

Fixpoint nth_list_label_p_s (n:nat) (l: list_label_p_s) {struct n} : option (label * p * s) :=
  match n,l with
  | O, Cons_list_label_p_s h0 h1 h2 tl_ => Some (h0,h1,h2)
  | O, _ => None
  | S m, Nil_list_label_p_s => None
  | S m, Cons_list_label_p_s h0 h1 h2 tl_ => nth_list_label_p_s m tl_
  end.

Fixpoint app_list_label_p_s (l m: list_label_p_s): list_label_p_s :=
  match l with
  | Nil_list_label_p_s => m
  | Cons_list_label_p_s h0 h1 h2 tl_ => Cons_list_label_p_s h0 h1 h2 (app_list_label_p_s tl_ m)
  end.

(* definitions *)

(* defns Jop *)
Inductive reduce : t -> t -> Prop :=    (* defn reduce *)
 | reduce_AppAbs : forall (x:termvar) (T11:T) (t12 v2:t),
     is_v_of_t v2 ->
     reduce (t_App  (t_Lam x T11 t12)  v2)  ( tsubst_t  v2   x   t12  ) 
 | reduce_TappTabs : forall (X:typevar) (T11:T) (t12:t) (T2:T),
     reduce (t_TApp  (t_TLam X T11 t12)  T2)  ( Tsubst_t  T2   X   t12  ) 
 | reduce_LetV : forall (p5:p) (t2:t) (s5:s) (v1:t),
     is_v_of_t v1 ->
     is_v_of_t v1 ->
     M p5 v1 s5 ->
     reduce (t_Let p5 v1 t2)  ( m_t_subst_t  s5   t2  ) 
 | reduce_ProjRcd : forall (l'_v_list:list_label_t) (j:index) (t105 t106:(label*t)),
          nth_list_label_t (j - 1) l'_v_list = Some t105 ->
     nth_list_label_t (j - 1) l'_v_list = Some t106 ->
(Forall (fun (tmp_:(label*t)) => match tmp_ with (l'_,v_) => is_v_of_t v_ end) (unmake_list_label_t l'_v_list)) ->
     reduce (t_Proj (t_Rec l'_v_list) (match t106 with (l'_,v_) => l'_ end)) (match t105 with (l'_,v_) => v_ end)
 | reduce_Ctx_app_fun : forall (t1 t_5 t1':t),
     reduce t1 t1' ->
     reduce (t_App t1 t_5) (t_App t1' t_5)
 | reduce_Ctx_app_arg : forall (v5 t1 t1':t),
     is_v_of_t v5 ->
     reduce t1 t1' ->
     reduce (t_App v5 t1) (t_App v5 t1')
 | reduce_Ctx_type_fun : forall (t1:t) (T5:T) (t1':t),
     reduce t1 t1' ->
     reduce (t_TApp t1 T5) (t_TApp t1' T5)
 | reduce_Ctx_record : forall (l'_t'_list l_v_list:list_label_t) (l:label) (t5 t':t),
     (Forall (fun (tmp_:(label*t)) => match tmp_ with (l_,v_) => is_v_of_t v_ end) (unmake_list_label_t l_v_list)) ->
     reduce t5 t' ->
     reduce (t_Rec ((app_list_label_t l_v_list (app_list_label_t (Cons_list_label_t l t5 Nil_list_label_t) (app_list_label_t l'_t'_list Nil_list_label_t))))) (t_Rec ((app_list_label_t l_v_list (app_list_label_t (Cons_list_label_t l t' Nil_list_label_t) (app_list_label_t l'_t'_list Nil_list_label_t)))))
 | reduce_Ctx_let_binding : forall (p5:p) (t1 t2 t1':t),
     reduce t1 t1' ->
     reduce (t_Let p5 t1 t2) (t_Let p5 t1' t2)
with M : p -> t -> s -> Prop :=    (* defn M *)
 | M_Var : forall (x:termvar) (T5:T) (v5:t),
     is_v_of_t v5 ->
     is_v_of_t v5 ->
     M (P_Var x T5) v5  (cons ( x , v5 ) nil) 
 | M_Rcd : forall (l_p_s_list:list_label_p_s) (k_v_list:list_label_t) (i m:index) (t107 t108 t109:(label*p*s)),
          nth_list_label_p_s (i - 1) l_p_s_list = Some t107 ->
     nth_list_label_p_s (i - 1) l_p_s_list = Some t108 ->
     nth_list_label_p_s (i - 1) l_p_s_list = Some t109 ->
(Forall (fun (tmp_:(label*t)) => match tmp_ with (k_,v_) => is_v_of_t v_ end) (unmake_list_label_t k_v_list)) ->
      (forall  i , (1<= i  /\  i  <= m) ->  Mf (match t109 with (l_,p_,s_) => l_ end) (match t108 with (l_,p_,s_) => p_ end) k_v_list (match t107 with (l_,p_,s_) => s_ end) )  ->
     M (P_Rec (make_list_label_p (map_list_label_p_s (fun (l_:label) (p_:p) (s_:s) => (l_,p_)) l_p_s_list))) (t_Rec k_v_list)  (List.flat_map (fun x => x)  (map_list_label_p_s (fun (l_:label) (p_:p) (s_:s) => s_) l_p_s_list) ) 
with Mf : label -> p -> (list_label_t) -> s -> Prop :=    (* defn Mf *)
 | Mf_found : forall (k_v_list:list_label_t) (l:label) (p5:p) (v_5:t) (s5:s),
     is_v_of_t v_5 ->
     (Forall (fun (tmp_:(label*t)) => match tmp_ with (k_,v_) => is_v_of_t v_ end) (unmake_list_label_t k_v_list)) ->
     M p5 v_5 s5 ->
     Mf l p5 ((app_list_label_t (Cons_list_label_t l v_5 Nil_list_label_t) (app_list_label_t k_v_list Nil_list_label_t))) s5
 | Mf_skip : forall (k_v_list:list_label_t) (l:label) (p5:p) (k:label) (v_5:t) (s5:s),
     is_v_of_t v_5 ->
     (Forall (fun (tmp_:(label*t)) => match tmp_ with (k_,v_) => is_v_of_t v_ end) (unmake_list_label_t k_v_list)) ->
     Mf l p5 k_v_list s5 ->
     Mf l p5 ((app_list_label_t (Cons_list_label_t k v_5 Nil_list_label_t) (app_list_label_t k_v_list Nil_list_label_t))) s5.


