(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/1Bsemantics/l1.ott *)
theory testRegr_l1
imports Main
begin

type_synonym "Location" = "UNDEFINED" \<comment> \<open>Store locations\<close>
datatype "operations" =  \<comment> \<open>operations\<close>
   op_plus  
 | op_gteq  

datatype "Tloc" =  \<comment> \<open>types of locations\<close>
   TLoc_intref  

datatype "expr" =  \<comment> \<open>expressions\<close>
   e_num "n"  
 | e_bool "b"  
 | e_op "expr" "operations" "expr"  
 | e_if "expr" "expr" "expr"  
 | e_assign "Location" "expr"  
 | e_ref "Location"  
 | e_skip  
 | e_sequence "expr" "expr"  
 | e_while "expr" "expr"  

datatype "store" =  \<comment> \<open>stores\<close>
   store_empty  
 | store_extend "store" "Location" "n"  

datatype "type_assumption" =  \<comment> \<open>type assumption\<close>
   TA_loc "Location" "Tloc"  

datatype "config" =  \<comment> \<open>configurations\<close>
   Config_config "expr" "store"  

datatype "typ" =  \<comment> \<open>types\<close>
   t_int  
 | t_bool  
 | t_unit  


(** subrules *)
primrec
is_v_of_expr :: "expr => bool"
where
"is_v_of_expr (e_num n) = ((True))"
| "is_v_of_expr (e_bool b) = ((True))"
| "is_v_of_expr (e_op e1 op e2) = (False)"
| "is_v_of_expr (e_if e1 e2 e3) = (False)"
| "is_v_of_expr (e_assign l e1) = (False)"
| "is_v_of_expr (e_ref l) = (False)"
| "is_v_of_expr e_skip = ((True))"
| "is_v_of_expr (e_sequence e1 e2) = (False)"
| "is_v_of_expr (e_while e1 e2) = (False)"

(** definitions *)
(* defns Jop *)
inductive Reduce :: "config \<Rightarrow> config \<Rightarrow> bool"
 and Typing :: "G \<Rightarrow> expr \<Rightarrow> typ \<Rightarrow> bool"
where
(* defn Reduce *)

op_plusI: "\<lbrakk>(formula_sum n1 n2 n)\<rbrakk> \<Longrightarrow>
Reduce ((Config_config (e_op (e_num n1) op_plus (e_num n2)) s)) ((Config_config (e_num n) s))"

| op_gteqI: "\<lbrakk>(formula_leq n1 n2 b)\<rbrakk> \<Longrightarrow>
Reduce ((Config_config (e_op (e_num n1) op_gteq (e_num n2)) s)) ((Config_config (e_bool b) s))"

| op1I: "\<lbrakk>Reduce ((Config_config e1 s)) ((Config_config e1' s'))\<rbrakk> \<Longrightarrow>
Reduce ((Config_config (e_op e1 op e2) s)) ((Config_config (e_op e1' op e2) s'))"

| op2I: "\<lbrakk>Reduce ((Config_config e2 s)) ((Config_config e2' s'))\<rbrakk> \<Longrightarrow>
Reduce ((Config_config (e_op e1 op e2) s)) ((Config_config (e_op e1 op e2') s'))"

| derefI: "\<lbrakk>(formula_lookup s l n)\<rbrakk> \<Longrightarrow>
Reduce ((Config_config (e_ref l) s)) ((Config_config (e_num n) s))"

| assign1I: "Reduce ((Config_config (e_assign l (e_num n)) s)) ((Config_config e_skip (store_extend s l n)))"

| assign2I: "\<lbrakk>Reduce ((Config_config e s)) ((Config_config e' s'))\<rbrakk> \<Longrightarrow>
Reduce ((Config_config (e_assign l e) s)) ((Config_config (e_assign l e') s'))"

| seq1I: "Reduce ((Config_config (e_sequence e_skip e) s)) ((Config_config e s))"

| seq2I: "\<lbrakk>Reduce ((Config_config e1 s)) ((Config_config e1' s'))\<rbrakk> \<Longrightarrow>
Reduce ((Config_config (e_sequence e1 e2) s)) ((Config_config (e_sequence e1' e2) s'))"

| if1I: "Reduce ((Config_config (e_if (e_bool B_true) e1 e2) s)) ((Config_config e1 s))"

| if2I: "Reduce ((Config_config (e_if (e_bool B_false) e1 e2) s)) ((Config_config e2 s))"

| if3I: "\<lbrakk>Reduce ((Config_config e s)) ((Config_config e' s'))\<rbrakk> \<Longrightarrow>
Reduce ((Config_config (e_if e e1 e2) s)) ((Config_config (e_if e' e1 e2) s'))"

| whileI: "Reduce ((Config_config (e_while e1 e2) s)) ((Config_config (e_if e1  ( (e_sequence e2 (e_while e1 e2)) )  e_skip) s))"

| (* defn Typing *)

ty_intI: "Typing (G) ((e_num n)) (t_int)"

| ty_boolI: "Typing (G) ((e_bool b)) (t_bool)"

| ty_op_plusI: "\<lbrakk>Typing (G) (e1) (t_int) ;
Typing (G) (e2) (t_int)\<rbrakk> \<Longrightarrow>
Typing (G) ((e_op e1 op_plus e2)) (t_int)"

| ty_op_gteqI: "\<lbrakk>Typing (G) (e1) (t_int) ;
Typing (G) (e2) (t_int)\<rbrakk> \<Longrightarrow>
Typing (G) ((e_op e1 op_gteq e2)) (t_bool)"

| ty_ifI: "\<lbrakk>Typing (G) (e1) (t_bool) ;
Typing (G) (e2) (T) ;
Typing (G) (e3) (T)\<rbrakk> \<Longrightarrow>
Typing (G) ((e_if e1 e1 e3)) (T)"

| ty_assignI: "\<lbrakk>(formula_type_lookup G l TLoc_intref) ;
Typing (G) (e) (t_int)\<rbrakk> \<Longrightarrow>
Typing (G) ((e_assign l e)) (t_unit)"

| ty_derefI: "\<lbrakk>(formula_type_lookup G l TLoc_intref)\<rbrakk> \<Longrightarrow>
Typing (G) ((e_ref l)) (t_int)"

| ty_skipI: "Typing (G) (e_skip) (t_unit)"

| ty_seqI: "\<lbrakk>Typing (G) (e1) (t_unit) ;
Typing (G) (e2) (T)\<rbrakk> \<Longrightarrow>
Typing (G) ((e_sequence e1 e2)) (T)"

| ty_whileI: "\<lbrakk>Typing (G) (e1) (t_bool) ;
Typing (G) (e2) (t_unit)\<rbrakk> \<Longrightarrow>
Typing (G) ((e_while e1 e2)) (t_unit)"

end



