(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test11.ott *)

type termvar = int

type 
t = 
   T_Var of termvar
 | T_Lam of termvar * t
 | T_App of t * t
 | T_Foo of t


(** subrules *)
let rec is_t_of_t (t5:t) : bool =
  match t5 with
  | (T_Var x) -> (true)
  | (T_Lam (x,t)) -> ((is_t_of_t t))
  | (T_App (t,t')) -> ((is_t_of_t t) && (is_t_of_t t'))
  | (T_Foo v) -> ((is_v_of_t v))
and
is_v_of_t (t5:t) : bool =
  match t5 with
  | (T_Var x) -> false
  | (T_Lam (x,t)) -> ((is_t_of_t t))
  | (T_App (t,t')) -> false
  | (T_Foo v) -> false


(** definitions *)


