/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test16.6.ott -/




abbrev value_name := Nat
abbrev index := Nat

mutual
inductive a : Type where
  | a_x (x : value_name) : a
  | a_A (_ : list_a) : a
  deriving Inhabited
inductive list_a : Type where
  | Nil_list_a : list_a
  | Cons_list_a (_ : a) (_ : list_a) : list_a
  deriving Inhabited
end
open list_a a
def map_list_a {A : Type} (f : a -> A) (l : list_a) : List A :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => (f h) :: (map_list_a f tl_)

def make_list_a (l : List a) : list_a :=
  match l with
  | [] => Nil_list_a
  | h :: tl_ => Cons_list_a h (make_list_a tl_)

def unmake_list_a (l : list_a) : List a :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => h :: (unmake_list_a tl_)

def nth_list_a (n : Nat) (l : list_a) : Option a :=
  match n, l with
  | 0, Cons_list_a h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_a => none
  | k+1, Cons_list_a _ tl_ => nth_list_a k tl_

def app_list_a (l m : list_a) : list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)



/- - substitutions - -/
mutual
def subst_a_list (a_5:a) (x5:value_name) (a__6:list_a) : list_a :=
  match a__6 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (subst_a a_5 x5 a) (subst_a_list a_5 x5 a_tl)
def subst_a (a_5:a) (x5:value_name) (a__6:a) : a :=
  match a__6 with
  | (a_x x) => (if x=x5 then a_5 else (a_x x))
  | (a_A a_list) => a_A (subst_a_list a_5 x5 a_list)
end



