/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test4.ott -/




abbrev ident := Nat
abbrev index := Nat

inductive type : Type where
  | Typ_unit : type
  | Typ_tuple (_ : List type) : type
  deriving Inhabited

inductive expr : Type where
  /-- ident -/
  | Expr_var (x : ident) : expr
  /-- unit -/
  | Expr_unit : expr
  | Expr_tuple (_ : List (expr × type)) : expr
  | Expr_proj (e : expr) (j : index) : expr
  | Expr_foo (e1 : expr) (e2 : expr) : expr
  deriving Inhabited

inductive foo1expr : Type where
  | Foo1Expr_tuple (x : ident) (_ : List (expr × type)) : foo1expr
  deriving Inhabited

inductive foo2expr : Type where
  | Foo2Expr_tuple (x : ident) (_ : List (expr × expr × type)) : foo2expr
  deriving Inhabited

inductive foo3expr : Type where
  | Foo3Expr_tuple (x : ident) (_ : List (expr × type)) : foo3expr
  deriving Inhabited
open expr type foo1expr foo2expr foo3expr
def aux_b_foo1expr_of_foo1expr (foo1expr5:foo1expr) : List type :=
  match foo1expr5 with
  | (Foo1Expr_tuple x (e_t_list)) => (List.map (fun (e_,t_) => t_) e_t_list)


/- - library functions - -/
def list_assoc {α β : Type} [DecidableEq α] (l:List (α × β)) (x:α) : Option β :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def m_subst_expr_type_list (sub:List (ident×expr)) (e__t__list:List (expr × type)) : List (expr × type) :=
  match e__t__list with
  | [] => []
  | (e__,t__) :: e__t__list_ => ((m_subst_expr sub e__),t__) :: (m_subst_expr_type_list sub e__t__list_)
def m_subst_expr (sub:List (ident×expr)) (e__6:expr) : expr :=
  match e__6 with
  | (Expr_var x) => (match list_assoc sub x with | none => (Expr_var x)| some e_5 => e_5 )
  | Expr_unit => Expr_unit 
  | (Expr_tuple (e_t_list)) => Expr_tuple (m_subst_expr_type_list sub e_t_list)
  | (Expr_proj e j) => Expr_proj (m_subst_expr sub e) j
  | (Expr_foo e1 e2) => Expr_foo (m_subst_expr sub e1) (m_subst_expr sub e2)
end

mutual
def subst_expr_type_list (e__5:expr) (x5:ident) (e__t__list:List (expr × type)) : List (expr × type) :=
  match e__t__list with
  | [] => []
  | (e__,t__) :: e__t__list_ => ((subst_expr e__5 x5 e__),t__) :: (subst_expr_type_list e__5 x5 e__t__list_)
def subst_expr (e_5:expr) (x5:ident) (e__6:expr) : expr :=
  match e__6 with
  | (Expr_var x) => (if x=x5 then e_5 else (Expr_var x))
  | Expr_unit => Expr_unit 
  | (Expr_tuple (e_t_list)) => Expr_tuple (subst_expr_type_list e_5 x5 e_t_list)
  | (Expr_proj e j) => Expr_proj (subst_expr e_5 x5 e) j
  | (Expr_foo e1 e2) => Expr_foo (subst_expr e_5 x5 e1) (subst_expr e_5 x5 e2)
end

def m_subst_expr_expr_type_list (sub:List (ident×expr)) (e_e'_t_list:List (expr × expr × type)) : List (expr × expr × type) :=
  match e_e'_t_list with
  | [] => []
  | (e_,e'_,t_) :: e_e'_t_list_ => ((m_subst_expr sub e_),(m_subst_expr sub e'_),t_) :: (m_subst_expr_expr_type_list sub e_e'_t_list_)


def subst_expr_expr_type_list (e_5:expr) (x5:ident) (e_e'_t_list:List (expr × expr × type)) : List (expr × expr × type) :=
  match e_e'_t_list with
  | [] => []
  | (e_,e'_,t_) :: e_e'_t_list_ => ((subst_expr e_5 x5 e_),(subst_expr e_5 x5 e'_),t_) :: (subst_expr_expr_type_list e_5 x5 e_e'_t_list_)


def m_subst_foo3expr (sub:List (ident×expr)) (foo3expr5:foo3expr) : foo3expr :=
  match foo3expr5 with
  | (Foo3Expr_tuple x (e__t__list)) => Foo3Expr_tuple x (m_subst_expr_type_list sub e__t__list)


def m_subst_foo2expr (sub:List (ident×expr)) (foo2expr5:foo2expr) : foo2expr :=
  match foo2expr5 with
  | (Foo2Expr_tuple x (e_e'_t_list)) => Foo2Expr_tuple x (m_subst_expr_expr_type_list sub e_e'_t_list)


def m_subst_foo1expr (sub:List (ident×expr)) (foo1expr5:foo1expr) : foo1expr :=
  match foo1expr5 with
  | (Foo1Expr_tuple x (e_t_list)) => Foo1Expr_tuple x (m_subst_expr_type_list sub e_t_list)


def subst_foo3expr (e__5:expr) (x5:ident) (foo3expr5:foo3expr) : foo3expr :=
  match foo3expr5 with
  | (Foo3Expr_tuple x (e__t__list)) => Foo3Expr_tuple x (subst_expr_type_list e__5 x5 e__t__list)


def subst_foo2expr (e_5:expr) (x5:ident) (foo2expr5:foo2expr) : foo2expr :=
  match foo2expr5 with
  | (Foo2Expr_tuple x (e_e'_t_list)) => Foo2Expr_tuple x (subst_expr_expr_type_list e_5 x5 e_e'_t_list)


def subst_foo1expr (e_5:expr) (x5:ident) (foo1expr5:foo1expr) : foo1expr :=
  match foo1expr5 with
  | (Foo1Expr_tuple x (e_t_list)) => Foo1Expr_tuple x (subst_expr_type_list e_5 x5 e_t_list)


/- definitions -/


/- defns Jin -/
mutual
/-- defn eok -/
inductive eok : expr → Prop where
  | eok_unit :       eok Expr_unit

  | eok_tuple : ∀ (e_t_list : List (expr × type)),
      eok (Expr_tuple (e_t_list))


/-- defn ered -/
inductive ered : expr → expr → Prop where
  | ered_proj : ∀ (e_t_list : List (expr × type)) (j : index),
      ered (Expr_proj (Expr_tuple (e_t_list)) j) ((fun (e_,t_) => e_) (e_t_list[j - 1]!))


end


