/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test18.1.ott -/




/-- term variable -/
abbrev termvar := Nat
abbrev index := Nat

inductive a : Type where
  | a_AA : a
  | a_C (_ : List a) : a
  | a_D (x : termvar) (_ : List a) : a
  deriving Inhabited
open a
/- definitions -/


/- defns Jtype -/
/-- defn Foo -/
inductive Foo : a → Prop where
  | Foo_1C : ∀ (a_list : List a),
      Foo (a_C (a_list))

  | Foo_1D : ∀ (a_list : List a) (x : termvar),
      Foo (a_D x (a_list))

  | Foo_2 : ∀ (a_list : List a) (x_list : List termvar),
      Foo (a_C ((List.map (fun x_ => (a_D x_ (a_list))) x_list)))



