(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test-mjp.ott *)
theory testRegr_test_mjp
imports Main
begin

type_synonym "h" = "UNDEFINED"
datatype "s" = 
   state "h" "h" "h"  

datatype "A" =  \<comment> \<open>abstract command\<close>
   

end



