(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.


Definition index : Set := nat.
Lemma eq_index: forall (x y : index), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_index : ott_coq_equality.
Definition x : Set := nat.
Lemma eq_x: forall (x' y : x), {x' = y} + {x' <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_x : ott_coq_equality.

Inductive a : Set := 
 | a_Ax (x5:x)
 | a_AA : a
 | a_a (a5:a)
 | a_C (_:list_a)
 | a_D (_:list_a)
 | a_CC (_:list_a)
 | a_DD (_:list_a)
with list_a : Set := 
 | Nil_list_a : list_a
 | Cons_list_a (av:a) (_:list_a).
Fixpoint map_list_a (A:Type) (f:a->A) (l:list_a) : list A :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a h tl_ => cons (f h) (map_list_a A f tl_)
  end.
Arguments map_list_a [A] _ _.

Fixpoint make_list_a (l: list a): list_a :=
  match l with
  | nil  => Nil_list_a
  | cons h tl_ => Cons_list_a h (make_list_a tl_)
  end.

Fixpoint unmake_list_a (l: list_a): list a :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a h tl_ => cons h (unmake_list_a tl_)
  end.

Fixpoint nth_list_a (n:nat) (l: list_a) {struct n} : option a :=
  match n,l with
  | O, Cons_list_a h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_a => None
  | S m, Cons_list_a h tl_ => nth_list_a m tl_
  end.

Fixpoint app_list_a (l m: list_a): list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)
  end.



(** subrules *)
Fixpoint is_a_of_a_list (l:list_a) : Prop :=
  match l with
  | Nil_list_a => True
  | Cons_list_a av_ av_list_ => (is_av_of_a av_) /\ (is_a_of_a_list av_list_)
end
with is_a_of_a (a_6:a) : Prop :=
  match a_6 with
  | (a_Ax x5) => (True)
  | a_AA => (True)
  | (a_a a5) => ((is_a_of_a a5))
  | (a_C a_list) => (is_a_of_a_list a_list)
  | (a_D av_list) => (is_a_of_a_list av_list)
  | (a_CC a_list) => (is_a_of_a_list a_list)
  | (a_DD av_list) => (is_a_of_a_list av_list)
end
with is_av_of_a_list (l:list_a) : Prop :=
  match l with
  | Nil_list_a => True
  | Cons_list_a av_ av_list_ => (is_av_of_a av_) /\ (is_av_of_a_list av_list_)
end
with is_av_of_a (a_6:a) : Prop :=
  match a_6 with
  | (a_Ax x5) => False
  | a_AA => False
  | (a_a a5) => ((is_a_of_a a5))
  | (a_C a_list) => (is_av_of_a_list a_list)
  | (a_D av_list) => (is_av_of_a_list av_list)
  | (a_CC a_list) => False
  | (a_DD av_list) => False
end.


(** free variables *)
Fixpoint fv_a_list (l:list_a) : list x :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a a_ a_list_ => app ((fv_a a_)) (fv_a_list a_list_)
end
with fv_a (a_6:a) : list x :=
  match a_6 with
  | (a_Ax x5) => (cons x5 nil)
  | a_AA => nil
  | (a_a a5) => ((fv_a a5))
  | (a_C a_list) => ((fv_a_list a_list))
  | (a_D av_list) => (nil)
  | (a_CC a_list) => ((fv_a_list a_list))
  | (a_DD av_list) => (nil)
end.



