/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_3.ott -/




abbrev i := Nat

mutual
inductive data : Type where
  | data_tuple (_ : list_data) : data

inductive list_data : Type where
  | Nil_list_data : list_data
  | Cons_list_data (_ : data) (_ : list_data) : list_data

end

mutual
inductive map : Type where
  | map_finite (_ : list_data_map) : map

inductive list_data_map : Type where
  | Nil_list_data_map : list_data_map
  | Cons_list_data_map (_ : data) (_ : map) (_ : list_data_map) : list_data_map

end
open list_data_map list_data data map
def map_list_data_map {A : Type} (f : data -> map -> A) (l : list_data_map) : List A :=
  match l with
  | Nil_list_data_map => []
  | Cons_list_data_map h0 h1 tl_ => (f h0 h1) :: (map_list_data_map f tl_)

def make_list_data_map (l : List (data × map)) : list_data_map :=
  match l with
  | [] => Nil_list_data_map
  | (h0,h1) :: tl_ => Cons_list_data_map h0 h1 (make_list_data_map tl_)

def unmake_list_data_map (l : list_data_map) : List (data × map) :=
  match l with
  | Nil_list_data_map => []
  | Cons_list_data_map h0 h1 tl_ => (h0,h1) :: (unmake_list_data_map tl_)

def nth_list_data_map (n : Nat) (l : list_data_map) : Option (data × map) :=
  match n, l with
  | 0, Cons_list_data_map h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_data_map => none
  | k+1, Cons_list_data_map _ _ tl_ => nth_list_data_map k tl_

def app_list_data_map (l m : list_data_map) : list_data_map :=
  match l with
  | Nil_list_data_map => m
  | Cons_list_data_map h0 h1 tl_ => Cons_list_data_map h0 h1 (app_list_data_map tl_ m)

def map_list_data {A : Type} (f : data -> A) (l : list_data) : List A :=
  match l with
  | Nil_list_data => []
  | Cons_list_data h tl_ => (f h) :: (map_list_data f tl_)

def make_list_data (l : List data) : list_data :=
  match l with
  | [] => Nil_list_data
  | h :: tl_ => Cons_list_data h (make_list_data tl_)

def unmake_list_data (l : list_data) : List data :=
  match l with
  | Nil_list_data => []
  | Cons_list_data h tl_ => h :: (unmake_list_data tl_)

def nth_list_data (n : Nat) (l : list_data) : Option data :=
  match n, l with
  | 0, Cons_list_data h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_data => none
  | k+1, Cons_list_data _ tl_ => nth_list_data k tl_

def app_list_data (l m : list_data) : list_data :=
  match l with
  | Nil_list_data => m
  | Cons_list_data h tl_ => Cons_list_data h (app_list_data tl_ m)


/- definitions -/


/- defns Data -/
/-- defn data -/
inductive Data_data : data → Prop where
  | Data_data_tuple : ∀ (data_list : list_data),
      (∀ data_list_ ∈ (unmake_list_data data_list), (fun data_ => (Data_data data_)) data_list_) →
      Data_data (data_tuple data_list)

/- definitions -/


/- defns Map -/
/-- defn map -/
inductive Map_map : map → Prop where
  | Map_map_finite : ∀ (data_map_list : list_data_map),
      (∀ data_map_list_ ∈ (unmake_list_data_map data_map_list), (fun (data_,map_) => (Data_data data_)) data_map_list_) →
      (∀ data_map_list_ ∈ (unmake_list_data_map data_map_list), (fun (data_,map_) => (Map_map map_)) data_map_list_) →
      Map_map (map_finite data_map_list)



