/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test10_isasyn.ott -/




/-- term variable -/
abbrev termvar := Nat

/-- term -/
inductive t : Type where
  /-- variable -/
  | t_Var (x : termvar) : t
  /-- abstraction -/
  | t_Lam (x : termvar) (t5 : t) : t
  /-- application -/
  | t_App (t5 : t) (t' : t) : t
  deriving Inhabited
open t

/- - subrules - -/
def is_v_of_t (t_6:t) : Bool :=
  match t_6 with
  | (t_Var x) => false
  | (t_Lam x t5) => (true)
  | (t_App t5 t') => false



/- - substitutions - -/
def tsubst_t (t_6:t) (x5:termvar) (t__7:t) : t :=
  match t__7 with
  | (t_Var x) => (if x=x5 then t_6 else (t_Var x))
  | (t_Lam x t5) => t_Lam x (if  List.elem x5 ([x]) then t5 else (tsubst_t t_6 x5 t5))
  | (t_App t5 t') => t_App (tsubst_t t_6 x5 t5) (tsubst_t t_6 x5 t')


/- definitions -/


/- defns Jop -/
/-- defn reduce -/
inductive reduce : t → t → Prop where
  | ax_app : ∀ (x : termvar) (t12 : t) (v2 : t),
      (is_v_of_t v2) →
      reduce (t_App (t_Lam x t12) v2) (tsubst_t v2 x t12)

  | ctx_app_fun : ∀ (t1 : t) (t_5 : t) (t1' : t),
      (reduce t1 t1') →
      reduce (t_App t1 t_5) (t_App t1' t_5)

  | ctx_app_arg : ∀ (v5 : t) (t1 : t) (t1' : t),
      (is_v_of_t v5) →
      (reduce t1 t1') →
      reduce (t_App v5 t1) (t_App v5 t1')



