(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.6.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
Require Import Ott.ott_list_core.


Definition value_name : Set := nat.
Lemma eq_value_name: forall (x y : value_name), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_value_name : ott_coq_equality.
Definition index : Set := nat.

Inductive c : Set := 
 | c_C (x:value_name).

Inductive a : Set := 
 | a_x (x:value_name)
 | a_E (_:list (c*c*c)).
Definition aux_b_c_of_c (c5:c) : list value_name :=
  match c5 with
  | (c_C x) => (cons x nil)
end.

Definition aux_b_a_of_a (a5:a) : list value_name :=
  match a5 with
  | (a_x x) => (cons x nil)
  | (a_E c_c'_c''_list) => (flat_map (fun (pat_:(c*c*c)) => match pat_ with (c_,c'_,c''_) => aux_b_c_of_c c_ end ) c_c'_c''_list)
end.



