(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_freevars_1.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
Require Import Ott.ott_list_core.


Definition i : Set := nat.
Definition x : Set := nat.

Inductive p : Set := 
 | p_x (x5:x).

Inductive t : Set := 
 | t_x (x5:x)
 | t_tuple (_:list t)
 | t_cond (_:list (p*t)).
(** induction principles *)
Section t_rect.

Variables
  (P_t : t -> Prop)
  (P_list_t : list t -> Prop)
  (P_list_p_t : list (p*t) -> Prop).

Hypothesis
  (H_t_x : forall (x5:x), P_t (t_x x5))
  (H_t_tuple : forall (t_list:list t), P_list_t t_list -> P_t (t_tuple t_list))
  (H_t_cond : forall (p_t_list:list (p*t)), P_list_p_t p_t_list -> P_t (t_cond p_t_list))
  (H_list_t_nil : P_list_t nil)
  (H_list_t_cons : forall (t0:t), P_t t0 -> forall (t_l:list t), P_list_t t_l -> P_list_t (cons t0 t_l))
  (H_list_p_t_nil : P_list_p_t nil)
  (H_list_p_t_cons : forall (p0:p), forall (t1:t), P_t t1 -> forall (p_t_l:list (p*t)), P_list_p_t p_t_l -> P_list_p_t (cons (p0,t1) p_t_l)).

Fixpoint t_ott_ind (n:t) : P_t n :=
  match n as x return P_t x with
  | (t_x x5) => H_t_x x5
  | (t_tuple t_list) => H_t_tuple t_list (((fix t_list_ott_ind (t_l:list t) : P_list_t t_l := match t_l as x return P_list_t x with nil => H_list_t_nil | cons t2 xl => H_list_t_cons t2(t_ott_ind t2)xl (t_list_ott_ind xl) end)) t_list)
  | (t_cond p_t_list) => H_t_cond p_t_list (((fix p_t_list_ott_ind (p_t_l:list (p*t)) : P_list_p_t p_t_l := match p_t_l as x return P_list_p_t x with nil => H_list_p_t_nil | cons (p1,t3) xl => H_list_p_t_cons p1  t3(t_ott_ind t3)xl (p_t_list_ott_ind xl) end)) p_t_list)
end.

End t_rect.

(** free variables *)
Fixpoint fv_t (t_5:t) : list x :=
  match t_5 with
  | (t_x x5) => (cons x5 nil)
  | (t_tuple t_list) => ((flat_map (fun (t_:t) => (fv_t t_)) t_list))
  | (t_cond p_t_list) => ((flat_map (fun (pat_:(p*t)) => match pat_ with (p_,t_) => (fv_t t_) end) p_t_list))
end.



