(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test16.5.ott *)

type value_name = UNDEFINED
type index = UNDEFINED

type 
a = 
   A_x of value_name
 | A_A of (a) list
 | A_C

let rec aux_f_a_of_a (aa5:a) : value_name list =
  match aa5 with
  | (A_x x) -> [x]
  | (A_A (aaa_list)) -> (List.flatten (List.map aux_f_a_of_a (aaa_list)))
  | A_C -> []



(** substitutions *)
let rec msubst_a (sub: (value_name*a) list) (aa_6:a) : a =
  match aa_6 with
  | (A_x x) -> (try List.assoc x sub with Not_found -> (A_x x))
  | (A_A (aaa_list)) -> A_A (List.map (fun aaa_ -> (msubst_a sub aaa_)) aaa_list)
  | A_C -> A_C 


let rec subst_a (aa5:a) (x5:value_name) (aa_6:a) : a =
  match aa_6 with
  | (A_x x) -> (if x=x5 then aa5 else (A_x x))
  | (A_A (aaa_list)) -> A_A (List.map (fun aaa_ -> (subst_a aa5 x5 aaa_)) aaa_list)
  | A_C -> A_C 




