/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_1.ott -/




abbrev i := Nat
abbrev ident := Nat

inductive typevar : Type where
  | TV_ident (ident5 : ident) : typevar
  deriving Inhabited

inductive list_typevar : Type where
  | Nil_list_typevar : list_typevar
  | Cons_list_typevar (_ : typevar) (_ : list_typevar) : list_typevar
  deriving Inhabited

inductive typexpr : Type where
  | TE_var (typevar5 : typevar) : typexpr
  deriving Inhabited

inductive typevars : Type where
  | TVS_list (_ : list_typevar) : typevars
  deriving Inhabited

inductive value_name : Type where
  | VN_id (ident5 : ident) : value_name
  deriving Inhabited

inductive typescheme : Type where
  | TS_forall (typevars5 : typevars) (t : typexpr) : typescheme
  deriving Inhabited

inductive environment_binding : Type where
  | EB_vn (value_name5 : value_name) (typescheme5 : typescheme) : environment_binding
  deriving Inhabited

inductive environment : Type where
  | Env_nil : environment
  | Env_snoc (E : environment) (EB : environment_binding) : environment
  deriving Inhabited

inductive list_environment : Type where
  | Nil_list_environment : list_environment
  | Cons_list_environment (E : environment) (_ : list_environment) : list_environment
  deriving Inhabited
open list_environment list_typevar value_name typexpr typevar typevars typescheme environment_binding environment
def map_list_environment {A : Type} (f : environment -> A) (l : list_environment) : List A :=
  match l with
  | Nil_list_environment => []
  | Cons_list_environment h tl_ => (f h) :: (map_list_environment f tl_)

def make_list_environment (l : List environment) : list_environment :=
  match l with
  | [] => Nil_list_environment
  | h :: tl_ => Cons_list_environment h (make_list_environment tl_)

def unmake_list_environment (l : list_environment) : List environment :=
  match l with
  | Nil_list_environment => []
  | Cons_list_environment h tl_ => h :: (unmake_list_environment tl_)

def nth_list_environment (n : Nat) (l : list_environment) : Option environment :=
  match n, l with
  | 0, Cons_list_environment h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_environment => none
  | k+1, Cons_list_environment _ tl_ => nth_list_environment k tl_

def app_list_environment (l m : list_environment) : list_environment :=
  match l with
  | Nil_list_environment => m
  | Cons_list_environment h tl_ => Cons_list_environment h (app_list_environment tl_ m)

def map_list_typevar {A : Type} (f : typevar -> A) (l : list_typevar) : List A :=
  match l with
  | Nil_list_typevar => []
  | Cons_list_typevar h tl_ => (f h) :: (map_list_typevar f tl_)

def make_list_typevar (l : List typevar) : list_typevar :=
  match l with
  | [] => Nil_list_typevar
  | h :: tl_ => Cons_list_typevar h (make_list_typevar tl_)

def unmake_list_typevar (l : list_typevar) : List typevar :=
  match l with
  | Nil_list_typevar => []
  | Cons_list_typevar h tl_ => h :: (unmake_list_typevar tl_)

def nth_list_typevar (n : Nat) (l : list_typevar) : Option typevar :=
  match n, l with
  | 0, Cons_list_typevar h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_typevar => none
  | k+1, Cons_list_typevar _ tl_ => nth_list_typevar k tl_

def app_list_typevar (l m : list_typevar) : list_typevar :=
  match l with
  | Nil_list_typevar => m
  | Cons_list_typevar h tl_ => Cons_list_typevar h (app_list_typevar tl_ m)


/- definitions -/


/- defns Jtype -/
/-- defn value_name -/
inductive JT_value_name : environment → value_name → typexpr → Prop where
  | JT_value_name_value_name : ∀ (E1 : environment) (x : value_name) (ts : typescheme) (E2 : environment) (t : typexpr),
      JT_value_name (@List.flat_map _ _ (fun l=>l) ((app_list_environment (Cons_list_environment (Env_snoc E1 (EB_vn x ts)) Nil_list_environment) (app_list_environment (Cons_list_environment E2 Nil_list_environment) Nil_list_environment)))) x t



