/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/tmp_test7.ott -/




set_option linter.unusedVariables false

/-- type variable -/
abbrev typevar := String
/-- term variable -/
abbrev termvar := String
/-- field label -/
abbrev label := String
/-- indices -/
abbrev index := Nat

/-- type -/
inductive Typ : Type where
  /-- type variable -/
  | Ty_Var (X : typevar) : Typ
  /-- maximum type -/
  | Ty_Top : Typ
  /-- type of functions -/
  | Ty_Fun (T5 : Typ) (T' : Typ) : Typ
  /-- universal type -/
  | Ty_Forall (X : typevar) (T5 : Typ) (T' : Typ) : Typ
  /-- record -/
  | Ty_Rec (_ : List (label × Typ)) : Typ
  deriving Inhabited

/-- pattern -/
inductive p : Type where
  /-- variable pattern -/
  | P_Var (x : termvar) (T5 : Typ) : p
  /-- record pattern -/
  | P_Rec (_ : List (label × p)) : p
  deriving Inhabited

/-- term -/
inductive t : Type where
  /-- variable -/
  | t_Var (x : termvar) : t
  /-- abstraction -/
  | t_Lam (x : termvar) (T5 : Typ) (t5 : t) : t
  /-- application -/
  | t_App (t5 : t) (t' : t) : t
  /-- type abstraction -/
  | t_TLam (X : typevar) (T5 : Typ) (t5 : t) : t
  /-- type application -/
  | t_TApp (t5 : t) (T5 : Typ) : t
  /-- record -/
  | t_Rec (_ : List (label × t)) : t
  /-- projection -/
  | t_Proj (t5 : t) (l : label) : t
  /-- pattern binding -/
  | t_Let (p5 : p) (t5 : t) (t' : t) : t
  deriving Inhabited

abbrev s := List (termvar×t)


/-- type environment -/
inductive TypEnv : Type where
  | G_empty : TypEnv
  | G_type (G5 : TypEnv) (X : typevar) (T5 : Typ) : TypEnv
  | G_term (G5 : TypEnv) (x : termvar) (T5 : Typ) : TypEnv
  deriving Inhabited
open Typ t p TypEnv
mutual
def aux_b_p_of_p_list (l_p_list:List (label × p)) : List termvar :=
  match l_p_list with
  | [] => []
  | (l_,p_) :: l_p_list_ => (aux_b_p_of_p p_) ++ (aux_b_p_of_p_list l_p_list_)
def aux_b_p_of_p (p_5:p) : List termvar :=
  match p_5 with
  | (P_Var x T5) => [x]
  | (P_Rec (l_p_list)) => (aux_b_p_of_p_list l_p_list)
end


/- - subrules - -/
mutual
def is_v_of_t (t_6:t) : Bool :=
  match t_6 with
  | (t_Var x) => false
  | (t_Lam x T5 t5) => (true)
  | (t_App t5 t') => false
  | (t_TLam X T5 t5) => (true)
  | (t_TApp t5 T5) => false
  | (t_Rec (l_t_list)) => (is_v_of_l_t_list l_t_list)
  | (t_Proj t5 l) => false
  | (t_Let p5 t5 t') => false
def is_v_of_l_t_list (l_t_list:List (label × t)) : Bool :=
  match l_t_list with
  | [] => true
  | (l_,t_) :: l_t_list_ => ((is_v_of_t t_)) && (is_v_of_l_t_list l_t_list_)
end

/- - library functions - -/
def list_assoc {α β : Type} [DecidableEq α] (l:List (α × β)) (x:α) : Option β :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def m_T_subst_label_T_list (sub:List (typevar×Typ)) (l_T_list:List (label × Typ)) : List (label × Typ) :=
  match l_T_list with
  | [] => []
  | (l_,T_) :: l_T_list_ => (l_,(m_T_subst_T sub T_)) :: (m_T_subst_label_T_list sub l_T_list_)
def m_T_subst_T (sub:List (typevar×Typ)) (S_6:Typ) : Typ :=
  match S_6 with
  | (Ty_Var X) => (match list_assoc sub X with | none => (Ty_Var X)| some S5 => S5 )
  | Ty_Top => Ty_Top 
  | (Ty_Fun T5 T') => Ty_Fun (m_T_subst_T sub T5) (m_T_subst_T sub T')
  | (Ty_Forall X T5 T') => Ty_Forall X (m_T_subst_T sub T5) (m_T_subst_T (List.filter (fun (X5,S5) => not ( List.elem X5 ([X]))) sub) T')
  | (Ty_Rec (l_T_list)) => Ty_Rec (m_T_subst_label_T_list sub l_T_list)
end

mutual
def Tsubst_label_T_list (S5:Typ) (X5:typevar) (l_T_list:List (label × Typ)) : List (label × Typ) :=
  match l_T_list with
  | [] => []
  | (l_,T_) :: l_T_list_ => (l_,(Tsubst_T S5 X5 T_)) :: (Tsubst_label_T_list S5 X5 l_T_list_)
def Tsubst_T (S5:Typ) (X5:typevar) (S_6:Typ) : Typ :=
  match S_6 with
  | (Ty_Var X) => (if X=X5 then S5 else (Ty_Var X))
  | Ty_Top => Ty_Top 
  | (Ty_Fun T5 T') => Ty_Fun (Tsubst_T S5 X5 T5) (Tsubst_T S5 X5 T')
  | (Ty_Forall X T5 T') => Ty_Forall X (Tsubst_T S5 X5 T5) (if  List.elem X5 ([X]) then T' else (Tsubst_T S5 X5 T'))
  | (Ty_Rec (l_T_list)) => Ty_Rec (Tsubst_label_T_list S5 X5 l_T_list)
end

mutual
def m_T_subst_label_p_list (sub:List (typevar×Typ)) (l_p_list:List (label × p)) : List (label × p) :=
  match l_p_list with
  | [] => []
  | (l_,p_) :: l_p_list_ => (l_,(m_T_subst_p sub p_)) :: (m_T_subst_label_p_list sub l_p_list_)
def m_T_subst_p (sub:List (typevar×Typ)) (p_5:p) : p :=
  match p_5 with
  | (P_Var x T5) => P_Var x (m_T_subst_T sub T5)
  | (P_Rec (l_p_list)) => P_Rec (m_T_subst_label_p_list sub l_p_list)
end

mutual
def Tsubst_label_p_list (S5:Typ) (X5:typevar) (l_p_list:List (label × p)) : List (label × p) :=
  match l_p_list with
  | [] => []
  | (l_,p_) :: l_p_list_ => (l_,(Tsubst_p S5 X5 p_)) :: (Tsubst_label_p_list S5 X5 l_p_list_)
def Tsubst_p (S5:Typ) (X5:typevar) (p_5:p) : p :=
  match p_5 with
  | (P_Var x T5) => P_Var x (Tsubst_T S5 X5 T5)
  | (P_Rec (l_p_list)) => P_Rec (Tsubst_label_p_list S5 X5 l_p_list)
end

def m_T_subst_G (sub:List (typevar×Typ)) (D5:TypEnv) : TypEnv :=
  match D5 with
  | G_empty => G_empty 
  | (G_type G5 X T5) => G_type (m_T_subst_G sub G5) X (m_T_subst_T sub T5)
  | (G_term G5 x T5) => G_term (m_T_subst_G sub G5) x (m_T_subst_T sub T5)


mutual
def m_T_subst_label_t_list (sub:List (typevar×Typ)) (l_t_list:List (label × t)) : List (label × t) :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (l_,(m_T_subst_t sub t_)) :: (m_T_subst_label_t_list sub l_t_list_)
def m_T_subst_t (sub:List (typevar×Typ)) (t_6:t) : t :=
  match t_6 with
  | (t_Var x) => t_Var x
  | (t_Lam x T5 t5) => t_Lam x (m_T_subst_T sub T5) (m_T_subst_t sub t5)
  | (t_App t5 t') => t_App (m_T_subst_t sub t5) (m_T_subst_t sub t')
  | (t_TLam X T5 t5) => t_TLam X (m_T_subst_T sub T5) (m_T_subst_t (List.filter (fun (X5,S5) => not ( List.elem X5 ([X]))) sub) t5)
  | (t_TApp t5 T5) => t_TApp (m_T_subst_t sub t5) (m_T_subst_T sub T5)
  | (t_Rec (l_t_list)) => t_Rec (m_T_subst_label_t_list sub l_t_list)
  | (t_Proj t5 l) => t_Proj (m_T_subst_t sub t5) l
  | (t_Let p5 t5 t') => t_Let (m_T_subst_p sub p5) (m_T_subst_t sub t5) (m_T_subst_t sub t')
end

mutual
def m_t_subst_label_t_list (sub:List (termvar×t)) (l_t_list:List (label × t)) : List (label × t) :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (l_,(m_t_subst_t sub t_)) :: (m_t_subst_label_t_list sub l_t_list_)
def m_t_subst_t (sub:List (termvar×t)) (t__7:t) : t :=
  match t__7 with
  | (t_Var x) => (match list_assoc sub x with | none => (t_Var x)| some t_6 => t_6 )
  | (t_Lam x T5 t5) => t_Lam x T5 (m_t_subst_t (List.filter (fun (x5,t_6) => not ( List.elem x5 ([x]))) sub) t5)
  | (t_App t5 t') => t_App (m_t_subst_t sub t5) (m_t_subst_t sub t')
  | (t_TLam X T5 t5) => t_TLam X T5 (m_t_subst_t sub t5)
  | (t_TApp t5 T5) => t_TApp (m_t_subst_t sub t5) T5
  | (t_Rec (l_t_list)) => t_Rec (m_t_subst_label_t_list sub l_t_list)
  | (t_Proj t5 l) => t_Proj (m_t_subst_t sub t5) l
  | (t_Let p5 t5 t') => t_Let p5 (m_t_subst_t sub t5) (m_t_subst_t (List.filter (fun (x5,t_6) => not ( List.elem x5 ((aux_b_p_of_p p5)))) sub) t')
end

def Tsubst_G (S5:Typ) (X5:typevar) (D5:TypEnv) : TypEnv :=
  match D5 with
  | G_empty => G_empty 
  | (G_type G5 X T5) => G_type (Tsubst_G S5 X5 G5) X (Tsubst_T S5 X5 T5)
  | (G_term G5 x T5) => G_term (Tsubst_G S5 X5 G5) x (Tsubst_T S5 X5 T5)


mutual
def Tsubst_label_t_list (S5:Typ) (X5:typevar) (l_t_list:List (label × t)) : List (label × t) :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (l_,(Tsubst_t S5 X5 t_)) :: (Tsubst_label_t_list S5 X5 l_t_list_)
def Tsubst_t (S5:Typ) (X5:typevar) (t_6:t) : t :=
  match t_6 with
  | (t_Var x) => t_Var x
  | (t_Lam x T5 t5) => t_Lam x (Tsubst_T S5 X5 T5) (Tsubst_t S5 X5 t5)
  | (t_App t5 t') => t_App (Tsubst_t S5 X5 t5) (Tsubst_t S5 X5 t')
  | (t_TLam X T5 t5) => t_TLam X (Tsubst_T S5 X5 T5) (if  List.elem X5 ([X]) then t5 else (Tsubst_t S5 X5 t5))
  | (t_TApp t5 T5) => t_TApp (Tsubst_t S5 X5 t5) (Tsubst_T S5 X5 T5)
  | (t_Rec (l_t_list)) => t_Rec (Tsubst_label_t_list S5 X5 l_t_list)
  | (t_Proj t5 l) => t_Proj (Tsubst_t S5 X5 t5) l
  | (t_Let p5 t5 t') => t_Let (Tsubst_p S5 X5 p5) (Tsubst_t S5 X5 t5) (Tsubst_t S5 X5 t')
end

mutual
def tsubst_label_t_list (t_6:t) (x5:termvar) (l_t_list:List (label × t)) : List (label × t) :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (l_,(tsubst_t t_6 x5 t_)) :: (tsubst_label_t_list t_6 x5 l_t_list_)
def tsubst_t (t_6:t) (x5:termvar) (t__7:t) : t :=
  match t__7 with
  | (t_Var x) => (if x=x5 then t_6 else (t_Var x))
  | (t_Lam x T5 t5) => t_Lam x T5 (if  List.elem x5 ([x]) then t5 else (tsubst_t t_6 x5 t5))
  | (t_App t5 t') => t_App (tsubst_t t_6 x5 t5) (tsubst_t t_6 x5 t')
  | (t_TLam X T5 t5) => t_TLam X T5 (tsubst_t t_6 x5 t5)
  | (t_TApp t5 T5) => t_TApp (tsubst_t t_6 x5 t5) T5
  | (t_Rec (l_t_list)) => t_Rec (tsubst_label_t_list t_6 x5 l_t_list)
  | (t_Proj t5 l) => t_Proj (tsubst_t t_6 x5 t5) l
  | (t_Let p5 t5 t') => t_Let p5 (tsubst_t t_6 x5 t5) (if  List.elem x5 ((aux_b_p_of_p p5)) then t' else (tsubst_t t_6 x5 t'))
end

/- - library functions - -/
def list_minus {α : Type} [BEq α] (l1:List α) (l2:List α) : (List α) :=
  match l1 with
  | [] => []
  | h::t => if List.elem h l2 then list_minus t l2 else h::(list_minus t l2)


/- - free variables - -/
mutual
def ftv_label_T_list (l_T_list:List (label × Typ)) : List typevar :=
  match l_T_list with
  | [] => []
  | (l_,T_) :: l_T_list_ => (ftv_T T_) ++ (ftv_label_T_list l_T_list_)
def ftv_T (S5:Typ) :  List typevar :=
  match S5 with
  | (Ty_Var X) => [X]
  | Ty_Top => []
  | (Ty_Fun T5 T') => (ftv_T T5) ++ (ftv_T T')
  | (Ty_Forall X T5 T') => (ftv_T T5) ++ (list_minus (ftv_T T') [X])
  | (Ty_Rec (l_T_list)) => (ftv_label_T_list l_T_list)
end

mutual
def ftv_label_p_list (l_p_list:List (label × p)) : List typevar :=
  match l_p_list with
  | [] => []
  | (l_,p_) :: l_p_list_ => (ftv_p p_) ++ (ftv_label_p_list l_p_list_)
def ftv_p (p_5:p) :  List typevar :=
  match p_5 with
  | (P_Var x T5) => (ftv_T T5)
  | (P_Rec (l_p_list)) => (ftv_label_p_list l_p_list)
end

mutual
def fv_label_t_list (l_t_list:List (label × t)) : List termvar :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (fv_t t_) ++ (fv_label_t_list l_t_list_)
def fv_t (t_6:t) :  List termvar :=
  match t_6 with
  | (t_Var x) => [x]
  | (t_Lam x T5 t5) => (list_minus (fv_t t5) [x])
  | (t_App t5 t') => (fv_t t5) ++ (fv_t t')
  | (t_TLam X T5 t5) => (fv_t t5)
  | (t_TApp t5 T5) => (fv_t t5)
  | (t_Rec (l_t_list)) => (fv_label_t_list l_t_list)
  | (t_Proj t5 l) => (fv_t t5)
  | (t_Let p5 t5 t') => (fv_t t5) ++ (list_minus (fv_t t') (aux_b_p_of_p p5))
end

def ftv_G (D5:TypEnv) :  List typevar :=
  match D5 with
  | G_empty => []
  | (G_type G5 X T5) => (ftv_G G5) ++ (ftv_T T5)
  | (G_term G5 x T5) => (ftv_G G5) ++ (ftv_T T5)


mutual
def ftv_label_t_list (l_t_list:List (label × t)) : List typevar :=
  match l_t_list with
  | [] => []
  | (l_,t_) :: l_t_list_ => (ftv_t t_) ++ (ftv_label_t_list l_t_list_)
def ftv_t (t_6:t) :  List typevar :=
  match t_6 with
  | (t_Var x) => []
  | (t_Lam x T5 t5) => (ftv_T T5) ++ (ftv_t t5)
  | (t_App t5 t') => (ftv_t t5) ++ (ftv_t t')
  | (t_TLam X T5 t5) => (ftv_T T5) ++ (list_minus (ftv_t t5) [X])
  | (t_TApp t5 T5) => (ftv_t t5) ++ (ftv_T T5)
  | (t_Rec (l_t_list)) => (ftv_label_t_list l_t_list)
  | (t_Proj t5 l) => (ftv_t t5)
  | (t_Let p5 t5 t') => (ftv_p p5) ++ (ftv_t t5) ++ (ftv_t t')
end

 /- embedded definitions of operations on type environments -/
 def append_G (g1:TypEnv) (g2:TypEnv) :=
   match g2 with
   | G_empty => g1
   | G_type gh tv t => G_type (append_G g1 gh) tv t
   | G_term gh v t => G_term (append_G g1 gh) v t
  
 def flatten_G : List TypEnv -> TypEnv
   | [] => G_empty
   | g :: gs => append_G g (flatten_G gs)
  
/- definitions -/


/- defns Judgement_in -/
mutual
/-- defn xinG -/
inductive xinG : termvar → TypEnv → Prop where
  | xinG_1 : ∀ (x : termvar) (G5 : TypEnv) (T5 : Typ),
      xinG x (G_term G5 x T5)

  | xinG_2 : ∀ (x : termvar) (G5 : TypEnv) (X' : typevar) (U' : Typ),
      (xinG x G5) →
      xinG x (G_type G5 X' U')

  | xinG_3 : ∀ (x : termvar) (G5 : TypEnv) (x' : termvar) (T' : Typ),
      (xinG x G5) →
      xinG x (G_term G5 x' T')


/-- defn XinG -/
inductive XinG : typevar → TypEnv → Prop where
  | XinG_1 : ∀ (X : typevar) (G5 : TypEnv) (U : Typ),
      XinG X (G_type G5 X U)

  | XinG_2 : ∀ (X : typevar) (G5 : TypEnv) (X' : typevar) (U' : Typ),
      (XinG X G5) →
      XinG X (G_type G5 X' U')

  | XinG_3 : ∀ (X : typevar) (G5 : TypEnv) (x' : termvar) (T' : Typ),
      (XinG X G5) →
      XinG X (G_term G5 x' T')


/-- defn tin -/
inductive tin : termvar → Typ → TypEnv → Prop where
  | tin_1 : ∀ (x : termvar) (T5 : Typ) (G5 : TypEnv),
      tin x T5 (G_term G5 x T5)

  | tin_2 : ∀ (x : termvar) (T5 : Typ) (G5 : TypEnv) (X' : typevar) (U' : Typ),
      (tin x T5 G5) →
      tin x T5 (G_type G5 X' U')

  | tin_3 : ∀ (x : termvar) (T5 : Typ) (G5 : TypEnv) (x' : termvar) (T' : Typ),
      (tin x T5 G5) →
      tin x T5 (G_term G5 x' T')


/-- defn Tin -/
inductive Tin : typevar → Typ → TypEnv → Prop where
  | Tin_1 : ∀ (X : typevar) (U : Typ) (G5 : TypEnv),
      Tin X U (G_type G5 X U)

  | Tin_2 : ∀ (X : typevar) (U : Typ) (G5 : TypEnv) (X' : typevar) (U' : Typ),
      (Tin X U G5) →
      Tin X U (G_type G5 X' U')

  | Tin_3 : ∀ (X : typevar) (U : Typ) (G5 : TypEnv) (x' : termvar) (T' : Typ),
      (Tin X U G5) →
      Tin X U (G_term G5 x' T')


end
/- definitions -/


/- defns Jtype -/
mutual
/-- defn Gok -/
inductive Gok : TypEnv → Prop where
  | Gok_1 :       Gok G_empty

  | Gok_2 : ∀ (G5 : TypEnv) (x : termvar) (T5 : Typ),
      (GT G5 T5) →
      (¬ ((xinG x G5))) →
      Gok (G_term G5 x T5)

  | Gok_3 : ∀ (G5 : TypEnv) (X : typevar) (T5 : Typ),
      (GT G5 T5) →
      (¬ ((XinG X G5))) →
      Gok (G_type G5 X T5)


/-- defn GT -/
inductive GT : TypEnv → Typ → Prop where
  | GT_Var : ∀ (G5 : TypEnv) (X : typevar) (U : Typ),
      (Gok G5) →
      (Tin X U G5) →
      GT G5 (Ty_Var X)

  | GT_Top : ∀ (G5 : TypEnv),
      (Gok G5) →
      GT G5 Ty_Top

  | GT_Fun : ∀ (G5 : TypEnv) (T5 : Typ) (T' : Typ),
      (GT G5 T5) →
      (GT G5 T') →
      GT G5 (Ty_Fun T5 T')

  | GT_Forall : ∀ (G5 : TypEnv) (X : typevar) (T5 : Typ) (T' : Typ),
      (GT (G_type G5 X T5) T') →
      GT G5 (Ty_Forall X T5 T')

  | GT_Rcd : ∀ (l_T_list : List (label × Typ)) (G5 : TypEnv),
      (∀ l_T_list_ ∈ l_T_list, (fun (l_,T_) => (GT G5 T_)) l_T_list_) →
      GT G5 (Ty_Rec (l_T_list))


/-- defn SA -/
inductive SA : TypEnv → Typ → Typ → Prop where
  | SA_Top : ∀ (G5 : TypEnv) (S : Typ),
      (Gok G5) →
      SA G5 S Ty_Top

  | SA_Refl_TVar : ∀ (G5 : TypEnv) (X : typevar),
      (Gok G5) →
      SA G5 (Ty_Var X) (Ty_Var X)

  | SA_Trans_TVar : ∀ (G5 : TypEnv) (X : typevar) (T5 : Typ) (U : Typ),
      (Tin X U G5) →
      (SA G5 U T5) →
      SA G5 (Ty_Var X) T5

  | SA_Arrow : ∀ (G5 : TypEnv) (S1 : Typ) (S2 : Typ) (T1 : Typ) (T2 : Typ),
      (SA G5 T1 S1) →
      (SA G5 S2 T2) →
      SA G5 (Ty_Fun S1 S2) (Ty_Fun T1 T2)

  | SA_All : ∀ (G5 : TypEnv) (X : typevar) (S1 : Typ) (S2 : Typ) (T1 : Typ) (T2 : Typ),
      (SA G5 T1 S1) →
      (SA (G_type G5 X T1) S2 T2) →
      SA G5 (Ty_Forall X S1 S2) (Ty_Forall X T1 T2)

  | SA_Rcd : ∀ (l_T_list : List (label × Typ)) (k_S_list : List (label × Typ)) (G5 : TypEnv) (i : index) (m : index),
      (∀ i, (1 <= i ∧ i <= m) → SAf G5 ((fun (k_,S_) => k_) (k_S_list[i - 1]!)) ((fun (k_,S_) => S_) (k_S_list[i - 1]!)) (l_T_list)) →
      SA G5 (Ty_Rec (k_S_list)) (Ty_Rec (l_T_list))


/-- defn SAf -/
inductive SAf : TypEnv → label → Typ → List (label × Typ) → Prop where
  | SAf_found : ∀ (l_T_list : List (label × Typ)) (G5 : TypEnv) (k : label) (S : Typ) (T_5 : Typ),
      (SA G5 S T_5) →
      SAf G5 k S ([(k,T_5)] ++ l_T_list)

  | SAf_skip : ∀ (l_T_list : List (label × Typ)) (G5 : TypEnv) (k : label) (S : Typ) (l : label) (T_5 : Typ),
      (SAf G5 k S (l_T_list)) →
      SAf G5 k S ([(l,T_5)] ++ l_T_list)


/-- defn Ty -/
inductive Ty : TypEnv → t → Typ → Prop where
  | TyCh_Var : ∀ (G5 : TypEnv) (x : termvar) (T5 : Typ),
      (Gok G5) →
      (tin x T5 G5) →
      Ty G5 (t_Var x) T5

  | TyCh_Abs : ∀ (G5 : TypEnv) (x : termvar) (T1 : Typ) (t2 : t) (T2 : Typ),
      (Ty (G_term G5 x T1) t2 T2) →
      Ty G5 (t_Lam x T1 t2) (Ty_Fun T1 T2)

  | TyCh_App : ∀ (G5 : TypEnv) (t1 : t) (t2 : t) (T12 : Typ) (T11 : Typ),
      (Ty G5 t1 (Ty_Fun T11 T12)) →
      (Ty G5 t2 T11) →
      Ty G5 (t_App t1 t2) T12

  | TyCh_TAbs : ∀ (G5 : TypEnv) (X : typevar) (T1 : Typ) (t2 : t) (T2 : Typ),
      (Ty (G_type G5 X T1) t2 T2) →
      Ty G5 (t_TLam X T1 t2) (Ty_Forall X T1 T2)

  | TyCh_TApp : ∀ (G5 : TypEnv) (t1 : t) (T2 : Typ) (X : typevar) (T12 : Typ) (T11 : Typ),
      (Ty G5 t1 (Ty_Forall X T11 T12)) →
      (SA G5 T2 T11) →
      Ty G5 (t_TApp t1 T2) (Tsubst_T T2 X T12)

  | TyCh_Let : ∀ (G5 : TypEnv) (p5 : p) (t1 : t) (t2 : t) (T2 : Typ) (T1 : Typ) (D : TypEnv),
      (Ty G5 t1 T1) →
      (Pat p5 T1 D) →
      (Ty (flatten_G ([(G5)] ++ [(D)])) t2 T2) →
      Ty G5 (t_Let p5 t1 t2) T2

  | TyCh_Rcd : ∀ (l_t_T_list : List (label × t × Typ)) (G5 : TypEnv),
      (∀ l_t_T_list_ ∈ l_t_T_list, (fun (l_,t_,T_) => (Ty G5 t_ T_)) l_t_T_list_) →
      Ty G5 (t_Rec ((List.map (fun (l_,t_,T_) => (l_,t_)) l_t_T_list))) (Ty_Rec ((List.map (fun (l_,t_,T_) => (l_,T_)) l_t_T_list)))

  | TyCh_Proj : ∀ (l_T_list : List (label × Typ)) (j : index) (G5 : TypEnv) (t5 : t),
      (Ty G5 t5 (Ty_Rec (l_T_list))) →
      Ty G5 (t_Proj t5 ((fun (l_,T_) => l_) (l_T_list[j - 1]!))) ((fun (l_,T_) => T_) (l_T_list[j - 1]!))

  | TyCh_Sub : ∀ (G5 : TypEnv) (t5 : t) (T5 : Typ) (S : Typ),
      (Ty G5 t5 S) →
      (SA G5 S T5) →
      Ty G5 t5 T5


/-- defn Pat -/
inductive Pat : p → Typ → TypEnv → Prop where
  | Pat_Var : ∀ (x : termvar) (T5 : Typ),
      Pat (P_Var x T5) T5 (G_term G_empty x T5)

  | Pat_Rcd : ∀ (l_p_T_D_list : List (label × p × Typ × TypEnv)),
      (∀ l_p_T_D_list_ ∈ l_p_T_D_list, (fun (l_,p_,T_,D_) => (Pat p_ T_ D_)) l_p_T_D_list_) →
      Pat (P_Rec ((List.map (fun (l_,p_,T_,D_) => (l_,p_)) l_p_T_D_list))) (Ty_Rec ((List.map (fun (l_,p_,T_,D_) => (l_,T_)) l_p_T_D_list))) (flatten_G ((List.map (fun (l_,p_,T_,D_) => D_) l_p_T_D_list)))


end
/- definitions -/


/- defns Jop -/
mutual
/-- defn reduce -/
inductive reduce : t → t → Prop where
  | reduce_AppAbs : ∀ (x : termvar) (T11 : Typ) (t12 : t) (v2 : t),
      (is_v_of_t v2) →
      reduce (t_App (t_Lam x T11 t12) v2) (tsubst_t v2 x t12)

  | reduce_TappTabs : ∀ (X : typevar) (T11 : Typ) (t12 : t) (T2 : Typ),
      reduce (t_TApp (t_TLam X T11 t12) T2) (Tsubst_t T2 X t12)

  | reduce_LetV : ∀ (p5 : p) (t2 : t) (s5 : s) (v1 : t),
      (is_v_of_t v1) →
      (is_v_of_t v1) →
      (M p5 v1 s5) →
      reduce (t_Let p5 v1 t2) (m_t_subst_t s5 t2)

  | reduce_ProjRcd : ∀ (l'_v_list : List (label × t)) (j : index),
      (List.all l'_v_list (fun (l'_,v_) => is_v_of_t v_)) →
      reduce (t_Proj (t_Rec (l'_v_list)) ((fun (l'_,v_) => l'_) (l'_v_list[j - 1]!))) ((fun (l'_,v_) => v_) (l'_v_list[j - 1]!))

  | reduce_Ctx_app_fun : ∀ (t1 : t) (t_5 : t) (t1' : t),
      (reduce t1 t1') →
      reduce (t_App t1 t_5) (t_App t1' t_5)

  | reduce_Ctx_app_arg : ∀ (v5 : t) (t1 : t) (t1' : t),
      (is_v_of_t v5) →
      (reduce t1 t1') →
      reduce (t_App v5 t1) (t_App v5 t1')

  | reduce_Ctx_type_fun : ∀ (t1 : t) (T5 : Typ) (t1' : t),
      (reduce t1 t1') →
      reduce (t_TApp t1 T5) (t_TApp t1' T5)

  | reduce_Ctx_record : ∀ (l'_t'_list : List (label × t)) (l_v_list : List (label × t)) (l : label) (t5 : t) (t' : t),
      (List.all l_v_list (fun (l_,v_) => is_v_of_t v_)) →
      (reduce t5 t') →
      reduce (t_Rec (l_v_list ++ [(l,t5)] ++ l'_t'_list)) (t_Rec (l_v_list ++ [(l,t')] ++ l'_t'_list))

  | reduce_Ctx_let_binding : ∀ (p5 : p) (t1 : t) (t2 : t) (t1' : t),
      (reduce t1 t1') →
      reduce (t_Let p5 t1 t2) (t_Let p5 t1' t2)


/-- defn M -/
inductive M : p → t → s → Prop where
  | M_Var : ∀ (x : termvar) (T5 : Typ) (v5 : t),
      (is_v_of_t v5) →
      (is_v_of_t v5) →
      M (P_Var x T5) v5 [ (x, v5) ]

  | M_Rcd : ∀ (l_p_s_list : List (label × p × s)) (k_v_list : List (label × t)) (i : index) (m : index),
      (List.all k_v_list (fun (k_,v_) => is_v_of_t v_)) →
      (∀ i, (1 <= i ∧ i <= m) → Mf ((fun (l_,p_,s_) => l_) (l_p_s_list[i - 1]!)) ((fun (l_,p_,s_) => p_) (l_p_s_list[i - 1]!)) (k_v_list) ((fun (l_,p_,s_) => s_) (l_p_s_list[i - 1]!))) →
      M (P_Rec ((List.map (fun (l_,p_,s_) => (l_,p_)) l_p_s_list))) (t_Rec (k_v_list)) (List.flatten ((List.map (fun (l_,p_,s_) => s_) l_p_s_list)))


/-- defn Mf -/
inductive Mf : label → p → List (label × t) → s → Prop where
  | Mf_found : ∀ (k_v_list : List (label × t)) (l : label) (p5 : p) (v_5 : t) (s5 : s),
      (is_v_of_t v_5) →
      (List.all k_v_list (fun (k_,v_) => is_v_of_t v_)) →
      (M p5 v_5 s5) →
      Mf l p5 ([(l,v_5)] ++ k_v_list) s5

  | Mf_skip : ∀ (k_v_list : List (label × t)) (l : label) (p5 : p) (k : label) (v_5 : t) (s5 : s),
      (is_v_of_t v_5) →
      (List.all k_v_list (fun (k_,v_) => is_v_of_t v_)) →
      (Mf l p5 (k_v_list) s5) →
      Mf l p5 ([(k,v_5)] ++ k_v_list) s5


end


