(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_2.ott *)

type i = UNDEFINED

type 
constant = 
   CONST_unit


type 
p = 
   P_constant of constant


type 
e = 
   E_constant of constant


(** subrules *)
let is_v_of_e (e5:e) : bool =
  match e5 with
  | (E_constant constant) -> (true)


(** definitions *)


