/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.4.ott -/




abbrev value_name := Nat
abbrev index := Nat

inductive list_value_name : Type where
  | Nil_list_value_name : list_value_name
  | Cons_list_value_name (x : value_name) (_ : list_value_name) : list_value_name
  deriving Inhabited

mutual
inductive a : Type where
  | a_x (x : value_name) : a
  | a_X (_ : list_value_name) : a
  | a_F (c5 : c) : a
  | a_E (_ : list_c) : a

inductive list_c : Type where
  | Nil_list_c : list_c
  | Cons_list_c (_ : c) (_ : list_c) : list_c

inductive c : Type where
  | c_C (_ : list_a) : c

inductive list_a : Type where
  | Nil_list_a : list_a
  | Cons_list_a (_ : a) (_ : list_a) : list_a

end
open list_a list_value_name list_c a c
def map_list_a {A : Type} (f : a -> A) (l : list_a) : List A :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => (f h) :: (map_list_a f tl_)

def make_list_a (l : List a) : list_a :=
  match l with
  | [] => Nil_list_a
  | h :: tl_ => Cons_list_a h (make_list_a tl_)

def unmake_list_a (l : list_a) : List a :=
  match l with
  | Nil_list_a => []
  | Cons_list_a h tl_ => h :: (unmake_list_a tl_)

def nth_list_a (n : Nat) (l : list_a) : Option a :=
  match n, l with
  | 0, Cons_list_a h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_a => none
  | k+1, Cons_list_a _ tl_ => nth_list_a k tl_

def app_list_a (l m : list_a) : list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)

def map_list_value_name {A : Type} (f : value_name -> A) (l : list_value_name) : List A :=
  match l with
  | Nil_list_value_name => []
  | Cons_list_value_name h tl_ => (f h) :: (map_list_value_name f tl_)

def make_list_value_name (l : List value_name) : list_value_name :=
  match l with
  | [] => Nil_list_value_name
  | h :: tl_ => Cons_list_value_name h (make_list_value_name tl_)

def unmake_list_value_name (l : list_value_name) : List value_name :=
  match l with
  | Nil_list_value_name => []
  | Cons_list_value_name h tl_ => h :: (unmake_list_value_name tl_)

def nth_list_value_name (n : Nat) (l : list_value_name) : Option value_name :=
  match n, l with
  | 0, Cons_list_value_name h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_value_name => none
  | k+1, Cons_list_value_name _ tl_ => nth_list_value_name k tl_

def app_list_value_name (l m : list_value_name) : list_value_name :=
  match l with
  | Nil_list_value_name => m
  | Cons_list_value_name h tl_ => Cons_list_value_name h (app_list_value_name tl_ m)

def map_list_c {A : Type} (f : c -> A) (l : list_c) : List A :=
  match l with
  | Nil_list_c => []
  | Cons_list_c h tl_ => (f h) :: (map_list_c f tl_)

def make_list_c (l : List c) : list_c :=
  match l with
  | [] => Nil_list_c
  | h :: tl_ => Cons_list_c h (make_list_c tl_)

def unmake_list_c (l : list_c) : List c :=
  match l with
  | Nil_list_c => []
  | Cons_list_c h tl_ => h :: (unmake_list_c tl_)

def nth_list_c (n : Nat) (l : list_c) : Option c :=
  match n, l with
  | 0, Cons_list_c h tl_ => some h
  | 0, _ => none
  | _+1, Nil_list_c => none
  | k+1, Cons_list_c _ tl_ => nth_list_c k tl_

def app_list_c (l m : list_c) : list_c :=
  match l with
  | Nil_list_c => m
  | Cons_list_c h tl_ => Cons_list_c h (app_list_c tl_ m)



/- - substitutions - -/
mutual
def subst_a_list (a_5:a) (x5:value_name) (c5:list_a) : list_a :=
  match c5 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (subst_a a_5 x5 a) (subst_a_list a_5 x5 a_tl)
def subst_c (a_5:a) (x5:value_name) (c5:c) : c :=
  match c5 with
  | (c_C a_list) => c_C (subst_a_list a_5 x5 a_list)
def subst_c_list (a5:a) (x_5:value_name) (a_6:list_c) : list_c :=
  match a_6 with
  | Nil_list_c => Nil_list_c
  | Cons_list_c c c_tl => Cons_list_c (subst_c a5 x_5 c) (subst_c_list a5 x_5 c_tl)
def subst_a (a5:a) (x_5:value_name) (a_6:a) : a :=
  match a_6 with
  | (a_x x) => (if x=x_5 then a5 else (a_x x))
  | (a_X x_list) => a_X x_list
  | (a_F c5) => a_F (subst_c a5 x_5 c5)
  | (a_E c_list) => a_E (subst_c_list a5 x_5 c_list)
end



