(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_subrule_1.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.


Definition i : Set := nat.
Definition x : Set := nat.

Inductive foobar : Set := 
 | foobar_foo : foobar
 | foobar_bar : foobar.

Inductive list_foobar_foobar : Set := 
 | Nil_list_foobar_foobar : list_foobar_foobar
 | Cons_list_foobar_foobar (foo:foobar) (_:foobar) (_:list_foobar_foobar).

Inductive seq : Set := 
 | seq_foofoobar (_:list_foobar_foobar).
Fixpoint map_list_foobar_foobar (A:Type) (f:foobar->foobar->A) (l:list_foobar_foobar) : list A :=
  match l with
  | Nil_list_foobar_foobar => nil
  | Cons_list_foobar_foobar h0 h1 tl_ => cons (f h0 h1) (map_list_foobar_foobar A f tl_)
  end.
Arguments map_list_foobar_foobar [A] _ _.

Fixpoint make_list_foobar_foobar (l: list (foobar * foobar)): list_foobar_foobar :=
  match l with
  | nil  => Nil_list_foobar_foobar
  | cons (h0,h1) tl_ => Cons_list_foobar_foobar h0 h1 (make_list_foobar_foobar tl_)
  end.

Fixpoint unmake_list_foobar_foobar (l: list_foobar_foobar): list (foobar * foobar) :=
  match l with
  | Nil_list_foobar_foobar => nil
  | Cons_list_foobar_foobar h0 h1 tl_ => cons (h0,h1) (unmake_list_foobar_foobar tl_)
  end.

Fixpoint nth_list_foobar_foobar (n:nat) (l: list_foobar_foobar) {struct n} : option (foobar * foobar) :=
  match n,l with
  | O, Cons_list_foobar_foobar h0 h1 tl_ => Some (h0,h1)
  | O, _ => None
  | S m, Nil_list_foobar_foobar => None
  | S m, Cons_list_foobar_foobar h0 h1 tl_ => nth_list_foobar_foobar m tl_
  end.

Fixpoint app_list_foobar_foobar (l m: list_foobar_foobar): list_foobar_foobar :=
  match l with
  | Nil_list_foobar_foobar => m
  | Cons_list_foobar_foobar h0 h1 tl_ => Cons_list_foobar_foobar h0 h1 (app_list_foobar_foobar tl_ m)
  end.



(** subrules *)
Definition is_foo_of_foobar (foobar5:foobar) : Prop :=
  match foobar5 with
  | foobar_foo => (True)
  | foobar_bar => False
end.

Fixpoint is_seq_of_foobar_foobar_list (l:list_foobar_foobar) : Prop :=
  match l with
  | Nil_list_foobar_foobar => True
  | Cons_list_foobar_foobar foo_ foobar_ foo_foobar_list_ => (is_foo_of_foobar foo_) /\ (is_seq_of_foobar_foobar_list foo_foobar_list_)
end.

Definition is_seq_of_seq (seq5:seq) : Prop :=
  match seq5 with
  | (seq_foofoobar foo_foobar_list) => (is_seq_of_foobar_foobar_list foo_foobar_list)
end.

(* definitions *)

(* defns J *)
Inductive J_zip : (list_foobar) -> (list_foobar) -> seq -> Prop :=    (* defn zip *)
 | J_zip_zap : forall (foo_foobar_list:list_foobar_foobar),
     (Forall (fun (tmp_:(foobar*foobar)) => match tmp_ with (foo_,foobar_) => is_foo_of_foobar foo_ end) (unmake_list_foobar_foobar foo_foobar_list)) ->
     J_zip (make_list_foobar (map_list_foobar_foobar (fun (foo_:foobar) (foobar_:foobar) => foo_) foo_foobar_list)) (make_list_foobar (map_list_foobar_foobar (fun (foo_:foobar) (foobar_:foobar) => foobar_) foo_foobar_list)) (seq_foofoobar foo_foobar_list).


