/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test14.ott -/




/-- term variable -/
abbrev termvar := Nat
/-- field label -/
abbrev label := Nat
/-- indices -/
abbrev index := Nat

mutual
/-- term -/
inductive t : Type where
  /-- variable -/
  | t_Var (x : termvar) : t
  /-- abstraction -/
  | t_Lam (x : termvar) (t5 : t) : t
  /-- application -/
  | t_App (t5 : t) (t' : t) : t
  /-- record -/
  | t_Rec (_ : list_label_t) : t
  /-- projection -/
  | t_Proj (t5 : t) (l : label) : t
  deriving Inhabited
inductive list_label_t : Type where
  | Nil_list_label_t : list_label_t
  | Cons_list_label_t (l : label) (v : t) (_ : list_label_t) : list_label_t
  deriving Inhabited
end
open list_label_t t
def map_list_label_t {A : Type} (f : label -> t -> A) (l : list_label_t) : List A :=
  match l with
  | Nil_list_label_t => []
  | Cons_list_label_t h0 h1 tl_ => (f h0 h1) :: (map_list_label_t f tl_)

def make_list_label_t (l : List (label × t)) : list_label_t :=
  match l with
  | [] => Nil_list_label_t
  | (h0,h1) :: tl_ => Cons_list_label_t h0 h1 (make_list_label_t tl_)

def unmake_list_label_t (l : list_label_t) : List (label × t) :=
  match l with
  | Nil_list_label_t => []
  | Cons_list_label_t h0 h1 tl_ => (h0,h1) :: (unmake_list_label_t tl_)

def nth_list_label_t (n : Nat) (l : list_label_t) : Option (label × t) :=
  match n, l with
  | 0, Cons_list_label_t h0 h1 tl_ => some (h0,h1)
  | 0, _ => none
  | _+1, Nil_list_label_t => none
  | k+1, Cons_list_label_t _ _ tl_ => nth_list_label_t k tl_

def app_list_label_t (l m : list_label_t) : list_label_t :=
  match l with
  | Nil_list_label_t => m
  | Cons_list_label_t h0 h1 tl_ => Cons_list_label_t h0 h1 (app_list_label_t tl_ m)



/- - subrules - -/
mutual
def is_v_of_l_t_list (l:list_label_t) : Bool :=
  match l with
  | Nil_list_label_t => true
  | Cons_list_label_t l_ t_ l_t_list_ => ((is_v_of_t t_)) && (is_v_of_l_t_list l_t_list_)
def is_v_of_t (t_6:t) : Bool :=
  match t_6 with
  | (t_Var x) => false
  | (t_Lam x t5) => (true)
  | (t_App t5 t') => false
  | (t_Rec l_t_list) => (is_v_of_l_t_list l_t_list)
  | (t_Proj t5 l) => false
end



