(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.1.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.


Definition value_name : Set := nat.
Lemma eq_value_name: forall (x y : value_name), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_value_name : ott_coq_equality.
Definition index : Set := nat.
Lemma eq_index: forall (x y : index), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_index : ott_coq_equality.

Inductive list_value_name : Set := 
 | Nil_list_value_name : list_value_name
 | Cons_list_value_name (x:value_name) (_:list_value_name).

Inductive a : Set := 
 | a_x (x:value_name)
 | a_A (_:list_a)
 | a_X (_:list_value_name)
with list_a : Set := 
 | Nil_list_a : list_a
 | Cons_list_a (_:a) (_:list_a).
Fixpoint map_list_a (A:Type) (f:a->A) (l:list_a) : list A :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a h tl_ => cons (f h) (map_list_a A f tl_)
  end.
Arguments map_list_a [A] _ _.

Fixpoint make_list_a (l: list a): list_a :=
  match l with
  | nil  => Nil_list_a
  | cons h tl_ => Cons_list_a h (make_list_a tl_)
  end.

Fixpoint unmake_list_a (l: list_a): list a :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a h tl_ => cons h (unmake_list_a tl_)
  end.

Fixpoint nth_list_a (n:nat) (l: list_a) {struct n} : option a :=
  match n,l with
  | O, Cons_list_a h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_a => None
  | S m, Cons_list_a h tl_ => nth_list_a m tl_
  end.

Fixpoint app_list_a (l m: list_a): list_a :=
  match l with
  | Nil_list_a => m
  | Cons_list_a h tl_ => Cons_list_a h (app_list_a tl_ m)
  end.

Fixpoint map_list_value_name (A:Type) (f:value_name->A) (l:list_value_name) : list A :=
  match l with
  | Nil_list_value_name => nil
  | Cons_list_value_name h tl_ => cons (f h) (map_list_value_name A f tl_)
  end.
Arguments map_list_value_name [A] _ _.

Fixpoint make_list_value_name (l: list value_name): list_value_name :=
  match l with
  | nil  => Nil_list_value_name
  | cons h tl_ => Cons_list_value_name h (make_list_value_name tl_)
  end.

Fixpoint unmake_list_value_name (l: list_value_name): list value_name :=
  match l with
  | Nil_list_value_name => nil
  | Cons_list_value_name h tl_ => cons h (unmake_list_value_name tl_)
  end.

Fixpoint nth_list_value_name (n:nat) (l: list_value_name) {struct n} : option value_name :=
  match n,l with
  | O, Cons_list_value_name h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_value_name => None
  | S m, Cons_list_value_name h tl_ => nth_list_value_name m tl_
  end.

Fixpoint app_list_value_name (l m: list_value_name): list_value_name :=
  match l with
  | Nil_list_value_name => m
  | Cons_list_value_name h tl_ => Cons_list_value_name h (app_list_value_name tl_ m)
  end.



(** free variables *)
Fixpoint fv_a_list (l:list_a) : list value_name :=
  match l with
  | Nil_list_a => nil
  | Cons_list_a a_ a_list_ => app ((fv_a a_)) (fv_a_list a_list_)
end
with fv_a (a_5:a) : list value_name :=
  match a_5 with
  | (a_x x) => (cons x nil)
  | (a_A a_list) => ((fv_a_list a_list))
  | (a_X x_list) => (nil)
end.

(** library functions *)
Fixpoint list_assoc A B (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list (A*B)) {struct l} : option B :=
  match l with
  | nil => None
  | cons (a,b) t => if (eq a x) then Some b else list_assoc A B eq x t
end.
Arguments list_assoc [A B] _ _ _.


(** substitutions *)
Fixpoint msubst_a_list (sub:list (value_name*a)) (a__6:list_a) {struct a__6} : list_a :=
  match a__6 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (msubst_a sub a) (msubst_a_list sub a_tl)
end
with msubst_a (sub:list (value_name*a)) (a__6:a) {struct a__6} : a :=
  match a__6 with
  | (a_x x) => (match list_assoc eq_value_name x sub with None => (a_x x) | Some a_5 => a_5 end)
  | (a_A a_list) => a_A (msubst_a_list sub a_list)
  | (a_X x_list) => a_X x_list
end.

Fixpoint subst_a_list (a_5:a) (x_5:value_name) (a__6:list_a) {struct a__6} : list_a :=
  match a__6 with
  | Nil_list_a => Nil_list_a
  | Cons_list_a a a_tl => Cons_list_a (subst_a a_5 x_5 a) (subst_a_list a_5 x_5 a_tl)
end
with subst_a (a_5:a) (x_5:value_name) (a__6:a) {struct a__6} : a :=
  match a__6 with
  | (a_x x) => (if eq_value_name x x_5 then a_5 else (a_x x))
  | (a_A a_list) => a_A (subst_a_list a_5 x_5 a_list)
  | (a_X x_list) => a_X x_list
end.



