(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/arrow_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/sub_arrow.ott /home/pes20/claude-home/ott/regression/../examples/tapl/top.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common_labels.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common_index.ott /home/pes20/claude-home/ott/regression/../examples/tapl/record.ott /home/pes20/claude-home/ott/regression/../examples/tapl/sub_record.ott *)
From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
(** warning: the backend selected ignores the file structure informations *)
(** syntax *)
Definition termvar : Set := nat.
Lemma eq_termvar: forall (x y : termvar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_termvar : ott_coq_equality.
Definition label : Set := nat. (* field label *)
Lemma eq_label: forall (x y : label), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_label : ott_coq_equality.
Definition index : Set := nat. (* indices *)

Inductive T : Set :=  (* types: *)
 | TyArr (T5:T) (T':T) (* type of functions *)
 | TyTop : T (* maximum type *)
 | TyRecord (_:list_label_T) (* type of records *)
with list_label_T : Set := 
 | Nil_list_label_T : list_label_T
 | Cons_list_label_T (l:label) (_:T) (_:list_label_T).

Inductive list_label : Set := 
 | Nil_list_label : list_label
 | Cons_list_label (l:label) (_:list_label).

Inductive t : Set :=  (* terms: *)
 | TmVar (x:termvar) (* variable *)
 | TmAbs (x:termvar) (T5:T) (t5:t) (* abstraction *)
 | TmApp (t1:t) (t2:t) (* application *)
 | TmRecord (_:list_label_t) (* record *)
 | TmProj (t5:t) (l:label) (* projection *)
with list_label_t : Set := 
 | Nil_list_label_t : list_label_t
 | Cons_list_label_t (l:label) (v:t) (_:list_label_t).

Inductive labels : Set := 
 | labels_seq (_:list_label).

Definition G : Set := list (termvar*T).

(** auxiliary functions on the new list types *)
Fixpoint map_list_label_t (A:Type) (f:label->t->A) (l:list_label_t) : list A :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t h0 h1 tl_ => cons (f h0 h1) (map_list_label_t A f tl_)
  end.
Arguments map_list_label_t [A] _ _.

Fixpoint make_list_label_t (l: list (label * t)): list_label_t :=
  match l with
  | nil  => Nil_list_label_t
  | cons (h0,h1) tl_ => Cons_list_label_t h0 h1 (make_list_label_t tl_)
  end.

Fixpoint unmake_list_label_t (l: list_label_t): list (label * t) :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t h0 h1 tl_ => cons (h0,h1) (unmake_list_label_t tl_)
  end.

Fixpoint nth_list_label_t (n:nat) (l: list_label_t) {struct n} : option (label * t) :=
  match n,l with
  | O, Cons_list_label_t h0 h1 tl_ => Some (h0,h1)
  | O, _ => None
  | S m, Nil_list_label_t => None
  | S m, Cons_list_label_t h0 h1 tl_ => nth_list_label_t m tl_
  end.

Fixpoint app_list_label_t (l m: list_label_t): list_label_t :=
  match l with
  | Nil_list_label_t => m
  | Cons_list_label_t h0 h1 tl_ => Cons_list_label_t h0 h1 (app_list_label_t tl_ m)
  end.

Fixpoint map_list_label_T (A:Type) (f:label->T->A) (l:list_label_T) : list A :=
  match l with
  | Nil_list_label_T => nil
  | Cons_list_label_T h0 h1 tl_ => cons (f h0 h1) (map_list_label_T A f tl_)
  end.
Arguments map_list_label_T [A] _ _.

Fixpoint make_list_label_T (l: list (label * T)): list_label_T :=
  match l with
  | nil  => Nil_list_label_T
  | cons (h0,h1) tl_ => Cons_list_label_T h0 h1 (make_list_label_T tl_)
  end.

Fixpoint unmake_list_label_T (l: list_label_T): list (label * T) :=
  match l with
  | Nil_list_label_T => nil
  | Cons_list_label_T h0 h1 tl_ => cons (h0,h1) (unmake_list_label_T tl_)
  end.

Fixpoint nth_list_label_T (n:nat) (l: list_label_T) {struct n} : option (label * T) :=
  match n,l with
  | O, Cons_list_label_T h0 h1 tl_ => Some (h0,h1)
  | O, _ => None
  | S m, Nil_list_label_T => None
  | S m, Cons_list_label_T h0 h1 tl_ => nth_list_label_T m tl_
  end.

Fixpoint app_list_label_T (l m: list_label_T): list_label_T :=
  match l with
  | Nil_list_label_T => m
  | Cons_list_label_T h0 h1 tl_ => Cons_list_label_T h0 h1 (app_list_label_T tl_ m)
  end.

Fixpoint map_list_label (A:Type) (f:label->A) (l:list_label) : list A :=
  match l with
  | Nil_list_label => nil
  | Cons_list_label h tl_ => cons (f h) (map_list_label A f tl_)
  end.
Arguments map_list_label [A] _ _.

Fixpoint make_list_label (l: list label): list_label :=
  match l with
  | nil  => Nil_list_label
  | cons h tl_ => Cons_list_label h (make_list_label tl_)
  end.

Fixpoint unmake_list_label (l: list_label): list label :=
  match l with
  | Nil_list_label => nil
  | Cons_list_label h tl_ => cons h (unmake_list_label tl_)
  end.

Fixpoint nth_list_label (n:nat) (l: list_label) {struct n} : option label :=
  match n,l with
  | O, Cons_list_label h tl_ => Some h
  | O, _ => None
  | S m, Nil_list_label => None
  | S m, Cons_list_label h tl_ => nth_list_label m tl_
  end.

Fixpoint app_list_label (l m: list_label): list_label :=
  match l with
  | Nil_list_label => m
  | Cons_list_label h tl_ => Cons_list_label h (app_list_label tl_ m)
  end.

(** library functions *)
Fixpoint list_mem A (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list A) {struct l} : bool :=
  match l with
  | nil => false
  | cons h t => if eq h x then true else list_mem A eq x t
end.
Arguments list_mem [A] _ _ _.

Fixpoint list_minus A (eq:forall a b:A,{a=b}+{a<>b}) (l1:list A) (l2:list A) {struct l1} : list A :=
  match l1 with
  | nil => nil
  | cons h t => if (list_mem (A:=A) eq h l2) then list_minus A eq t l2 else cons h (list_minus A eq t l2)
end.
Arguments list_minus [A] _ _ _.

(** subrules *)
Fixpoint is_v_of_l_t_list (l:list_label_t) : Prop :=
  match l with
  | Nil_list_label_t => True
  | Cons_list_label_t l_ t_ l_t_list_ => (is_v_of_t t_) /\ (is_v_of_l_t_list l_t_list_)
end
with is_v_of_t (t_6:t) : Prop :=
  match t_6 with
  | (TmVar x) => False
  | (TmAbs x T5 t5) => (True)
  | (TmApp t1 t2) => False
  | (TmRecord l_t_list) => (is_v_of_l_t_list l_t_list)
  | (TmProj t5 l) => False
end.

(** auxiliary functions *)
(** free variables *)
Fixpoint fv_label_t_list (l:list_label_t) : list termvar :=
  match l with
  | Nil_list_label_t => nil
  | Cons_list_label_t l_ t_ l_t_list_ => app ((fv_t t_)) (fv_label_t_list l_t_list_)
end
with fv_t (t_6:t) : list termvar :=
  match t_6 with
  | (TmVar x) => (cons x nil)
  | (TmAbs x T5 t5) => ((list_minus eq_termvar (fv_t t5) (cons x nil)))
  | (TmApp t1 t2) => (app (fv_t t1) (fv_t t2))
  | (TmRecord l_t_list) => ((fv_label_t_list l_t_list))
  | (TmProj t5 l) => ((fv_t t5))
end.

(** substitutions *)
Fixpoint subst_label_t_list (t_6:t) (x5:termvar) (t__7:list_label_t) {struct t__7} : list_label_t :=
  match t__7 with
  | Nil_list_label_t => Nil_list_label_t
  | Cons_list_label_t label1 t2 label_t_tl => Cons_list_label_t label1 (subst_t t_6 x5 t2) (subst_label_t_list t_6 x5 label_t_tl)
end
with subst_t (t_6:t) (x5:termvar) (t__7:t) {struct t__7} : t :=
  match t__7 with
  | (TmVar x) => (if eq_termvar x x5 then t_6 else (TmVar x))
  | (TmAbs x T5 t5) => TmAbs x T5 (if list_mem eq_termvar x5 (cons x nil) then t5 else (subst_t t_6 x5 t5))
  | (TmApp t1 t2) => TmApp (subst_t t_6 x5 t1) (subst_t t_6 x5 t2)
  | (TmRecord l_t_list) => TmRecord (subst_label_t_list t_6 x5 l_t_list)
  | (TmProj t5 l) => TmProj (subst_t t_6 x5 t5) l
end.

(** context application *)
Require Import Ott.ott_list. (* for [all_distinct] *)

Definition bound x T0 G :=
  exists G1, exists G2,
    (G = G1 ++ (x,T0)::G2)%list /\
    ~In x (List.map (@fst termvar T) G1).

Definition list'label : Set. exact list_label || exact (list label). Defined.
Definition unmake_list'label : list'label -> list label.
  exact unmake_list_label || exact (fun x => x). Defined.

(*
These definitions are a hack to make [unmake_list'T] (and similarly
[unmake_list't]) work whether native lists or specific lists are
generated by ott. We use [unmake_list'T] in homs, and that should be a
function that converts from whatever type ott uses to represent lists
of [T] to standard lists of [T]. The type [list'T] is defined just so
as to express the argument type of [unmake_list'T].
*)
Definition list'T : Set. exact list_T || exact (list T). Defined.
Definition unmake_list'T : list'T -> list T.
  exact unmake_list_T || exact (fun x => x). Defined.
Definition list't : Set. exact list_t || exact (list t). Defined.
Definition unmake_list't : list't -> list t.
  exact unmake_list_t || exact (fun x => x). Defined.


Inductive list_label_t_T : Set := Nil_list_label_t_T | Cons_list_label_t_T (_:label) (_:t) (_:T) (tl_ : list_label_t_T).

Fixpoint map_list_label_t_T (A:Type) (f:label->t->T->A) (l:list_label_t_T) : list A :=
  match l with
  | Nil_list_label_t_T => nil
  | Cons_list_label_t_T h0 h1 h2 tl_ => cons (f h0 h1 h2) (map_list_label_t_T A f tl_)
  end.
Arguments map_list_label_t_T [A] _ _.

Fixpoint make_list_label_t_T (l: list (label * t * T)): list_label_t_T :=
  match l with
  | nil  => Nil_list_label_t_T
  | cons (h0,h1,h2) tl_ => Cons_list_label_t_T h0 h1 h2 (make_list_label_t_T tl_)
  end.

Fixpoint unmake_list_label_t_T (l: list_label_t_T): list (label * t * T) :=
  match l with
  | Nil_list_label_t_T => nil
  | Cons_list_label_t_T h0 h1 h2 tl_ => cons (h0,h1,h2) (unmake_list_label_t_T tl_)
  end.

Fixpoint nth_list_label_t_T (n:nat) (l: list_label_t_T) {struct n} : option (label * t * T) :=
  match n,l with
  | O, Cons_list_label_t_T h0 h1 h2 tl_ => Some (h0,h1,h2)
  | O, _ => None
  | S m, Nil_list_label_t_T => None
  | S m, Cons_list_label_t_T h0 h1 h2 tl_ => nth_list_label_t_T m tl_
  end.

Fixpoint app_list_label_t_T (l m: list_label_t_T): list_label_t_T :=
  match l with
  | Nil_list_label_t_T => m
  | Cons_list_label_t_T h0 h1 h2 tl_ => Cons_list_label_t_T h0 h1 h2 (app_list_label_t_T tl_ m)
  end.

Inductive list_label_T_T : Set := Nil_list_label_T_T | Cons_list_label_T_T (_:label) (_:T) (_:T) (tl_ : list_label_T_T).

Fixpoint map_list_label_T_T (A:Type) (f:label->T->T->A) (l:list_label_T_T) : list A :=
  match l with
  | Nil_list_label_T_T => nil
  | Cons_list_label_T_T h0 h1 h2 tl_ => cons (f h0 h1 h2) (map_list_label_T_T A f tl_)
  end.
Arguments map_list_label_T_T [A] _ _.

Fixpoint make_list_label_T_T (l: list (label * T * T)): list_label_T_T :=
  match l with
  | nil  => Nil_list_label_T_T
  | cons (h0,h1,h2) tl_ => Cons_list_label_T_T h0 h1 h2 (make_list_label_T_T tl_)
  end.

Fixpoint unmake_list_label_T_T (l: list_label_T_T): list (label * T * T) :=
  match l with
  | Nil_list_label_T_T => nil
  | Cons_list_label_T_T h0 h1 h2 tl_ => cons (h0,h1,h2) (unmake_list_label_T_T tl_)
  end.

Fixpoint nth_list_label_T_T (n:nat) (l: list_label_T_T) {struct n} : option (label * T * T) :=
  match n,l with
  | O, Cons_list_label_T_T h0 h1 h2 tl_ => Some (h0,h1,h2)
  | O, _ => None
  | S m, Nil_list_label_T_T => None
  | S m, Cons_list_label_T_T h0 h1 h2 tl_ => nth_list_label_T_T m tl_
  end.

Fixpoint app_list_label_T_T (l m: list_label_T_T): list_label_T_T :=
  match l with
  | Nil_list_label_T_T => m
  | Cons_list_label_T_T h0 h1 h2 tl_ => Cons_list_label_T_T h0 h1 h2 (app_list_label_T_T tl_ m)
  end.

(* definitions *)

(* defns Jop *)
Inductive red : t -> t -> Prop :=    (* defn red *)
 | E_App1 : forall (t1 t2 t1':t),
     red t1 t1' ->
     red (TmApp t1 t2) (TmApp t1' t2)
 | E_App2 : forall (v1 t2 t2':t),
     is_v_of_t v1 ->
     red t2 t2' ->
     red (TmApp v1 t2) (TmApp v1 t2')
 | E_AppAbs : forall (x:termvar) (T5:T) (t12 v2:t),
     is_v_of_t v2 ->
     red (TmApp  (TmAbs x T5 t12)  v2)  (subst_t  v2   x   t12 ) 
 | E_ProjRcd : forall (l_v_list:list_label_t) (j:index) (t101 t102:(label*t)),
          nth_list_label_t (j - 1) l_v_list = Some t101 ->
     nth_list_label_t (j - 1) l_v_list = Some t102 ->
(Forall (fun (tmp_:(label*t)) => match tmp_ with (l_,v_) => is_v_of_t v_ end) (unmake_list_label_t l_v_list)) ->
     red (TmProj (TmRecord l_v_list) (match t102 with (l_,v_) => l_ end)) (match t101 with (l_,v_) => v_ end)
 | E_Proj : forall (t1:t) (l:label) (t1':t),
     red t1 t1' ->
     red (TmProj t1 l) (TmProj t1' l)
 | E_Rcd : forall (l'_t_list l_v_list:list_label_t) (l:label) (t_5 t':t),
     (Forall (fun (tmp_:(label*t)) => match tmp_ with (l_,v_) => is_v_of_t v_ end) (unmake_list_label_t l_v_list)) ->
     red t_5 t' ->
     red (TmRecord ((app_list_label_t l_v_list (app_list_label_t (Cons_list_label_t l t_5 Nil_list_label_t) (app_list_label_t l'_t_list Nil_list_label_t))))) (TmRecord ((app_list_label_t l_v_list (app_list_label_t (Cons_list_label_t l t' Nil_list_label_t) (app_list_label_t l'_t_list Nil_list_label_t))))).

(* defns Jtype *)
Inductive typing : G -> t -> T -> Prop :=    (* defn typing *)
 | T_Var : forall (G5:G) (x:termvar) (T5:T),
      (bound  x   T5   G5 )  ->
     typing G5 (TmVar x) T5
 | T_Abs : forall (G5:G) (x:termvar) (T1:T) (t2:t) (T2:T),
     typing  (cons ( x , T1 )  G5 )  t2 T2 ->
     typing G5 (TmAbs x T1 t2) (TyArr T1 T2)
 | T_App : forall (G5:G) (t1 t2:t) (T12 T11:T),
     typing G5 t1 (TyArr T11 T12) ->
     typing G5 t2 T11 ->
     typing G5 (TmApp t1 t2) T12
 | T_Sub : forall (G5:G) (t5:t) (T5 S:T),
     typing G5 t5 S ->
     subtyping S T5 ->
     typing G5 t5 T5
 | T_Rcd : forall (l_t_T_list:list_label_t_T) (G5:G),
     (forall G5 t_ T_, In (G5,t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (G5,t_,T_) end) (unmake_list_label_t_T l_t_T_list)) -> (typing G5 t_ T_)) ->
      (Is_true (all_distinct eq_label (unmake_list'label  (make_list_label (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => l_) l_t_T_list)) )))  ->
     typing G5 (TmRecord (make_list_label_t (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,t_)) l_t_T_list))) (TyRecord (make_list_label_T (map_list_label_t_T (fun (l_:label) (t_:t) (T_:T) => (l_,T_)) l_t_T_list)))
 | T_Proj : forall (l_T_list:list_label_T) (j:index) (G5:G) (t1:t) (t103 t104:(label*T)),
          nth_list_label_T (j - 1) l_T_list = Some t103 ->
     nth_list_label_T (j - 1) l_T_list = Some t104 ->
typing G5 t1 (TyRecord l_T_list) ->
     typing G5 (TmProj t1 (match t104 with (l_,T_) => l_ end)) (match t103 with (l_,T_) => T_ end)
with subtyping : T -> T -> Prop :=    (* defn subtyping *)
 | S_Refl : forall (S:T),
     subtyping S S
 | S_Trans : forall (S T5 U:T),
     subtyping S U ->
     subtyping U T5 ->
     subtyping S T5
 | S_Arrow : forall (S1 S2 T1 T2:T),
     subtyping T1 S1 ->
     subtyping S2 T2 ->
     subtyping (TyArr S1 S2) (TyArr T1 T2)
 | S_Top : forall (S:T),
     subtyping S TyTop
 | S_RcdWidth : forall (l'_T'_list l_T_list:list_label_T),
     subtyping (TyRecord ((app_list_label_T l_T_list (app_list_label_T l'_T'_list Nil_list_label_T)))) (TyRecord l_T_list)
 | S_RcdDepth : forall (l_S_T_list:list_label_T_T),
     (forall S_ T_, In (S_,T_) (map (fun (pat_: (label*T*T)) => match pat_ with (l_,S_,T_) => (S_,T_) end) (unmake_list_label_T_T l_S_T_list)) -> (subtyping S_ T_)) ->
     subtyping (TyRecord (make_list_label_T (map_list_label_T_T (fun (l_:label) (S_:T) (T_:T) => (l_,S_)) l_S_T_list))) (TyRecord (make_list_label_T (map_list_label_T_T (fun (l_:label) (S_:T) (T_:T) => (l_,T_)) l_S_T_list)))
 | S_RcdPerm : forall (l_T_list k_S_list:list_label_T),
      TODO  ->
     subtyping (TyRecord k_S_list) (TyRecord l_T_list).


