/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_defn_repeated_nonterminal_1.ott -/




abbrev n := Nat

inductive a : Type where
  | a_tuple (_ : List a) : a
  deriving Inhabited
open a
/- definitions -/


/- defns J -/
/-- defn equal -/
inductive J_equal : a → a → Prop where
  | J_equal_unit : ∀ (a_a'_list : List (a × a)),
      (∀ a_a'_list_ ∈ a_a'_list, (fun (a_,a'_) => (J_equal a_ a'_)) a_a'_list_) →
      J_equal (a_tuple ((List.map (fun (a_,a'_) => a_) a_a'_list))) (a_tuple ((List.map (fun (a_,a'_) => a'_) a_a'_list)))



