/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_2.ott -/




abbrev i := Nat

inductive constant : Type where
  | CONST_unit : constant
  deriving Inhabited

inductive p : Type where
  | P_constant (constant5 : constant) : p
  deriving Inhabited

inductive e : Type where
  | E_constant (constant5 : constant) : e
  deriving Inhabited
open constant p e

/- - subrules - -/
def is_v_of_e (e5:e) : Bool :=
  match e5 with
  | (E_constant constant5) => (true)


/- definitions -/


/- defns Jred -/
/-- defn match -/
inductive JR_match : e → p → Prop where
  | JR_match_constant : ∀ (v_list : List e) (v_5 : e) (constant5 : constant),
      (is_v_of_e v_5) →
      (List.all v_list (fun v_ => is_v_of_e v_)) →
      (∀ v_list_ ∈ v_list, (fun v_ => (JR_match v_ (P_constant constant5))) v_list_) →
      JR_match v_5 (P_constant constant5)



