(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.2.ott *)
theory testRegr_test17_2
imports Main
begin

type_synonym "value_name" = "string"
type_synonym "index" = "nat"
datatype "a" = 
   a_x "value_name"  
 | a_A "a list"  
 | a_X "value_name list"  

primrec
aux_b_a_of_a_list :: "a list => value_name list"
and aux_b_a_of_a :: "a => value_name list"
where
"aux_b_a_of_a_list Nil = ([])"
| "aux_b_a_of_a_list (a_XXX#a_list_XXX) = ((aux_b_a_of_a a_XXX) @ (aux_b_a_of_a_list a_list_XXX))"
| "aux_b_a_of_a (a_x x) = ([x])"
| "aux_b_a_of_a (a_A (a_list)) = ((aux_b_a_of_a_list a_list))"
| "aux_b_a_of_a (a_X (x_list)) = (x_list)"


(** free variables *)
primrec
fv_a_list :: "a list => value_name list"
and fv_a :: "a => value_name list"
where
"fv_a_list Nil = ([])"
| "fv_a_list (a_XXX#a_list_XXX) = ((fv_a a_XXX) @ (fv_a_list a_list_XXX))"
| "fv_a (a_x x) = ([x])"
| "fv_a (a_A (a_list)) = ((fv_a_list a_list))"
| "fv_a (a_X (x_list)) = ([])"

(** library functions *)
primrec
list_assoc :: "'a => ('a*'b) list => 'b option"
where
  "list_assoc x0 Nil = None"
| "list_assoc x0 (Cons xy  xys) = (if x0=fst xy then Some (snd xy) else list_assoc x0 xys)"


(** substitutions *)
primrec
msubst_a_list :: "(value_name*a) list => a list => a list"
and msubst_a :: "(value_name*a) list => a => a"
where
"msubst_a_list sub Nil = (Nil)"
| "msubst_a_list sub (a_XXX#a_list_XXX) = ((msubst_a sub a_XXX) # (msubst_a_list sub a_list_XXX))"
| "msubst_a sub (a_x x) = ((case list_assoc x sub of None => (a_x x) | Some a_5 => a_5))"
| "msubst_a sub (a_A (a_list)) = (a_A (msubst_a_list sub a_list))"
| "msubst_a sub (a_X (x_list)) = (a_X x_list)"

primrec
subst_a_list :: "a => value_name => a list => a list"
and subst_a :: "a => value_name => a => a"
where
"subst_a_list a_5 x_5 Nil = (Nil)"
| "subst_a_list a_5 x_5 (a_XXX#a_list_XXX) = ((subst_a a_5 x_5 a_XXX) # (subst_a_list a_5 x_5 a_list_XXX))"
| "subst_a a_5 x_5 (a_x x) = ((if x=x_5 then a_5 else (a_x x)))"
| "subst_a a_5 x_5 (a_A (a_list)) = (a_A (subst_a_list a_5 x_5 a_list))"
| "subst_a a_5 x_5 (a_X (x_list)) = (a_X x_list)"


end



