/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test2.ott -/




abbrev ident := Nat

inductive T : Type where
  | T_integer : T
  | T_float : T
  deriving Inhabited

inductive E : Type where
  | E_empty : E
  | E_ident (E5 : E) (x : ident) (T5 : T) : E
  deriving Inhabited

inductive F : Type where
  | F_empty : F
  | F_ident (E5 : E) (x1 : ident) (x2 : ident) : F
  deriving Inhabited
open T E F


