(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_tuple_1.ott *)
theory testRegr_test_lists_coq_defn_tuple_1
imports Main
begin

type_synonym "i" = "UNDEFINED"
type_synonym "x" = "UNDEFINED"
datatype "foo" = 
   foo_foo  

(** definitions *)
(* defns J *)
inductive J_wibble :: "(foo*foo) list \<Rightarrow> bool"
where
(* defn wibble *)


end



