(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/bool.ott *)
theory testRegr_sys_untyped
imports Main
begin

(** warning: the backend selected ignores the file structure informations *)
(** syntax *)
datatype "t" =  \<comment> \<open>terms:\<close>
   TmTrue   \<comment> \<open>constant true\<close>
 | TmFalse   \<comment> \<open>constant false\<close>
 | TmIf "t" "t" "t"   \<comment> \<open>conditional\<close>


(** auxiliary functions on the new list types *)
(** library functions *)
(** subrules *)
primrec
is_v_of_t :: "t => bool"
where
"is_v_of_t TmTrue = ((True))"
| "is_v_of_t TmFalse = ((True))"
| "is_v_of_t (TmIf t1 t2 t3) = (False)"

(** auxiliary functions *)
(** free variables *)
(** substitutions *)
(** context application *)

(** definitions *)
(* defns Jop *)
inductive red :: "t \<Rightarrow> t \<Rightarrow> bool"
where
(* defn red *)

E_IfTrueI: "red ((TmIf TmTrue t2 t3)) (t2)"

| E_IfFalseI: "red ((TmIf TmFalse t2 t3)) (t3)"

| E_IfI: "\<lbrakk>red (t1) (t1')\<rbrakk> \<Longrightarrow>
red ((TmIf t1 t2 t3)) ((TmIf t1' t2 t3))"



end
