/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4c.ott -/




abbrev index := Nat
abbrev x := Nat

mutual
inductive a : Type where
  | a_Ax (x5 : x) : a
  | a_AA : a
  | a_a (a5 : a) : a
  | a_C (_ : list_a_a_a) : a
  | a_CC (_ : list_a_a_a) : a
  deriving Inhabited
inductive list_a_a_a : Type where
  | Nil_list_a_a_a : list_a_a_a
  | Cons_list_a_a_a (av : a) (av : a) (av : a) (_ : list_a_a_a) : list_a_a_a
  deriving Inhabited
end
open list_a_a_a a
def map_list_a_a_a {A : Type} (f : a -> a -> a -> A) (l : list_a_a_a) : List A :=
  match l with
  | Nil_list_a_a_a => []
  | Cons_list_a_a_a h0 h1 h2 tl_ => (f h0 h1 h2) :: (map_list_a_a_a f tl_)

def make_list_a_a_a (l : List (a × a × a)) : list_a_a_a :=
  match l with
  | [] => Nil_list_a_a_a
  | (h0,h1,h2) :: tl_ => Cons_list_a_a_a h0 h1 h2 (make_list_a_a_a tl_)

def unmake_list_a_a_a (l : list_a_a_a) : List (a × a × a) :=
  match l with
  | Nil_list_a_a_a => []
  | Cons_list_a_a_a h0 h1 h2 tl_ => (h0,h1,h2) :: (unmake_list_a_a_a tl_)

def nth_list_a_a_a (n : Nat) (l : list_a_a_a) : Option (a × a × a) :=
  match n, l with
  | 0, Cons_list_a_a_a h0 h1 h2 tl_ => some (h0,h1,h2)
  | 0, _ => none
  | _+1, Nil_list_a_a_a => none
  | k+1, Cons_list_a_a_a _ _ _ tl_ => nth_list_a_a_a k tl_

def app_list_a_a_a (l m : list_a_a_a) : list_a_a_a :=
  match l with
  | Nil_list_a_a_a => m
  | Cons_list_a_a_a h0 h1 h2 tl_ => Cons_list_a_a_a h0 h1 h2 (app_list_a_a_a tl_ m)



/- - subrules - -/
mutual
def is_av_of_a_a'_a''_list (l:list_a_a_a) : Bool :=
  match l with
  | Nil_list_a_a_a => true
  | Cons_list_a_a_a a_ a'_ a''_ a_a'_a''_list_ => ((is_av_of_a a_) /\ (is_av_of_a a'_) /\ (is_av_of_a a''_)) && (is_av_of_a_a'_a''_list a_a'_a''_list_)
def is_av_of_a (a_6:a) : Bool :=
  match a_6 with
  | (a_Ax x5) => false
  | a_AA => false
  | (a_a a5) => (true)
  | (a_C a_a'_a''_list) => (is_av_of_a_a'_a''_list a_a'_a''_list)
  | (a_CC a_a'_a''_list) => (is_av_of_a_a'_a''_list a_a'_a''_list)
end


/- - free variables - -/
mutual
def fv_a_a_a_list (l:list_a_a_a) : List x :=
  match l with
  | Nil_list_a_a_a => []
  | Cons_list_a_a_a a_ a'_ a''_ a_a'_a''_list_ => ((fv_a a_) ++ (fv_a a'_) ++ (fv_a a''_)) ++ (fv_a_a_a_list a_a'_a''_list_)
def fv_a (a_6:a) :  List x :=
  match a_6 with
  | (a_Ax x5) => [x5]
  | a_AA => []
  | (a_a a5) => (fv_a a5)
  | (a_C a_a'_a''_list) => (fv_a_a_a_list a_a'_a''_list)
  | (a_CC a_a'_a''_list) => (fv_a_a_a_list a_a'_a''_list)
end

/- - library functions - -/
def list_assoc {α β : Type} [DecidableEq α] (l:List (α × β)) (x:α) : Option β :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def su_a_a_a_list (a_6:a) (x_6:x) (a__7:list_a_a_a) : list_a_a_a :=
  match a__7 with
  | Nil_list_a_a_a => Nil_list_a_a_a
  | Cons_list_a_a_a a1 a2 a3 a_a_a_tl => Cons_list_a_a_a (su_a a_6 x_6 a1) (su_a a_6 x_6 a2) (su_a a_6 x_6 a3) (su_a_a_a_list a_6 x_6 a_a_a_tl)
def su_a (a_6:a) (x_6:x) (a__7:a) : a :=
  match a__7 with
  | (a_Ax x5) => (if x5=x_6 then a_6 else (a_Ax x5))
  | a_AA => a_AA 
  | (a_a a5) => a_a (su_a a_6 x_6 a5)
  | (a_C a_a'_a''_list) => a_C (su_a_a_a_list a_6 x_6 a_a'_a''_list)
  | (a_CC a_a'_a''_list) => a_CC (su_a_a_a_list a_6 x_6 a_a'_a''_list)
end

mutual
def sum_a_a_a_list (sub:List (x×a)) (a__7:list_a_a_a) : list_a_a_a :=
  match a__7 with
  | Nil_list_a_a_a => Nil_list_a_a_a
  | Cons_list_a_a_a a1 a2 a3 a_a_a_tl => Cons_list_a_a_a (sum_a sub a1) (sum_a sub a2) (sum_a sub a3) (sum_a_a_a_list sub a_a_a_tl)
def sum_a (sub:List (x×a)) (a__7:a) : a :=
  match a__7 with
  | (a_Ax x5) => (match list_assoc sub x5 with | none => (a_Ax x5)| some a_6 => a_6 )
  | a_AA => a_AA 
  | (a_a a5) => a_a (sum_a sub a5)
  | (a_C a_a'_a''_list) => a_C (sum_a_a_a_list sub a_a'_a''_list)
  | (a_CC a_a'_a''_list) => a_CC (sum_a_a_a_list sub a_a'_a''_list)
end



