(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4b.ott *)

From Stdlib Require Import Arith.
From Stdlib Require Import Bool.
From Stdlib Require Import List.
Require Import Ott.ott_list_core.


Definition index : Set := nat.
Lemma eq_index: forall (x y : index), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_index : ott_coq_equality.
Definition x : Set := nat.
Lemma eq_x: forall (x' y : x), {x' = y} + {x' <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_x : ott_coq_equality.

Inductive a : Set := 
 | a_Ax (x5:x)
 | a_a (a5:a)
 | a_C (_:list a)
 | a_CC (_:list a).
(** induction principles *)
Section a_rect.

Variables
  (P_a : a -> Prop)
  (P_list_a : list a -> Prop).

Hypothesis
  (H_a_Ax : forall (x5:x), P_a (a_Ax x5))
  (H_a_a : forall (a5:a), P_a a5 -> P_a (a_a a5))
  (H_a_C : forall (a_list:list a), P_list_a a_list -> P_a (a_C a_list))
  (H_a_CC : forall (a_list:list a), P_list_a a_list -> P_a (a_CC a_list))
  (H_list_a_nil : P_list_a nil)
  (H_list_a_cons : forall (a0:a), P_a a0 -> forall (a_l:list a), P_list_a a_l -> P_list_a (cons a0 a_l)).

Fixpoint a_ott_ind (n:a) : P_a n :=
  match n as x return P_a x with
  | (a_Ax x5) => H_a_Ax x5
  | (a_a a5) => H_a_a a5 (a_ott_ind a5)
  | (a_C a_list) => H_a_C a_list (((fix a_list_ott_ind (a_l:list a) : P_list_a a_l := match a_l as x return P_list_a x with nil => H_list_a_nil | cons a1 xl => H_list_a_cons a1(a_ott_ind a1)xl (a_list_ott_ind xl) end)) a_list)
  | (a_CC a_list) => H_a_CC a_list (((fix a_list_ott_ind (a_l:list a) : P_list_a a_l := match a_l as x return P_list_a x with nil => H_list_a_nil | cons a2 xl => H_list_a_cons a2(a_ott_ind a2)xl (a_list_ott_ind xl) end)) a_list)
end.

End a_rect.
Fixpoint aux_b_a_of_a (a_6:a) : list x :=
  match a_6 with
  | (a_Ax x5) => (cons x5 nil)
  | (a_a a5) => (aux_b_a_of_a a5)
  | (a_C a_list) => (flat_map (fun (a_:a) => aux_b_a_of_a a_) a_list)
  | (a_CC a_list) => (flat_map (fun (a_:a) => aux_b_a_of_a a_) a_list)
end.


(** subrules *)
Fixpoint is_av_of_a (a_6:a) : bool :=
  match a_6 with
  | (a_Ax x5) => false
  | (a_a a5) => (true)
  | (a_C a_list) => ((forall_list (fun (a_:a) => (is_av_of_a a_)) a_list))
  | (a_CC a_list) => ((forall_list (fun (a_:a) => (is_av_of_a a_)) a_list))
end.


(** free variables *)
Fixpoint ftv_a (a_6:a) : list x :=
  match a_6 with
  | (a_Ax x5) => (cons x5 nil)
  | (a_a a5) => ((ftv_a a5))
  | (a_C a_list) => ((flat_map (fun (a_:a) => (ftv_a a_)) a_list))
  | (a_CC a_list) => ((flat_map (fun (a_:a) => (ftv_a a_)) a_list))
end.

(** library functions *)
Fixpoint list_assoc A B (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list (A*B)) {struct l} : option B :=
  match l with
  | nil => None
  | cons (a,b) t => if (eq a x) then Some b else list_assoc A B eq x t
end.
Arguments list_assoc [A B] _ _ _.


(** substitutions *)
Fixpoint msubst_a (sub:list (x*a)) (a__7:a) {struct a__7} : a :=
  match a__7 with
  | (a_Ax x5) => (match list_assoc eq_x x5 sub with None => (a_Ax x5) | Some a_6 => a_6 end)
  | (a_a a5) => a_a (msubst_a sub a5)
  | (a_C a_list) => a_C (map (fun (a_:a) => (msubst_a sub a_)) a_list)
  | (a_CC a_list) => a_CC (map (fun (a_:a) => (msubst_a sub a_)) a_list)
end.

Fixpoint subst_a (a_6:a) (x_6:x) (a__7:a) {struct a__7} : a :=
  match a__7 with
  | (a_Ax x5) => (if eq_x x5 x_6 then a_6 else (a_Ax x5))
  | (a_a a5) => a_a (subst_a a_6 x_6 a5)
  | (a_C a_list) => a_C (map (fun (a_:a) => (subst_a a_6 x_6 a_)) a_list)
  | (a_CC a_list) => a_CC (map (fun (a_:a) => (subst_a a_6 x_6 a_)) a_list)
end.



