(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test13b.ott *)
(* to compile: Holmake testRegr_test13bTheory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test13b";

Type terminal = ``:string``
Type metavarroot = ``:string``
Type nontermroot = ``:string``
Type suffix = ``:string``
Type auxfn = ``:string``
Type prodname = ``:string``
Type index = ``:num``
val _ = Hol_datatype ` 
metavar = 
   mv_1 of metavarroot => suffix
`;
val _ = Hol_datatype ` 
nonterm = 
   nt_1 of nontermroot => suffix
`;
val _ = Hol_datatype ` 
mse = 
   mse_mv of metavar
 | mse_f of auxfn => nonterm
 | mse_union of mse => mse
 | mse_empty
`;
val _ = Hol_datatype ` 
element = 
   e_tm of terminal
 | e_mv of metavar
 | e_nt of nonterm
`;
val _ = Hol_datatype ` 
bindspec = 
   bs_bind of mse => nonterm
 | bs_auxfn of auxfn => mse
`;
val _ = Hol_datatype ` 
prod = 
   p_1 of element list => prodname => bindspec list
`;
val _ = Hol_datatype ` 
rule = 
   r_1 of nontermroot => prod list
`;
val _ = Hol_datatype ` 
auxfn_type = 
   at_1 of nontermroot list => metavarroot
`;
val _ = Hol_datatype ` 
grammar_rules = 
   g_1 of rule list
`;
val _ = Hol_datatype ` 
auxfn_type_env = 
   ate_1
 | ate_2 of auxfn_type_env => auxfn => auxfn_type
`;
val _ = Hol_datatype ` 
grammar_type = 
   gt_1 of nontermroot list
`;
(** definitions *)

(* defns Jtype *)
Inductive Jtype:
(* defn FF *)

[FF_1:] (! (Phi:auxfn_type_env) (f:auxfn) (at:auxfn_type) .
(clause_name "FF_1")
 ==> 
( ( FF (ate_2 Phi f at) f at )))

[FF_2:] (! (Phi:auxfn_type_env) (f':auxfn) (at':auxfn_type) (f:auxfn) (at:auxfn_type) .
(clause_name "FF_2") /\
(( ( FF Phi f at )) /\
( ~(   (   ( f  =  f' )   )   ) ))
 ==> 
( ( FF (ate_2 Phi f' at') f at )))

(* defn Mse *)

[Mse_1:] (! (e_list:element list) (Phi:auxfn_type_env) (mvr:metavarroot) .
(clause_name "Mse_1")
 ==> 
( ( Mse Phi (e_list) mse_empty mvr )))

[Mse_2:] (! (e_list:element list) (j:index) (Phi:auxfn_type_env) (mvr:metavarroot) (suff:suffix) .
(clause_name "Mse_2") /\
(( (  ((\ e_ . e_) (EL  (j - 1) e_list))   =  (e_mv (mv_1 mvr suff)) ) ))
 ==> 
( ( Mse Phi (e_list) (mse_mv (mv_1 mvr suff)) mvr )))

[Mse_3:] (! (ntr_list:nontermroot list) (e_list:element list) (j:index) (i:index) (Phi:auxfn_type_env) (f:auxfn) (nt:nonterm) (mvr:metavarroot) (suff:suffix) .
(clause_name "Mse_3") /\
(( ( FF Phi f (at_1 (ntr_list) mvr) )) /\
( (  ((\ e_ . e_) (EL  (j - 1) e_list))   =  (e_nt nt) ) ) /\
( ( nt  =  (nt_1  ((\ ntr_ . ntr_) (EL  (i - 1) ntr_list))  suff) ) ))
 ==> 
( ( Mse Phi (e_list) (mse_f f nt) mvr )))

[Mse_4:] (! (e_list:element list) (Phi:auxfn_type_env) (mse:mse) (mse':mse) (mvr:metavarroot) .
(clause_name "Mse_4") /\
(( ( Mse Phi (e_list) mse mvr )) /\
( ( Mse Phi (e_list) mse' mvr )))
 ==> 
( ( Mse Phi (e_list) (mse_union mse mse') mvr )))

(* defn Bs *)

[Bs_1:] (! (e_list:element list) (j:index) (Phi:auxfn_type_env) (mse:mse) (nt:nonterm) (mvr:metavarroot) .
(clause_name "Bs_1") /\
(( ( Mse Phi (e_list) mse mvr )) /\
( (  ((\ e_ . e_) (EL  (j - 1) e_list))   =  (e_nt nt) ) ))
 ==> 
( ( Bs Phi (e_list) (bs_bind mse nt) )))

[Bs_2:] (! (e_ntr_list:(element#nontermroot) list) (Phi:auxfn_type_env) (f:auxfn) (mse:mse) (mvr:metavarroot) .
(clause_name "Bs_2") /\
(( ( Mse Phi ((MAP (\(e_,ntr_) . e_) e_ntr_list)) mse mvr )) /\
( ( FF Phi f (at_1 ((MAP (\(e_,ntr_) . ntr_) e_ntr_list)) mvr) )))
 ==> 
( ( Bs Phi ((MAP (\(e_,ntr_) . e_) e_ntr_list)) (bs_auxfn f mse) )))

(* defn Prod *)

[Prod_1:] (! (bs_list:bindspec list) (e_list:element list) (Phi:auxfn_type_env) (prodd:prod) (i:index) (m:index) (prodname:prodname) .
(clause_name "Prod_1") /\
(( (! i . (1<= i  /\ i<= m ) ==>   ( Bs Phi (e_list)  ((\ bs_ . bs_) (EL  (i - 1) bs_list))  ) ) ) /\
( ( prodd  =  (p_1 (e_list) prodname (bs_list)) ) ))
 ==> 
( ( Prod Phi prodd )))

(* defn Rule *)

[Rule_1:] (! (prodd_list:prod list) (Phi:auxfn_type_env) (rule:rule) (i:index) (m:index) (ntr:nontermroot) .
(clause_name "Rule_1") /\
(( (! i . (1<= i  /\ i<= m ) ==>   ( Prod Phi  ((\ prodd_ . prodd_) (EL  (i - 1) prodd_list))  ) ) ) /\
( ( rule  =  (r_1 ntr (prodd_list)) ) ))
 ==> 
( ( Rule Phi rule )))

(* defn Grammar *)

[Grammar_1:] (! (prodd'_list:prod list) (rule_prodd_list:(rule#prod) list) (Phi:auxfn_type_env) (grammar_rules:grammar_rules) (i:index) (m:index) (j:index) (n:index) (ntr:nontermroot) .
(clause_name "Grammar_1") /\
(( (! i . (1<= i  /\ i<= m ) ==>   ( Rule Phi  ((\ (rule_,prodd_) . rule_) (EL  (i - 1) rule_prodd_list))  ) ) ) /\
( ( grammar_rules  =  (g_1 ((MAP (\(rule_,prodd_) . rule_) rule_prodd_list))) ) ) /\
( (! i . (1<= i  /\ i<= m ) ==>   (! j . (1<= j  /\ i<= n ) ==>   (   (  (   (  (  ((\ (rule_,prodd_) . rule_) (EL  (i - 1) rule_prodd_list))   =  (r_1 ntr ((MAP (\(rule_,prodd_) . prodd_) rule_prodd_list))) )   /\   (  ((\ (rule_,prodd_) . rule_) (EL  (j - 1) rule_prodd_list))   =  (r_1 ntr (prodd'_list)) )  )   )   ==>   ( i  =  j )  )   )  )  ) ))
 ==> 
( ( Grammar Phi grammar_rules )))
End

val _ = export_theory ();



