(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/bool.ott /home/pes20/claude-home/ott/regression/../examples/tapl/bool_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/arrow_typing.ott *)
theory testRegr_sys_tybool
imports Main
begin

(** warning: the backend selected ignores the file structure informations *)
(** syntax *)
type_synonym "termvar" = "string"
datatype "T" =  \<comment> \<open>types:\<close>
   TyBool   \<comment> \<open>type of booleans\<close>
 | TyArr "T" "T"   \<comment> \<open>type of functions\<close>

type_synonym "G" = "(termvar*T) list"
datatype "t" =  \<comment> \<open>terms:\<close>
   TmTrue   \<comment> \<open>constant true\<close>
 | TmFalse   \<comment> \<open>constant false\<close>
 | TmIf "t" "t" "t"   \<comment> \<open>conditional\<close>
 | TmVar "termvar"   \<comment> \<open>variable\<close>
 | TmAbs "termvar" "T" "t"   \<comment> \<open>abstraction\<close>
 | TmApp "t" "t"   \<comment> \<open>application\<close>


(** auxiliary functions on the new list types *)
(** library functions *)
primrec
list_minus :: "'a list => 'a list => 'a list"
where
  "list_minus Nil ys = Nil"
| "list_minus (Cons x xs) ys = (if Not(x : set ys) then Cons x (list_minus xs ys) else list_minus xs ys)"

(** subrules *)
primrec
is_v_of_t :: "t => bool"
where
"is_v_of_t TmTrue = ((True))"
| "is_v_of_t TmFalse = ((True))"
| "is_v_of_t (TmIf t1 t2 t3) = (False)"
| "is_v_of_t (TmVar x) = (False)"
| "is_v_of_t (TmAbs x T t) = ((True))"
| "is_v_of_t (TmApp t1 t2) = (False)"

(** auxiliary functions *)
(** free variables *)
primrec
fv_t :: "t => termvar list"
where
"fv_t TmTrue = ([])"
| "fv_t TmFalse = ([])"
| "fv_t (TmIf t1 t2 t3) = ((fv_t t1) @ (fv_t t2) @ (fv_t t3))"
| "fv_t (TmVar x) = ([x])"
| "fv_t (TmAbs x T t) = ((list_minus (fv_t t) [x]))"
| "fv_t (TmApp t1 t2) = ((fv_t t1) @ (fv_t t2))"

(** substitutions *)
primrec
subst_t :: "t => termvar => t => t"
where
"subst_t t_5 x5 TmTrue = (TmTrue )"
| "subst_t t_5 x5 TmFalse = (TmFalse )"
| "subst_t t_5 x5 (TmIf t1 t2 t3) = (TmIf (subst_t t_5 x5 t1) (subst_t t_5 x5 t2) (subst_t t_5 x5 t3))"
| "subst_t t_5 x5 (TmVar x) = ((if x=x5 then t_5 else (TmVar x)))"
| "subst_t t_5 x5 (TmAbs x T t) = (TmAbs x T (if x5 : set [x] then t else (subst_t t_5 x5 t)))"
| "subst_t t_5 x5 (TmApp t1 t2) = (TmApp (subst_t t_5 x5 t1) (subst_t t_5 x5 t2))"

(** context application *)

(** definitions *)
(* defns Jop *)
inductive red :: "t \<Rightarrow> t \<Rightarrow> bool"
where
(* defn red *)

E_IfTrueI: "red ((TmIf TmTrue t2 t3)) (t2)"

| E_IfFalseI: "red ((TmIf TmFalse t2 t3)) (t3)"

| E_IfI: "\<lbrakk>red (t1) (t1')\<rbrakk> \<Longrightarrow>
red ((TmIf t1 t2 t3)) ((TmIf t1' t2 t3))"

| E_App1I: "\<lbrakk>red (t1) (t1')\<rbrakk> \<Longrightarrow>
red ((TmApp t1 t2)) ((TmApp t1' t2))"

| E_App2I: "\<lbrakk>is_v_of_t v1 ;
red (t2) (t2')\<rbrakk> \<Longrightarrow>
red ((TmApp v1 t2)) ((TmApp v1 t2'))"

| E_AppAbsI: "\<lbrakk>is_v_of_t v2\<rbrakk> \<Longrightarrow>
red ((TmApp  (TmAbs x T t12)  v2)) ( (subst_t  v2   x   t12 ) )"
(* defns Jtype *)
inductive typing :: "G \<Rightarrow> t \<Rightarrow> T \<Rightarrow> bool"
where
(* defn typing *)

T_TrueI: "typing (G) (TmTrue) (TyBool)"

| T_FalseI: "typing (G) (TmFalse) (TyBool)"

| T_IfI: "\<lbrakk>typing (G) (t1) (TyBool) ;
typing (G) (t2) (T) ;
typing (G) (t3) (T)\<rbrakk> \<Longrightarrow>
typing (G) ((TmIf t1 t2 t3)) (T)"

| T_VarI: "\<lbrakk> ? G1 G2.  G  = G1 @ ( x , T )#G2 &  x ~:fst ` set G1 \<rbrakk> \<Longrightarrow>
typing (G) ((TmVar x)) (T)"

| T_AbsI: "\<lbrakk>typing ( ( x , T1 )# G ) (t2) (T2)\<rbrakk> \<Longrightarrow>
typing (G) ((TmAbs x T1 t2)) ((TyArr T1 T2))"

| T_AppI: "\<lbrakk>typing (G) (t1) ((TyArr T11 T12)) ;
typing (G) (t2) (T11)\<rbrakk> \<Longrightarrow>
typing (G) ((TmApp t1 t2)) (T12)"



end
