(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test-pottier1.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


Definition termvar : Set := nat. (* term variable *)
Lemma eq_termvar: forall (x y : termvar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_termvar : ott_coq_equality.

Inductive t : Set := 
 | t_Var (x:termvar)
 | t_Lam (x:termvar) (t5:t)
 | t_App (t1:t) (t2:t).
Fixpoint aux_bv_t_of_t (t_6:t) : list termvar :=
  match t_6 with
  | (t_Var x) => nil
  | (t_Lam x t5) => (app (cons x nil) (aux_bv_t_of_t t5))
  | (t_App t1 t2) => (app (aux_bv_t_of_t t1) (aux_bv_t_of_t t2))
end.

(** library functions *)
Fixpoint list_mem A (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list A) {struct l} : bool :=
  match l with
  | nil => false
  | cons h t => if eq h x then true else list_mem A eq x t
end.
Arguments list_mem [A] _ _ _.


(** substitutions *)
Fixpoint subst_t (t_6:t) (x5:termvar) (t__7:t) {struct t__7} : t :=
  match t__7 with
  | (t_Var x) => (if eq_termvar x x5 then t_6 else (t_Var x))
  | (t_Lam x t5) => t_Lam x (if list_mem eq_termvar x5 (cons x nil) then t5 else (subst_t t_6 x5 t5))
  | (t_App t1 t2) => t_App (subst_t t_6 x5 t1) (subst_t t_6 x5 t2)
end.



