(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_subrule_3.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


Definition i : Set := nat.
Definition ident : Set := nat.
Lemma eq_ident: forall (x y : ident), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_ident : ott_coq_equality.

Inductive constant : Set := 
 | CONST_unit : constant.

Inductive expr : Set := 
 | Expr_constant (constant5:constant).

Inductive substs_x : Set := 
 | substs_x_xs (_:list (ident*expr)).

(** subrules *)
Definition is_valu_of_expr (e5:expr) : bool :=
  match e5 with
  | (Expr_constant constant5) => (true)
end.

(* definitions *)

(* defns Jred *)
Inductive JR_match : expr -> substs_x -> Prop :=    (* defn match *)
 | JR_match_alias : forall (x_v_list:list (ident*expr)) (x:ident) (v:expr),
     Is_true (is_valu_of_expr v) ->
     (Forall (fun (tmp_:(ident*expr)) => match tmp_ with (x_,v_) => Is_true (is_valu_of_expr v_) end) x_v_list) ->
     JR_match v (substs_x_xs x_v_list) ->
     JR_match v (substs_x_xs ((app x_v_list (app (cons (x,v) nil) nil))))
with JR_matches : list expr -> substs_x -> Prop :=    (* defn matches *)
 | JR_matches_and : forall (v_list:list expr) (substs_x5:substs_x),
     (forall v_, In (v_) (map (fun (v_ : expr) => (v_)) v_list) -> (JR_match v_ substs_x5)) ->
     JR_matches v_list substs_x5.


