(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.3.ott *)
(* to compile: Holmake testRegr_test17_3Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test17_3";

Type value_name = ``:string``
Type index = ``:num``
val _ = Hol_datatype ` 
a = 
   a_x of value_name
 | a_A of a list
 | a_X of value_name list
`;
val _ = Hol_datatype ` 
c = 
   c_C of a => a
`;
val _ = ottDefine "aux_b_a_of_a" `
    ( aux_b_a_of_a (a_x x) = [x])
/\  ( aux_b_a_of_a (a_A (a_list)) = (FLAT (MAP aux_b_a_of_a (a_list))))
/\  ( aux_b_a_of_a (a_X (x_list)) = x_list)
`;

(** free variables *)
val _ = ottDefine "fv_a" `
    ( fv_a (a_x x) = [x])
/\  ( fv_a (a_A (a_list)) = (FLAT (MAP (\a_. (fv_a a_)) a_list)))
/\  ( fv_a (a_X (x_list)) = [])
`;

val _ = ottDefine "fv_c" `
    ( fv_c (c_C a a') = (fv_a a) ++ (list_minus (fv_a a') (aux_b_a_of_a a)))
`;

(** substitutions *)
val _ = ottDefine "msubst_a" `
    ( msubst_a sub (a_x x) = (case list_assoc x sub of NONE => (a_x x) | SOME a_5 => a_5))
/\  ( msubst_a sub (a_A (a_list)) = a_A (MAP (\a_. (msubst_a sub a_)) a_list))
/\  ( msubst_a sub (a_X (x_list)) = a_X x_list)
`;

val _ = ottDefine "subst_a" `
    ( subst_a a_5 x_5 (a_x x) = (if x=x_5 then a_5 else (a_x x)))
/\  ( subst_a a_5 x_5 (a_A (a_list)) = a_A (MAP (\a_. (subst_a a_5 x_5 a_)) a_list))
/\  ( subst_a a_5 x_5 (a_X (x_list)) = a_X x_list)
`;

val _ = ottDefine "msubst_c" `
    ( msubst_c sub (c_C a a') = c_C (msubst_a sub a) (msubst_a (FILTER (\(x5,a5). ~(MEM x5 (aux_b_a_of_a a))) sub) a'))
`;

val _ = ottDefine "subst_c" `
    ( subst_c a5 x5 (c_C a a') = c_C (subst_a a5 x5 a) (if MEM x5 (aux_b_a_of_a a) then a' else (subst_a a5 x5 a')))
`;

val _ = export_theory ();



