(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_defn_list_form_1.ott *)

type i = UNDEFINED
type x = UNDEFINED

type 
e = 
   E_tuple of (x) list

(** definitions *)


