(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test16.3.ott *)
(* to compile: Holmake testRegr_test16_3Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test16_3";

Type value_name = ``:string``
val _ = Hol_datatype ` 
a = 
   a_x of value_name
 | a_A of a => a
 | a_C
`;
val _ = ottDefine "aux_f_a_of_a" `
    ( aux_f_a_of_a (a_x x) = [x])
/\  ( aux_f_a_of_a (a_A a1 a2) = ((aux_f_a_of_a a1) ++ (aux_g_a_of_a a2)))
/\  ( aux_f_a_of_a a_C = [])
/\  ( aux_g_a_of_a (a_x x) = [x])
/\  ( aux_g_a_of_a (a_A a1 a2) = (aux_f_a_of_a a1))
/\  ( aux_g_a_of_a a_C = [])
`;

(** substitutions *)
val _ = ottDefine "msubst_a" `
    ( msubst_a sub (a_x x) = (case list_assoc x sub of NONE => (a_x x) | SOME a_5 => a_5))
/\  ( msubst_a sub (a_A a1 a2) = a_A (msubst_a sub a1) (msubst_a sub a2))
/\  ( msubst_a sub a_C = a_C )
`;

val _ = ottDefine "subst_a" `
    ( subst_a a_5 x5 (a_x x) = (if x=x5 then a_5 else (a_x x)))
/\  ( subst_a a_5 x5 (a_A a1 a2) = a_A (subst_a a_5 x5 a1) (subst_a a_5 x5 a2))
/\  ( subst_a a_5 x5 a_C = a_C )
`;

val _ = export_theory ();



