(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4d.ott *)
theory testRegr_test15_4d
imports Main
begin

type_synonym "index" = "nat"
type_synonym "x" = "nat"
datatype "a" = 
   a_Ax "x"  
 | a_AA  
 | a_a "a"  
 | a_C "a list" "a list"  
 | a_CC "a list" "a list"  

primrec
aux_b_a_of_a_list_a_C :: "a list => x list"
and aux_b_a_of_a_list :: "a list => x list"
and aux_b_a_of_a :: "a => x list"
and aux_b_a_of_a_list_a_CC1 :: "a list => x list"
and aux_b_a_of_a_list_a_CC :: "a list => x list"
where
"aux_b_a_of_a_list_a_C Nil = ([])"
| "aux_b_a_of_a_list_a_C (a_XXX#a_list_XXX) = ((aux_b_a_of_a a_XXX) @ (aux_b_a_of_a_list_a_C a_list_XXX))"
| "aux_b_a_of_a_list Nil = ([])"
| "aux_b_a_of_a_list (a_XXX#a_list_XXX) = ((aux_b_a_of_a a_XXX) @ (aux_b_a_of_a_list a_list_XXX))"
| "aux_b_a_of_a (a_Ax x) = ([x])"
| "aux_b_a_of_a a_AA = ([])"
| "aux_b_a_of_a (a_a pluto) = ((aux_b_a_of_a pluto))"
| "aux_b_a_of_a (a_C (pluto_list) (pluto'_list)) = ((aux_b_a_of_a_list pluto_list) @ (aux_b_a_of_a_list_a_C pluto'_list))"
| "aux_b_a_of_a (a_CC (pluto_list) (pluto'_list)) = ((aux_b_a_of_a_list_a_CC pluto_list) @ (aux_b_a_of_a_list_a_CC1 pluto'_list))"
| "aux_b_a_of_a_list_a_CC1 Nil = ([])"
| "aux_b_a_of_a_list_a_CC1 (a_XXX#a_list_XXX) = ((aux_b_a_of_a a_XXX) @ (aux_b_a_of_a_list_a_CC1 a_list_XXX))"
| "aux_b_a_of_a_list_a_CC Nil = ([])"
| "aux_b_a_of_a_list_a_CC (a_XXX#a_list_XXX) = ((aux_b_a_of_a a_XXX) @ (aux_b_a_of_a_list_a_CC a_list_XXX))"


(** subrules *)
primrec
is_av_of_pluto_list_a_CC1 :: "a list => bool"
and is_av_of_pluto_list_a_CC :: "a list => bool"
and is_av_of_pluto_list_a_C1 :: "a list => bool"
and is_av_of_pluto_list_a_C :: "a list => bool"
and is_av_of_a :: "a => bool"
where
"is_av_of_pluto_list_a_CC1 Nil = (True)"
| "is_av_of_pluto_list_a_CC1 (pluto'_XXX#pluto'_list_XXX) = (((is_av_of_a pluto'_XXX) & (is_av_of_pluto_list_a_CC1 pluto'_list_XXX)))"
| "is_av_of_pluto_list_a_CC Nil = (True)"
| "is_av_of_pluto_list_a_CC (pluto_XXX#pluto_list_XXX) = (((is_av_of_a pluto_XXX) & (is_av_of_pluto_list_a_CC pluto_list_XXX)))"
| "is_av_of_pluto_list_a_C1 Nil = (True)"
| "is_av_of_pluto_list_a_C1 (pluto'_XXX#pluto'_list_XXX) = (((is_av_of_a pluto'_XXX) & (is_av_of_pluto_list_a_C1 pluto'_list_XXX)))"
| "is_av_of_pluto_list_a_C Nil = (True)"
| "is_av_of_pluto_list_a_C (pluto_XXX#pluto_list_XXX) = (((is_av_of_a pluto_XXX) & (is_av_of_pluto_list_a_C pluto_list_XXX)))"
| "is_av_of_a (a_Ax x) = (False)"
| "is_av_of_a a_AA = (False)"
| "is_av_of_a (a_a pluto) = ((True))"
| "is_av_of_a (a_C (pluto_list) (pluto'_list)) = ((is_av_of_pluto_list_a_C pluto_list & is_av_of_pluto_list_a_C1 pluto'_list))"
| "is_av_of_a (a_CC (pluto_list) (pluto'_list)) = ((is_av_of_pluto_list_a_CC pluto_list & is_av_of_pluto_list_a_CC1 pluto'_list))"


(** free variables *)
primrec
fv_pluto_list_a_CC1 :: "a list => x list"
and fv_pluto_list_a_CC :: "a list => x list"
and fv_pluto_list_a_C1 :: "a list => x list"
and fv_pluto_list_a_C :: "a list => x list"
and fv_pluto :: "a => x list"
where
"fv_pluto_list_a_CC1 Nil = ([])"
| "fv_pluto_list_a_CC1 (pluto'_XXX#pluto'_list_XXX) = ((fv_pluto pluto'_XXX) @ (fv_pluto_list_a_CC1 pluto'_list_XXX))"
| "fv_pluto_list_a_CC Nil = ([])"
| "fv_pluto_list_a_CC (pluto_XXX#pluto_list_XXX) = ((fv_pluto pluto_XXX) @ (fv_pluto_list_a_CC pluto_list_XXX))"
| "fv_pluto_list_a_C1 Nil = ([])"
| "fv_pluto_list_a_C1 (pluto'_XXX#pluto'_list_XXX) = ((fv_pluto pluto'_XXX) @ (fv_pluto_list_a_C1 pluto'_list_XXX))"
| "fv_pluto_list_a_C Nil = ([])"
| "fv_pluto_list_a_C (pluto_XXX#pluto_list_XXX) = ((fv_pluto pluto_XXX) @ (fv_pluto_list_a_C pluto_list_XXX))"
| "fv_pluto (a_Ax x) = ([x])"
| "fv_pluto a_AA = ([])"
| "fv_pluto (a_a pluto) = ((fv_pluto pluto))"
| "fv_pluto (a_C (pluto_list) (pluto'_list)) = ((fv_pluto_list_a_C pluto_list) @ (fv_pluto_list_a_C1 pluto'_list))"
| "fv_pluto (a_CC (pluto_list) (pluto'_list)) = ((fv_pluto_list_a_CC pluto_list) @ (fv_pluto_list_a_CC1 pluto'_list))"

(** library functions *)
primrec
list_assoc :: "'a => ('a*'b) list => 'b option"
where
  "list_assoc x0 Nil = None"
| "list_assoc x0 (Cons xy  xys) = (if x0=fst xy then Some (snd xy) else list_assoc x0 xys)"


(** substitutions *)
primrec
sum_pluto_list_a_CC1 :: "(x*a) list => a list => a list"
and sum_pluto_list_a_CC :: "(x*a) list => a list => a list"
and sum_pluto_list_a_C1 :: "(x*a) list => a list => a list"
and sum_pluto_list_a_C :: "(x*a) list => a list => a list"
and sum_pluto :: "(x*a) list => a => a"
where
"sum_pluto_list_a_CC1 sub Nil = (Nil)"
| "sum_pluto_list_a_CC1 sub (pluto_XXX#pluto_list_XXX) = ((sum_pluto sub pluto_XXX) # (sum_pluto_list_a_CC1 sub pluto_list_XXX))"
| "sum_pluto_list_a_CC sub Nil = (Nil)"
| "sum_pluto_list_a_CC sub (pluto_XXX#pluto_list_XXX) = ((sum_pluto sub pluto_XXX) # (sum_pluto_list_a_CC sub pluto_list_XXX))"
| "sum_pluto_list_a_C1 sub Nil = (Nil)"
| "sum_pluto_list_a_C1 sub (pluto_XXX#pluto_list_XXX) = ((sum_pluto sub pluto_XXX) # (sum_pluto_list_a_C1 sub pluto_list_XXX))"
| "sum_pluto_list_a_C sub Nil = (Nil)"
| "sum_pluto_list_a_C sub (pluto_XXX#pluto_list_XXX) = ((sum_pluto sub pluto_XXX) # (sum_pluto_list_a_C sub pluto_list_XXX))"
| "sum_pluto sub (a_Ax x) = ((case list_assoc x sub of None => (a_Ax x) | Some pluto_5 => pluto_5))"
| "sum_pluto sub a_AA = (a_AA )"
| "sum_pluto sub (a_a pluto) = (a_a (sum_pluto sub pluto))"
| "sum_pluto sub (a_C (pluto_list) (pluto'_list)) = (a_C (sum_pluto_list_a_C sub pluto_list) (sum_pluto_list_a_C1 sub pluto'_list))"
| "sum_pluto sub (a_CC (pluto_list) (pluto'_list)) = (a_CC (sum_pluto_list_a_CC sub pluto_list) (sum_pluto_list_a_CC1 sub pluto'_list))"

primrec
su_pluto_list_a_CC1 :: "a => x => a list => a list"
and su_pluto_list_a_CC :: "a => x => a list => a list"
and su_pluto_list_a_C1 :: "a => x => a list => a list"
and su_pluto_list_a_C :: "a => x => a list => a list"
and su_pluto :: "a => x => a => a"
where
"su_pluto_list_a_CC1 pluto_5 x5 Nil = (Nil)"
| "su_pluto_list_a_CC1 pluto_5 x5 (pluto_XXX#pluto_list_XXX) = ((su_pluto pluto_5 x5 pluto_XXX) # (su_pluto_list_a_CC1 pluto_5 x5 pluto_list_XXX))"
| "su_pluto_list_a_CC pluto_5 x5 Nil = (Nil)"
| "su_pluto_list_a_CC pluto_5 x5 (pluto_XXX#pluto_list_XXX) = ((su_pluto pluto_5 x5 pluto_XXX) # (su_pluto_list_a_CC pluto_5 x5 pluto_list_XXX))"
| "su_pluto_list_a_C1 pluto_5 x5 Nil = (Nil)"
| "su_pluto_list_a_C1 pluto_5 x5 (pluto_XXX#pluto_list_XXX) = ((su_pluto pluto_5 x5 pluto_XXX) # (su_pluto_list_a_C1 pluto_5 x5 pluto_list_XXX))"
| "su_pluto_list_a_C pluto_5 x5 Nil = (Nil)"
| "su_pluto_list_a_C pluto_5 x5 (pluto_XXX#pluto_list_XXX) = ((su_pluto pluto_5 x5 pluto_XXX) # (su_pluto_list_a_C pluto_5 x5 pluto_list_XXX))"
| "su_pluto pluto_5 x5 (a_Ax x) = ((if x=x5 then pluto_5 else (a_Ax x)))"
| "su_pluto pluto_5 x5 a_AA = (a_AA )"
| "su_pluto pluto_5 x5 (a_a pluto) = (a_a (su_pluto pluto_5 x5 pluto))"
| "su_pluto pluto_5 x5 (a_C (pluto_list) (pluto'_list)) = (a_C (su_pluto_list_a_C pluto_5 x5 pluto_list) (su_pluto_list_a_C1 pluto_5 x5 pluto'_list))"
| "su_pluto pluto_5 x5 (a_CC (pluto_list) (pluto'_list)) = (a_CC (su_pluto_list_a_CC pluto_5 x5 pluto_list) (su_pluto_list_a_CC1 pluto_5 x5 pluto'_list))"


end



