(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test13b.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


Definition terminal : Set := nat.
Definition metavarroot : Set := nat.
Definition nontermroot : Set := nat.
Definition suffix : Set := nat.
Definition auxfn : Set := nat.
Definition prodname : Set := nat.
Definition index : Set := nat.

Inductive metavar : Set := 
 | mv_1 (metavarroot5:metavarroot) (suffix5:suffix).

Inductive nonterm : Set := 
 | nt_1 (nontermroot5:nontermroot) (suffix5:suffix).

Inductive mse : Set := 
 | mse_mv (metavar5:metavar)
 | mse_f (auxfn5:auxfn) (nonterm5:nonterm)
 | mse_union (mse5:mse) (mse':mse)
 | mse_empty : mse.

Inductive element : Set := 
 | e_tm (terminal5:terminal)
 | e_mv (metavar5:metavar)
 | e_nt (nonterm5:nonterm).

Inductive bindspec : Set := 
 | bs_bind (mse5:mse) (nonterm5:nonterm)
 | bs_auxfn (auxfn5:auxfn) (mse5:mse).

Inductive prod : Set := 
 | p_1 (_:list element) (prodname5:prodname) (_:list bindspec).

Inductive rule : Set := 
 | r_1 (nontermroot5:nontermroot) (_:list prod).

Inductive auxfn_type : Set := 
 | at_1 (_:list nontermroot) (metavarroot5:metavarroot).

Inductive grammar_rules : Set := 
 | g_1 (_:list rule).

Inductive auxfn_type_env : Set := 
 | ate_1 : auxfn_type_env
 | ate_2 (Phi:auxfn_type_env) (auxfn5:auxfn) (auxfn_type5:auxfn_type).

Inductive grammar_type : Set := 
 | gt_1 (_:list nontermroot).
(* definitions *)

(* defns Jtype *)
Inductive FF : auxfn_type_env -> auxfn -> auxfn_type -> Prop :=    (* defn FF *)
 | FF_1 : forall (Phi:auxfn_type_env) (f:auxfn) (at:auxfn_type),
     FF (ate_2 Phi f at) f at
 | FF_2 : forall (Phi:auxfn_type_env) (f':auxfn) (at':auxfn_type) (f:auxfn) (at:auxfn_type),
     FF Phi f at ->
     (formula_not  (   ( f  =  f' )   ) ) ->
     FF (ate_2 Phi f' at') f at
with Mse : auxfn_type_env -> list element -> mse -> metavarroot -> Prop :=    (* defn Mse *)
 | Mse_1 : forall (e_list:list element) (Phi:auxfn_type_env) (mvr:metavarroot),
     Mse Phi e_list mse_empty mvr
 | Mse_2 : forall (e_list:list element) (j:index) (Phi:auxfn_type_env) (mvr:metavarroot) (suff:suffix) (t101:element),
          nth_error e_list (j - 1) = Some t101 ->
 ( t101  =  (e_mv (mv_1 mvr suff)) )  ->
     Mse Phi e_list (mse_mv (mv_1 mvr suff)) mvr
 | Mse_3 : forall (ntr_list:list nontermroot) (e_list:list element) (j i:index) (Phi:auxfn_type_env) (f:auxfn) (nt:nonterm) (mvr:metavarroot) (suff:suffix) (t102:element) (t103:nontermroot),
          nth_error e_list (j - 1) = Some t102 ->
     nth_error ntr_list (i - 1) = Some t103 ->
FF Phi f (at_1 ntr_list mvr) ->
      ( t102  =  (e_nt nt) )  ->
      ( nt  =  (nt_1 t103 suff) )  ->
     Mse Phi e_list (mse_f f nt) mvr
 | Mse_4 : forall (e_list:list element) (Phi:auxfn_type_env) (mse5 mse':mse) (mvr:metavarroot),
     Mse Phi e_list mse5 mvr ->
     Mse Phi e_list mse' mvr ->
     Mse Phi e_list (mse_union mse5 mse') mvr
with Bs : auxfn_type_env -> list element -> bindspec -> Prop :=    (* defn Bs *)
 | Bs_1 : forall (e_list:list element) (j:index) (Phi:auxfn_type_env) (mse5:mse) (nt:nonterm) (mvr:metavarroot) (t104:element),
          nth_error e_list (j - 1) = Some t104 ->
Mse Phi e_list mse5 mvr ->
      ( t104  =  (e_nt nt) )  ->
     Bs Phi e_list (bs_bind mse5 nt)
 | Bs_2 : forall (e_ntr_list:list (element*nontermroot)) (Phi:auxfn_type_env) (f:auxfn) (mse5:mse) (mvr:metavarroot),
     Mse Phi (map (fun (pat_:(element*nontermroot)) => match pat_ with (e_,ntr_) => e_ end ) e_ntr_list) mse5 mvr ->
     FF Phi f (at_1 (map (fun (pat_:(element*nontermroot)) => match pat_ with (e_,ntr_) => ntr_ end ) e_ntr_list) mvr) ->
     Bs Phi (map (fun (pat_:(element*nontermroot)) => match pat_ with (e_,ntr_) => e_ end ) e_ntr_list) (bs_auxfn f mse5)
with Prod : auxfn_type_env -> prod -> Prop :=    (* defn Prod *)
 | Prod_1 : forall (bs_list:list bindspec) (e_list:list element) (Phi:auxfn_type_env) (prod5:prod) (i m:index) (prodname5:prodname) (t105:bindspec),
          nth_error bs_list (i - 1) = Some t105 ->
(formula_forall i m Bs Phi e_list t105) ->
      ( prod5  =  (p_1 e_list prodname5 bs_list) )  ->
     Prod Phi prod5
with Rule : auxfn_type_env -> rule -> Prop :=    (* defn Rule *)
 | Rule_1 : forall (prod_list:list prod) (Phi:auxfn_type_env) (rule5:rule) (i m:index) (ntr:nontermroot) (t106:prod),
          nth_error prod_list (i - 1) = Some t106 ->
(formula_forall i m Prod Phi t106) ->
      ( rule5  =  (r_1 ntr prod_list) )  ->
     Rule Phi rule5
with Grammar : auxfn_type_env -> grammar_rules -> Prop :=    (* defn Grammar *)
 | Grammar_1 : forall (prod'_list:list prod) (rule_prod_list:list (rule*prod)) (Phi:auxfn_type_env) (grammar_rules5:grammar_rules) (i m j n:index) (ntr:nontermroot) (t107 t108 t109:(rule*prod)),
          nth_error rule_prod_list (i - 1) = Some t107 ->
     nth_error rule_prod_list (j - 1) = Some t108 ->
     nth_error rule_prod_list (i - 1) = Some t109 ->
(formula_forall i m Rule Phi (match t107 with (rule_,prod_) => rule_ end)) ->
      ( grammar_rules5  =  (g_1 (map (fun (pat_:(rule*prod)) => match pat_ with (rule_,prod_) => rule_ end ) rule_prod_list)) )  ->
     (formula_forall i m (formula_forall j n  (  (formula_implies  (  (formula_and  ( (match t109 with (rule_,prod_) => rule_ end)  =  (r_1 ntr (map (fun (pat_:(rule*prod)) => match pat_ with (rule_,prod_) => prod_ end ) rule_prod_list)) )   ( (match t108 with (rule_,prod_) => rule_ end)  =  (r_1 ntr prod'_list) ) )  )   ( i  =  j ) )  ) )) ->
     Grammar Phi grammar_rules5.


