/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.0.ott -/





inductive a where
    | a_AA : a
    | a_a : (_:a) -> a

  deriving Inhabited
open a

/- - subrules - -/
def is_av_of_a (a5:a) : Bool :=
  match a5 with
  | a_AA => false
  | (a_a a) => (true)




