(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_embed_location_1.ott *)
(* to compile: Holmake testRegr_test_embed_location_1Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test_embed_location_1";

val _ = type_abbrev("index", ``:num``);

Type i = ``:index``
val _ = Hol_datatype ` 
thing = 
   thing_normal
`;
(** definitions *)

(* defns relations *)
Inductive relations:
(* defn ok *)

[ok_wibble:] (
(clause_name "ok_wibble")
 ==> 
( ( ok  thing_meta  )))
End

val _ = export_theory ();



