(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4c.ott *)
theory testRegr_test15_4c
imports Main
begin

type_synonym "index" = "nat"
type_synonym "x" = "nat"
datatype "a" = 
   a_Ax "x"  
 | a_AA  
 | a_a "a"  
 | a_C "(a*a*a) list"  
 | a_CC "(a*a*a) list"  


(** subrules *)
primrec
is_av_of_a_a_a_CC :: "(a*a) => bool"
and is_av_of_a_a_a_a_CC :: "(a*(a*a)) => bool"
and is_av_of_a_a_a_list_a_CC :: "(a*a*a) list => bool"
and is_av_of_a_a_a_C :: "(a*a) => bool"
and is_av_of_a_a_a_a_C :: "(a*(a*a)) => bool"
and is_av_of_a_a_a_list_a_C :: "(a*a*a) list => bool"
and is_av_of_a :: "a => bool"
where
"is_av_of_a_a_a_CC (a'_XXX,a''_XXX) = (((is_av_of_a a'_XXX) & (is_av_of_a a''_XXX)))"
| "is_av_of_a_a_a_a_CC (a_XXX,a'_a''_XXX) = ((is_av_of_a a_XXX) & (is_av_of_a_a_a_CC a'_a''_XXX))"
| "is_av_of_a_a_a_list_a_CC Nil = (True)"
| "is_av_of_a_a_a_list_a_CC (a_a'_a''_XXX#a_a'_a''_list_XXX) = (((is_av_of_a_a_a_a_CC a_a'_a''_XXX) & (is_av_of_a_a_a_list_a_CC a_a'_a''_list_XXX)))"
| "is_av_of_a_a_a_C (a'_XXX,a''_XXX) = (((is_av_of_a a'_XXX) & (is_av_of_a a''_XXX)))"
| "is_av_of_a_a_a_a_C (a_XXX,a'_a''_XXX) = ((is_av_of_a a_XXX) & (is_av_of_a_a_a_C a'_a''_XXX))"
| "is_av_of_a_a_a_list_a_C Nil = (True)"
| "is_av_of_a_a_a_list_a_C (a_a'_a''_XXX#a_a'_a''_list_XXX) = (((is_av_of_a_a_a_a_C a_a'_a''_XXX) & (is_av_of_a_a_a_list_a_C a_a'_a''_list_XXX)))"
| "is_av_of_a (a_Ax x) = (False)"
| "is_av_of_a a_AA = (False)"
| "is_av_of_a (a_a a) = ((True))"
| "is_av_of_a (a_C (a_a'_a''_list)) = ((is_av_of_a_a_a_list_a_C a_a'_a''_list))"
| "is_av_of_a (a_CC (a_a'_a''_list)) = ((is_av_of_a_a_a_list_a_CC a_a'_a''_list))"


(** free variables *)
primrec
fv_a_a_a_CC :: "(a*a) => x list"
and fv_a_a_a_a_CC :: "a*(a*a) => x list"
and fv_a_a_a_list_a_CC :: "(a*a*a) list => x list"
and fv_a_a_a_C :: "(a*a) => x list"
and fv_a_a_a_a_C :: "a*(a*a) => x list"
and fv_a_a_a_list_a_C :: "(a*a*a) list => x list"
and fv_a :: "a => x list"
where
"fv_a_a_a_CC (a'_XXX,a''_XXX) = ((fv_a a'_XXX) @ (fv_a a''_XXX))"
| "fv_a_a_a_a_CC (a_XXX,a'_a''_XXX) = ((fv_a a_XXX) @ (fv_a_a_a_CC a'_a''_XXX))"
| "fv_a_a_a_list_a_CC Nil = ([])"
| "fv_a_a_a_list_a_CC (a_a'_a''_XXX#a_a'_a''_list_XXX) = ((fv_a_a_a_a_CC a_a'_a''_XXX) @ (fv_a_a_a_list_a_CC a_a'_a''_list_XXX))"
| "fv_a_a_a_C (a'_XXX,a''_XXX) = ((fv_a a'_XXX) @ (fv_a a''_XXX))"
| "fv_a_a_a_a_C (a_XXX,a'_a''_XXX) = ((fv_a a_XXX) @ (fv_a_a_a_C a'_a''_XXX))"
| "fv_a_a_a_list_a_C Nil = ([])"
| "fv_a_a_a_list_a_C (a_a'_a''_XXX#a_a'_a''_list_XXX) = ((fv_a_a_a_a_C a_a'_a''_XXX) @ (fv_a_a_a_list_a_C a_a'_a''_list_XXX))"
| "fv_a (a_Ax x) = ([x])"
| "fv_a a_AA = ([])"
| "fv_a (a_a a) = ((fv_a a))"
| "fv_a (a_C (a_a'_a''_list)) = ((fv_a_a_a_list_a_C a_a'_a''_list))"
| "fv_a (a_CC (a_a'_a''_list)) = ((fv_a_a_a_list_a_CC a_a'_a''_list))"

(** library functions *)
primrec
list_assoc :: "'a => ('a*'b) list => 'b option"
where
  "list_assoc x0 Nil = None"
| "list_assoc x0 (Cons xy  xys) = (if x0=fst xy then Some (snd xy) else list_assoc x0 xys)"


(** substitutions *)
primrec
su_a_a_a_CC :: "a => x => (a*a) => (a*a)"
and su_a_a_a_a_CC :: "a => x => a*(a*a) => a*(a*a)"
and su_a_a_a_list_a_CC :: "a => x => (a*a*a) list => (a*a*a) list"
and su_a_a_a_C :: "a => x => (a*a) => (a*a)"
and su_a_a_a_a_C :: "a => x => a*(a*a) => a*(a*a)"
and su_a_a_a_list_a_C :: "a => x => (a*a*a) list => (a*a*a) list"
and su_a :: "a => x => a => a"
where
"su_a_a_a_CC a_5 x5 (a1,a2) = (su_a a_5 x5 a1 , su_a a_5 x5 a2)"
| "su_a_a_a_a_CC a_5 x5 (a1,a_a_a_CC1) = (su_a a_5 x5 a1 , su_a_a_a_CC a_5 x5 a_a_a_CC1)"
| "su_a_a_a_list_a_CC a_5 x5 Nil = (Nil)"
| "su_a_a_a_list_a_CC a_5 x5 (a_a_a_XXX#a_a_a_list_XXX) = ((su_a_a_a_a_CC a_5 x5 a_a_a_XXX) # (su_a_a_a_list_a_CC a_5 x5 a_a_a_list_XXX))"
| "su_a_a_a_C a_5 x5 (a1,a2) = (su_a a_5 x5 a1 , su_a a_5 x5 a2)"
| "su_a_a_a_a_C a_5 x5 (a1,a_a_a_C1) = (su_a a_5 x5 a1 , su_a_a_a_C a_5 x5 a_a_a_C1)"
| "su_a_a_a_list_a_C a_5 x5 Nil = (Nil)"
| "su_a_a_a_list_a_C a_5 x5 (a_a_a_XXX#a_a_a_list_XXX) = ((su_a_a_a_a_C a_5 x5 a_a_a_XXX) # (su_a_a_a_list_a_C a_5 x5 a_a_a_list_XXX))"
| "su_a a_5 x5 (a_Ax x) = ((if x=x5 then a_5 else (a_Ax x)))"
| "su_a a_5 x5 a_AA = (a_AA )"
| "su_a a_5 x5 (a_a a) = (a_a (su_a a_5 x5 a))"
| "su_a a_5 x5 (a_C (a_a'_a''_list)) = (a_C (su_a_a_a_list_a_C a_5 x5 a_a'_a''_list))"
| "su_a a_5 x5 (a_CC (a_a'_a''_list)) = (a_CC (su_a_a_a_list_a_CC a_5 x5 a_a'_a''_list))"

primrec
sum_a_a_a_list_a_C :: "(x*a) list => (a*a*a) list => (a*a*a) list"
and sum_a :: "(x*a) list => a => a"
and sum_a_a_a_CC :: "(x*a) list => (a*a) => (a*a)"
and sum_a_a_a_a_CC :: "(x*a) list => a*(a*a) => a*(a*a)"
and sum_a_a_a_list_a_CC :: "(x*a) list => (a*a*a) list => (a*a*a) list"
and sum_a_a_a_C :: "(x*a) list => (a*a) => (a*a)"
and sum_a_a_a_a_C :: "(x*a) list => a*(a*a) => a*(a*a)"
where
"sum_a_a_a_list_a_C sub Nil = (Nil)"
| "sum_a_a_a_list_a_C sub (a_a_a_XXX#a_a_a_list_XXX) = ((sum_a_a_a_a_C sub a_a_a_XXX) # (sum_a_a_a_list_a_C sub a_a_a_list_XXX))"
| "sum_a sub (a_Ax x) = ((case list_assoc x sub of None => (a_Ax x) | Some a_5 => a_5))"
| "sum_a sub a_AA = (a_AA )"
| "sum_a sub (a_a a) = (a_a (sum_a sub a))"
| "sum_a sub (a_C (a_a'_a''_list)) = (a_C (sum_a_a_a_list_a_C sub a_a'_a''_list))"
| "sum_a sub (a_CC (a_a'_a''_list)) = (a_CC (sum_a_a_a_list_a_CC sub a_a'_a''_list))"
| "sum_a_a_a_CC sub (a1,a2) = (sum_a sub a1 , sum_a sub a2)"
| "sum_a_a_a_a_CC sub (a1,a_a_a_CC1) = (sum_a sub a1 , sum_a_a_a_CC sub a_a_a_CC1)"
| "sum_a_a_a_list_a_CC sub Nil = (Nil)"
| "sum_a_a_a_list_a_CC sub (a_a_a_XXX#a_a_a_list_XXX) = ((sum_a_a_a_a_CC sub a_a_a_XXX) # (sum_a_a_a_list_a_CC sub a_a_a_list_XXX))"
| "sum_a_a_a_C sub (a1,a2) = (sum_a sub a1 , sum_a sub a2)"
| "sum_a_a_a_a_C sub (a1,a_a_a_C1) = (sum_a sub a1 , sum_a_a_a_C sub a_a_a_C1)"


end



