(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_tuple_2.ott *)

type i = UNDEFINED

type 
foo = 
   Foo_Foo


type 
barbar = 
   Barbar_Bar
 | Barbar_Qux


(** subrules *)
let is_bar_of_barbar (barbar5:barbar) : bool =
  match barbar5 with
  | Barbar_Bar -> (true)
  | Barbar_Qux -> false


(** definitions *)


