(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_empty_defn.ott *)
(* to compile: Holmake testRegr_test_empty_defnTheory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test_empty_defn";

(** definitions *)

(* defns Empty_defns *)
Inductive Empty_defns:
End
(** definitions *)

(* defns Nonempty_defns *)
Inductive Nonempty_defns:
(* defn non_empty_defn *)

[1:] (
(clause_name "1")
 ==> 
( ( non_empty_defn  )))

(* defn empty_defn *)

End

val _ = export_theory ();



