(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.8.ott *)

type index = UNDEFINED

type 
t = 
   T_unit
 | T_tuple of (t) list
 | T_sum of t * t


type 
a = 
   A_unit
 | A_tuple of (a) list
 | A_typedtuple of ((a * t)) list
 | A_proj of a * index

(** definitions *)


