/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.14.ott -/




abbrev value_name := UNDEFINED
abbrev index := UNDEFINED

inductive a where
    | a_x : (x:value_name) -> a
    | a_E : (_:List (c × c × c)) -> a

where c where
    | c_C : (_:List a) -> c

  deriving Inhabited
open a c

/- - subrules - -/
def is_av_of_c_c'_c''_list (c_c'_c''_list:List (c × c × c)) : Bool :=
  match c_c'_c''_list with
  | [] => true
  | (c_,c'_,c''_) :: c_c'_c''_list_ => (true) && (is_av_of_c_c'_c''_list c_c'_c''_list_)


def is_av_of_a (a5:a) : Bool :=
  match a5 with
  | (a_x x) => false
  | (a_E (c_c'_c''_list)) => (is_av_of_c_c'_c''_list c_c'_c''_list)



/- - substitutions - -/
mutual
def subst_a_list (a_5:a) (x5:value_name) (a_list:List a) : List a :=
  match a_list with
  | [] => []
  | a_ :: a_list_ => (subst_a a_5 x5 a_) :: (subst_a_list a_5 x5 a_list_)
def subst_c (a_5:a) (x5:value_name) (c5:c) : c :=
  match c5 with
  | (c_C (a_list)) => c_C (subst_a_list a_5 x5 a_list)
def subst_c_c_c_list (a5:a) (x5:value_name) (c_c'_c''_list:List (c × c × c)) : List (c × c × c) :=
  match c_c'_c''_list with
  | [] => []
  | (c_,c'_,c''_) :: c_c'_c''_list_ => ((subst_c a5 x5 c_),(subst_c a5 x5 c'_),(subst_c a5 x5 c''_)) :: (subst_c_c_c_list a5 x5 c_c'_c''_list_)
def subst_a (a5:a) (x5:value_name) (a_6:a) : a :=
  match a_6 with
  | (a_x x) => (if x=x5 then a5 else (a_x x))
  | (a_E (c_c'_c''_list)) => a_E (subst_c_c_c_list a5 x5 c_c'_c''_list)
end


/- - free variables - -/
mutual
def fv_a_list (a_list:List a) : List value_name :=
  match a_list with
  | [] => []
  | a_ :: a_list_ => (fv_a a_) ++ (fv_a_list a_list_)
def fv_c (c5:c) :  List value_name :=
  match c5 with
  | (c_C (a_list)) => (fv_a_list a_list)
def fv_c_c_c_list (c_c'_c''_list:List (c × c × c)) : List value_name :=
  match c_c'_c''_list with
  | [] => []
  | (c_,c'_,c''_) :: c_c'_c''_list_ => ((fv_c c_) ++ (fv_c c'_) ++ (fv_c c''_)) ++ (fv_c_c_c_list c_c'_c''_list_)
def fv_a (a5:a) :  List value_name :=
  match a5 with
  | (a_x x) => [x]
  | (a_E (c_c'_c''_list)) => (fv_c_c_c_list c_c'_c''_list)
end



