(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.13.ott *)

type value_name = UNDEFINED
type index = UNDEFINED

type 
a = 
   A_x of value_name
 | A_A of (a) list
 | A_X of (value_name) list
 | A_V of (a) list
 | A_C of (c) list

and c = 
   C_C of a * a
 | C_VC of (a) list

let rec aux_b_c_of_c (c5:c) : value_name list =
  match c5 with
  | (C_C (a,a')) -> (aux_b_a_of_a a)
  | (C_VC (av_list)) -> (List.flatten (List.map aux_b_a_of_a (av_list)))
and
aux_b_a_of_a (a_5:a) : value_name list =
  match a_5 with
  | (A_x x) -> [x]
  | (A_A (a_list)) -> (List.flatten (List.map aux_b_a_of_a (a_list)))
  | (A_X (x_list)) -> x_list
  | (A_V (av_list)) -> (List.flatten (List.map aux_b_a_of_a (av_list)))
  | (A_C (c_list)) -> (List.flatten (List.map aux_b_c_of_c (c_list)))



(** subrules *)
let rec is_c_of_c (c5:c) : bool =
  match c5 with
  | (C_C (a,a')) -> ((is_a_of_a a) && (is_a_of_a a'))
  | (C_VC (av_list)) -> ((List.for_all (fun av_ -> (is_av_of_a av_)) av_list))
and
is_a_of_a (a_5:a) : bool =
  match a_5 with
  | (A_x x) -> (true)
  | (A_A (a_list)) -> ((List.for_all (fun a_ -> (is_a_of_a a_)) a_list))
  | (A_X (x_list)) -> ((List.for_all (fun x_ -> true) x_list))
  | (A_V (av_list)) -> ((List.for_all (fun av_ -> (is_av_of_a av_)) av_list))
  | (A_C (c_list)) -> ((List.for_all (fun c_ -> (is_c_of_c c_)) c_list))
and
is_av_of_a (a_5:a) : bool =
  match a_5 with
  | (A_x x) -> false
  | (A_A (a_list)) -> ((List.for_all (fun a_ -> (is_a_of_a a_)) a_list))
  | (A_X (x_list)) -> false
  | (A_V (av_list)) -> ((List.for_all (fun av_ -> (is_av_of_a av_)) av_list))
  | (A_C (c_list)) -> false


(** library functions *)
let rec list_minus (l1:'a list) (l2:'a list) : 'a list =
  match l1 with
  | [] -> []
  | h::t -> if (List.mem h l2) then list_minus t l2 else h::(list_minus t l2)


(** free variables *)
let rec fv_c (c5:c) : value_name list =
  match c5 with
  | (C_C (a,a')) -> (fv_a a) @ (list_minus (fv_a a') (aux_b_a_of_a a))
  | (C_VC (av_list)) -> []
and
fv_a (a_5:a) : value_name list =
  match a_5 with
  | (A_x x) -> [x]
  | (A_A (a_list)) -> (List.flatten (List.map (fun a_ -> (fv_a a_)) a_list))
  | (A_X (x_list)) -> []
  | (A_V (av_list)) -> []
  | (A_C (c_list)) -> (List.flatten (List.map (fun c_ -> (fv_c c_)) c_list))



(** substitutions *)
let rec msubst_c (sub: (value_name*a) list) (c5:c) : c =
  match c5 with
  | (C_C (a,a')) -> C_C ((msubst_a sub a),(msubst_a (List.filter (fun (x5,a5) -> not(List.mem x5 ((aux_b_a_of_a a)))) sub) a'))
  | (C_VC (av_list)) -> C_VC av_list
and
msubst_a (sub: (value_name*a) list) (a__6:a) : a =
  match a__6 with
  | (A_x x) -> (try List.assoc x sub with Not_found -> (A_x x))
  | (A_A (a_list)) -> A_A (List.map (fun a_ -> (msubst_a sub a_)) a_list)
  | (A_X (x_list)) -> A_X x_list
  | (A_V (av_list)) -> A_V av_list
  | (A_C (c_list)) -> A_C (List.map (fun c_ -> (msubst_c sub c_)) c_list)


let rec subst_c (a5:a) (x5:value_name) (c5:c) : c =
  match c5 with
  | (C_C (a,a')) -> C_C ((subst_a a5 x5 a),(if List.mem x5 ((aux_b_a_of_a a)) then a' else (subst_a a5 x5 a')))
  | (C_VC (av_list)) -> C_VC av_list
and
subst_a (a_5:a) (x_5:value_name) (a__6:a) : a =
  match a__6 with
  | (A_x x) -> (if x=x_5 then a_5 else (A_x x))
  | (A_A (a_list)) -> A_A (List.map (fun a_ -> (subst_a a_5 x_5 a_)) a_list)
  | (A_X (x_list)) -> A_X x_list
  | (A_V (av_list)) -> A_V av_list
  | (A_C (c_list)) -> A_C (List.map (fun c_ -> (subst_c a_5 x_5 c_)) c_list)




