/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_subrule_3.ott -/




abbrev i := UNDEFINED
abbrev ident := UNDEFINED

inductive constant where
    | CONST_unit : constant

  deriving Inhabited

inductive expr where
    | Expr_constant : (_:constant) -> expr

  deriving Inhabited

inductive substs_x where
    | substs_x_xs : (_:List (ident × expr)) -> substs_x

  deriving Inhabited
open constant expr substs_x

/- - subrules - -/
def is_valu_of_expr (e5:expr) : Bool :=
  match e5 with
  | (Expr_constant constant) => (true)


/- definitions -/


/- defns Jred -/
mutual
inductive JR_match : expr -> substs_x -> Prop where    /- defn match -/
| JR_match_alias: forall (x_v_list:List (ident × expr)) (x:_root_.ident) (v:_root_.expr),
(is_valu_of_expr v) ->
(List.all x_v_list (fun (x_,v_) => is_valu_of_expr v_)) ->
(JR_match v (substs_x_xs (x_v_list)))
 -> 
JR_match v (substs_x_xs (x_v_list ++ [(x,v)]))


inductive JR_matches : List expr -> substs_x -> Prop where    /- defn matches -/
| JR_matches_and: forall (v_list:List expr) (substs_x:_root_.substs_x),
((∀ v_list_ ∈ v_list, (fun v_ => (JR_match v_ substs_x)) v_list_))
 -> 
JR_matches (v_list) substs_x


end


