/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.5.ott -/




abbrev value_name := UNDEFINED
abbrev index := UNDEFINED

inductive a where
    | a_x : (x:value_name) -> a
    | a_X : (_:List value_name) -> a
    | a_F : (_:c) -> a
    | a_E : (_:List (c × c)) -> a

where c where
    | c_C : (_:List a) -> c

  deriving Inhabited
open a c

/- - substitutions - -/
mutual
def subst_a_list (a_5:a) (x5:value_name) (a_list:List a) : List a :=
  match a_list with
  | [] => []
  | a_ :: a_list_ => (subst_a a_5 x5 a_) :: (subst_a_list a_5 x5 a_list_)
def subst_c (a_5:a) (x5:value_name) (c5:c) : c :=
  match c5 with
  | (c_C (a_list)) => c_C (subst_a_list a_5 x5 a_list)
def subst_c_c_list (a5:a) (x_5:value_name) (c_c'_list:List (c × c)) : List (c × c) :=
  match c_c'_list with
  | [] => []
  | (c_,c'_) :: c_c'_list_ => ((subst_c a5 x_5 c_),(subst_c a5 x_5 c'_)) :: (subst_c_c_list a5 x_5 c_c'_list_)
def subst_a (a5:a) (x_5:value_name) (a_6:a) : a :=
  match a_6 with
  | (a_x x) => (if x=x_5 then a5 else (a_x x))
  | (a_X (x_list)) => a_X x_list
  | (a_F c) => a_F (subst_c a5 x_5 c)
  | (a_E (c_c'_list)) => a_E (subst_c_c_list a5 x_5 c_c'_list)
end



