(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test12.ott *)
(* to compile: Holmake testRegr_test12Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test12";

val _ = Hol_datatype ` 
a = 
   a_b of b
 | a_0
;
b = 
   b_a of a
`;
val _ = Hol_datatype ` 
c = 
   c_a of a
`;
val _ = Hol_datatype ` 
e = 
   e_f of f
 | e_c of c
;
f = 
   f_ea of e => a
`;

Type d = ``:string``

val _ = export_theory ();



