/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.1.ott -/





inductive a where
    | a_AA : a
    | a_a : (_:a) -> a
    | a_b : (_:b) -> a

where b where
    | b_BB : b
    | b_a : (_:a) -> b
    | b_b : (_:b) -> b

  deriving Inhabited
open a b

/- - subrules - -/
def is_bv_of_b (b5:b) : Bool :=
  match b5 with
  | b_BB => false
  | (b_a a) => (true)
  | (b_b b) => (true)


def is_av_of_a (a5:a) : Bool :=
  match a5 with
  | a_AA => false
  | (a_a a) => (true)
  | (a_b b) => (true)




