(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common_typing.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common_index.ott /home/pes20/claude-home/ott/regression/../examples/tapl/unit.ott /home/pes20/claude-home/ott/regression/../examples/tapl/tuple.ott *)
(* to compile: Holmake testRegr_sys_tupleTheory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_sys_tuple";
(** warning: the backend selected ignores the file structure informations *)
(** syntax *)
Type index = ``:num`` (* indices *)
val _ = Hol_datatype ` 
T =  (* types: *)
   TyUnit (* unit type *)
 | TyTuple of T list (* tuple type *)
`;

Type G = ``:(termvar#Typ) list``
val _ = Hol_datatype ` 
t =  (* terms: *)
   TmUnit (* constant unit *)
 | TmTuple of t list (* tuple *)
 | TmProjTp of t => index (* projection *)
`;

(** auxiliary functions on the new list types *)
(** library functions *)
(** subrules *)
val _ = ottDefine "is_v_of_t" `
    ( is_v_of_t TmUnit = (T))
/\  ( is_v_of_t (TmTuple (t_list)) = ((EVERY (\t_. (is_v_of_t t_)) t_list)))
/\  ( is_v_of_t (TmProjTp t i) = F)
`;
(** auxiliary functions *)
(** free variables *)
(** substitutions *)
(** context application *)

(** definitions *)

(* defns Jop *)
Inductive Jop:
(* defn red *)

[E_ProjTuple:] (! (v_list:t list) (j:index) .
(clause_name "E_ProjTuple") /\
((EVERY (\v_. is_v_of_t v_) v_list) /\
( (1 <=  j  /\  j  <= LENGTH  (v_list) ) ))
 ==> 
( ( red (TmProjTp (TmTuple (v_list)) j)  ((\ v_ . v_) (EL  (j - 1) v_list))  )))

[E_ProjTp:] (! (t1:t) (i:index) (t1':t) .
(clause_name "E_ProjTp") /\
(( ( red t1 t1' )))
 ==> 
( ( red (TmProjTp t1 i) (TmProjTp t1' i) )))

[E_Tuple:] (! (t_list:t list) (v_list:t list) (t:t) (t':t) .
(clause_name "E_Tuple") /\
((EVERY (\v_. is_v_of_t v_) v_list) /\
( ( red t t' )))
 ==> 
( ( red (TmTuple (v_list ++ [(t)] ++ t_list)) (TmTuple (v_list ++ [(t')] ++ t_list)) )))
End

(* defns Jtype *)
Inductive Jtype:
(* defn typing *)

[T_Unit:] (! (G:G) .
(clause_name "T_Unit")
 ==> 
( ( typing G TmUnit TyUnit )))

[T_Tuple:] (! (t_T_list:(t#T) list) (G:G) .
(clause_name "T_Tuple") /\
(((EVERY (\ b . b) ((MAP (\(t_,T_) .  ( typing G t_ T_ )) t_T_list)))))
 ==> 
( ( typing G (TmTuple ((MAP (\(t_,T_) . t_) t_T_list))) (TyTuple ((MAP (\(t_,T_) . T_) t_T_list))) )))

[T_ProjTp:] (! (T_list:T list) (G:G) (t1:t) (j:index) .
(clause_name "T_ProjTp") /\
(( ( typing G t1 (TyTuple (T_list)) )) /\
( (1 <=  j  /\  j  <= LENGTH  (T_list) ) ))
 ==> 
( ( typing G (TmProjTp t1 j)  ((\ T_ . T_) (EL  (j - 1) T_list))  )))
End



val _ = export_theory ();
