(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test18.1.ott *)

type termvar = UNDEFINED (* term variable *)
type index = UNDEFINED

type 
a = 
   A_AA
 | A_C of (a) list
 | A_D of termvar * (a) list

(** definitions *)


