(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.4.ott *)
theory testRegr_test17_4
imports Main
begin

type_synonym "value_name" = "string"
type_synonym "index" = "nat"
datatype "a" = 
   a_x "value_name"  
 | a_X "value_name list"  
 | a_F "c"  
 | a_E "c list"  
and "c" = 
   c_C "a list"  


(** substitutions *)
primrec
subst_a_list :: "a => value_name => a list => a list"
and subst_c :: "a => value_name => c => c"
and subst_c_list :: "a => value_name => c list => c list"
and subst_a :: "a => value_name => a => a"
where
"subst_a_list a_5 x5 Nil = (Nil)"
| "subst_a_list a_5 x5 (a_XXX#a_list_XXX) = ((subst_a a_5 x5 a_XXX) # (subst_a_list a_5 x5 a_list_XXX))"
| "subst_c a_5 x5 (c_C (a_list)) = (c_C (subst_a_list a_5 x5 a_list))"
| "subst_c_list a5 x_5 Nil = (Nil)"
| "subst_c_list a5 x_5 (c_XXX#c_list_XXX) = ((subst_c a5 x_5 c_XXX) # (subst_c_list a5 x_5 c_list_XXX))"
| "subst_a a5 x_5 (a_x x) = ((if x=x_5 then a5 else (a_x x)))"
| "subst_a a5 x_5 (a_X (x_list)) = (a_X x_list)"
| "subst_a a5 x_5 (a_F c) = (a_F (subst_c a5 x_5 c))"
| "subst_a a5 x_5 (a_E (c_list)) = (a_E (subst_c_list a5 x_5 c_list))"


end



