/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test-pottier1.ott -/




abbrev termvar := UNDEFINED /- term variable -/

inductive t where
    | t_Var : (x:termvar) -> t
    | t_Lam : (x:termvar) -> (_:t) -> t
    | t_App : (t1:t) -> (t2:t) -> t

  deriving Inhabited
open t
def aux_bv_t_of_t (t_5:t) : List termvar :=
  match t_5 with
  | (t_Var x) => []
  | (t_Lam x t) => [x] ++ (aux_bv_t_of_t t)
  | (t_App t1 t2) => (aux_bv_t_of_t t1) ++ (aux_bv_t_of_t t2)



/- - substitutions - -/
def subst_t (t_5:t) (x5:termvar) (t__6:t) : t :=
  match t__6 with
  | (t_Var x) => (if x=x5 then t_5 else (t_Var x))
  | (t_Lam x t) => t_Lam x (if  List.elem x5 ([x]) then t else (subst_t t_5 x5 t))
  | (t_App t1 t2) => t_App (subst_t t_5 x5 t1) (subst_t t_5 x5 t2)




