/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test14.ott -/




abbrev termvar := UNDEFINED /- term variable -/
abbrev label := UNDEFINED /- field label -/
abbrev index := UNDEFINED /- indices -/

inductive t where /- term -/
    | t_Var : (x:termvar) -> t /- variable -/
    | t_Lam : (x:termvar) -> (_:t) -> t /- abstraction -/
    | t_App : (_:t) -> (t':t) -> t /- application -/
    | t_Rec : (_:List (label × t)) -> t /- record -/
    | t_Proj : (_:t) -> (l:label) -> t /- projection -/

  deriving Inhabited
open t

/- - subrules - -/
mutual
def is_v_of_l_t_list (l_t_list:List (label × t)) : Bool :=
  match l_t_list with
  | [] => true
  | (l_,t_) :: l_t_list_ => ((is_v_of_t t_)) && (is_v_of_l_t_list l_t_list_)
def is_v_of_t (t_5:t) : Bool :=
  match t_5 with
  | (t_Var x) => false
  | (t_Lam x t) => (true)
  | (t_App t t') => false
  | (t_Rec (l_t_list)) => (is_v_of_l_t_list l_t_list)
  | (t_Proj t l) => false
end



