(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.10.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


Definition typevar : Set := nat. (* type variable *)
Lemma eq_typevar: forall (x y : typevar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_typevar : ott_coq_equality.
Definition termvar : Set := nat. (* term variable *)
Lemma eq_termvar: forall (x y : termvar), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_termvar : ott_coq_equality.
Definition label : Set := nat. (* field label *)
Definition index : Set := nat. (* indices *)

Inductive T : Set :=  (* type *)
 | T_Var (X:typevar) (* type variable *)
 | T_Rec (_:list (label*T)) (* record *).

Inductive t : Set :=  (* term *)
 | t_Var (x:termvar) (* variable *)
 | t_Rec_comp_lu_some (_:list (label*t)) (* record --- complu with terminal *)
 | t_Proj (t5:t) (l:label) (* projection *).

Inductive G : Set :=  (* type environment *)
 | G_empty : G
 | G_type (G5:G) (X:typevar) (T5:T)
 | G_term (G5:G) (x:termvar) (T5:T).
(** induction principles *)
Section T_rect.

Variables
  (P_T : T -> Prop)
  (P_list_label_T : list (label*T) -> Prop).

Hypothesis
  (H_T_Var : forall (X:typevar), P_T (T_Var X))
  (H_T_Rec : forall (l_T_list:list (label*T)), P_list_label_T l_T_list -> P_T (T_Rec l_T_list))
  (H_list_label_T_nil : P_list_label_T nil)
  (H_list_label_T_cons : forall (label0:label), forall (T0:T), P_T T0 -> forall (label_T_l:list (label*T)), P_list_label_T label_T_l -> P_list_label_T (cons (label0,T0) label_T_l)).

Fixpoint T_ott_ind (n:T) : P_T n :=
  match n as x return P_T x with
  | (T_Var X) => H_T_Var X
  | (T_Rec l_T_list) => H_T_Rec l_T_list (((fix l_T_list_ott_ind (label_T_l:list (label*T)) : P_list_label_T label_T_l := match label_T_l as x return P_list_label_T x with nil => H_list_label_T_nil | cons (label1,T1) xl => H_list_label_T_cons label1  T1(T_ott_ind T1)xl (l_T_list_ott_ind xl) end)) l_T_list)
end.

End T_rect.


Section t_rect.

Variables
  (P_list_label_t : list (label*t) -> Prop)
  (P_t : t -> Prop).

Hypothesis
  (H_t_Var : forall (x:termvar), P_t (t_Var x))
  (H_t_Rec_comp_lu_some : forall (l_t_list:list (label*t)), P_list_label_t l_t_list -> P_t (t_Rec_comp_lu_some l_t_list))
  (H_t_Proj : forall (t5:t), P_t t5 -> forall (l:label), P_t (t_Proj t5 l))
  (H_list_label_t_nil : P_list_label_t nil)
  (H_list_label_t_cons : forall (label0:label), forall (t0:t), P_t t0 -> forall (label_t_l:list (label*t)), P_list_label_t label_t_l -> P_list_label_t (cons (label0,t0) label_t_l)).

Fixpoint t_ott_ind (n:t) : P_t n :=
  match n as x return P_t x with
  | (t_Var x) => H_t_Var x
  | (t_Rec_comp_lu_some l_t_list) => H_t_Rec_comp_lu_some l_t_list (((fix l_t_list_ott_ind (label_t_l:list (label*t)) : P_list_label_t label_t_l := match label_t_l as x return P_list_label_t x with nil => H_list_label_t_nil | cons (label1,t1) xl => H_list_label_t_cons label1  t1(t_ott_ind t1)xl (l_t_list_ott_ind xl) end)) l_t_list)
  | (t_Proj t5 l) => H_t_Proj t5 (t_ott_ind t5) l
end.

End t_rect.


Section G_rect.

Variables
  (P_G : G -> Prop).

Hypothesis
  (H_G_empty : P_G G_empty)
  (H_G_type : forall (G5:G), P_G G5 -> forall (X:typevar), forall (T5:T), P_G (G_type G5 X T5))
  (H_G_term : forall (G5:G), P_G G5 -> forall (x:termvar), forall (T5:T), P_G (G_term G5 x T5))
.

Fixpoint G_ott_ind (n:G) : P_G n :=
  match n as x return P_G x with
  | G_empty => H_G_empty 
  | (G_type G5 X T5) => H_G_type G5 (G_ott_ind G5) X T5
  | (G_term G5 x T5) => H_G_term G5 (G_ott_ind G5) x T5
end.

End G_rect.
(* definitions *)

(* defns Jtype *)
Inductive Ty : G -> t -> T -> Prop :=    (* defn Ty *)
 | Ty_Rcd_dotform : forall (l_t_T_list:list (label*t*T)) (G5:G),
     (forall t_ T_, In (t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (t_,T_) end) l_t_T_list) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec_comp_lu_some (map (fun (pat_:(label*t*T)) => match pat_ with (l_,t_,T_) => (l_,t_) end ) l_t_T_list)) (T_Rec (map (fun (pat_:(label*t*T)) => match pat_ with (l_,t_,T_) => (l_,T_) end ) l_t_T_list))
 | Ty_Proj_dotform : forall (l_T_list:list (label*T)) (j:index) (G5:G) (t5:t) (t101 t102:(label*T)),
          nth_error l_T_list (j - 1) = Some t101 ->
     nth_error l_T_list (j - 1) = Some t102 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t102 with (l_,T_) => l_ end)) (match t101 with (l_,T_) => T_ end)
 | Ty_Rcd_comp : forall (l_t_T_list:list (label*t*T)) (G5:G),
     (forall t_ T_, In (t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (t_,T_) end) l_t_T_list) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec_comp_lu_some (map (fun (pat_:(label*t*T)) => match pat_ with (l_,t_,T_) => (l_,t_) end ) l_t_T_list)) (T_Rec (map (fun (pat_:(label*t*T)) => match pat_ with (l_,t_,T_) => (l_,T_) end ) l_t_T_list))
 | Ty_Proj_comp : forall (l_T_list:list (label*T)) (j:index) (G5:G) (t5:t) (t103 t104:(label*T)),
          nth_error l_T_list j = Some t103 ->
     nth_error l_T_list j = Some t104 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t104 with (l_,T_) => l_ end)) (match t103 with (l_,T_) => T_ end)
 | Ty_Rcd_comp_u : forall (l_t_T_list:list (label*t*T)) (G5:G),
     (forall t_ T_, In (t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (t_,T_) end) l_t_T_list) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec_comp_lu_some (map (fun (pat_:(label*t*T)) => match pat_ with (l_,t_,T_) => (l_,t_) end ) l_t_T_list)) (T_Rec (map (fun (pat_:(label*t*T)) => match pat_ with (l_,t_,T_) => (l_,T_) end ) l_t_T_list))
 | Ty_Proj_comp_u : forall (l_T_list:list (label*T)) (j:index) (G5:G) (t5:t) (t105 t106:(label*T)),
          nth_error l_T_list j = Some t105 ->
     nth_error l_T_list j = Some t106 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t106 with (l_,T_) => l_ end)) (match t105 with (l_,T_) => T_ end)
 | Ty_Rcd_comp_lu : forall (l_t_T_list:list (label*t*T)) (G5:G),
     (forall t_ T_, In (t_,T_) (map (fun (pat_: (label*t*T)) => match pat_ with (l_,t_,T_) => (t_,T_) end) l_t_T_list) -> (Ty G5 t_ T_)) ->
     Ty G5 (t_Rec_comp_lu_some (map (fun (pat_:(label*t*T)) => match pat_ with (l_,t_,T_) => (l_,t_) end ) l_t_T_list)) (T_Rec (map (fun (pat_:(label*t*T)) => match pat_ with (l_,t_,T_) => (l_,T_) end ) l_t_T_list))
 | Ty_Proj_comp_lu : forall (l_T_list:list (label*T)) (j:index) (G5:G) (t5:t) (t107 t108:(label*T)),
          nth_error l_T_list (j - 1) = Some t107 ->
     nth_error l_T_list (j - 1) = Some t108 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t108 with (l_,T_) => l_ end)) (match t107 with (l_,T_) => T_ end)
 | Ty_Proj_dotform_minus : forall (l_T_list:list (label*T)) (j:index) (G5:G) (t5:t) (t109 t110:(label*T)),
          nth_error l_T_list j = Some t109 ->
     nth_error l_T_list j = Some t110 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t110 with (l_,T_) => l_ end)) (match t109 with (l_,T_) => T_ end)
 | Ty_Proj_comp_lu_minus : forall (l_T_list:list (label*T)) (j:index) (G5:G) (t5:t) (t111 t112:(label*T)),
          nth_error l_T_list j = Some t111 ->
     nth_error l_T_list j = Some t112 ->
Ty G5 t5 (T_Rec l_T_list) ->
     Ty G5 (t_Proj t5 (match t112 with (l_,T_) => l_ end)) (match t111 with (l_,T_) => T_ end).


