(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../examples/tapl/nat.ott /home/pes20/claude-home/ott/regression/../examples/tapl/common.ott /home/pes20/claude-home/ott/regression/../examples/tapl/bool.ott *)
Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.
(** warning: the backend selected ignores the file structure informations *)
(** syntax *)

Inductive t : Set :=  (* terms: *)
 | TmZero : t (* constant zero *)
 | TmSucc (t5:t) (* successor *)
 | TmPred (t5:t) (* predecessor *)
 | TmIszero (t5:t) (* zero test *)
 | TmTrue : t (* constant true *)
 | TmFalse : t (* constant false *)
 | TmIf (t1:t) (t2:t) (t3:t) (* conditional *).

(** auxiliary functions on the new list types *)
(** library functions *)
(** subrules *)
Fixpoint is_v_of_t (t_6:t) : bool :=
  match t_6 with
  | TmZero => (true)
  | (TmSucc t5) => ((is_v_of_t t5))
  | (TmPred t5) => false
  | (TmIszero t5) => false
  | TmTrue => (true)
  | TmFalse => (true)
  | (TmIf t1 t2 t3) => false
end.

(** auxiliary functions *)
(** free variables *)
(** substitutions *)
(** context application *)
Require Import Ott.ott_list. (* for [all_distinct] *)


(* definitions *)

(* defns Jop *)
Inductive red : t -> t -> Prop :=    (* defn red *)
 | E_Succ : forall (t1 t1':t),
     red t1 t1' ->
     red (TmSucc t1) (TmSucc t1')
 | E_PredZero : 
     red (TmPred TmZero) TmZero
 | E_PredSucc : forall (v1:t),
     Is_true (is_v_of_t v1) ->
     red (TmPred  (TmSucc v1) ) v1
 | E_Pred : forall (t1 t1':t),
     red t1 t1' ->
     red (TmPred t1) (TmPred t1')
 | E_IsZeroZero : 
     red (TmIszero TmZero) TmTrue
 | E_IsZeroSucc : forall (v1:t),
     Is_true (is_v_of_t v1) ->
     red (TmIszero  (TmSucc v1) ) TmFalse
 | E_IsZero : forall (t1 t1':t),
     red t1 t1' ->
     red (TmIszero t1) (TmIszero t1')
 | E_IfTrue : forall (t2 t3:t),
     red (TmIf TmTrue t2 t3) t2
 | E_IfFalse : forall (t2 t3:t),
     red (TmIf TmFalse t2 t3) t3
 | E_If : forall (t1 t2 t3 t1':t),
     red t1 t1' ->
     red (TmIf t1 t2 t3) (TmIf t1' t2 t3).


