(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.6.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.



Inductive a : Set := 
 | a_AAA : a
 | a_BBB : a
 | a_CC : a
 | a_a (a5:a).

(** subrules *)
Definition is_avv_of_a (a_6:a) : bool :=
  match a_6 with
  | a_AAA => false
  | a_BBB => false
  | a_CC => false
  | (a_a a5) => (true)
end.

Definition is_avB_of_a (a_6:a) : bool :=
  match a_6 with
  | a_AAA => false
  | a_BBB => (true)
  | a_CC => (true)
  | (a_a a5) => (true)
end.

Definition is_avA_of_a (a_6:a) : bool :=
  match a_6 with
  | a_AAA => (true)
  | a_BBB => false
  | a_CC => (true)
  | (a_a a5) => (true)
end.

(* definitions *)

(* defns Jtype *)
Inductive T : a -> a -> Prop :=    (* defn T *)
 | T_1 : forall (avv5:a),
     Is_true (is_avv_of_a avv5) ->
     T avv5 avv5.


