(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test-lj-list_ambiguity.ott *)

type t = UNDEFINED
type i = UNDEFINED

type 
t = 
   T_one of t
 | T_many of (t) list

(** definitions *)


