(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_bind_1.ott *)
theory testRegr_test_lists_coq_bind_1
imports Main
begin

type_synonym "index" = "nat"
type_synonym "value_name" = "nat"
datatype "pattern" = 
   P_var "value_name"  

datatype "expr" = 
   Expr_letrec "letrec_binding list" "expr"  
and "pattern_matching" = 
   PM_pm "(pattern*expr) list"  
and "letrec_binding" = 
   LRB_simple "value_name" "pattern_matching"  

primrec
aux_gives_letrec_binding_of_letrec_binding :: "letrec_binding => value_name list"
where
"aux_gives_letrec_binding_of_letrec_binding (LRB_simple value_name pattern_matching) = ([value_name])"


end



