(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test16.6.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


Definition value_name : Set := nat.
Lemma eq_value_name: forall (x y : value_name), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_value_name : ott_coq_equality.
Definition index : Set := nat.
Lemma eq_index: forall (x y : index), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_index : ott_coq_equality.

Inductive a : Set := 
 | a_x (x:value_name)
 | a_A (_:list a).
(** induction principles *)
Section a_rect.

Variables
  (P_a : a -> Prop)
  (P_list_a : list a -> Prop).

Hypothesis
  (H_a_x : forall (x:value_name), P_a (a_x x))
  (H_a_A : forall (a_list:list a), P_list_a a_list -> P_a (a_A a_list))
  (H_list_a_nil : P_list_a nil)
  (H_list_a_cons : forall (a0:a), P_a a0 -> forall (a_l:list a), P_list_a a_l -> P_list_a (cons a0 a_l)).

Fixpoint a_ott_ind (n:a) : P_a n :=
  match n as x return P_a x with
  | (a_x x) => H_a_x x
  | (a_A a_list) => H_a_A a_list (((fix a_list_ott_ind (a_l:list a) : P_list_a a_l := match a_l as x return P_list_a x with nil => H_list_a_nil | cons a1 xl => H_list_a_cons a1(a_ott_ind a1)xl (a_list_ott_ind xl) end)) a_list)
end.

End a_rect.

(** substitutions *)
Fixpoint subst_a (a_5:a) (x5:value_name) (a__6:a) {struct a__6} : a :=
  match a__6 with
  | (a_x x) => (if eq_value_name x x5 then a_5 else (a_x x))
  | (a_A a_list) => a_A (map (fun (a_:a) => (subst_a a_5 x5 a_)) a_list)
end.



