(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test2.ott *)
(* to compile: Holmake testRegr_test2Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test2";

Type ident = ``:UNDEFINED``
val _ = Hol_datatype ` 
T = 
   T_integer
 | T_float
`;
val _ = Hol_datatype ` 
E = 
   E_empty
 | E_ident of E => ident => T
`;
val _ = Hol_datatype ` 
F = 
   F_empty
 | F_ident of E => ident => ident
`;

val _ = export_theory ();



