(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_3.ott *)
theory testRegr_test_lists_coq_list_functions_3
imports Main
begin

type_synonym "i" = "num"
datatype "data" = 
   data_tuple "data list"  

datatype "map" = 
   map_finite "(data*map) list"  

(** definitions *)
(* defns Data *)
inductive Data_data :: "data \<Rightarrow> bool"
where
(* defn data *)

Data_data_tupleI: "\<lbrakk>(List.list_all (% b . b) ((List.map (%(data_XXX::data).Data_data (data_XXX)) data_list)))\<rbrakk> \<Longrightarrow>
Data_data ((data_tuple (data_list)))"
(** definitions *)
(* defns Map *)
inductive Map_map :: "map \<Rightarrow> bool"
where
(* defn map *)

Map_map_finiteI: "\<lbrakk>(List.list_all (% b . b) ((List.map (%((data_XXX::data),(map_XXX::map)).Data_data (data_XXX)) data_map_list))) ;
(List.list_all (% b . b) ((List.map (%((data_XXX::data),(map_XXX::map)).Map_map (map_XXX)) data_map_list)))\<rbrakk> \<Longrightarrow>
Map_map ((map_finite (data_map_list)))"

end



