(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.13.ott *)
(* to compile: Holmake testRegr_test17_13Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test17_13";

Type value_name = ``:string``
Type index = ``:num``
val _ = Hol_datatype ` 
a = 
   a_x of value_name
 | a_A of a list
 | a_X of value_name list
 | a_V of a list
 | a_C of c list
;
c = 
   c_C of a => a
 | c_VC of a list
`;
val _ = ottDefine "aux_b_c_of_c" `
    ( aux_b_c_of_c (c_C a a') = (aux_b_a_of_a a))
/\  ( aux_b_c_of_c (c_VC (av_list)) = (FLAT (MAP aux_b_a_of_a (av_list))))
/\  ( aux_b_a_of_a (a_x x) = [x])
/\  ( aux_b_a_of_a (a_A (a_list)) = (FLAT (MAP aux_b_a_of_a (a_list))))
/\  ( aux_b_a_of_a (a_X (x_list)) = x_list)
/\  ( aux_b_a_of_a (a_V (av_list)) = (FLAT (MAP aux_b_a_of_a (av_list))))
/\  ( aux_b_a_of_a (a_C (c_list)) = (FLAT (MAP aux_b_c_of_c (c_list))))
`;

(** subrules *)
val _ = ottDefine "is_c_of_c" `
    ( is_c_of_c (c_C a a') = ((is_a_of_a a) /\ (is_a_of_a a')))
/\  ( is_c_of_c (c_VC (av_list)) = ((EVERY (\av_. (is_av_of_a av_)) av_list)))
/\  ( is_a_of_a (a_x x) = (T))
/\  ( is_a_of_a (a_A (a_list)) = ((EVERY (\a_. (is_a_of_a a_)) a_list)))
/\  ( is_a_of_a (a_X (x_list)) = ((EVERY (\x_. T) x_list)))
/\  ( is_a_of_a (a_V (av_list)) = ((EVERY (\av_. (is_av_of_a av_)) av_list)))
/\  ( is_a_of_a (a_C (c_list)) = ((EVERY (\c_. (is_c_of_c c_)) c_list)))
/\  ( is_av_of_a (a_x x) = F)
/\  ( is_av_of_a (a_A (a_list)) = ((EVERY (\a_. (is_a_of_a a_)) a_list)))
/\  ( is_av_of_a (a_X (x_list)) = F)
/\  ( is_av_of_a (a_V (av_list)) = ((EVERY (\av_. (is_av_of_a av_)) av_list)))
/\  ( is_av_of_a (a_C (c_list)) = F)
`;

(** free variables *)
val _ = ottDefine "fv_c" `
    ( fv_c (c_C a a') = (fv_a a) ++ (list_minus (fv_a a') (aux_b_a_of_a a)))
/\  ( fv_c (c_VC (av_list)) = [])
/\  ( fv_a (a_x x) = [x])
/\  ( fv_a (a_A (a_list)) = (FLAT (MAP (\a_. (fv_a a_)) a_list)))
/\  ( fv_a (a_X (x_list)) = [])
/\  ( fv_a (a_V (av_list)) = [])
/\  ( fv_a (a_C (c_list)) = (FLAT (MAP (\c_. (fv_c c_)) c_list)))
`;

(** substitutions *)
val _ = ottDefine "msubst_c" `
    ( msubst_c sub (c_C a a') = c_C (msubst_a sub a) (msubst_a (FILTER (\(x5,a5). ~(MEM x5 (aux_b_a_of_a a))) sub) a'))
/\  ( msubst_c sub (c_VC (av_list)) = c_VC av_list)
/\  ( msubst_a sub (a_x x) = (case list_assoc x sub of NONE => (a_x x) | SOME a_5 => a_5))
/\  ( msubst_a sub (a_A (a_list)) = a_A (MAP (\a_. (msubst_a sub a_)) a_list))
/\  ( msubst_a sub (a_X (x_list)) = a_X x_list)
/\  ( msubst_a sub (a_V (av_list)) = a_V av_list)
/\  ( msubst_a sub (a_C (c_list)) = a_C (MAP (\c_. (msubst_c sub c_)) c_list))
`;

val _ = ottDefine "subst_c" `
    ( subst_c a5 x5 (c_C a a') = c_C (subst_a a5 x5 a) (if MEM x5 (aux_b_a_of_a a) then a' else (subst_a a5 x5 a')))
/\  ( subst_c a5 x5 (c_VC (av_list)) = c_VC av_list)
/\  ( subst_a a_5 x_5 (a_x x) = (if x=x_5 then a_5 else (a_x x)))
/\  ( subst_a a_5 x_5 (a_A (a_list)) = a_A (MAP (\a_. (subst_a a_5 x_5 a_)) a_list))
/\  ( subst_a a_5 x_5 (a_X (x_list)) = a_X x_list)
/\  ( subst_a a_5 x_5 (a_V (av_list)) = a_V av_list)
/\  ( subst_a a_5 x_5 (a_C (c_list)) = a_C (MAP (\c_. (subst_c a_5 x_5 c_)) c_list))
`;

val _ = export_theory ();



