(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_subrules_1.ott *)
(* to compile: Holmake testRegr_test_subrules_1Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test_subrules_1";

val _ = Hol_datatype ` 
big = 
   big_foo of big
 | big_bar of big
 | big_qux of big
`;

(** subrules *)
val _ = ottDefine "is_tweedledum_of_big" `
    ( is_tweedledum_of_big (big_foo big) = ((is_tweedledum_of_big big)))
/\  ( is_tweedledum_of_big (big_bar big) = F)
/\  ( is_tweedledum_of_big (big_qux tweedledum) = F)
`;

val _ = ottDefine "is_big_of_big" `
    ( is_big_of_big (big_foo big) = ((is_big_of_big big)))
/\  ( is_big_of_big (big_bar big) = ((is_big_of_big big)))
/\  ( is_big_of_big (big_qux tweedledum) = ((is_tweedledum_of_big tweedledum)))
`;

val _ = ottDefine "is_tweedledee_of_big" `
    ( is_tweedledee_of_big (big_foo big) = ((is_tweedledee_of_big big)))
/\  ( is_tweedledee_of_big (big_bar big) = F)
/\  ( is_tweedledee_of_big (big_qux tweedledum) = F)
`;

val _ = export_theory ();



