/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4c.ott -/




abbrev index := UNDEFINED
abbrev x := UNDEFINED

inductive a where
    | a_Ax : (_:x) -> a
    | a_AA : a
    | a_a : (_:a) -> a
    | a_C : (_:List (a × a × a)) -> a
    | a_CC : (_:List (a × a × a)) -> a

  deriving Inhabited
open a

/- - subrules - -/
mutual
def is_av_of_a_a'_a''_list (a_a'_a''_list:List (a × a × a)) : Bool :=
  match a_a'_a''_list with
  | [] => true
  | (a_,a'_,a''_) :: a_a'_a''_list_ => ((is_av_of_a a_) /\ (is_av_of_a a'_) /\ (is_av_of_a a''_)) && (is_av_of_a_a'_a''_list a_a'_a''_list_)
def is_av_of_a (a_5:a) : Bool :=
  match a_5 with
  | (a_Ax x) => false
  | a_AA => false
  | (a_a a) => (true)
  | (a_C (a_a'_a''_list)) => (is_av_of_a_a'_a''_list a_a'_a''_list)
  | (a_CC (a_a'_a''_list)) => (is_av_of_a_a'_a''_list a_a'_a''_list)
end


/- - free variables - -/
mutual
def fv_a_a_a_list (a_a'_a''_list:List (a × a × a)) : List x :=
  match a_a'_a''_list with
  | [] => []
  | (a_,a'_,a''_) :: a_a'_a''_list_ => ((fv_a a_) ++ (fv_a a'_) ++ (fv_a a''_)) ++ (fv_a_a_a_list a_a'_a''_list_)
def fv_a (a_5:a) :  List x :=
  match a_5 with
  | (a_Ax x) => [x]
  | a_AA => []
  | (a_a a) => (fv_a a)
  | (a_C (a_a'_a''_list)) => (fv_a_a_a_list a_a'_a''_list)
  | (a_CC (a_a'_a''_list)) => (fv_a_a_a_list a_a'_a''_list)
end

/- - library functions - -/
def list_assoc [DecidableEq a] (l:List (a × b)) (x:a) : Option b :=
match l with
| [] => none
| (x',y')::t => if x=x' then some y' else list_assoc t x


/- - substitutions - -/
mutual
def sum_a_a_a_list (sub:List (x×a)) (a_a'_a''_list:List (a × a × a)) : List (a × a × a) :=
  match a_a'_a''_list with
  | [] => []
  | (a_,a'_,a''_) :: a_a'_a''_list_ => ((sum_a sub a_),(sum_a sub a'_),(sum_a sub a''_)) :: (sum_a_a_a_list sub a_a'_a''_list_)
def sum_a (sub:List (x×a)) (a__6:a) : a :=
  match a__6 with
  | (a_Ax x) => (match list_assoc sub x with | none => (a_Ax x)| some a_5 => a_5 )
  | a_AA => a_AA 
  | (a_a a) => a_a (sum_a sub a)
  | (a_C (a_a'_a''_list)) => a_C (sum_a_a_a_list sub a_a'_a''_list)
  | (a_CC (a_a'_a''_list)) => a_CC (sum_a_a_a_list sub a_a'_a''_list)
end

mutual
def su_a_a_a_list (a_5:a) (x5:x) (a_a'_a''_list:List (a × a × a)) : List (a × a × a) :=
  match a_a'_a''_list with
  | [] => []
  | (a_,a'_,a''_) :: a_a'_a''_list_ => ((su_a a_5 x5 a_),(su_a a_5 x5 a'_),(su_a a_5 x5 a''_)) :: (su_a_a_a_list a_5 x5 a_a'_a''_list_)
def su_a (a_5:a) (x5:x) (a__6:a) : a :=
  match a__6 with
  | (a_Ax x) => (if x=x5 then a_5 else (a_Ax x))
  | a_AA => a_AA 
  | (a_a a) => a_a (su_a a_5 x5 a)
  | (a_C (a_a'_a''_list)) => a_C (su_a_a_a_list a_5 x5 a_a'_a''_list)
  | (a_CC (a_a'_a''_list)) => a_CC (su_a_a_a_list a_5 x5 a_a'_a''_list)
end



