(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.0.ott *)
(* to compile: Holmake testRegr_test17_0Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test17_0";

Type index = ``:num``
val _ = Hol_datatype ` 
a = 
   a_AA
 | a_A of a
 | a_C of a list
`;

(** subrules *)
val _ = ottDefine "is_av_of_a" `
    ( is_av_of_a a_AA = F)
/\  ( is_av_of_a (a_A a) = (T))
/\  ( is_av_of_a (a_C (a_list)) = ((EVERY (\a_. (is_av_of_a a_)) a_list)))
`;

val _ = export_theory ();



