(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_subrule_1.ott *)
theory testRegr_test_lists_coq_defn_subrule_1
imports Main
begin

type_synonym "i" = "nat"
type_synonym "x" = "nat"
datatype "foobar" = 
   foobar_foo  
 | foobar_bar  

datatype "seq" = 
   seq_foofoobar "(foobar*foobar) list"  


(** subrules *)
primrec
is_foo_of_foobar :: "foobar => bool"
where
"is_foo_of_foobar foobar_foo = ((True))"
| "is_foo_of_foobar foobar_bar = (False)"

primrec
is_seq_of_foobar_foobar :: "(foobar*foobar) => bool"
where
"is_seq_of_foobar_foobar (foo_XXX,foobar_XXX) = ((is_foo_of_foobar foo_XXX))"

primrec
is_seq_of_foobar_foobar_list :: "(foobar*foobar) list => bool"
where
"is_seq_of_foobar_foobar_list Nil = (True)"
| "is_seq_of_foobar_foobar_list (foo_foobar_XXX#foo_foobar_list_XXX) = (((is_seq_of_foobar_foobar foo_foobar_XXX) & (is_seq_of_foobar_foobar_list foo_foobar_list_XXX)))"

primrec
is_seq_of_seq :: "seq => bool"
where
"is_seq_of_seq (seq_foofoobar (foo_foobar_list)) = ((is_seq_of_foobar_foobar_list foo_foobar_list))"

(** definitions *)
(* defns J *)
inductive J_zip :: "foobar list \<Rightarrow> foobar list \<Rightarrow> seq \<Rightarrow> bool"
where
(* defn zip *)

J_zip_zapI: "\<lbrakk>List.list_all (%(foo_XXX,foobar_XXX). is_foo_of_foobar foo_XXX) foo_foobar_list\<rbrakk> \<Longrightarrow>
J_zip (((List.map (%((foo_XXX::foobar),(foobar_XXX::foobar)).foo_XXX) foo_foobar_list))) (((List.map (%((foo_XXX::foobar),(foobar_XXX::foobar)).foobar_XXX) foo_foobar_list))) ((seq_foofoobar (foo_foobar_list)))"

end



