(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.5.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.



Inductive a : Set := 
 | a_AAA : a
 | a_AA : a
 | a_a (a5:a)
 | a_B (a5:a) (a':a) (av5:a)
 | a_C (a5:a) (a':a) (av5:a).

(** subrules *)
Fixpoint is_a_of_a (a_6:a) : bool :=
  match a_6 with
  | a_AAA => (true)
  | a_AA => (true)
  | (a_a a5) => ((is_a_of_a a5))
  | (a_B a5 a' av5) => ((is_a_of_a a5) && (is_a_of_a a') && (is_av_of_a av5))
  | (a_C a5 a' av5) => ((is_a_of_a a5) && (is_a_of_a a') && (is_av_of_a av5))
end
with is_avv_of_a (a_6:a) : bool :=
  match a_6 with
  | a_AAA => false
  | a_AA => false
  | (a_a a5) => ((is_a_of_a a5))
  | (a_B a5 a' av5) => ((is_avv_of_a a5) && (is_avv_of_a a') && (is_avv_of_a av5))
  | (a_C a5 a' av5) => ((is_av_of_a a5) && (is_avv_of_a a') && (is_avv_of_a av5))
end
with is_av_of_a (a_6:a) : bool :=
  match a_6 with
  | a_AAA => false
  | a_AA => (true)
  | (a_a a5) => ((is_a_of_a a5))
  | (a_B a5 a' av5) => ((is_av_of_a a5) && (is_avv_of_a a') && (is_avv_of_a av5))
  | (a_C a5 a' av5) => ((is_a_of_a a5) && (is_a_of_a a') && (is_av_of_a av5))
end.



