/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test18.0.ott -/





inductive c where
    | c_bar : c

  deriving Inhabited

inductive a where
    | a_c : (_:c) -> a

  deriving Inhabited

inductive b where
    | b_foo : b

  deriving Inhabited
open a b c


