(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_2.ott *)
theory testRegr_test_lists_coq_list_functions_2
imports Main
begin

type_synonym "i" = "nat"
datatype "constant" = 
   CONST_unit  

datatype "p" = 
   P_constant "constant"  

datatype "e" = 
   E_constant "constant"  


(** subrules *)
primrec
is_v_of_e :: "e => bool"
where
"is_v_of_e (E_constant constant) = ((True))"

(** definitions *)
(* defns Jred *)
inductive JR_match :: "e \<Rightarrow> p \<Rightarrow> bool"
where
(* defn match *)

JR_match_constantI: "\<lbrakk>is_v_of_e v ;
List.list_all (%v_XXX. is_v_of_e v_XXX) v_list ;
(List.list_all (% b . b) ((List.map (%(v_XXX::e).JR_match (v_XXX) ((P_constant constant))) v_list)))\<rbrakk> \<Longrightarrow>
JR_match (v) ((P_constant constant))"

end



