/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.3.ott -/





inductive a where
    | a_AA : a
    | a_a : (_:a) -> a
    | a_b : (_:b) -> a
    | a_C : (av:a) -> (bv:b) -> a
    | a_D : (av:a) -> (bv:b) -> a

where b where
    | b_BB : b
    | b_a : (_:a) -> b
    | b_b : (_:b) -> b

  deriving Inhabited
open a b

/- - subrules - -/
mutual
def is_b_of_b (b5:b) : Bool :=
  match b5 with
  | b_BB => (true)
  | (b_a a) => ((is_a_of_a a))
  | (b_b b) => ((is_b_of_b b))
def is_a_of_a (a5:a) : Bool :=
  match a5 with
  | a_AA => (true)
  | (a_a a) => ((is_a_of_a a))
  | (a_b b) => ((is_b_of_b b))
  | (a_C av bv) => ((is_av_of_a av) /\ (is_bv_of_b bv))
  | (a_D av bv) => ((is_av_of_a av) /\ (is_bv_of_b bv))
def is_bv_of_b (b5:b) : Bool :=
  match b5 with
  | b_BB => false
  | (b_a a) => ((is_a_of_a a))
  | (b_b b) => ((is_b_of_b b))
def is_av_of_a (a5:a) : Bool :=
  match a5 with
  | a_AA => false
  | (a_a a) => ((is_a_of_a a))
  | (a_b b) => ((is_b_of_b b))
  | (a_C av bv) => ((is_av_of_a av) /\ (is_bv_of_b bv))
  | (a_D av bv) => false
end



