(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4d.ott *)
(* to compile: Holmake testRegr_test15_4dTheory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test15_4d";

Type index = ``:num``
Type x = ``:num``
val _ = Hol_datatype ` 
a = 
   a_Ax of x
 | a_AA
 | a_a of a
 | a_C of a list => a list
 | a_CC of a list => a list
`;
val _ = ottDefine "aux_b_a_of_a" `
    ( aux_b_a_of_a (a_Ax x) = [x])
/\  ( aux_b_a_of_a a_AA = [])
/\  ( aux_b_a_of_a (a_a a) = (aux_b_a_of_a a))
/\  ( aux_b_a_of_a (a_C (a_list) (a'_list)) = ((FLAT (MAP aux_b_a_of_a (a_list))) ++ (FLAT (MAP aux_b_a_of_a (a'_list)))))
/\  ( aux_b_a_of_a (a_CC (a_list) (a'_list)) = ((FLAT (MAP aux_b_a_of_a (a_list))) ++ (FLAT (MAP aux_b_a_of_a (a'_list)))))
`;

(** subrules *)
val _ = ottDefine "is_av_of_a" `
    ( is_av_of_a (a_Ax x) = F)
/\  ( is_av_of_a a_AA = F)
/\  ( is_av_of_a (a_a a) = (T))
/\  ( is_av_of_a (a_C (a_list) (a'_list)) = ((EVERY (\a_. (is_av_of_a a_)) a_list) /\ (EVERY (\a'_. (is_av_of_a a'_)) a'_list)))
/\  ( is_av_of_a (a_CC (a_list) (a'_list)) = ((EVERY (\a_. (is_av_of_a a_)) a_list) /\ (EVERY (\a'_. (is_av_of_a a'_)) a'_list)))
`;

(** free variables *)
val _ = ottDefine "fv_a" `
    ( fv_a (a_Ax x) = [x])
/\  ( fv_a a_AA = [])
/\  ( fv_a (a_a a) = (fv_a a))
/\  ( fv_a (a_C (a_list) (a'_list)) = (FLAT (MAP (\a_. (fv_a a_)) a_list)) ++ (FLAT (MAP (\a'_. (fv_a a'_)) a'_list)))
/\  ( fv_a (a_CC (a_list) (a'_list)) = (FLAT (MAP (\a_. (fv_a a_)) a_list)) ++ (FLAT (MAP (\a'_. (fv_a a'_)) a'_list)))
`;

(** substitutions *)
val _ = ottDefine "sum_a" `
    ( sum_a sub (a_Ax x) = (case list_assoc x sub of NONE => (a_Ax x) | SOME a_5 => a_5))
/\  ( sum_a sub a_AA = a_AA )
/\  ( sum_a sub (a_a a) = a_a (sum_a sub a))
/\  ( sum_a sub (a_C (a_list) (a'_list)) = a_C (MAP (\a_. (sum_a sub a_)) a_list) (MAP (\a'_. (sum_a sub a'_)) a'_list))
/\  ( sum_a sub (a_CC (a_list) (a'_list)) = a_CC (MAP (\a_. (sum_a sub a_)) a_list) (MAP (\a'_. (sum_a sub a'_)) a'_list))
`;

val _ = ottDefine "su_a" `
    ( su_a a_5 x5 (a_Ax x) = (if x=x5 then a_5 else (a_Ax x)))
/\  ( su_a a_5 x5 a_AA = a_AA )
/\  ( su_a a_5 x5 (a_a a) = a_a (su_a a_5 x5 a))
/\  ( su_a a_5 x5 (a_C (a_list) (a'_list)) = a_C (MAP (\a_. (su_a a_5 x5 a_)) a_list) (MAP (\a'_. (su_a a_5 x5 a'_)) a'_list))
/\  ( su_a a_5 x5 (a_CC (a_list) (a'_list)) = a_CC (MAP (\a_. (su_a a_5 x5 a_)) a_list) (MAP (\a'_. (su_a a_5 x5 a'_)) a'_list))
`;

val _ = export_theory ();



