/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_1.ott -/




abbrev i := natish
abbrev x := natish

inductive b where
    | b_x : (_:x) -> b

  deriving Inhabited

inductive t where
    | t_x : (_:x) -> t
    | t_letrec : (_:List lb) -> (_:t) -> t

where lb where
    | lb_simple : (_:x) -> (_:t) -> lb

  deriving Inhabited

inductive E where
    | E_concrete : (_:List b) -> E

  deriving Inhabited
open t lb b E
/- definitions -/


/- defns Typing -/
mutual
inductive Typing_ok : E -> Prop where    /- defn ok -/
| Typing_ok_nil: Typing_ok  wibble 

| Typing_ok_x: forall (E:_root_.E) (x:_root_.x),
(Typing_ok E)
 -> 
Typing_ok  wobble 


inductive Typing_term : E -> t -> Prop where    /- defn term -/
| Typing_term_x: forall (E1:_root_.E) (x:_root_.x) (E2:_root_.E),
(Typing_ok  wobble )
 -> 
Typing_term  wobble  (t_x x)

| Typing_term_letrec: forall (lb_E_list:List (lb × E)) (E:_root_.E) (t:_root_.t),
((PARSE_ERROR "File /home/pes20/claude-home/ott/regression/../tests/test_lists_1.ott on line 45 - 46" "no parses (char 35): E, E1, ... , En |- lb1 gives E1   .***..   E, E1, ... , En |- lbn ")) ->
(Typing_term  wobble  t)
 -> 
Typing_term E (t_letrec ((List.map (fun (lb_,E_) => lb_) lb_E_list)) t)


inductive Typing_lb : E -> lb -> E -> Prop where    /- defn lb -/
| Typing_lb_simple: forall (E:_root_.E) (x:_root_.x) (t:_root_.t),
(Typing_term E t)
 -> 
Typing_lb E (lb_simple x t) (E_concrete ([((b_x x))]))


end


