(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_coq_equality_x_1.ott *)
theory testRegr_test_coq_equality_x_1
imports Main
begin

type_synonym "x" = "string"

end



