(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test17.0.ott *)
theory testRegr_test17_0
imports Main
begin

type_synonym "index" = "nat"
datatype "a" = 
   a_AA  
 | a_A "a"  
 | a_C "a list"  


(** subrules *)
primrec
is_av_of_a_list :: "a list => bool"
and is_av_of_a :: "a => bool"
where
"is_av_of_a_list Nil = (True)"
| "is_av_of_a_list (a_XXX#a_list_XXX) = (((is_av_of_a a_XXX) & (is_av_of_a_list a_list_XXX)))"
| "is_av_of_a a_AA = (False)"
| "is_av_of_a (a_A a) = ((True))"
| "is_av_of_a (a_C (a_list)) = ((is_av_of_a_list a_list))"


end



