/- generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_2.ott -/




abbrev i := UNDEFINED

inductive constant where
    | CONST_unit : constant

  deriving Inhabited

inductive p where
    | P_constant : (_:constant) -> p

  deriving Inhabited

inductive e where
    | E_constant : (_:constant) -> e

  deriving Inhabited
open constant p e

/- - subrules - -/
def is_v_of_e (e5:e) : Bool :=
  match e5 with
  | (E_constant constant) => (true)


/- definitions -/


/- defns Jred -/
inductive JR_match : e -> p -> Prop where    /- defn match -/
| JR_match_constant: forall (v_list:List e) (v:_root_.e) (constant:_root_.constant),
(is_v_of_e v) ->
(List.all v_list (fun v_ => is_v_of_e v_)) ->
((∀ v_list_ ∈ v_list, (fun v_ => (JR_match v_ (P_constant constant))) v_list_))
 -> 
JR_match v (P_constant constant)



