(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_list_functions_1.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


Definition i : Set := nat.
Definition ident : Set := nat.

Inductive typevar : Set := 
 | TV_ident (ident5:ident).

Inductive typexpr : Set := 
 | TE_var (typevar5:typevar).

Definition typevars : Set := (list typevar).

Inductive value_name : Set := 
 | VN_id (ident5:ident).

Inductive typescheme : Set := 
 | TS_forall (typevars5:typevars) (t:typexpr).

Inductive environment_binding : Set := 
 | EB_vn (value_name5:value_name) (typescheme5:typescheme).

Definition environment : Set := list environment_binding.
(* definitions *)

(* defns Jtype *)
Inductive JT_value_name : environment -> value_name -> typexpr -> Prop :=    (* defn value_name *)
 | JT_value_name_value_name : forall (E1:environment) (x:value_name) (ts:typescheme) (E2:environment) (t:typexpr),
     JT_value_name  (@List.flat_map _ _ (fun l=>l)  ((app (cons  (@List.cons environment_binding  (EB_vn x ts)   E1 )  nil) (app (cons E2 nil) nil))) )  x t.


