(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test_lists_coq_defn_tuple_2.ott *)
(* to compile: Holmake testRegr_test_lists_coq_defn_tuple_2Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib ottLib;
infix THEN THENC |-> ## ;
local open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory in end;

val _ = new_theory "testRegr_test_lists_coq_defn_tuple_2";

Type i = ``:num``
val _ = Hol_datatype ` 
foo = 
   foo_Foo
`;
val _ = Hol_datatype ` 
barbar = 
   barbar_Bar
 | barbar_Qux
`;

(** subrules *)
val _ = ottDefine "is_bar_of_barbar" `
    ( is_bar_of_barbar barbar_Bar = (T))
/\  ( is_bar_of_barbar barbar_Qux = F)
`;
(** definitions *)

(* defns J *)
Inductive J:
(* defn one *)


(* defn hello *)

[J_hello_world:] (! (foo_bar_list:(foo#barbar) list) .
(clause_name "J_hello_world") /\
((EVERY (\(foo_,bar_). is_bar_of_barbar bar_) foo_bar_list) /\
((EVERY (\ b . b) ((MAP (\(foo_,bar_) .  ( J_one foo_ bar_ )) foo_bar_list)))))
 ==> 
( ( J_hello  )))
End

val _ = export_theory ();



