(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.1.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.



Inductive a : Set := 
 | a_AA : a
 | a_a (a5:a)
 | a_b (b5:b)
with b : Set := 
 | b_BB : b
 | b_a (a5:a)
 | b_b (b5:b).

(** subrules *)
Definition is_bv_of_b (b_6:b) : bool :=
  match b_6 with
  | b_BB => false
  | (b_a a5) => (true)
  | (b_b b5) => (true)
end.

Definition is_av_of_a (a_6:a) : bool :=
  match a_6 with
  | a_AA => false
  | (a_a a5) => (true)
  | (a_b b5) => (true)
end.



