(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test16.5.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


Definition value_name : Set := nat.
Lemma eq_value_name: forall (x y : value_name), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_value_name : ott_coq_equality.
Definition index : Set := nat.

Inductive a : Set := 
 | a_x (x:value_name)
 | a_A (_:list a)
 | a_C : a.
(** induction principles *)
Section a_rect.

Variables
  (P_a : a -> Prop)
  (P_list_a : list a -> Prop).

Hypothesis
  (H_a_x : forall (x:value_name), P_a (a_x x))
  (H_a_A : forall (aaa_list:list a), P_list_a aaa_list -> P_a (a_A aaa_list))
  (H_a_C : P_a a_C)
  (H_list_a_nil : P_list_a nil)
  (H_list_a_cons : forall (a0:a), P_a a0 -> forall (a_l:list a), P_list_a a_l -> P_list_a (cons a0 a_l)).

Fixpoint a_ott_ind (n:a) : P_a n :=
  match n as x return P_a x with
  | (a_x x) => H_a_x x
  | (a_A aaa_list) => H_a_A aaa_list (((fix aaa_list_ott_ind (a_l:list a) : P_list_a a_l := match a_l as x return P_list_a x with nil => H_list_a_nil | cons a1 xl => H_list_a_cons a1(a_ott_ind a1)xl (aaa_list_ott_ind xl) end)) aaa_list)
  | a_C => H_a_C 
end.

End a_rect.
Fixpoint aux_f_a_of_a (aa5:a) : list value_name :=
  match aa5 with
  | (a_x x) => (cons x nil)
  | (a_A aaa_list) => (flat_map (fun (aaa_:a) => aux_f_a_of_a aaa_) aaa_list)
  | a_C => nil
end.

(** library functions *)
Fixpoint list_assoc A B (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list (A*B)) {struct l} : option B :=
  match l with
  | nil => None
  | cons (a,b) t => if (eq a x) then Some b else list_assoc A B eq x t
end.
Arguments list_assoc [A B] _ _ _.


(** substitutions *)
Fixpoint msubst_a (sub:list (value_name*a)) (aa_6:a) {struct aa_6} : a :=
  match aa_6 with
  | (a_x x) => (match list_assoc eq_value_name x sub with None => (a_x x) | Some aa5 => aa5 end)
  | (a_A aaa_list) => a_A (map (fun (aaa_:a) => (msubst_a sub aaa_)) aaa_list)
  | a_C => a_C 
end.

Fixpoint subst_a (aa5:a) (x5:value_name) (aa_6:a) {struct aa_6} : a :=
  match aa_6 with
  | (a_x x) => (if eq_value_name x x5 then aa5 else (a_x x))
  | (a_A aaa_list) => a_A (map (fun (aaa_:a) => (subst_a aa5 x5 aaa_)) aaa_list)
  | a_C => a_C 
end.



