(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test18.0.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.



Inductive c : Set := 
 | c_bar : c.

Inductive a : Set := 
 | a_c (c5:c).

Inductive b : Set := 
 | b_foo : b.


