(* generated by Ott 0.34 from: /home/pes20/claude-home/ott/regression/../tests/test15.4c.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Ott.ott_list_core.


Definition index : Set := nat.
Lemma eq_index: forall (x y : index), {x = y} + {x <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_index : ott_coq_equality.
Definition x : Set := nat.
Lemma eq_x: forall (x' y : x), {x' = y} + {x' <> y}.
Proof.
  decide equality; auto with ott_coq_equality arith.
Defined.
#[export] Hint Resolve eq_x : ott_coq_equality.

Inductive a : Set := 
 | a_Ax (x5:x)
 | a_AA : a
 | a_a (a5:a)
 | a_C (_:list (a*a*a))
 | a_CC (_:list (a*a*a)).
(** induction principles *)
Section a_rect.

Variables
  (P_a : a -> Prop)
  (P_list_a_a_a : list (a*a*a) -> Prop).

Hypothesis
  (H_a_Ax : forall (x5:x), P_a (a_Ax x5))
  (H_a_AA : P_a a_AA)
  (H_a_a : forall (a5:a), P_a a5 -> P_a (a_a a5))
  (H_a_C : forall (a_a'_a''_list:list (a*a*a)), P_list_a_a_a a_a'_a''_list -> P_a (a_C a_a'_a''_list))
  (H_a_CC : forall (a_a'_a''_list:list (a*a*a)), P_list_a_a_a a_a'_a''_list -> P_a (a_CC a_a'_a''_list))
  (H_list_a_a_a_nil : P_list_a_a_a nil)
  (H_list_a_a_a_cons : forall (a0:a), P_a a0 -> forall (a1:a), P_a a1 -> forall (a2:a), P_a a2 -> forall (a_a_a_l:list (a*a*a)), P_list_a_a_a a_a_a_l -> P_list_a_a_a (cons (a0,a1,a2) a_a_a_l)).

Fixpoint a_ott_ind (n:a) : P_a n :=
  match n as x return P_a x with
  | (a_Ax x5) => H_a_Ax x5
  | a_AA => H_a_AA 
  | (a_a a5) => H_a_a a5 (a_ott_ind a5)
  | (a_C a_a'_a''_list) => H_a_C a_a'_a''_list (((fix a_a'_a''_list_ott_ind (a_a_a_l:list (a*a*a)) : P_list_a_a_a a_a_a_l := match a_a_a_l as x return P_list_a_a_a x with nil => H_list_a_a_a_nil | cons (a3,a4,a5) xl => H_list_a_a_a_cons a3(a_ott_ind a3) a4(a_ott_ind a4) a5(a_ott_ind a5)xl (a_a'_a''_list_ott_ind xl) end)) a_a'_a''_list)
  | (a_CC a_a'_a''_list) => H_a_CC a_a'_a''_list (((fix a_a'_a''_list_ott_ind (a_a_a_l:list (a*a*a)) : P_list_a_a_a a_a_a_l := match a_a_a_l as x return P_list_a_a_a x with nil => H_list_a_a_a_nil | cons (a6,a7,a8) xl => H_list_a_a_a_cons a6(a_ott_ind a6) a7(a_ott_ind a7) a8(a_ott_ind a8)xl (a_a'_a''_list_ott_ind xl) end)) a_a'_a''_list)
end.

End a_rect.

(** subrules *)
Fixpoint is_av_of_a (a_6:a) : bool :=
  match a_6 with
  | (a_Ax x5) => false
  | a_AA => false
  | (a_a a5) => (true)
  | (a_C a_a'_a''_list) => ((forall_list (fun (pat_:(a*a*a)) => match pat_ with (a_,a'_,a''_) => (is_av_of_a a_) && (is_av_of_a a'_) && (is_av_of_a a''_) end) a_a'_a''_list))
  | (a_CC a_a'_a''_list) => ((forall_list (fun (pat_:(a*a*a)) => match pat_ with (a_,a'_,a''_) => (is_av_of_a a_) && (is_av_of_a a'_) && (is_av_of_a a''_) end) a_a'_a''_list))
end.


(** free variables *)
Fixpoint fv_a (a_6:a) : list x :=
  match a_6 with
  | (a_Ax x5) => (cons x5 nil)
  | a_AA => nil
  | (a_a a5) => ((fv_a a5))
  | (a_C a_a'_a''_list) => ((flat_map (fun (pat_:(a*a*a)) => match pat_ with (a_,a'_,a''_) => (fv_a a_) ++ (fv_a a'_) ++ (fv_a a''_) end) a_a'_a''_list))
  | (a_CC a_a'_a''_list) => ((flat_map (fun (pat_:(a*a*a)) => match pat_ with (a_,a'_,a''_) => (fv_a a_) ++ (fv_a a'_) ++ (fv_a a''_) end) a_a'_a''_list))
end.

(** library functions *)
Fixpoint list_assoc A B (eq:forall a b:A,{a=b}+{a<>b}) (x:A) (l:list (A*B)) {struct l} : option B :=
  match l with
  | nil => None
  | cons (a,b) t => if (eq a x) then Some b else list_assoc A B eq x t
end.
Arguments list_assoc [A B] _ _ _.


(** substitutions *)
Fixpoint sum_a (sub:list (x*a)) (a__7:a) {struct a__7} : a :=
  match a__7 with
  | (a_Ax x5) => (match list_assoc eq_x x5 sub with None => (a_Ax x5) | Some a_6 => a_6 end)
  | a_AA => a_AA 
  | (a_a a5) => a_a (sum_a sub a5)
  | (a_C a_a'_a''_list) => a_C (map (fun (pat_:(a*a*a)) => match pat_ with (a_,a'_,a''_) => ((sum_a sub a_),(sum_a sub a'_),(sum_a sub a''_)) end) a_a'_a''_list)
  | (a_CC a_a'_a''_list) => a_CC (map (fun (pat_:(a*a*a)) => match pat_ with (a_,a'_,a''_) => ((sum_a sub a_),(sum_a sub a'_),(sum_a sub a''_)) end) a_a'_a''_list)
end.

Fixpoint su_a (a_6:a) (x_6:x) (a__7:a) {struct a__7} : a :=
  match a__7 with
  | (a_Ax x5) => (if eq_x x5 x_6 then a_6 else (a_Ax x5))
  | a_AA => a_AA 
  | (a_a a5) => a_a (su_a a_6 x_6 a5)
  | (a_C a_a'_a''_list) => a_C (map (fun (pat_:(a*a*a)) => match pat_ with (a_,a'_,a''_) => ((su_a a_6 x_6 a_),(su_a a_6 x_6 a'_),(su_a a_6 x_6 a''_)) end) a_a'_a''_list)
  | (a_CC a_a'_a''_list) => a_CC (map (fun (pat_:(a*a*a)) => match pat_ with (a_,a'_,a''_) => ((su_a a_6 x_6 a_),(su_a a_6 x_6 a'_),(su_a a_6 x_6 a''_)) end) a_a'_a''_list)
end.



